[STEP 02] 박스오피스 앱 ― D\.O\., Jenna
tasty-code/ios-box-office pull request #12
Opened 2023-05-04 07:15 UTC by ueunli

안녕하세요 Cory!! @corykim0829
`디오` & `제나` 입니다👋

`STEP2`에서는 일일 박스오피스와 개별 영화 API를 요청하는 `네트워크 모델을 구현하는 단계`였습니다. 저희는 `url`과 `urlRequest를` 생성할 수 있는 타입과 `dataTask`를 `request`하는 타입으로 나누어 만들어 보았습니다.

추가로 STEP2-1(도전스텝)에서 테스트와 관련된 내용이 있었으나, `Network layer`에 대한 추가 학습 이후 도전해보기로 했어요. 잘 부탁드립니다 🙇🏻‍♀️🙇🏻‍♂️!!

---

　
# 요구 사항 및 구현

### 요구 사항
- [x] 네트워크 통신을 담당할 타입을 설계하고 구현합니다.
- [x] 영화진흥위원회의 일별 박스오피스 API 문서의 데이터 형식을 고려하여 서버와 실제로 데이터를 주고받도록 구현합니다.
   - [x] 오늘의 일일 박스오피스 조회
   - [x] 영화 개별 상세 조회

### 구현
<img src="https://i.imgur.com/ZfLTArR.png" width="40%"></img>
- **Network**
    - `API`:  네트워크 통신에 필요한 엔드포인트, `url`, `urlRequest` 생성 
    - `NetworkError`: 네트워크시 발생한 에러타입 정의, `LocalizedError` 채택
    - `HTTPMethodType`: `get`, `post`, `put`, `delete` 정의
    - `NetworkServable`: `dataTask` 메서드를 정의한 프로토콜 구현
- **Model**
    - `DailyBoxOfficeDTO`: 일일박스오피스 정의한 DTO
    - `MovieDetailDTO`: 개별영화 데이터를 정의한 DTO
- **View**
    - `LaunchScreen`
    - `Main`
- **Controllers**
    - `ViewController`

　
# 고민했던 부분
- **ViewController의 저장속성**
   - 추후 ViewController가 DataSource로서 기능하기 용이하도록 보다 정제된 형태의 DTO를 가지게 하는 편이 맞다고 생각했으나, 
   - 현재 요구사항이 '데이터를 주고받도록 구현'임을 고려하여 추가적인 네트워크 레이어를 구현하지 않았으므로, 뷰컨트롤러가 임시로 `NetworkServable`을 채택, 현 DTO들을 갖도록 구현했어요
   - → 다음 스텝에서 저장속성 타입 등을 수정할 계획입니다!
- **Endpoint**
   - 지금 구현에서는 `API` 열거형이 Endpoint의 역할을 겸하고 있는데요, 
   - `API`의 로직이 다소 무거워진 점이 걸려 리팩토링을 하려고 했으나, 앞으로 추가될 api 조건도 고려해야 될 것 같아 다음 스텝 혹은 Test Double 적용 과정에서 진행하는 게 좋겠다고 판단했습니다..!

　
　

2023-05-05 09:16 UTC, corykim0829 requested changes
수고하셨습니다!!

다음 스텝에 해야할 게 많아보이지만 같이 이야기해보고 넘어가면 좋을 것 같아요!

커멘트 확인해주세요!

2023-05-05 09:16 UTC, corykim0829 commented on BoxOffice/Controllers/ViewController.swift
> +            case .failure(let error): print(error.localizedDescription)
case의 `:` 뒤에는 개행을 해주어서 확실하게 알아볼 수 있도록 하면 좋을 것 같아요!

2023-05-05 09:16 UTC, corykim0829 commented on BoxOffice/Network/NetworkServable.swift
> +    func fetchData(apiType: API, completion: @escaping (Result<APIRepresentable, NetworkError>) -> Void)
NetworkServable을 프로토콜로 가져가는 이유가 어떻게 되나요? 프로토콜로 사용하면 어떤 장점이 있나요?

completion 클로저에서 APIRepresentable 프로토콜 타입으로 반환하는 부분은 사용할 때마다 타입 변환을 한번 더 옵셔널 처리해야한다는 번거로움이 있는 것 같아요.

원하는 타입으로 반환하는 방법을 고민해보면 좋을 것 같아요.

2023-05-05 09:16 UTC, corykim0829 commented on BoxOffice/Network/API.swift
> +enum API {
이렇게 enum으로 구현하면, 나중에 요청할 케이스가 많아지면 유지보수가 힘들어지게 될 것 같네요
하나의 케이스를 추가하거나 제거하게 되면, 모든 switch를 반영해줘야해서 불편함이 있으니 참고하세요!

enum + case으로 사용하는 것은 확실한 케이스가 나뉘어지는 변수처럼 사용하는게 좋습니다!

2023-05-05 09:16 UTC, corykim0829 commented on BoxOffice/Network/NetworkError.swift
> +    var errorDescription: String? {
다양한 에러 케이스를 고려해서 description까지 처리한 부분이 좋네요 👍

2023-05-08 07:21 UTC, ueunli commented on BoxOffice/Network/API.swift
> +enum API {
의논 끝에, 케이스가 많아지면 말씀해주신 문제점이 두드러질 것 같아 프로토콜 및 case별 구조체로 리팩토링 했습니다!

> 해당 커밋: 373bef5

2023-05-08 07:23 UTC, ghost commented on BoxOffice/Network/NetworkServable.swift
> +    func fetchData(apiType: API, completion: @escaping (Result<APIRepresentable, NetworkError>) -> Void)
Step2-1 추가 스텝의 테스트 더블 염두해두고 만들다 보니까 확장성을 위해 프로토콜로 구현하였습니다.

제네릭을 적용하여 원하는 타입을 직접 명시함으로써 짚어주신 문제점이 나타나지 않도록 수정하였습니다.

해당 커밋: 373bef5

2023-05-08 07:25 UTC, ueunli commented on BoxOffice/Controllers/ViewController.swift
> +            case .failure(let error): print(error.localizedDescription)
수정하였습니다 🙆🏻‍♀️

> 해당 커밋: 7da679b

2023-05-08 15:01 UTC, corykim0829 approved these changes
수고하셨습니다!!!

다음 스텝 진행 해주시고

남겨드린 커멘트 반영해주시고, 커멘트에 대한 의견 있으시면 답글로 남겨주세요!

2023-05-08 15:01 UTC, corykim0829 commented on BoxOffice/Controllers/ViewController.swift
> +    func updateData<T: APIRepresentable, E: EndPointProtocol>(from api: E, completion: @escaping (T?) -> Void) where E.DTO == T {
EndPointProtocol에 APIRepresentable 타입이 있어서 해당 타입을 굳이 제너릭 선언을 할 필요가 없어보여요

2023-05-08 15:01 UTC, merged