박스오피스 [STEP 3-1] Sunny, Blu
tasty-code/ios-box-office pull request #16
Opened 2023-05-10 15:11 UTC by SunnnySong

# 박스오피스 [STEP 3-1] Sunny, Blu
>안녕하세요! 븨븨(@YebinKim)!
🧴**TEAM SUNBLock**🧴 의 Sunny, Blu입니다!
>STEP3는 View를 만드는 3-1과 데이터와 View 연결하는 부분을 3-2로 나누어 해당 스텝을 두 단계로 나누어서 진행하려고 해요.
>
>우선, **STEP 3-1**에서는 **Mock 데이터를 구성하여 Collection View를 구현**해 보았어요.
>3-2에서는 네트워크 통신으로 받아온 데이터와 Collection View를 연결하는 세부 구현을 진행해 보려고 합니다!
>
>리뷰 잘 부탁드립니다! 감사합니다! ❤️

<br>

# 🧑🏼‍💻 작업 목록

## Mock 데이터를 활용한 Collection View 구현
- [x] Collection View 구현
    - [x] 리스트 형태로 박스오피스 정보 표기
    - [x] 맨 왼쪽: 영화의 현재 등수 표기
    - [x] 신규 영화: 등수 아래에 "신작" 표기
    - [x] 기존 영화: 어제와 비교한 등락을 표기
        - 순위 상승: 빨간 화살표 + 등락 편차
        - 순위 하락: 파란 화살표 + 등락 편차
        - 변동 없음: "-" 표기
- [x] Collection View에 보여질 모델 타입 구현
- [x] Safe Area을 고려한 오토 레이아웃 구현

<br>

# 📚 학습 키워드 및 학습 내용
## 1. Controller가 가벼운 MVC 구현하기

- **학습 내용**
   - 우리가 원래 알고 있었던 MVC는 Controller가 비대해진다는 단점을 갖고 있었음
   - 하지만 과거 븨븨에게 디자인 패턴에 대해 질문을 드렸을 때, Controller가 가벼운 MVC에 대한 힌트를 얻어 학습하게 되었음
- **적용 과정**
   - CollectionView의 DataSource 분리를 위한 BoxOfficeDataSource 타입 생성
       - 처음 구현했던 코드에는 UICollectionViewDataSource가 ViewController에 있었다. 
       - 하지만 DataSource는 UICollectionView라는 View에 데이터를 전달시키는 객체이지 ViewController에 있을 필요성을 느끼지 못했다.
       - BoxOfficeDataSource 타입을 따로 생성후 View 폴더에 넣고 ViewController를 더 가볍게 만들었다.
       
   - CollectionView의 layout을 생성하는 CollectionViewLayout 타입 생성
       - 처음 구현했던 코드에는 CollectionView layout을 만드는 함수가 View Controller 내부에 존재했었다.
       - CollectionView layout은 CollectionView라는 View를 만들기 위해 필요한 함수로, 위와 동일하게 View Controller에 있을 이유가 없다는 생각이 들었다.
       - CollectionViewLayout 타입을 생성해 View 폴더에 넣어 분리하였다.
  
- **고민**
   - 😰 **`UICollectionViewDataSource` vs `UICollectionViewDiffableDataSource` 선택**
        -  CollectionView가 iOS를 배우는데 있어어 중요한 학습 요소라 생각하였고 이번에 UICollectionView를 구현하면서 `UICollectionViewDataSource`와 `UICollectionViewDiffableDataSource` 모두 시도해 보려고 함
        - `UICollectionViewDiffableDataSource` 코드
    ```swift
        private func configureDataSource() {
        
        let cellRegistration = UICollectionView.CellRegistration<RankCell, RankItem> { (cell, indexPath, item) in
            
            cell.updateWithItem(item)
            cell.accessories = [.disclosureIndicator()]
        }
        
        dataSource = UICollectionViewDiffableDataSource<Section, RankItem>(collectionView: collectionView) { (collectionView: UICollectionView, indexPath: IndexPath, item: RankItem) -> UICollectionViewCell? in
            
            let collectionView = collectionView.dequeueConfiguredReusableCell(using: cellRegistration, for: indexPath, item: item)
            return collectionView
        }
        
        var snapshot = NSDiffableDataSourceSnapshot<Section, RankItem>()
        snapshot.appendSections([.main])
        snapshot.appendItems(RankItem.mock)
        
        dataSource?.apply(snapshot, animatingDifferences: false)
    }
    ```
    
    </br>
    
    - 🚀 **`UICollectionViewDataSource`로 결정한 이유**
        - UICollectionViewDiffableDataSource는 dataSource를 관리하는데 있어 더 깔끔한 코드를 제공해 줌
        - 데이터가 변경되었을 때 기존 `reloadData()`와 달리 애니메이션이 제공되 사용자 경험을 향상시킴
        - 하지만 우리의 앱은 네트워킹을 통해 데이터를 불러와 CollectionView에 전달해주면, 그 이후의 데이터 변경이 일어나지 않음
        - DiffableDataSource의 최대 장점은 손 쉬운 데이터 변경 및 업데이트 라고 생각하는데 우리의 프로젝트에서는 해당 장점을 활용할 수 없기 때문에 `UICollectionViewDataSource`를 사용했음

## 2. Cell에 데이터를 전달하는 방식
- **학습 내용**
    - 과거 CollectionViewCell에서 데이터를 연결할 때, DataSource의 `func collectionView(_, cellForItemAt)` 메서드에서 Cell의 요소와 데이터를 매칭해주는 코드를 구현했었음
    - UICollectionView를 학습함에 따라 `func collectionView(_, cellForItemAt)` 메서드는 CollectionView가 Cell을 표시할 때 마다 호출되기 때문에 내부 코드가 가벼워야 함을 알게 되었음

- **적용 과정**
    - UICollectionViewCell을 custom한 `CustomListCell` 에 프로퍼티로 cell에 보여질 데이터 타입을 갖도록 구현함.
    - `func updateConfiguration(using:)` 메서드 내부에서 cell의 UI Objects와 cell에 보여질 데이터 타입을 매칭시켰음.
    - `func collectionView(_, cellForItemAt)` 에서는 cell에 정의된 데이터 프로퍼티에 Mock 데이터의 요소들이 할당되도록 구현하였음.

## 3. 휴먼 에러를 줄이기 위한 Extension
- **고민**
    - CollectionView에서 Cell을 register 하거나 dequeue할 때, String 타입의 `Identifier`을 입력하는 과정에서 휴먼 에러가 발생할 가능성이 있다고 판단했음
- **적용 과정**
```swift
extension UICollectionReusableView {

    static var reuseIdentifier: String {
        return String(describing: Self.self)
    }
}    
```
```swift
extension UICollectionView {

    func register<T: UICollectionViewCell>(cell: T.Type) {

        register(T.self, forCellWithReuseIdentifier: T.reuseIdentifier)
    }

    func dequeue<T: UICollectionViewCell>(cell: T.Type, for indexPath: IndexPath) -> T {

        return dequeueReusableCell(withReuseIdentifier: cell.reuseIdentifier, for: indexPath) as! T
    }
}
```
- `UICollectionReusableView`에 extension으로 자기 자신의 타입을 String으로 갖는 `reuseIdentifier` 속성 추가
- `UICollectionView`에 extension으로 register와 dequeue 메서드 추가
    - 파라미터로 UICollectionViewCell의 메타타입을 입력하면, 해당 cell의 `reuseIdentifier`로 접근해 identifier을 넣어줌
    - identifier을 입력할 때 발생할 수 있는 휴먼 에러를 최대한 제거한 방법으로 구현했음

<br>

# 🔫 트러블 슈팅
## Separator layout guide

### 문제 발생
<img src="https://hackmd.io/_uploads/BkrQApdVh.png" width="400" height="400">

- (View 화면을 구현하고 있던 중이라,, 컬러플한 cell 이해 바랍니다,,,😅)
- Separator layout guide가 왼쪽 끝까지 붙지 않는 문제 발생

### 문제 해결 시도
- Apple 공식문서에 있는 Modern Collection Views 프로젝트에서 separatorLayoutGuide 키워드 힌트를 얻었다.
    - CustomCellListViewController.swift 내부의 updateSeparatorConstraint() 함수
    - <img src="https://hackmd.io/_uploads/rkLn0puV3.png" width="400" height="400">
    - 해당 프로젝트에서는 separatorLayoutGuide를 UIListContentView.textLayoutGuide.leadingAnchor 과 동일하게 주었다.
    ```swift
    private func updateSeparatorConstraint() {
        guard let textLayoutGuide = listContentView.textLayoutGuide else { return }
        if let existingConstraint = separatorConstraint, existingConstraint.isActive {
            return
        }
        let constraint = separatorLayoutGuide.leadingAnchor.constraint(equalTo: textLayoutGuide.leadingAnchor)
        constraint.isActive = true
        separatorConstraint = constraint
    }
    ```

### 문제 해결
```swift
let constraint = separatorLayoutGuide.leadingAnchor.constraint(equalTo: contentView.leadingAnchor)
constraint.isActive = true
```

2023-05-11 11:46 UTC, YebinKim requested changes
블루, 써니 안녕하세요 😊
Step3를 두 단계로 나눠서 구현하기로 하셨군요!
뷰와 데이터 연동 코드를 명확히 구분해보는 것은 좋은 시도라고 생각합니다 👍

이번 스텝은 UI 구현 위주라 코멘트가 많진 않은데요.
프로젝트 요구사항 스크린샷과 달리 현재는 하단 SafeArea 가 깨지고 있어서 이 부분만 수정하고 다음 스텝으로 진행해보면 좋을 거 같아요~
<img width="300" alt="SafeArea" src="https://github.com/tasty-code/ios-box-office/assets/38066039/e9425d52-f234-4bb0-8e28-00b8881def83">

그 외 기기별 사이즈 대응에는 문제 없는 것 확인했습니다!
고생 많으셨어요 ☺️

2023-05-11 11:46 UTC, YebinKim commented on BoxOffice/Model/BoxOfficeRank/BoxOfficeItem.swift
> +    ]
질문;

샘플 데이터를 기존의 `box_office_sample.json` 데이터로 활용해볼 수도 있었을 거 같은데 하드코딩으로 데이터를 추가한 이유가 있을까요 🤔

2023-05-11 11:46 UTC, YebinKim commented on BoxOffice/View/BoxOfficeRank/CustomListCell.swift
> +
p4;

불필요한 공백이 있어보여요 👀

2023-05-11 11:46 UTC, YebinKim commented on BoxOffice/Model/Network/Provider/Implementation/NetworkProvider.swift
> +    init(session: NetworkSessionProtocol = NetworkSession()) {
리뷰 코멘트 반영 고맙습니다! 😆

2023-05-12 07:32 UTC, SunnnySong commented on BoxOffice/View/BoxOfficeRank/CustomListCell.swift
> +
수정했어요😀

2023-05-12 07:40 UTC, SunnnySong commented on BoxOffice/Model/BoxOfficeRank/BoxOfficeItem.swift
> +    ]
엄.. `box_office_sample.json`을 추가해 Unit Test에만 사용하고 여기에 목 데이터로 사용할 생각은 해보지 못했네요...🥲 다음엔 목 데이터가 필요할 때 이부분에 대해 한번 더 생각해보도록 할게요!

2023-05-12 07:51 UTC, SunnnySong commented
### SafeArea 를 반영한 AutoLayout 수정

적절한 목 데이터를 사용하지 못해 SafeArea를 반영한 AutoLayout을 생각하지 못했어요. 븨븨의 코멘트를 받아 바로 수정했습니다!(븨븨의 대면 피드백과 함께,,,,💜💙)

- CollectionView에 적용했던 autoresizingMask 적용을 삭제했어요.
     - CollectionView의 위치와 크기를 결정하는데 있어 autoresizingMask를 사용하지 않고, autoLayout을 사용하는 것으로 변경했어요.
     - autoLayout을 사용함에 따라 `translatesAutoresizingMaskIntoConstraints = false`로 변경했어요.
- CollectionView의 leftAnchor, rightAnchor, bottomAnchor 를 `safeAreaLayoutGuide`를 사용해 잡았어요.

- **화면**
<img width="509" alt="스크린샷 2023-05-12 오후 4 50 49" src="https://github.com/tasty-code/ios-box-office/assets/85678496/4c2b0ed4-bb04-4c54-8017-e40f7ec05042">

2023-05-15 01:18 UTC, YebinKim commented on BoxOffice/Model/BoxOfficeRank/BoxOfficeItem.swift
> +    ]
네엡! 대량의 데이터를 추가할 때 편하기도 해서 혹시 json 사용을 생각해보셨을지 궁금했어요 ㅎㅎ

2023-05-15 01:21 UTC, YebinKim approved these changes
블루, 써니 안녕하세요~
Step3-1 수정까지 고생 많으셨어요!
이번 스텝은 여기서 머지 진행하도록 할게요 😄

다음 스텝 진행도 화이팅입니다!!

2023-05-15 01:21 UTC, merged