[STEP 03] 박스오피스 앱 ― D\.O\., Jenna
tasty-code/ios-box-office pull request #18
Opened 2023-05-12 08:42 UTC by ueunli

안녕하세요 Cory🐾 @corykim0829
`디오` & `제나` 입니다 !  

`STEP3`는 네트워크 모델을 뷰에 연결하기 위한 로직을 만드는 단계였어요!
저희는 MVC 패턴으로 작성했기에 뷰컨트롤러 구현이 이번 스텝의 주된 작업이었습니다.
`BoxOfficeViewController.swift`, `MovieCollectionViewListCell.swift` 파일 위주로 살펴 주시면 감사하겠습니다 🤗

이번 피드백도 잘 부탁드려요 🙇🏻‍♀️🙇🏻‍♂️!!

---

　
# 요구 사항 및 구현

### 요구 사항
- [ ] STEP 2-1)　Test Double
- [x] STEP 2에서 구현한 네트워킹 기능을 통해 실제 영화 목록을 API 서버에 요청하여 불러오기
- [x] 어제의 박스오피스를 볼 수 있는 화면을 구현하기
    - [x] 당겨서 새로고침 기능
    - [x] 화면 상단에는 날짜를 표기, 불러온 정보는 리스트 형태로 구현
    - [x] 처음 목록을 로드할 때, 빈 화면 대신 로드 중임을 알리는 장치 구현

### 구현
<table>
    <thead>
        <tr style="background:#FFFBE4">
            <th colspan="1" style="text-align:center">폴더링</th>
            <th colspan="1" style="text-align:center">설명</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style="background:#F8F8F8;"><pre><code>
├── BoxOffice
│   ├── Model
│   │   └── MovieDTO
│   │       ├── DailyBoxOfficeDTO
│   │       │   ├── BoxOfficeResultDTO.swift
│   │       │   ├── DailyBoxOfficeDTO.swift
│   │       │   └── MovieDTO.swift
│   │       └── MovieDetailDTO
│   │           └── MovieDetailDTO.swift
│   └── View
│   │   ├── Base.lproj
│   │   │   ├── LaunchScreen.storyboard
│   │   │   └── Main.storyboard
│   │   └── MovieCollectionViewListCell.swift
│   ├── Controllers
│   │   └── BoxOfficeViewController.swift
│   ├── Network
│   │   ├── Common
│   │   │   ├── APIRepresentable.swift
│   │   │   ├── HTTPMethodType.swift
│   │   │   └── NetworkError.swift
│   │   ├── EndPoint
│   │   │   ├── Implementation
│   │   │   │   ├── DailyBoxOfficeEndPoint.swift
│   │   │   │   └── MovieDetailEndPoint.swift
│   │   │   └── Interface
│   │   │       └── EndPointProtocol.swift
│   │   └── Service
│   │       ├── Implementation
│   │       │   └── NetworkService.swift
│   │       └── Interface
│   │           └── NetworkServable.swift
│   ├── AppDelegate.swift
│   ├── SceneDelegate.swift
│   ├── Assets.xcassets
│   ├── Info.plist
├── BoxOffice.xcodeproj
│   ├── project.pbxproj
│   ├── project.xcworkspace
├── BoxOfficeTests
│   ├── BoxOfficeTests.swift
│   └── TestData
│       └── DailyBoxOfficeData.json
└── README.md
            </code></pre></td>
            <td valign="top">
                <h3>Model</h3>
                <li><code>DailyBoxOfficeDTO</code>: 일일박스오피스 정의한 DTO</li>
                <li>
                    <code>MovieDetailDTO</code>: 개별영화 데이터를 정의한 DTO</li>
                <h3>View</h3>
                <li><code>MovieCollectionViewListCell.swift</code>: <code>CollectionView</code> 커스텀 셀 정의</li>
                <li><code>LaunchScreen</code></li>
                <li><code>Main</code></li>
                <h3>Controllers</h3>
                <li><code>BoxOfficeViewController</code>: 네트워크 호출 및 컬렉션 뷰 출력</li>
                <h3>Network</h3>
                <li><code>API</code>:  네트워크 통신에 필요한 엔드포인트, <code>url</code>, <code>urlRequest</code> 생성 </li>
                <li><code>NetworkError</code>: 네트워크시 발생한 에러타입 정의, <code>LocalizedError</code> 채택</li>
                <li><code>HTTPMethodType</code>: <code>get</code>, <code>post</code>, <code>put</code>, <code>delete</code> 정의</li>
                <li><code>NetworkServable</code>: <code>dataTask</code> 메서드를 정의한 프로토콜 구현</li>
            </td>
        </tr>
    </tbody>
</table>

　
　 
# 고민 및 질문
### ✔️　`파일 분리` vs `fileprivate extension`
숫자의 포맷(1,000)과 날짜 포맷(2023-05-12)을 맞추기 위해서 각각 `String`,`Date`에 대하여 `Extension`으로 구현을 하였어요
- `타입의 메서드로 구현`하면 타입의 인스턴스가 포맷을 바꿔주는 메서드를 가지게 되고, 해당 객체의 역할과 책임에는 어울리지 않는다고 생각했어요
- 그래서 `String`, `Date`의 `Extension`으로 구현하였어요. 이 때 포맷을 바꿔주는 함수는 해당 파일 안에서만 필요하고 다른 파일에서는 필요하지 않아 `fileprivate` 키워드로 작성하였어요
> 🙋‍♂️**(질문)** 로직에서 필요한 부분을 `Extension` 으로 처리하는 부분이 많아지면 파일이 길어지고 가독성이 떨어질 것 같은데요! 이런 부분은 어떻게 처리해야 할 지 궁금합니다.!

### ✔️　`apply(_:)`의 호출
저희가 구현한 `applyMovieDataSource()`메서드는  `UICollectionViewDiffableDataSource`의 `apply(_:)`를 호출하는 함수예요.
처음 앱을 켰을 때, api로부터의 데이터 수신이 완료되었을 때 ― 이렇게 2군데에서 사용하기 위해 구현했는데, main 스레드에서 호출해야 한다는 경고가 떴어요. 컴파일러가 권하는 대로 `DispatchQueue.main.async { }`로 감싸주려다가, 바로 수정하기보단 UI에 관한 이벤트가 아닌데도 main 스레드가 강제되는 이유를 정확히 알아보고 적용하기로 했어요.
그 결과, [공식문서](https://developer.apple.com/documentation/uikit/uicollectionviewdiffabledatasource/3375795-apply)를 통해 다음과 같은 내용을 확인할 수 있었어요!
```
You can safely call this method from a background queue, but you must do so consistently in your app. Always call this method exclusively from the main queue or from a background queue.
```

다시 보니, `applyMovieDataSource()`의 호출은 다음 2군데에서 이루어지고 있었어요. ㄱ
   1. `updateYesterdayData()`에서: background queue (컴플리션 클로저 내에서)
   2. `configureMovieDataSource()`에서: main queue

컴파일러의 경고는 '`apply(_:)`는 메인 스레드에서 호출해야 한다'는 뜻이 아니라, '`apply(_:)`는 일관된 스레드에서 호출해야 하는데, 아무래도 메인 스레드에서가 낫겠다'는 뜻이었던 거예요 😳
이번 기회에 공식문서의 중요성을 다시금 되새길 수 있었어요 :-D

### ✔️　`prepareForReuse()`
커스텀 셀을 구현하며 부모타입에 없는 서브뷰들을 새로 정의해 주었어요.
dataSource의 데이터 일부는 기본구현 요소에(`.text`, `.secondaryText` 등), 
또 일부는 새로 넣어준 요소에(`rankLabel`, `rankStatusImage` 등) 바인딩 되는데요, 
따라서 prepareForReuse() 메서드를 재정의 하며 super.prepareForReuse() 호출 후 '새로 넣어준 요소'들에 바인딩 된 값을 nil로 할당하는 로직을 추가했어요.
> 여기서 질문! 🙋🏻‍♀️
> **Q. 기본구현 요소(상속받은 속성)에 대해서는 초기화 해줄 필요가 없는가?**
> - 테이블뷰와 기본 콜렉션뷰를 학습하며 그렇다고 알고 있었지만, 이번엔 diffable data source 등 셀과 데이터에 대한 작동기전에 있어 달라진 바가 많아 확실히 알고 싶었어요
> - UICollectionViewListCell은 UICollectionViewCell를 상속하므로 같은 prepareForReuse() 메서드를 갖고 있지만, 이 메서드가 상위의 prepareForReuse()와 달리 하위타입에서 추가로 기본구현 된 (UIListContentConfiguration의) .text, .secondaryText 등의 값도 초기화 해주고 있는지 정확히 확인할 자료를 찾지 못했어요.
> - 참고할 만한 문서나 키워드가 있다면 조언 부탁드려요🥲

### ✔️　updateData 메서드 제네릭 없애기
저번 스텝 피드백에서 `updateData<T, E>(from:completion:)`의 제네릭타입 `T: APIRepresentable`에 대해 언급해 주셨는데요, 
말씀해 주신 이유가 맞다고 생각해 이번에 리팩토링을 해보려 했지만 제네릭 명시를 하지 않으면 타입추론이 제대로 이루어지지 않는 문제를 만났어요...
뭔가 아주 기초적인 부분을 놓치고 있는 듯한데 찾지 못했어요 🤯

> **SOS** ⚡️
어떻게 변형하면 보다 깔끔한 코드가 될 수 있을지 힌트를 더 주실 수 있을까요...!! 

　 
　

2023-05-15 04:53 UTC, corykim0829 requested changes
수고 많으셨습니다! 👍

전반적으로 구현도 깔끔하게 하셨고, Modern CollectionView를 깔끔하게 구현 하셨네요 👍

남겨드린 커멘트 기반으로 코드 개선해봅시다!!

---

> 🙋‍♂️**(질문)** 로직에서 필요한 부분을 Extension 으로 처리하는 부분이 많아지면 파일이 길어지고 가독성이 떨어질 것 같은데요! 이런 부분은 어떻게 처리해야 할 지 궁금합니다.!

➡️ fileprivate으로 구현한 부분은 좋은 것 같습니다! 그렇게 가독성이 떨어지는 것 같지는 않습니다.
다만 스위프트 타입의 확장인 만큼 나중에 이름이 중복되지 않고 해당 클래스에서만 사용되는 걸 나타낼 수 있게 구체적인 네이밍을 사용하는 게 좋아보입니다.

> 여기서 질문! 🙋🏻‍♀️ 
Q. 기본구현 요소(상속받은 속성)에 대해서는 초기화 해줄 필요가 없는가?

➡️ 이 부분은 직접 dequeue되는 cell들을 확인해보면 금방 확인할 수 있을 것 같아요!

> SOS ⚡️ 어떻게 변형하면 보다 깔끔한 코드가 될 수 있을지 힌트를 더 주실 수 있을까요...!!

➡️ 구현하신 `T: APIRepresentable, E: EndPointProtocol` 에서 EndPointProtocol이 APIPresentable 타입을 알고 있기 때문에 함수에서 APIRepresentable가 선언할 필요가 없어보여서 이전에 커멘트를 남겼습니다! 이 부분만 정리하면 될 것 같아요!

2023-05-15 04:53 UTC, corykim0829 commented on BoxOffice/Controllers/BoxOfficeViewController.swift
> +        let opacityKeyframe = CAKeyframeAnimation(keyPath: "opacity")
애니메이션 처리 좋네요 👍

2023-05-15 04:53 UTC, corykim0829 commented on BoxOffice/Controllers/BoxOfficeViewController.swift
> +            }
함수로 정리하면 더 깔끔할 것 같네요

2023-05-15 04:53 UTC, corykim0829 commented on BoxOffice/Controllers/BoxOfficeViewController.swift
> +    }
이 부분은 CollectionView에 필요한 값이여서 ViewController가 가지고 있는게 조금은 부자연스러워 보이네요

2023-05-15 04:53 UTC, corykim0829 commented on BoxOffice/Controllers/BoxOfficeViewController.swift
> +        view.addSubview(movieCollectionView)
미션 조건에 safeArea를 고려해서 autoLayout 처리를 해야한다고 되어있는데, 이 부분 한번 확인 부탁드립니다!

2023-05-15 04:53 UTC, corykim0829 commented on BoxOffice/Controllers/BoxOfficeViewController.swift
> +    private var movieDataSource: UICollectionViewDiffableDataSource<Section, MovieDTO>! = nil
Implicitly Unwrapped Optional 타입의 여기 두 프로퍼티 값을 nil로 선언할 필요는 없어보이네요!

2023-05-16 02:45 UTC, doshkor commented on BoxOffice/Controllers/BoxOfficeViewController.swift
> +            }
`removeLoadLabel()` 함수로 분리하였습니다

해당 커밋: b5021c7

2023-05-16 02:46 UTC, ueunli commented on BoxOffice/Controllers/BoxOfficeViewController.swift
> +    private var movieDataSource: UICollectionViewDiffableDataSource<Section, MovieDTO>! = nil
Implicitly Unwrapped Optional 타입의 기본값도 nil이므로 해당 부분 생략했습니다!

> 해당 커밋: b5021c7

2023-05-16 02:47 UTC, doshkor commented on BoxOffice/Controllers/BoxOfficeViewController.swift
> +        view.addSubview(movieCollectionView)
`movieCollectionView` 레아아웃을 `view.frame` 에서 `view.safeAreaLayoutGuide.layoutFrame`으로 변경하였습니다

해당 커밋: b5021c7

2023-05-16 02:54 UTC, ueunli commented on BoxOffice/Controllers/BoxOfficeViewController.swift
> +    }
ViewController가 가지기엔 어색하여 
1. View폴더에 Section파일로 분리
2. Controller폴더에 Section파일로 분리
3. 그냥 ViewController에 두기
4. ViewController가 있는 파일에 fileprivate으로 함께 두기
5. UICollectionView 또는 연관 타입에 extension으로 열거형(&메서드 오버라이드) 추가

↑ 위와 같은 방안들을 생각해 보았지만, 4번 방법이 가장 적절할 것 같아 ViewController가 정의된 파일 상단에 fileprivate enum으로 수정하였어요!

다른 좋은 방법이 있는지, 코리는 이럴 때 보통 어떻게 하시는지 조언 부탁드려요🙏🏻

> 해당 커밋: b5021c7

2023-05-16 10:55 UTC, corykim0829 approved these changes
수고 많으셨습니다!!

2023-05-16 10:55 UTC, corykim0829 commented on BoxOffice/Controllers/BoxOfficeViewController.swift
> +fileprivate enum Section {
CollectionView 클래스에 들어가는게 좋을 것 같은데, 다시보니 일단은 ViewController에 있어도 나쁘지 않을 것 같네요!

2023-05-16 10:55 UTC, merged