박스오피스 [STEP 4] Sunny, Blu
tasty-code/ios-box-office pull request #19
Opened 2023-05-17 02:55 UTC by calledBlu

>안녕하세요! 븨븨(@YebinKim)!
🧴**TEAM SUNBLock**🧴 의 Sunny, Blu입니다!
저번 븨븨가 용산에 놀러 오셨을 때, STEP3-2에 대한 대략적인 리뷰를 받기도 했고(대면 리뷰를 받을 수 있음에 행복했어요.😀)
촉박하게 프로젝트를 구현했기 때문에 이번 PR은 STEP 3-2와 STEP 4를 같이 보내게 되었어요🥰
>
>이번 리뷰도 잘 부탁드립니다!💙☀️
>븨븨의 리뷰를 받을 수 있어서 정말 알차고 즐거웠던 프로젝트였어요! 👍👍

<br>

# 🧑🏼‍💻 작업 목록
## 네트워크 통신 및 영화 상세화면 구현
- [x] 이미지 검색 API와의 통신
    - API Key를 Header에 포함하여 통신
    - 이미지 검색 결과를 받아올 모델타입 구현
    - 네트워크 통신을 담당하는 타입 개선
- [x] 영화 상세정보를 나타내는 뷰 구현
    - StackView 활용
    - Safe Area을 고려한 오토 레이아웃 구현
    - 나타내야 하는 정보
        - 영화 포스터 이미지
        - 영화 상세정보
- [x] refresh control 개선

<br>

# 실행 화면

<br>

# 📚 학습 키워드 및 학습 내용
## 1. Protocol과 Generic의 차이

- **학습 내용**
   - Generic: 정적인 다형성 구현 가능
       - 타입이 한번 지정되면 제네릭으로 지정된 모든 타입이 한번에 지정됨
       - generic이 protocol 내에 존재하는 경우 원래는 타입으로 사용할 수 없음!
       - 이를 가능하도록 하는 것이 `any`와 `some`키워드
   - Protocol: 동적인 다형성 구현 가능
       - Protocol을 채택하는 다양한 타입이 들어갈 수 있음
- **적용 과정**
   - `PresentationModel`(현 `PresentationProvider`)를 구현할 당시 endPoint의 다양한 EndPoint를 수용하기 위해 프로토콜을 사용하려고 함
        ```swift
        struct PresentationModel: PresentationProvidable {

            private let networkProvider: NetworkProvidable
            private var date: String {
                return Date.yesterday.formatData(type: .network)
            }

            private var endpoint: RequestResponseProtocol

            init(networkProvider: NetworkProvidable = NetworkProvider()) {
                self.networkProvider = networkProvider
                self.endpoint = DailyBoxOfficeEndpoint(date: date)
            }

            func dispatch(endpoint: RequestResponseProtocol) async {

                // NetworkProvider를 통해 데이터를 받아오는 request 함수 실행
                // networkProvider.request(endpoint)
            }
        }
        ```
- **문제와 해결**
    - 😰 위 코드 중 `private var endpoint: RequestResponseProtocol` 부분에서 `RequestResponseProtocol`을 타입으로 사용할 수 없어서 문제 발생
    - `RequestResponseProtocol`은 `Requestable & Responsable` 을 합성한 프로토콜이며 `Responsable` 프로토콜에서는 `associatedtype`을 가지고 있음!
    - 🚀 protocol 내에 associatedtype이 존재하므로 타입으로 사용할 수 없으므로 `Endpoint`라는 Generic을 생성하여 해당 Generic이 `RequestResponseProtocol`을 채택하도록 코드 수정
        ```swift
        struct PresentationModel<Endpoint: RequestResponseProtocol>: PresentationProvidable {

            private let networkProvider: NetworkProvidable
            private var date: String {

                return Date.yesterday.formatData(type: .network)
            }

            private var endpoint: Endpoint

            init(networkProvider: NetworkProvidable = NetworkProvider(), endpoint: Endpoint) {
                self.networkProvider = networkProvider
                self.endpoint = endpoint
            }
        ```
- **아쉬운 점**
   - endPoint를 내부에 가지고 있는 방향으로 코드를 수정하여 해결한 코드를 사용하지 못하게 된 것

<br>

## 2. UI 레이아웃 구성 방법

- **학습 내용**
    - iOS와 macOS의 사용자 인터페이스의 레이아웃은 3가지 방법으로 구성 가능
    - Frame-based Layout
        - view의 위치와 크기 정보를 frame으로 표현하는 것
    - Autoresizing Masks
        - Super view의 frame이 변경될 때 view의 frame이 변경되는 방식
        - 늘어난 Super view의 크기에 맞춰 자연스럽게 화면이 배치됨    
        예) `collectionView.autoresizingMask = [.flexibleWidth, .flexibleHeight]`
    - Auto Layout
        - view의 크기, 위치, view 사이 간격에 constraint를 설정하여 조정
        - view의 frame 대신 view 사이의 관계를 정의하여 내부/외부 변화에 모두 대응함
    - 적용되는 순서는`Autoresizing Masks` -> `autoLayout` -> `Frame`
- **적용 과정**
    - collection view의 레이아웃을 `Autoresizing Masks`로 조정하려고 함
- **문제 해결**
    - 😰 Autoresizing Masks를 사용하였을 때 view의 safeArea를 벗어나는 문제 발생
    - 🚀 Autoresizing Masks 대신 Auto Layout을 사용하는 방향으로 변경

<br>

# 🔫 트러블 슈팅
## 영화 포스터 이미지 비율대로 설정하기

### 문제 발생

<img src="https://hackmd.io/_uploads/ByY4hh-S2.png" width="260" height="450">

- 영화 세부정보를 보여주는 화면에서 영화 포스터 자체의 이미지 비율이 아니라 StackView의 layout에 꽉 차서 이미지가 나오는 문제 발생
- 이미지 고유의 비율이 아니기 때문에 이미지가 부자연스럽게 보이는 현상이 발생

### 문제 도전
아래 키워드에 대해 학습하면서 이미지 크기 조정을 시도함

- **contentMode** : View의 bounds가 변경될 때, content가 어떻게 배치될지 결정하는데 사용하는 mode

- contentMode를 쉽게 이해할 수 있는 그림 [출처](https://blog.naver.com/PostView.naver?blogId=soojin_2604&logNo=222439470655&parentCategoryNo=&categoryNo=&viewDate=&isShowPopularPosts=false&from=postView)
- <img src="https://hackmd.io/_uploads/SkCGah-S2.png" width="400" height="500"> 
    
- contentMode.scaleAspectFit : content 고유의 비율은 유지하면서, View 크기에 맞게 확장, 나머지 영역은 투명하게 변경됨

### 문제 해결
<img src="https://hackmd.io/_uploads/HkWw03bH2.png" width="260" height="450">

- UIImageView에 `contentMode` 설정
    ```swift
    private let moviePoster: UIImageView = {

        let imageView = UIImageView()
        imageView.heightAnchor.constraint(equalToConstant: 400).isActive = true
        imageView.contentMode = .scaleAspectFit
        return imageView
    }()
    ```

<br>

2023-05-17 12:12 UTC, YebinKim requested changes
써니, 블루 안녕하세요~
박스오피스 Step4 진행까지 고생 많으셨어요 🥳🎉
이번에도 타입의 추상화 구조에 신경을 많이 쓰셨음이 느껴졌어요 👍
Protocol 의 연관값 문법을 멋지게 활용하신 구조 또한 눈에 띄었습니다!! 🤩

또한, 데이터 전달 및 동작 전달을 위해 컴플리션 구조를 주로 활용하신 걸로 보이는데요 👀
이로 인해 발생하는 메모리 누수가 일부 있어서 코멘트 남겨두었으니 확인 부탁드려요~

---

이번 스텝의 핵심 경험은 아래와 같았는데요.
<img width="308" alt="step4" src="https://github.com/tasty-code/ios-box-office/assets/38066039/4174f8c1-fae1-4a37-b86c-c7698962d3f1">

스텝 핵심 경험과는 별개로 p1, p2 코멘트가 있어서 Request Changes 로 요청드렸어요.

뷰컨트롤러의 deinit 에 로그를 달아두면 뷰컨트롤러 내부에서 메모리 누수가 발생하는지 확인하기 편해요! 제가 주로 사용하는 방법입니다 😆
```swift
deinit {
	debugPrint("deinit \(self)")
}
```

2023-05-17 12:12 UTC, YebinKim commented on BoxOffice/Controller/ViewController/MovieInformationViewController.swift
> +        }
p1;

메모리 누수가 발생하고 있네요! 수정이 필요해보입니다 👀

2023-05-17 12:12 UTC, YebinKim commented on BoxOffice/Controller/ViewController/BoxOfficeViewController.swift
> +        }
p1;

마찬가지로 메모리 누수가 발생하고 있어요! `BoxOfficeViewController` 파일 내에서는 총 세 군데 발생합니다 👀

2023-05-17 12:12 UTC, YebinKim commented on BoxOffice/View/MovieInformation/MovieInformationStackView.swift
> +class MovieInformationStackView: UIStackView {
p3;

상속 가능성이 없는 class 는 final 처리를 해두면 빌드 성능 향상에 도움이 되어요! 😊
일부 클래스만 final 처리가 되지 않은 거 같아서 확인 부탁드려요.

2023-05-17 12:12 UTC, YebinKim commented on BoxOffice/View/MovieInformation/MovieInformationView.swift
> +    }
p2;

`information`은 외부에서 접근하고 변경 또한 가능한 상태 값으로 보이네요 👀
현재 사용하는 로직을 살펴보면 `MovieInformationViewController` 가 세팅될 때(`viewDidLoad()`에서) 설정되는 값으로 보이는데, `configureMovieInformation` 메서드를 통해 매개변수 형태로 받아오는 형태로 만들어보면 어떨까요?

2023-05-17 12:12 UTC, YebinKim commented on BoxOffice/View/BoxOfficeRank/BoxOfficeDataSource.swift
> +    var boxOffices: [BoxOfficeItem] = []
p3;

`boxOffices` 는 언제든 외부에서 접근 가능하고 변경 가능하기 때문에 캡슐화가 잘 되어 있지 않은 것으로 보여요 🤔
생성자를 통해 주입받는 형태로 변경해보면 어떨까요?

2023-05-17 12:12 UTC, YebinKim commented on BoxOffice/Controller/ViewController/MovieInformationViewController.swift
> +        view.addSubview(indicatorView)
p2;

super 메서드의 호출이 누락되어 있네요 👀
메서드가 제대로 동작할 수 있도록 super 메서드의 호출이 필요해보여요!

관련 문서: [viewWillAppear(_:)](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621510-viewwillappear)
> If you override this method, you must call super at some point in your implementation.

2023-05-18 01:52 UTC, SunnnySong commented on BoxOffice/Controller/ViewController/MovieInformationViewController.swift
> +        }
[weak self] 를 추가해 약한 참조로 메모리 누수를 해결했어요!@ 
deinit을 추가해 확인해보니 메모리 누수를 쉽게 알 수 있어서 편리했어요😀
꿀팁 감사드려요!

2023-05-18 01:59 UTC, SunnnySong commented on BoxOffice/Controller/ViewController/BoxOfficeViewController.swift
> +        }
수정 완료했습니다😉

2023-05-18 02:03 UTC, SunnnySong commented on BoxOffice/View/BoxOfficeRank/BoxOfficeDataSource.swift
> +    var boxOffices: [BoxOfficeItem] = []
`boxOffices`에 private 키워드를 붙여 접근 제어를 설정했어요.
대신 븨븨의 코멘트를 받아 생성자를 통해 해당 프로퍼티 값을 설정해 줄 수 있도록 수정했어요😀

2023-05-18 02:29 UTC, calledBlu commented on BoxOffice/View/MovieInformation/MovieInformationStackView.swift
> +class MovieInformationStackView: UIStackView {
final 키워드가 필요한 클래스들을 찾아 추가해 주었어요!

> 해당 커밋: 4d94932

2023-05-18 02:30 UTC, calledBlu commented on BoxOffice/View/MovieInformation/MovieInformationView.swift
> +    }
`information` 프로퍼티 캡슐화 및 이를 위한 메서드를 구현해 보았습니다!

> 해당 커밋: 32d5158

2023-05-18 02:30 UTC, calledBlu commented on BoxOffice/Controller/ViewController/MovieInformationViewController.swift
> +        view.addSubview(indicatorView)
관련 문서를 보면서 다시 한번 복습 후 수정하였습니다!

> 해당 커밋: 4d94932

2023-05-18 11:07 UTC, YebinKim approved these changes
써니, 블루 Step4 수정 커밋 모두 확인했습니다~
이번 스텝 및 프로젝트는 여기서 깔끔하게 마무리게 되었네요! 약 4주 간 박스오피스 프로젝트 진행하느라 정말 고생 많으셨어요 ☺️

2023-05-18 11:08 UTC, merged