박스오피스 앱 [STEP1] Jin, Sam
tasty-code/ios-box-office pull request #25
Opened 2024-02-14 06:45 UTC by ParkChanH

# 박스오피스 앱 🎬

**리뷰어**: 알라딘  @junbangg

**버드**: Jin @wlsdud-dev, Sam @ParkChanH

안녕하세요. 알라딘!

박스오피스 앱 프로젝트를 진행하는 Jin과 Sam입니다.

첫 PR 보내드립니다.

잘 부탁드립니다! 😄

## 프로젝트 요구사항

- 영화진흥위원회의 일별 박스오피스 API 문서의 데이터 형식을 고려하여 모델 타입을 구현합니다.
    - 제공된 JSON 데이터를 위에서 구현한 Model 타입으로 Parsing 할 수 있는지에 대한 단위 테스트(Unit Test)를 진행합니다.

## 파일트리

```swift
📦BoxOffice
 ┣ 📂Model
 ┃ ┣ 📂Json
 ┃ ┃ ┗ 📜box_office.json
 ┃ ┗ 📜BoxOfficeData.swift
 ┣ 📜AppDelegate.swift
 ┣ 📜Info.plist
 ┣ 📜SceneDelegate.swift
 ┗ 📜ViewController.swift
```

## **설계 및 구현 설명**

### BoxOfficeData

영화진흥위원회의 일별 박스오피스 API 응답구조 에 데이터 형식을 고려한 모델 타입을 구현**

### Unit Test

BoxOfficeData 의 구현이 맞는지 unit Test에서 테스트 케이스를 구현 하였습니다.

## 고민했던 점

- Json 키를 CodingKeys로 변경을 하는게 맞을까?
    - 현재 json으로 받는 키들의 이름이 ‘audiCnt’ 로 축약을 사용하고 있습니다. 축약은 명확성이 부족하다고 생각되어 축약을 배제하고 `audienceCount` 로 키의 네임을 변경 해주었는데 서버에서 받는 json키와 많이 다르게 되어 오히려 더 혼동이 일어나지는 않을지 고민이 됩니다.

2024-02-14 12:19 UTC, junbangg requested changes
스텝 1 수고하셨습니다!!!
테스트 코드 작성에 도전하신거 멋집니다! 코멘트 확인 부탁드려요!

그리고 고민했던 점에 적어주신 coding key 관련하여 저의 생각을 간단하게 말씀 드리자면!

서버 측에서 내려주는 형태의 JSON 이 저희 네이밍 컨벤션과 다른 경우가 있을 수 있어요..! 
예를 들어 snake_case 로 내려올 수도 있고
스위프트 스타일의 컨벤션을 안따를 수도 있겠죠(예시로 말씀하신 `audiCnt` 같은 경우에도 축약을 지양하는 저희 스타일은 아니죠ㅎㅎ)
아니면 그냥 서버에서 내려주는 네이밍이 마음에 안들 수도 있죠..!
그래서 저희 앱에서 사용하는 컨벤션에 맞게..! 
변환 해서 사용하는건 저는 아주 좋다고 생각합니다🙋🏻‍♂️

2024-02-14 12:19 UTC, junbangg commented on BoxOfficeTests/BoxOfficeTests.swift
> +        XCTAssertNotNil(persedData)
오타가 하나 있네요! :)

2024-02-14 12:19 UTC, junbangg commented on BoxOfficeTests/BoxOfficeTests.swift
> +final class BoxOfficeTests: XCTestCase {
해당 클래스에서 BoxOffice 의 모든 테스트 코드를 작성하는게 아니라면, 조금 더 구체적인 이름을 정하는것도 괜찮을것 같아요!

2024-02-14 12:19 UTC, junbangg commented on BoxOfficeTests/BoxOfficeTests.swift
> +              let data = try? Data(contentsOf: path) else { return }
여기서 만약에 언래핑에 실패해서 리턴되면 테스트 케이스는 실패한걸까요??🤔

2024-02-14 12:19 UTC, junbangg commented on BoxOfficeTests/BoxOfficeTests.swift
> +    }
요 메서드들은 어떤것들이고, 왜 override 하고 계신걸까요?!

2024-02-14 12:19 UTC, junbangg commented on BoxOfficeTests/BoxOfficeTests.swift
> +    func test_박스오피스_파싱_확인() {
지금 not nil 인지 체크하는 케이스 외에도, 테스트 해볼 수 있는 다른 케이스는 없을까요??🤔

2024-02-15 01:45 UTC, wlsdud-dev commented on BoxOfficeTests/BoxOfficeTests.swift
> +        XCTAssertNotNil(persedData)
parsed인데 잘못 입력했네요. :smiling_face_with_tear:
오타 없도록 한번더 확인 하겠습니다! 🔥

2024-02-15 02:05 UTC, wlsdud-dev commented on BoxOfficeTests/BoxOfficeTests.swift
> +    }
`setUp()` 메서드는 테스트 메서드가 실행되기 전에 호출되어 동기적으로 에러를 반환하지 않는 초기화 메서드입니다.
`tearDown()` 메서드는 테스트 메서드가 종료되고 나서 호출되는 메서드로 동기적으로 에러를 반환하지 않는 메서드입니다.
테스트 초기설정이나 끝나고 나서 처리가 필요할 것 같아 오버라이드 해 주었습니다 만 현재로서는 사용하지 않았습니다.

2024-02-15 04:00 UTC, ParkChanH commented on BoxOfficeTests/BoxOfficeTests.swift
> +    func test_박스오피스_파싱_확인() {
다른 다양한 케이스로 다시 생각해보겠습니다!!

2024-02-15 08:15 UTC, ParkChanH commented on BoxOfficeTests/BoxOfficeTests.swift
> +              let data = try? Data(contentsOf: path) else { return }
해당 경우는 미처 고려하지 못했던 거 같습니다. 해당 사항은 수정했습니다!!

2024-02-15 08:16 UTC, ParkChanH commented on BoxOfficeTests/BoxOfficeTests.swift
> +final class BoxOfficeTests: XCTestCase {
변경 후 반영했습니다.

2024-02-15 08:16 UTC, ParkChanH commented on BoxOfficeTests/BoxOfficeTests.swift
> +    func test_박스오피스_파싱_확인() {
케이스 추가 후 반영했습니다!!

2024-02-15 16:40 UTC, junbangg approved these changes
수고하셨습니다..! 
조금 더 유연하게 테스트 코드를 작성할 수 있는 방법 (`given/when/then` 를 활용해서)
에 대해서 고민하셔서 이후 스텝에라도 더 고민하고 추가해보시면 좋을것 같아요!

2024-02-15 16:40 UTC, junbangg commented on BoxOfficeTests/BoxOfficeJsonTests.swift
> +        guard let path = Bundle.main.url(forResource: "box_office", withExtension: "json"),
이렇게하면 모든 테스트의 대상은 `"box_office"` 라는 리소스에 대한 테스트일텐데, 조금 더 유연하게, 즉 다른 json 파일에 대해서도 테스트가 가능하게 안될까요??

2024-02-15 16:40 UTC, junbangg commented on BoxOfficeTests/BoxOfficeJsonTests.swift
> +        self.decodedData = decodedData
혹시 테스트 코드 공부하시면서 sut 라는 용어 들어본 적 있으실까요?!

2024-02-15 16:40 UTC, junbangg commented on BoxOfficeTests/BoxOfficeJsonTests.swift
> +        // then
여기는 왜 비어져 있나요?? 
위에 `setUpWithError` 라는 메서드가 너무 많은 일을 해버린게 아닐까요?🤔

2024-02-15 16:40 UTC, junbangg commented on BoxOfficeTests/BoxOfficeJsonTests.swift
> +        XCTAssertEqual(listCount, 10, "가져온 리스트가 10개가 맞다")
어떤 assertion인지 메세지 String 을 추가 하신거 좋네요.! 👍

2024-02-15 16:40 UTC, junbangg commented on BoxOfficeTests/BoxOfficeJsonTests.swift
> +        // then
`given, when, then` 이 각각 어떤것으로 생각하고 계신지 궁금합니다!

2024-02-15 16:40 UTC, junbangg commented on BoxOfficeTests/BoxOfficeJsonTests.swift
> +        // then
개인적인 의견을 하나 말씀드리자면, 지금 given과 when 에 해당하는 일을 `setupWithError` 에서 다 해버린것 같아요..! 
그래서 더 다양한 테스트 케이스 나오기가 어려운 형태가 된것 같아요
테스트 대상은 decodedData 인데, 지금 어떤 테스트 케이스를 작성하여도 `decodedData?.boxOfficeResult.dailyBoxOfficeList.count` 의 값은 10이겠죠..!

2024-02-19 01:55 UTC, wlsdud-dev commented on BoxOfficeTests/BoxOfficeJsonTests.swift
> +        guard let path = Bundle.main.url(forResource: "box_office", withExtension: "json"),
```swift
//파싱하는 함수 생성
    func paserJson(forResource: String) throws -> BoxOfficeData {
        guard let path = Bundle.main.url(forResource: forResource, withExtension: "json"),
              let data = try? Data(contentsOf: path) else { throw JsonError.jsonLoadFail }
        parsedData = data
        guard let decodedData = try? JSONDecoder().decode(BoxOfficeData.self, from: parsedData) else { throw JsonError.jsonDecodedFail }
        
        return decodedData
    }
```
다른 json 파일을 받을 수 있도록  함수를 만들어 json 이름을 매개변수로 받아 파싱 할 수 있도록 수정 하였습니다.

2024-02-19 01:55 UTC, wlsdud-dev commented on BoxOfficeTests/BoxOfficeJsonTests.swift
> +        self.decodedData = decodedData
SUT라는 용어는 xUnit Patterns 중 하나입니다.
SUT : System Under Test
AUT : Application Under Test
MUT : Method Under Test
CUT : Class Under Test
OUT : Object Under Test

현재 테스트 대상이 되는 시스템, 모듈, 또는 객체를 가리킵니다.
즉 단위 테스트(Unit Test)에서 특정 함수나 클래스의 인스턴스가 sut가 될 수 있습니다.

2024-02-19 01:57 UTC, ParkChanH commented on BoxOfficeTests/BoxOfficeJsonTests.swift
> +        // then
리뷰어님의 말씀대로 이렇게 진행되면 **decodedData 가 동일한 방식으로만 초기화되고 테스트가 단일 시나리오에 강하게 의존하게 되는거같습니다!!
이부분은 수정해서 반영하겠습니다..!!**

- **Given**: 테스트를 실행하기 전에 필요한 모든 조건을 설정하는 단계입니다. 
테스트 대상의 초기 상태를 설정하고, 필요한 모든 입력 데이터와 의존성을 준비하는 과정입니다.
- **When**: 테스트 대상 코드를 실행하는 단계입니다. 특정 함수를 호출하거나 특정 액션을 수행합니다.
- **Then**: 테스트의 결과를 검증하는 단계입니다. 여기서는 예상 결과가 실제 결과와 일치하는지 확인합니다.

2024-02-19 02:03 UTC, wlsdud-dev commented on BoxOfficeTests/BoxOfficeJsonTests.swift
> +        // then
테스트라는 생각에 원칙등을 지키지 않고 구현을 했던것 같습니다.

2024-02-21 02:58 UTC, junbangg reviewed
좋습니다~ 테스트코드가 다양해져서 마음이 아주 든든하네요 수고하셨습니다!

2024-02-21 02:58 UTC, junbangg commented on BoxOfficeTests/BoxOfficeJsonDataTests.swift
> +        let sut = Result { try paserJson(forResource: jsonName)}
제가 이야기한게 요겁니다! 아주 좋아요!

2024-02-21 02:59 UTC, merged