박스오피스 앱 [STEP 1] Hoi, Hoing
tasty-code/ios-box-office pull request #29
Opened 2024-02-14 09:05 UTC by happykwon

안녕하세요 July @July911, 만나서 반갑습니다! 😆
hoi @happykwon hong @ujhong7 @입니다.
박스오피스 앱 STEP1 PR 드립니다.

조언 및 미흡한 부분에 대한 건의 언제나 환영하며,
솔직하게 리뷰를 해주시면 어떤 부분이든 달게 고찰해보고 반영하려고 노력해보겠습니다.
PR이 읽기 어렵거나 보충 설명이 필요한 부분도 언제든 DM 부탁드립니다.
감사합니다! 🔥

# 🔍 What is this PR?

1. 파싱한 JSON 데이터와 매핑할 모델 설계
2. CodingKeys 프로토콜의 활용
3. 단위 테스트(Unit Test)를 통한 설계의 검증

# 질문사항 
### 1. UnitTest 
Unit Test 를 구현하는 과정에서, 어떤것을 기준으로 잡아야 하는지 어려웠습니다. 생각끝에 기준으로 잡은 것이 
(데이터를 가져와야 하며 / 가져온 데이터는 가져오려는 데이터를 전부 가져온 것인지 확인해야한다) 였습니다. 
1. `loadDatad()`의 리턴값이 nil값이 아니여야한다. (데이터를 잘 불러온 것을 확인)
2. 데이터의 갯수는 mockJson파일의 갯수와 같아야한다  ( 모든 데이터를 불러온 것을 확인)
좀 더 나은 비교 방법이 있는지 궁금합니다, 그리고 unitTest를 진행 시 기준점?을 잡는 팁같은게 있다면 조언 부탁드립니다. 

# 📸 Screenshot

main 콘솔 확인 화면
![image](https://hackmd.io/_uploads/BJIpUgcja.png)

box_office_sample.json 파싱한 값이 정상 출력되는 모습

2024-02-14 10:06 UTC, July911 requested changes

2024-02-14 10:06 UTC, July911 commented on BoxOffice/MovieData.swift
> +        if let data = data,
```
let decoder = JSONDecoder()
        let data = jsonString.data(using: .utf8)
        if let data = data, 
        let movieData = try? decoder.decode(MovieData.self, from: data) {
```
앞으로 자주 디코딩을 할거라면 제네릭을 활용하여 만들어보셔도 좋을 것 같습니다 ~

2024-02-14 10:06 UTC, July911 commented on BoxOffice/MovieData.swift
> +struct MovieData: Codable {
MovieData 
보통은 data라고 붙여주지 않습니다. 모든게 데이터일 수 있으니까요 !

2024-02-14 10:06 UTC, July911 commented on BoxOffice/MovieData.swift
> +// MARK: - MovieData
필요한 주석일까요 ? 하나씩 나누는게 추후에 찾기 더 편하지 않을까요 ?

2024-02-14 10:06 UTC, July911 commented on BoxOffice/MovieData.swift
> +struct BoxOfficeResult: Codable {
Codable 은 뭘까요? 
굳이 Codable 이 필요할까요 ?

2024-02-14 10:06 UTC, July911 commented on BoxOffice/MovieData.swift
> +    let dailyBoxOfficeList: [DailyBoxOfficeList]
List라는 이름보다는 복수형이 좋아보입니다.

2024-02-14 10:06 UTC, July911 commented on BoxOffice/MovieData.swift
> +    let dailyBoxOfficeList: [DailyBoxOfficeList]
[DailyBoxOfficeList] 리스트를 담고있는 배열처럼 보이네요. 의도하신게 맞을까요?

2024-02-14 10:06 UTC, July911 commented on BoxOffice/MovieData.swift
> +    enum CodingKeys: String, CodingKey {
외부에서 필요한 정보일까요 ?

2024-02-14 10:06 UTC, July911 commented on BoxOffice/MovieData.swift
> +struct LoadData {
LoadData 라는 객체가 있는건가요 ?

2024-02-14 10:06 UTC, July911 commented on BoxOffice/MovieData.swift
> +    func loadData(from bundle: Bundle = .main) -> MovieData? {
bundle은 무엇인가요 ?

2024-02-14 10:06 UTC, July911 commented on BoxOffice/ViewController.swift
> +            dump(movieData)
dump 는 왜 써주신건가요 ?

2024-02-14 10:06 UTC, July911 commented on BoxOffice/ViewController.swift
> +        if let movieData = loadData.loadData(from: bundle) {
loadData.loadData(from: 
모호하게 읽히는거같아서 수정이 필요해보이네요.

2024-02-14 10:06 UTC, July911 commented on BoxOfficeTests/BoxOfficeTests.swift
> +        //d
//d 는 실수인가요 ?

2024-02-15 08:01 UTC, happykwon commented on BoxOffice/MovieData.swift
> +struct LoadData {
네 refactoring에서는  `JsonDataLoader`로 만들고 파일 분류했습니다.

2024-02-15 08:40 UTC, ujhong7 commented on BoxOfficeTests/BoxOfficeTests.swift
> +        //d
급하게 작성하다보니 지우지 못했습니다.. 수정하겠습니다

2024-02-15 08:40 UTC, happykwon commented on BoxOffice/MovieData.swift
> +    func loadData(from bundle: Bundle = .main) -> MovieData? {
Bundle은 애플리케이션의 실행 파일과 그와 관련된 리소스를 포함하는 패키지입니다. 
예를들면  이미지, 사운드 파일, 지역화된 문자열, 스토리보드 파일, 그리고 JSON 파일 등이 포함될 수 있습니다.

2024-02-15 08:42 UTC, happykwon commented on BoxOffice/ViewController.swift
> +            dump(movieData)
test를 하고 싶은데 print문보다 정형화되어서 콘솔에 찍히기 때문에 `dump`를 사용했습니다

2024-02-15 08:45 UTC, happykwon commented on BoxOffice/ViewController.swift
> +        if let movieData = loadData.loadData(from: bundle) {
do - catch 문을 사용하는 형식으로 수정완료했습니다.

2024-02-15 08:45 UTC, happykwon commented on BoxOfficeTests/BoxOfficeTests.swift
> +        //d
네 실수입니다 😢 다음부터는 좀 더 꼼꼼하게 보겠습니다 .

2024-02-15 10:00 UTC, happykwon commented on BoxOffice/MovieData.swift
> +        if let data = data,
리펙토링 완료했습니다. :)

2024-02-15 10:00 UTC, happykwon commented on BoxOffice/MovieData.swift
> +struct MovieData: Codable {
수정 완료했습니다 좀 더 헷갈리지 않고 명확하게 할 수 있는 것 같습니다 감사합니다 !

2024-02-15 10:01 UTC, happykwon commented on BoxOffice/MovieData.swift
> +// MARK: - MovieData
주석은 삭제했고 step의 요구사항을 보고 추후에 나눠주겠습니다

2024-02-15 10:02 UTC, happykwon commented on BoxOffice/MovieData.swift
> +struct BoxOfficeResult: Codable {
`Decoding과` `Encoding` 프로토콜을 전부 채택 할 수 있는 프로토콜로 알고 있습니다.
추후 step의 요구사항이 어떻게 나올지 몰라 일단은` Codable`을 채택했습니다.

2024-02-15 10:02 UTC, happykwon commented on BoxOffice/MovieData.swift
> +    let dailyBoxOfficeList: [DailyBoxOfficeList]
수정완료했습니다 :)

2024-02-15 10:04 UTC, happykwon commented on BoxOffice/MovieData.swift
> +    let dailyBoxOfficeList: [DailyBoxOfficeList]
추후 step에서 요구사항을 미리 예상했고, 
여러 개의 일일 박스오피스 데이터를 하나의 리스트로 관리하고자 배열로 묶었습니다.

2024-02-15 10:05 UTC, happykwon commented on BoxOffice/MovieData.swift
> +    enum CodingKeys: String, CodingKey {
은닉화 구현 완료했습니다 :) 아직은 익숙하지 않아 자주 빼먹고 빠진곳도 많을텐데 .. 유의하면서 이번 프로젝트 진행하겠습니다 !

2024-02-16 02:41 UTC, closed without merging