[STEP 01] 박스오피스 앱 ― D\.O\., Jenna
tasty-code/ios-box-office pull request #3
Opened 2023-04-25 05:09 UTC by ueunli

안녕하세요 Cory🐾 @protocorn93
박스오피스 프로젝트를 진행하게 된 `디오` & `제나` 입니다👋

`STEP1` 주요 요구사항은 `API모델구현` 및 `UnitTest작성` 이였어요
지정된 더미데이터가 있어 한결 수월할 것 같았지만 막상 유닛 테스트를 하려고 보니 고민할 만한 부분이 많았어요.
유닛테스트의 소중함을 새삼 깨닫게 된 Step 1이었습니다🐶

잘 부탁드립니다 🙇🏻‍♀️🙇🏻‍♂️!!

---
# 프로젝트
#### 프로젝트명 
ios-box-office

#### 프로젝트 기간
`2023.04.10` ~ `2023.05.10`

#### 참여자
디오 & 제나

　
# 요구 사항 및 구현
- [x] 영화진흥위원회의 일별 박스오피스 API 문서의 데이터 형식을 고려하여 모델 타입을 구현합니다.
   - [x] Codable한 DailyBoxOffice모델 구현
   - [ ] CodingKey 프로토콜을 활용하여 모델의 프로퍼티 네이밍 수정 (미완)
- [x] 제공된 JSON 데이터를 위에서 구현한 Model 타입으로 Parsing 할 수 있는지에 대한 단위 테스트(Unit Test)를 진행합니다.

　
# 질문
## 1.　테스트용 더미 데이터 어디에 둘지
- JSON 더미 데이터를 테스트 메서드의 given에 선언하였는데요
- 테스트에 필요한 더미 데이터가 많아지면 데이터 선언으로 인해 코드의 가독성이 떨어질 것이라 생각해서 더미 데이터 선언부를 별도의 파일로 분리하면 좋겠다고 생각했어요
- 🙋‍♂️[**질문 ①**] 데이터를 별도의 파일로 분리해도 괜찮을까요? `BoxOfficeTests` 폴더에 `TestData` 라는 폴더를 만들고 추가되는 데이터 파일을 분리하려고 하는데 괜찮은 방법인지, 코리라면 어떤식으로 작성하시는지 궁금해요 
- 🙋‍♂️[**질문 ②**] 분리한 더미 데이터 파일에는 `dailyBoxOfficeData` 변수만 정의하고 있어요. 어떤 타입이 아닌 변수만을 정의한 파일일 때 파일명은 `대문자로 시작해야 하는지 소문자로 시작해야 하는지` 궁금해요.
    - 디오생각: 파일이 소문자로 시작하면 변수만을 담았다는 의미를 가지지 않을까! 생각했어요
    - 제나생각: 파일명은 UpperCamelCase라는 원칙만 알고 있었는데, 디오 의견을 듣고 보니 그 배경은 생각해 본 적이 없는 듯해 문서를 찾아봤어요. 하지만 위 원칙의 이유나 기준을 더 찾을 수 없어 일단은 대문자로 시작하는 게 좋겠다고 생각했어요!

## 2.　XCTAssertEqual 2줄 쓰기
- JSON 더미데이터가 모델타입(DailyBoxOffice 구조체)으로 잘 변환되는지 확인하기 위한 수단으로 층위가 다른 아래 2가지 프로퍼티의 일치 여부를 체크하기로 했어요.
   1. `showRange` -- DailyBoxOffice > BoxOfficeResult > showRange
   2. `name` -- DailyBoxOffice > BoxOfficeResult > dailyBoxOfficeList.Element > name
- given에 선언한 `expectedShowRange`, `expectedName`과의 일치 여부를 각각 검증하려면 `XCTAssertEqual`메서드를 2번 써야 했어요.
- 하지만 유닛테스트는 단일 기능을 테스트하기 위한 것으로, 테스트메서드당 Assert메서드 하나씩만 쓰는 걸 권장해요. 이는 두 Assert메서드가 완전히 병렬로 동작하지 않음으로써 의도치 않은 변수가 발생하여 테스트 결과가 오염되는 상황을 방지하기 위함이라고 알고 있어요.
- 🙋‍♂️[**질문**] 이런 경우 어떻게 하면 좋을까요?
   - 우리 코드는 위 지양 이유에 해당하지 않는 케이스이므로 그냥 Assert메서드 2줄로 작성할 것
   - `XCTAssertEqual` 하나로, 두 데이터를 쌍으로 묶어 검증하기: 현재 선택한 방법! - 배열로 묶어 비교
   - `XCTAssertTrue` 하나로, '1번끼리 같음 && 2번끼리 같음'을 검증하기: 하나로 해결 가능하지만, 여전히 '1가지가 아닌 2가지를 검증한다'는 인상에서 벗어났다고 보기 어려움

　

2023-04-26 14:42 UTC, corykim0829 requested changes
수고하셨습니다! 

남겨드린 피드백 기반으로 조금 더 개선해봅시다 🔥

### 1. 테스트용 더미 데이터 어디에 둘지

> 🙋‍♂️[질문 ①] 데이터를 별도의 파일로 분리해도 괜찮을까요? BoxOfficeTests 폴더에 TestData 라는 폴더를 만들고 추가되는 데이터 파일을 분리하려고 하는데 괜찮은 방법인지, 코리라면 어떤식으로 작성하시는지 궁금해요

데이터를 별도의 파일로 분리하는 접근은 좋습니다. 관리하기 더 좋으니까요
이번에 String 타입 프로퍼티로 선언하셨는데 이 방법 보다는 json 파일로 관리하면 어떨까요?

> 🙋‍♂️[질문 ②] 분리한 더미 데이터 파일에는 dailyBoxOfficeData 변수만 정의하고 있어요. 어떤 타입이 아닌 변수만을 정의한 파일일 때 파일명은 대문자로 시작해야 하는지 소문자로 시작해야 하는지 궁금해요.
디오생각: 파일이 소문자로 시작하면 변수만을 담았다는 의미를 가지지 않을까! 생각했어요
제나생각: 파일명은 UpperCamelCase라는 원칙만 알고 있었는데, 디오 의견을 듣고 보니 그 배경은 생각해 본 적이 없는 듯해 문서를 찾아봤어요. 하지만 위 원칙의 이유나 기준을 더 찾을 수 없어 일단은 대문자로 시작하는 게 좋겠다고 생각했어요!

변수명은 소문자로 하는게 원칙이라기 보다는 가이드입니다!
때문에 두분이 정한 컨벤션이 그렇다면 소문자로 시작하는게 맞다고 생각해요. 
그리고 만약 이번 프로젝트 또는 팀에서 예외 컨벤션으로 json String 값을 저장하는 변수는 대문자로 시작한다는 내용을 문서화를 해두면 컨벤션을 지키는 것이기 때문에 괜찮다고 생각해요 😊

### 2. XCTAssertEqual 2줄 쓰기

제가 생각하기에는 하나의 객체가 디코딩 되는 부분을, 즉 하나의 기능을 테스트하고 있기 때문에 asset 한개 두개는 큰 의미가 없다고 생각합니다.
제가 직접 프로젝트를 빌드해봤는데, json 값을 변경했을 때의 실패 케이스일 때에도 success로 통과 되더라구요!
실패예외 처리를 한번 고민하면 좋을 것 같습니다.

2023-04-26 14:42 UTC, corykim0829 commented on BoxOffice/Model/MovieDTO/DailyBoxOffice.swift
> +// MARK: - DailyBoxOffice
struct명을 똑같이 언급하는 MARK 주석은 큰 의미가 없어 보여요!
없어도 될 것 같아요!

2023-04-26 14:42 UTC, corykim0829 commented on BoxOfficeTests/BoxOfficeTests.swift
> +              let name = parsedData?.boxOfficeResult.dailyBoxOfficeList.first?.name else { return }
여기서 return 처리가 되면 테스트 결과는 어떻게 되나요?

2023-04-26 14:42 UTC, corykim0829 commented on BoxOffice/Model/MovieDTO/DailyBoxOffice.swift
> +struct DailyBoxOffice: Codable {
지금은 Decoding만 하니 Decodable만 채택하면 좋을 것 같아요!

2023-04-27 06:47 UTC, doshkor commented on BoxOffice/Model/MovieDTO/DailyBoxOffice.swift
> +// MARK: - DailyBoxOffice
MARK 주석 제거 및 파일 분리 진행하였습니다.

해당 커밋: ff7df53

2023-04-27 06:48 UTC, doshkor commented on BoxOffice/Model/MovieDTO/DailyBoxOffice.swift
> +struct DailyBoxOffice: Codable {
`Decodable` 프로토콜만 채택하도록 변경하였습니다 

필요한 프로토콜만 채택하도록 해봐야 겠어요! :) 

해당 커밋: f42c41a

2023-04-27 07:54 UTC, ueunli commented on BoxOfficeTests/BoxOfficeTests.swift
> +              let name = parsedData?.boxOfficeResult.dailyBoxOfficeList.first?.name else { return }
return처리가 되면 `XCTAssertEqual(_:_:)`메서드를 거치지 않고 종료되기 때문에 Test Succeeded로 뜹니다 ...!🥲

기존 `parsedData`는 guard let 바인딩을 하지 않고 nil여부를 바로 검증하도록 구현했고, 
대신 더미데이터를 json파일로 저장하도록 수정함으로써(7277279) 테스트메서드에 `data`라는 변수로 가져오는 로직을 추가하며 새로운 guard-else문을 구현하게 되었어요.
테스트에 필수적인 데이터인 data를 가져오는 로직이 실패할 경우 테스트 할 수 없기 때문에 이번 else문에는 return이나 테스트 실패로 처리하는 대신 fatalError를 넣어 검증이 이루어지지 않도록 했어요.

\+) 말씀해주신 아래 문제는 Movie의 CodingKey 중 한 케이스의 원시값에 오타가 있어 디코딩 실패 → else { return } 되었기 때문이었으며, cfd0210 커밋에서 수정하였습니다 알려주셔서 감사합니다💚
> json 값을 변경했을 때의 실패 케이스일 때에도 success로 통과 되더라구요!

　
해당 커밋: 66b191c

2023-04-27 15:41 UTC, corykim0829 approved these changes
수고하셨습니다!

피드백 드린 부분은 다음 스텝 진행하면서 수정하시면 될 것 같아요 :)

2023-04-27 15:41 UTC, corykim0829 commented on BoxOfficeTests/BoxOfficeTests.swift
> +        XCTAssertNotNil(parsedData)
깔끔하네요 👍

2023-04-27 15:41 UTC, corykim0829 commented on BoxOfficeTests/BoxOfficeTests.swift
> +              let data = json.data(using: .utf8) else { fatalError("Data 생성 실패") }
guard else 부분은 개행해서 확실하게 구분을 해주는게 코드 읽기에 좋을 것 같아요!
그리고 fatalError가 아닌 테스트 fail 처리를 하는 방식을 찾아보면 좋을 것 같아요!

2023-04-27 15:41 UTC, merged