박스오피스앱 [Step1] 미르, 이안
tasty-code/ios-box-office pull request #30
Opened 2024-02-14 14:44 UTC by mireu930

@keeplo 안녕하세요 말꼬!
이번 박스오피스앱 STEP1 보내드립니다!
STEP1도 잘부탁드립니다!🙇

### 🤔 고민했던점
주어진 Json파일이 Movie타입에 맞게 파싱이 잘 이루어지는지 테스트하는 방법
초기화를 통해 movie 인스턴스 생성하고, 주어진 json데이터 중 일부를 복사해 jsondata 변수를 생성한 후,
Movie, BoxOfficeResult, WeeklyBoxOfficeList타입에 Equatable 채택해서 둘이 비교할 수 있도록 만들었습니다.

### 🧐 조언을 얻고 싶은 부분
Json파일 내에 모든 데이터를 테스트할 필요는 없다고 판단하여 위와 같이 테스트를 시행하였습니다.
이렇게 하는 방법이 적절한지 아니면 json파일을 asset파일에 추가해서 테스트하는 방향이 나을지 조언을 구하고 싶습니다.

2024-02-15 11:29 UTC, keeplo requested changes
안녕하세요! 이안, 미르!

퇴근 후에 리뷰를 하게되어 거의 만 하루가 다되어서 좀 늦어버렸네요 ㅠㅠ 죄송해요😭
최대한 늦지 않게.. 그리고 기왕이면 PR 올린 다음날 오전에 고민하실 수 있게
리뷰를 최대한 빨리 할 수 있게 노력하겠습니다!

---

#### 고민했던점
> 주어진 Json파일이 Movie타입에 맞게 파싱이 잘 이루어지는지 테스트하는 방법
> 초기화를 통해 movie 인스턴스 생성하고, 주어진 json데이터 중 일부를 복사해 jsondata 변수를 생성한 후,
> Movie, BoxOfficeResult, WeeklyBoxOfficeList타입에 Equatable 채택해서 둘이 비교할 수 있도록 만들었습니다.

제가 확인한 버전에는 `Movie` 개체가 없었는데 커밋이 꼬이거나 푸시가 안된 것 같아요! 확인 부탁드려요!
저는 현재 테스트 방식이 위험성을 가지고 있다고 생각해요!
만약 API 에서 불필요하기때문에 한 프로퍼티를 지운다고하면,
테스트 코드, Codable 채택한 타입 모두 수정해야하는 상황이 벌어질 수 있습니다.

#### 조언을 얻고 싶은 부분
> Json파일 내에 모든 데이터를 테스트할 필요는 없다고 판단하여 위와 같이 테스트를 시행하였습니다.
> 이렇게 하는 방법이 적절한지 아니면 json파일을 asset파일에 추가해서 테스트하는 방향이 나을지 조언을 구하고 싶습니다.

좋고 나쁘고는 없을 것 같아요! 목적이 중요하지 않을까 생각이 됩니다.
모든 설계와 구현에는 정답은 없고 기준과 설득/납득의 반복이라고 생각해요!
설명해주신 것처럼 모든 데이터가 파싱되는건 확인할 필요가 없다고 판단하신게,
예를들어 파일 크기가 커진다, 데이터가 많으니 다루기 불편하다 등의 이유가 있다면
지금 이대로도 너무 좋을것 같습니다.

다른 내용에 이야기는 리뷰 코멘트에 남겨두었습니다.

--- 

저는 반대로 소개해드리려고 했는데 https://app.quicktype.io/
사이트를 아신다는 데서 JSON 파싱에 경험이 두 분다 있는건 아닐까 생각을 했습니다.
만약 경험이 있으시고 원리를 아신다면 너무나 좋은 기회라고 생각합니다.

제가 언급한 부분들 뿐만 아니라 Swift에서 JSON을 다루는 `Codable` 이외의 프로토콜을 
찾아본다거나 방법을 찾아보는 것도 좋을것 같고,
API 를 좀 더 분석해서 앱에서 불 필요한 데이터를 제외해본다거나 하는 시간을 좀 더 가지면 좋을것 같습니다.

조금 아쉬웠던 부분은 네이밍 부분과 가독성 부분이 있을것 같아요.
프로개발자가 되기전까지는 만드는 것만 하게 되지만,
업무를 시작하면 만드는 일보다 바꾸는 일과 수정하는 일이 더 많을 수도 있어요

네이밍과 가독성을 고려한 코드를 작성하는 건 습관화해야하는 부분이라고 생각합니다.
`클린코드` `개발자의 글쓰기` 같은 대표적인 서적도 추천드릴 수 있을것 같고
[Swift 개발자처럼 변수 이름 짓기](https://soojin.ro/blog/english-for-developers-swift) 노수진님의 포스트도 추천드릴 수 있을것 같아요

다양한 정보를 습득하시고 경험하시면서 신경쓰시기 시작하면 습관이 되고
습관이 되면 나중에 유지보수라거나 협업에서 시간이라는 큰 비용을 아낄 수 있습니다!

---

제가 리뷰가 좀 늦어서 아마 Step 2도 많이 둘러보시고 설계도 해보셨을거라 생각하지만
Step 1에서 고민해볼 부분을 좀 더 해보면 좋을것 같아요!
베이스가 단단하면 다음 스텝은 더 쉽게 갈 수 있을거에요! 💪💪

2024-02-15 11:29 UTC, Marcorable commented on BoxOffice/BoxOfficeData.swift
> +}
혹시 https://app.quicktype.io/ 이 사이트 이용하셨나요..?;;
똑같이 나와서 놀랐네요 ㅎㅎ

가독성을 좀 더 좋게 변형해보면 좋을것 같아요!
그리고 변수명은 Swift에 어울리게 새로 지어서 Response JSON에 Key와 매핑해주면 좋을것 같아요!

CodingKey에 대해 좀 더 조사해보고 내부에서 사용될 Model 데이터에는 프로퍼티에 이름을 바꿔줘보면 어떨까요?

2024-02-15 11:29 UTC, Marcorable commented on BoxOffice/BoxOfficeData.swift
> +struct DailyBoxOfficeList: Codable {
실제로는 영화의 정보를 담는 개체라고 생각해요 

List 라는 명칭은 어울리지 않을것 같습니다.

2024-02-15 11:29 UTC, Marcorable commented on BoxOffice/BoxOfficeData.swift
> +struct BoxOfficeData: Codable {
Data 라는 명칭은 Foundation.NSData 에 포함된 `Data` 타입과 혼동을 줄 수도 있을 것 같아요!

JSON Response를 1차적으로 마주하는 개체이니 `Response` postFix 네이밍이 들어가면 어떨까요?

2024-02-15 11:29 UTC, Marcorable commented on BoxOffice/BoxOfficeData.swift
> +struct BoxOfficeData: Codable {
`Codable`을 사용해주셨군요!

Codable 프로토콜은 어떤 역할을 하는지 간단하게 소개해주실 수 있으신가요?
JSON 데이터를 디코딩하는 방법은 또 어떤게 있을까요?

2024-02-15 11:29 UTC, Marcorable commented on BoxOffice/extension+.swift
> +}
테스트를 위한 코드라면 본 앱에는 포함되지 않는게 좋지 않을까요?

2024-02-15 11:29 UTC, Marcorable commented on BoxOfficeTests/BoxOfficeTests.swift
> +        let dailyBoxOfficeList = DailyBoxOfficeList(rnum: "1", rank: "1", rankInten: "0", rankOldAndNew: RankOldAndNew(rawValue: "NEW") ?? .new, movieCD: "20199882", movieNm: "경관의 피", openDt: "2022-0
테스트에서 검증의 기준은 무엇으로 결정하셨나요?
데이터의 모든 프로퍼티의 값이 같아야 테스트 통과인가요?

2024-02-15 11:29 UTC, keeplo commented on BoxOfficeTests/BoxOfficeTests.swift
> +    func test_인스턴스를통한_Movie타입과Json데이터를_비교했을때_서로같다() {
이 `test_인스턴스를통한_Movie타입과Json데이터를_비교했을때_서로같다()` 테스트 메서드는 무엇을 테스트하시려는 걸까요?
문장만으로 파악하면 수기로 작성하신 Movie 초기화와 JSON 데이터에 내용이 같은지를 테스트하는것처럼 느껴집니다.

저는 만들어주신 "모델이 Decodable 기능을 잘 수행해서 JSON 데이터를 파싱에 성공하는지"가 
테스트의 목표점이 되는게 좋지 않을까 생각했어요
그렇다면 꼭 특정한 인스턴스를 만들지 않고 테스트를 구성할 수도 있을거 같아요

~~~swift
// when
let decodedValue = try? JSONDecoder().decode(BoxOfficeData.self, from: data)
// then
XCTAssertNotNIl(decodedValue)
~~~

이러면 코드에서도 데이터 파싱이 성공하는지를 테스트한다는게 강하게 느껴질것 같습니다.

2024-02-15 11:29 UTC, keeplo commented on BoxOffice/BoxOfficeData.swift
> +enum RankOldAndNew: String, Codable {
네이밍을 좀 더 고민해보면 좋을것 같아요

API와 API에서 내려주는 데이터에 대한 분석을 해본다면 
이 데이터가 어떤 형태로 쓰일지 유추해 볼 수 있을것 같아요
특히 case를 구분해주는 용도의 `enum` 데이터이기 때문에
old & new 를 모두 아우를 수 있는 큰범위에 네이밍을 지어주면 어떨까요?
단순히 `Rank`로 짓는것도 현시점에선 나쁘지 않을것 같은데 
`DailyBoxOfficeList` 타입에서 같은 네이밍이 있기때문에 다른 아이디어를 내는게 좋아보여요!

2024-02-15 11:29 UTC, keeplo commented on BoxOffice/JsonData.swift
> +}
이 파일은 테스트 만을 위한 데이터이기 때문에 저는 `BoxOfficeTests` 폴더에 있는 게 좋을 것 같아요!

JSON 파일을 만들어서 불러오는 방법도 나쁘지 않을것 같습니다!

2024-02-15 14:18 UTC, mireu930 commented on BoxOfficeTests/BoxOfficeTests.swift
> +        let dailyBoxOfficeList = DailyBoxOfficeList(rnum: "1", rank: "1", rankInten: "0", rankOldAndNew: RankOldAndNew(rawValue: "NEW") ?? .new, movieCD: "20199882", movieNm: "경관의 피", openDt: "2022-0
네이밍을 병합하다가 수정을 못햇네요,,😅
테스트 검증기준은 BoxOfficeDataResponse(BoxOfficeData)초기화한 타입과 JSON데이터를 비교했을때 같다면
JSON데이터를 파싱하는데 성공했다라는 것을 보여주기 위함이였습니다!

2024-02-15 14:31 UTC, mireu930 commented on BoxOfficeTests/BoxOfficeTests.swift
> +    func test_인스턴스를통한_Movie타입과Json데이터를_비교했을때_서로같다() {
위에서도 말씀드리긴 했지만 BoxOfficeDataResponse(BoxOfficeData)초기화한 타입과 JSON데이터를 비교했을때 같다면
JSON데이터를 파싱하는데 성공했다라는 것을 보여주기 위함이였습니다만, 테스트의 가독성측면에서 디코딩이 잘수행해서 JSON 데이터를 잘파싱을 성공하기 보여주는 간단하게 테스트를 진행해도 좋아보여 수정해봤습니다!

2024-02-15 14:35 UTC, mireu930 commented on BoxOffice/BoxOfficeData.swift
> +}
[해당커밋](https://github.com/tasty-code/ios-box-office/pull/30/commits/9b9007ac5f7559759134be5923d53a3178aa99bb)에서 수정하였습니다!

2024-02-15 14:36 UTC, mireu930 commented on BoxOffice/BoxOfficeData.swift
> +struct DailyBoxOfficeList: Codable {
영화의 정보에 초점을 맞춰`DailyBoxOfficeInfo`라고 수정했습니다.

2024-02-15 14:36 UTC, mireu930 commented on BoxOffice/BoxOfficeData.swift
> +struct BoxOfficeData: Codable {
`BoxOfficeDataResponse`라고 수정했습니다.

2024-02-15 14:37 UTC, mireu930 commented on BoxOffice/extension+.swift
> +}
테스트를 위한 코드라 Test파일에 따로 분리해줬습니다!

2024-02-15 14:40 UTC, mireu930 commented on BoxOffice/BoxOfficeData.swift
> +enum RankOldAndNew: String, Codable {
순위를 매긴다라는 다른 네이밍이 어느것이 적절한지 어렵네요,,🤔
세대에 대한 구별됨을 주기위한 네이밍으로 `GenerationCheck`라고 수정해봤습니다

2024-02-15 15:07 UTC, mireu930 commented on BoxOffice/BoxOfficeData.swift
> +struct BoxOfficeData: Codable {
Codable은 JSON데이터를 인코딩과 디코딩을 해줄수 있는 프로토콜입니다.
[`JSONSerialization`](https://developer.apple.com/documentation/foundation/jsonserialization)클래스를 이용하여 JSON을 Foundation 객체로 변환하고 Foundation 객체를 JSON으로 변환한하는 방법이 있습니다.

2024-02-16 12:10 UTC, Marcorable commented on BoxOffice/BoxOfficeData.swift
> +struct BoxOfficeData: Codable {
말씀해주신 방법처럼 디코딩 방법은
Obj-C 부터 전통적으로 `JSONSerialization` 이용한 방법
Codable = Decodable & Encodable
두 가지가 대표적입니다!

현 시점에서 Codable은 잘 이해하고 잘 사용해주셨어요!! 👍🏼

그리고 배경지식을 위해 한가지 더 소개해드리면 지금처럼 모든 개체 타입을 생성하지 않고
CodingKeys 타입을 중첩으로 작성해서도 API 특성으로 묶여 있는 `BoxOfficeResult` 정도는 생략할 수 있게 만들 수도 있습니다.

[[iOS - swift] json, codable, nestedContainer(keyedBy:forKey:), Decoding 중첩 모델 처리 방법 (디코딩)](https://ios-development.tistory.com/869)

블로그를 참고해보세요!

2024-02-16 12:10 UTC, Marcorable commented on BoxOffice/extension+.swift
> +}
테스트가 제가 추천한 방식으로 바뀌었다면..
이 파일이 제거되는건 어떻게 생각하시나요?

2024-02-16 12:11 UTC, keeplo commented on BoxOffice/BoxOfficeData.swift
> +enum RankOldAndNew: String, Codable {
전반적으로 각 데이터의 목적을 잘 추측해주신것 같아요!!

2024-02-16 12:14 UTC, merged

2024-02-16 13:53 UTC, mireu930 commented on BoxOffice/BoxOfficeData.swift
> +enum RankOldAndNew: String, Codable {
말씀주신거처럼 특정구분을 가지고 가독성있게 구분짓기 어려워 줄바꿈해서 각각 선언해줬습니다!