박스오피스 앱 [STEP1] 이지, 희동
tasty-code/ios-box-office pull request #32
Opened 2024-02-16 04:08 UTC by MyNB1

@minsson
안녕하세요 민쏜~~
박스오피스 프로젝트를 함께하게 된 이지, 희동입니다! 🙇🏻‍♀️
앞으로 잘 부탁드려요! ☺️ 

---

## ✅ **요구사항 & 체크리스트**
- [x]  파싱한 JSON 데이터와 매핑할 모델 설계
- [x]  CodingKeys 프로토콜의 활용
- [x]  단위 테스트(Unit Test)를 통한 설계의 검증

## 🙌🏻 PR Point
이번 STEP은 구현할 사항들이 많지 않아 질문드릴 부분은 많지 않네요..!
앞으로 API 호출을 위한 DTO 설계와 json파싱, 유닛테스트에 익숙해지기가 이번 STEP의 포인트로 느껴졌습니다.

## 🤔고민과 해결
### Xcode target 설정
유닛테스트 과정에서 많은 시행착오가 있었는데 그 중 target 설정때문에 일어난 오류가 많았습니다.
![image](https://hackmd.io/_uploads/HkCpd4njp.png)
![image](https://hackmd.io/_uploads/HyuOu4hoa.png)

유닛테스트가 `BoxOffice` 번들에 접근하지 못하게 설정이 되어있어  Target Membership 을 수정해 해결했습니다.
그리고 파싱할 json 파일의 경로를 찾지 못하는 오류는 `Build Phases`의 `Copy Bundle Resources`에 해당 파일을 추가해 해결하였습니다.

### DTO와 json의 속성명 매칭
```swift
extension BoxOfficeResultDTO {
    struct BoxOfficeDTO: Decodable {
        let boxOfficeType: String
        let dateRange: String
        let dailyBoxOfficeList: [MovieInfo]?
    }
}
```
```swift!
{
    "boxOfficeResult": {
        "boxofficeType": "일별 박스오피스",
        "showRange": "20240202~20240202",
        "dailyBoxOfficeList": [
        ...
```
DTO는 json등의 데이터를 송수신 하기 위한 객체입니다.
따라서 DTO모델 속성의 네이밍과 받아올 json의 속성명들이 정확하게 일치하지 않으면 파싱 에러가 나는 것을 확인할 수 있었습니다.

```swift
extension BoxOfficeResultDTO.BoxOfficeDTO {
    enum CodingKeys: String, CodingKey {
        case dateRange = "showRange"
        case boxOfficeType = "boxofficeType"
        case dailyBoxOfficeList
    }
}
```
위와 같이 `CodingKey` 프로토콜을 활용하면 json 속성명을 프로젝트 상의 네이밍 컨벤션에 맞추거나 원하는 이름으로 커스텀 할 수 있습니다.

## 🧐 궁금했던 점

유닛테스트 실행시 문제없이 동작하던 코드가 가끔씩 데이터 파싱과정에서 오류가 발생하는 경우가 있었는데 단순 xcode의 자체에서 발생하는 오류인지 궁금합니다..! 민쏜도 이런 경우가 있었나요?

2024-02-19 11:58 UTC, minsson requested changes
안녕하세요, 이지, 희동! 박스오피스 앱 첫 PR이군요! 
저도 앞으로 잘 부탁드려요!

우선 PR을 너무 깔끔하게 잘 정리해주셨네요! 덕분에 어떤 고민을 하셨고, 어떻게 해결했는지 일목요연하게 볼 수 있어서 정말 좋았어요.

문제들을 잘 해결해주셨네요.
특히 DTO와 json의 속성명 매칭은 저도 여전히 가끔가다 실수하는 부분이라 공감이 되었어요.

이와 관련해, [quicktype](https://app.quicktype.io/)이라는 게 있어요! (이미 아실 수도 있지만요.)
앞으로 네트워킹 작업도 하실텐데, json 형태의 파일을 복사+붙여넣기 해놓으면 알아서 모델 객체를 생성해줘서 무척 편리하게 사용할 수 있어요. 

이번 스텝에서 직접 타이핑해보며 CodingKey의 개념을 학습해본 건 한번쯤 꼭 해봐야 하는 경험이라고 생각해요. 다만 개념이 익숙해지면 불필요한 반복 작업을 계속 할 필요는 없으니 참고하시면 좋을 것 같아요. 저는 즐겨찾기에 넣어 두고 자주 사용하는 편이에요.

남은 리뷰는 코드에 개별 코멘트로 남겨놓을게요!

### 질문에 대한 답변
> 유닛테스트 실행시 문제없이 동작하던 코드가 가끔씩 데이터 파싱과정에서 오류가 발생하는 경우가 있었는데 단순 xcode의 자체에서 발생하는 오류인지 궁금합니다..! 민쏜도 이런 경우가 있었나요?

음… 저는 겪어본 적이 없어서 확답을 드리기는 어려울 것 같아요. 우선 생각나는 게 json 데이터에서 null이 포함되어 있는 프로퍼티가 있는데, 모델 객체에서 그 프로퍼티의 타입을 Optional로 선언하지 않아서 에러가 발생하는 경우가 있는데, 프로젝트 내의 json 파일을 보니 그런 건 안 보이네요. 혹시 아직 해결이 안 되었다면 어떤 상황인지 더 자세히 공유해주실 수 있나요? 구체적으로 어떤 상황에서 어떻게 해당 상황이 발생하고, 어떤 에러메시지가 뜨는지에 대해 알아야 함께 논의해볼 수 있을 것 같아요.

2024-02-19 11:58 UTC, minsson commented on BoxOfficeUnitTest/JsonParser.swift
> +class JsonParser {
class, struct, enum 중 class를 선택한 이유가 무엇인가요?

2024-02-19 11:58 UTC, minsson commented on BoxOfficeUnitTest/JsonParser.swift
> +    }
`parseJson()`이라는 네이밍은 무척 범용적으로 느껴지는데, 사실은 `MovieData.json` 파일만을 파싱하기 위한 메서드고, `BoxOfficeResultDTO?`라는 고정된 타입을 반환하고 있어요. 이름에 맞게 더 범용적인 메서드를 만들거나, 더 구체적인 네이밍을 쓰면 좋을 것 같아요.

2024-02-19 11:58 UTC, minsson commented on BoxOffice/DTO/BoxOfficeResultDTO.swift
> +}
extension으로 Nested Struct를 따로 빼니 깔끔하네요!

2024-02-19 11:58 UTC, minsson commented on BoxOffice/DTO/BoxOfficeResultDTO.swift
> +}
`Decodable`을 써주셨는데, `Codable`, `Encodable`, `Decodable`에 대해 간단하게 설명해주실 수 있나요?

2024-02-19 11:58 UTC, minsson commented on BoxOfficeUnitTest/BoxOfficeTest.swift
> +    var sut: JsonParser!
```suggestion
    private var sut: JsonParser!
```

2024-02-19 11:58 UTC, minsson commented on BoxOfficeUnitTest/BoxOfficeTest.swift
> +        let expectation: String? = "일별 박스오피스"
expectation의 타입이 `String?`인 이유는 무엇인가요?

2024-02-19 11:58 UTC, minsson commented on BoxOfficeUnitTest/BoxOfficeTest.swift
> +}
- 테스트 이름은 영화이름을 파싱한다는 내용인데, expectation은 `일별 박스오피스`라고 되어 있어 잘 이해가 되지 않아요.
- `let result = sut.parseJson()?.boxOfficeResult.boxOfficeType`의 가독성이 좋지 않아요. 한 줄에서 너무 깊이 들어가고 있어서 그런 것 같은데, 여러 단계로 나눠볼 수 있을까요?

2024-02-20 01:39 UTC, yoruck2 commented on BoxOfficeUnitTest/JsonParser.swift
> +    }
그렇네요.. STEP2에서 반영 하겠습니다!

2024-02-20 03:42 UTC, yoruck2 commented on BoxOfficeUnitTest/JsonParser.swift
> +class JsonParser {
원래 NetworkManage 클래스를 만들다가 테스트를 위해 바꾸는 과정에서 생각하지 못했네요.. struct가 더 적절할 것 같습니다!

2024-02-20 04:40 UTC, yoruck2 commented on BoxOfficeUnitTest/BoxOfficeTest.swift
> +    var sut: JsonParser!
접근제어자..  신경쓰겠습니다!!

2024-02-20 04:55 UTC, yoruck2 commented on BoxOfficeUnitTest/BoxOfficeTest.swift
> +        let expectation: String? = "일별 박스오피스"
실수인 것 같습니다.. 붙인 이유가 떠오르지 않네요..😂

2024-02-20 04:56 UTC, MyNB1 commented on BoxOffice/DTO/BoxOfficeResultDTO.swift
> +}
Codable: 자기 자신을 변환하거나, 외부의 표현으로 변할 수 있는 타입
Encodable: swift데이터의 형태를 외부데이터 형태로 변환
Decodable: 외부데이터 형태를 swift데이터 형태로 변환
으로 이해하고 있습니다

2024-02-20 07:05 UTC, yoruck2 commented on BoxOfficeUnitTest/BoxOfficeTest.swift
> +}
1. 영화이름을 비교하는 테스트에서 바꾸다가 테스트명을 바꾸지 않았었네요.. 다음엔 좀 더 꼼꼼히 확인 하겠습니다!!

2. 
```swift
let boxOfficeResult = sut.parseJson()?.boxOfficeResult

let result = boxOfficeType
```
이런식으로 나눠볼 수 있겠네요

2024-02-24 06:00 UTC, minsson commented on BoxOffice/DTO/BoxOfficeResultDTO.swift
> +}
어딘가에서 정리해놓은 글이 아니라, 자신의 언어로 명쾌하게 표현해주시니 좋네요!! 다만 일반적으로 서버 등 외부의 json 파일을 가져다 쓸 때 많이 쓰기는 하지만 완전히 '외부 데이터'라고만 생각하면 오해의 여지가 있을 것 같다는 점만 덧붙이겠습니다. 예를 들어 키체인에 저장할 때도 Data 타입으로 Encoding이 필요할 수 있어요.

2024-02-24 06:02 UTC, minsson commented on BoxOfficeUnitTest/BoxOfficeTest.swift
> +}
넵, 다만 다른 코멘트에서도 말씀드렸던 것처럼 `parseJson()`이라는 네이밍이 잘 와닿지 않으니, 이 부분은 Step 2에서 다시 생각해보시면 좋을 것 같아요!

2024-02-24 06:02 UTC, merged