박스오피스 앱 [Step 2] 댄, L
tasty-code/ios-box-office pull request #33
Opened 2024-02-16 08:27 UTC by eensungkim

Step 2
멤버 : @eensungkim, @LeeSe0ngYe0n
리뷰어 : @ryan-son

박스오피스 앱 프로젝트의 두 번째 스텝입니다!
정리하여 PR 드립니다. 잘 부탁드립니다! :bow: 

# PR 상세
- `DTO` 에 네트워크 통신 기능 구현
- `API` 문서에 따른 `URL` 열거형 추가
- 네트워크 통신 `Unit Test` 추가(`Test Double` 활용)
</br>

# 이번 스텝을 통해서 배운 점
- `URLSession` 학습
- `async/await` 학습
- `*.plist` 파일을 활용한 안전한 키 보관
- `Test Double` 학습
    - `Dummy`, `Fake` 적용
- Extension 활용
- 열거형 `Associated Value` 학습 및 활용
</br>

# 구성
## Utility
### Extension
**BoxOffice_BundleExtension.swift**
- `APIKey.plist` 에 보관된 `API Key` 를 가져올 수 있도록 구현
 
### Enumeration
**KoreanFilmCouncilURLEnumeration.swift**
- 오늘의 일일 박스 오피스, 영화 개별 상세 조회를 위한 `URL` 관리용 열거형

**HTTPStatusError.swift**
- 수신한 상태 코드에 따른 내부 활용을 위한 에러 열거형

**APIKey.plist**
- `API Key` 를 관리할 `property list` 파일
- 깃 추적 중지를 활용하여 `API Key` 가 노출되지 않도록 구현

### BoxOfficeDTO.swift
- 파싱을 담당할 `DTO` 클래스

### BoxOfficeStructure.swift
- `JSON` 데이터와 매핑할 모델 구조체

### box_office_sample.json
- 미리 제공된 샘플 `JSON` 데이터

## Controller
### BoxOfficeViewController.swift
- 네트워크 통신 확인을 위해 `init()` 에 임시 로직 구현

## Model
### BoxOfficeDTO.swift
- API 데이터 요청 및 파싱을 담당하는 `DTO` 구조체

## Unit Test
### Utility
**FakeBoxOfficeDTO.swift**
- 데이터 요청 부분만 `FakeServer` 와 주고받는 테스트 더블용 `fake` 구조체

**FakeServer.swift**
- 테스트를 위해 네트워크 요청을 대신할 가짜 서버

### Resource
- 테스트용 샘플 `json` 파일

### ParseJSONDataTests.swift
- `ParseJSONDataTests` 타입 메서드 동작에 관한 유닛 테스트

### RequestDataTests.swift
- `RequestDataTests` 타입 메서드 동작에 관한 유닛 테스트

</br>

# 질문
- 이번 스텝에서는 `DTO`를 타입 메서드를 갖는 구조체로 구현했습니다. 이렇게 하고 나니 테스트를 위해 `sut(system under test)` 를 활용할 수 없는 구조가 되어, 일단 이 부분을 삭제할 수 밖에 없었는데요.
현재 구현에서는 메서드의 동작을 확인하면 되기 때문에 굳이 `sut`가 필요하지 않다는 생각도 들었습니다.
이렇게 `Unit Test` 를 구현해도 문제가 없는 것일까요?

- `HTTP` 상태 코드 중 100 번대 코드는 정보 교환을 위한 코드라고 해서, 에러 상황이라고 판단하지 않아 특별히 이를 위한 열거형 `case` 를 따로 구현해주지는 않았습니다.
100번대 코드도 에러라고 볼 수 있는 걸까요?

- `rootViewController` 의 역할을 `BoxOfficeViewController` 가 하고 있고, 현재 구현에서는 박스오피스 뷰컨트롤러가 초기화될 때 비동기 통신을 요청하여 화면에 노출하게 될 데이터를 불러오게 됩니다.
    1) 조금 더 빠르게 데이터를 불러오기 위해 박스오피스 뷰컨트롤러를 초기화 하기 전에 데이터를 미리 요청하고 저장할 수 있도록 하는 것이 더 나은 방법일까요?
    2) `init()`` 내부에서 자체적으로 데이터를 불러오고 있는 상황인데, 혹시 이 데이터가 외부에서 주입되는 것이 더 유연한 코드가 되는 것일까요?

- 무한정 에러를 상위 함수를 전파할 수는 없다 보니, 결국 누군가는 에러 처리에 대한 책임을 가져야 하는 것 같습니다. 
이때 에러 처리를 담당해야 하는 기준이 있다면 무엇일까요?
`DTO` 객체가 에러 처리를 최종적으로 담당하여 `ViewController` 가 불필요한 에러 처리까지 책임지지 않도록 해야 한다고 생각해서 지금은 보시는 것처럼 구현을 진행했습니다.

2024-02-18 17:34 UTC, ryan-son requested changes
L, 댄, Step 2 수행하시느라 고생 많으셨습니다.

이번에는 변경사항이 조금 있을 것 같네요. 개별 코멘트를 확인해보시면 더 이해하시기 좋으실거에요. 본문에서는 PR에 남겨주신 질문만 다루도록 하겠습니다.

># 질문
>- 이번 스텝에서는 `DTO`를 타입 메서드를 갖는 구조체로 구현했습니다. 이렇게 하고 나니 테스트를 위해 `sut(system under test)` 를 활용할 수 없는 구조가 되어, 일단 이 부분을 삭제할 수 밖에 없었는데요.
>현재 구현에서는 메서드의 동작을 확인하면 되기 때문에 굳이 `sut`가 필요하지 않다는 생각도 들었습니다.
>이렇게 `Unit Test` 를 구현해도 문제가 없는 것일까요?

질문을 명확하게 이해하지는 못했지만, 현재의 DTO는 `데이터 송수신 간 데이터 표현`이라는 역할 이상의 책임을 지고 있는 것으로 보입니다. 역할에 맞는 책임만 지도록 만드려면, 네트워크 인프라를 책임지는 타입, 그 인프라를 이용해 특정 endpoint에 요청을 만들어 보내고 처리하는 타입으로 나누는 것을 시작으로 더 적절한 형태의 단위 테스트를 구성해보실 수 있으실 겁니다.

>- `HTTP` 상태 코드 중 100 번대 코드는 정보 교환을 위한 코드라고 해서, 에러 상황이라고 판단하지 않아 특별히 이를 위한 열거형 `case` 를 따로 구현해주지는 않았습니다.
>100번대 코드도 에러라고 볼 수 있는 걸까요?

통상 400, 500번대를 제외한 상태 코드는 에러라고 판단하지는 않습니다. 주로 200, 400, 500번대 상태 코드를 다루시게 되므로 다른 상태 코드들은 종류만 이해하고 계시면 됩니다. 서버에서 예상한 상태 코드와 다른 코드를 응답했다면 유효하지 않은 상태 코드 에러 케이스로 처리해볼 수 있습니다.

>- `rootViewController` 의 역할을 `BoxOfficeViewController` 가 하고 있고, 현재 구현에서는 박스오피스 뷰컨트롤러가 초기화될 때 비동기 통신을 요청하여 화면에 노출하게 될 데이터를 불러오게 됩니다.
>    1) 조금 더 빠르게 데이터를 불러오기 위해 박스오피스 뷰컨트롤러를 초기화 하기 전에 데이터를 미리 요청하고 저장할 수 있도록 하는 것이 더 나은 방법일까요?

아니요. 코드상 몇 라인 먼저 요청한다고 하더라도 유의미하게 데이터를 일찍 응답받지 못합니다. 네트워크, 파일 쓰기 작업과 같은 IO 작업은 사용자도 시간이 필요함을 인지하고 있으므로 이에 따른 사용자 경험(UX)만 잘 디자인해주면 됩니다. 자주 사용하는 방식으로는 로딩 인디케이터 표시(Apple 등), 스켈레톤 UI 구성(YouTube 등), 앱의 첫 화면이라면 스플래시 화면에서 메인 화면의 데이터를 받아올 때까지 대기하게 만들기와 같은 방법이 있습니다.

>    2) `init()`` 내부에서 자체적으로 데이터를 불러오고 있는 상황인데, 혹시 이 데이터가 외부에서 주입되는 것이 더 유연한 코드가 되는 것일까요?

`ViewController`와 상태를 다루는 타입을 나누고, 상태를 다루는 타입에서 `BoxOffice`와 관련된 endpoint로 요청을 보내고 처리하는 타입의 프로토콜에 의존하게 만드는 방법으로 더 유연한 구조를 만들 수 있습니다. 이렇게 구성한다면, 네트워크 요청을 처리하는 타입의 프로토콜을 준수하는 Mock 타입을 구성해 실제 네트워크 요청을 하지 않고도 의도한 응답을 반환하게 만들 수 있습니다. 또 다른 방법으로는 [`URLProtocol`](https://developer.apple.com/documentation/foundation/urlprotocol)을 이용해 직접 네트워크 요청을 중간에 가로채 의도한 응답으로 변경하는 방법을 사용할 수 있습니다. 후자의 방법은 WWDC18에서 소개된 적이 있으니 궁금하시면 참고해보세요.

- [Testing Tips & Tricks - WWDC18](https://developer.apple.com/videos/play/wwdc2018/417/)

>- 무한정 에러를 상위 함수를 전파할 수는 없다 보니, 결국 누군가는 에러 처리에 대한 책임을 가져야 하는 것 같습니다. 
>이때 에러 처리를 담당해야 하는 기준이 있다면 무엇일까요?
>`DTO` 객체가 에러 처리를 최종적으로 담당하여 `ViewController` 가 불필요한 에러 처리까지 책임지지 않도록 해야 한다고 생각해서 지금은 보시는 것처럼 구현을 진행했습니다.

전파한 에러를 어느 수준에서 끊고 처리하게 만들지는 팀의 기준에 따라 다를 수 있습니다. 제 경우에는 가장 그 에러를 잘 파악할 수 있는 타입에서 처리하되 에러가 발생하면 얼럿 표시와 같은 책임을 가진 타입에서 해당 에러가 일어난 이유와 해결 방법을 사용자에게 제공하도록 구성합니다.

궁금하신 점 있으시면 언제든지 말씀해주세요. 고생 많으셨습니다.

2024-02-18 17:34 UTC, ryan-son commented on BoxOffice.xcodeproj/project.pbxproj
>  				8A8903842B7B756200E0A48D /* View */,
View 폴더는 제거된 것 같은데 reference는 제거되지 않은 것 같네요. 실제 디렉토리 정보와 `project.pbxproj` 파일을 일관성 있게 유지해야 팀원들이 혼동하지 않을 수 있을거에요.

2024-02-18 17:34 UTC, ryan-son commented on BoxOffice.xcodeproj/project.pbxproj
> +				9BB8EB062B7DE94500B33116 /* MovieStructure.swift */,
모델의 모음인데 파일 이름이 `-Structure`이라는 것은 조금 의아한 면이 있네요. 도메인 모델의 타입 이름을 그대로 따르면 좋을 것 같습니다.

2024-02-18 17:34 UTC, ryan-son commented on BoxOffice.xcodeproj/project.pbxproj
> +			);
`KoreanFilmCouncilURL`과 `HTTPStatusError`는 같은 열거형 타입이더라도 목적이 다를 것 같네요. 조금 더 관련있는 타입과 함께 모아두는 편이 좋을 것 같아요. 이 경우에는 인프라 수준의 네트워킹 기능을 제공하는 곳에는 `HTTPStatusError`를, 해당 인프라를 이용해 실제 의도한 Endpoint에 요청하는 곳에는 `KoreanFilmCouncilURL`을 위치시키는 것이 적절해보입니다.

2024-02-18 17:34 UTC, ryan-son commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        }
1. 네트워크 요청은 ViewController 초기화 시점에도 이루어질 수 있지만, 일반적으로는 `viewDidLoad` 시점에 수행합니다. ViewController가 인스턴스가 생성되는 시점이 반드시 화면에 표시되어야하는 시점이 아닐 수 있기 때문입니다.
2. 네트워크 요청 로직은 동일한 화면에서 여러번 수행될 수도 있으므로 네트워크 요청 로직을 재사용 가능하게 메서드로 분리해보세요. 여러분께서도 Pull to refresh와 같은 사용자 경험을 통해 많이 경험해보셨을 것 같네요.
3. DTO(Data Transfer Object)는 말 그대로 데이터 송수신 간 사용되는 타입이라는 점을 고려해보면 직접 네트워크 로직을 수행하는 책임을 가지고 있다는 것이 의아하게 느껴지네요. 이 경우에는 네트워크를 통해 데이터를 요청하고 가져와 파싱하는 타입(파싱하는 타입을 별도로 분리할 수도 있음)과 `BoxOfficeResult`를 관리하는 타입 하나를 둘 수 있을 것 같습니다.

2024-02-18 17:34 UTC, ryan-son commented on BoxOffice/Model/BoxOfficeDTO.swift
> +    static func requestData(with url: String) async -> Data? {
앞서 말씀드린 것처럼 DTO 타입이 네트워크 요청을 만들고 처리하는 것은 본인의 책임을 넘어선 것이라고 볼 수 있습니다. 네트워크 요청을 만들고 처리하는 타입을 분리해보고, DTO는 데이터 송수신 간 데이터 표현만을 위한 역할만 수행하도록 변경해보는 것이 어떨까요?

2024-02-18 17:34 UTC, ryan-son commented on BoxOffice/Model/BoxOfficeDTO.swift
> +            let data = try await URLSession.shared.data(from: URL)
1. 이미 알고계시듯이 `data(from:)` 메서드는 data와 response를 반환합니다. 튜플을 사용하는 대신에 명시적으로 변수를 사용할 수 있도록 `let (data, response)`로 변경해보는 건 어떨까요? 
2. 네트워크 요청을 만들고 처리하는 타입도 경우에 따라 커스텀 세션 인스턴스를 필요로 할 수도 있습니다. `URLSession` 인스턴스의 의존성을 분리해볼까요?
3. 네트워크 요청과 처리가 처음인만큼 Swift Concurrency를 지원하는 `data(from:)` 메서드 대신 `dataTask` 메서드를 이용하는 방법도 학습해보셨으면 좋겠습니다. 이미 작성된 코드들 중에는 dataTask를 이용한 방식이 아직 많이 남아있습니다.

2024-02-18 17:34 UTC, ryan-son commented on BoxOffice/Model/BoxOfficeDTO.swift
> +        }
애써 에러를 throw했는데 프린트 후 nil 반환만 한다면 수고한 것이 조금 아까울 수 있겠네요. 던진 에러를 받는 곳에서 사용자에게 에러를 어떻게 표현할지 처리하는 로직을 작성해보면 좋겠습니다.

2024-02-18 17:34 UTC, ryan-son commented on BoxOffice/Model/BoxOfficeDTO.swift
> +            return data
이 로직은 범용적으로 사용될 수 있으니 `BoxOfficeDTO`가 가지지 않아도 괜찮을 것 같네요. 파싱 로직을 책임지는 별도의 타입을 구성하거나, 네트워크 인프라 타입의 로직으로 포함하거나, Free funciton으로 두는 것도 방법일 것 같습니다. 그런데, JSONDecoder의 `decode(_:from:)` 메서드와 throw 여부 및 반환 타입만 다른데 별도 메서드로 구성한 이유가 무엇인가요?

2024-02-18 17:34 UTC, ryan-son commented on BoxOffice/Model/MovieStructure.swift
> +    }
CodingKeys를 외부에 공개해야할 필요가 없다면 private으로 만들어 줄 수 있을 것 같습니다.

2024-02-18 17:34 UTC, ryan-son commented on BoxOffice/Utility/APIKey.plist
API Key를 property list에 위치시켰을 경우 리버스 엔지니어링 시 쉽게 API Key를 탈취할 수 있습니다. 패키징되어 출시되는 앱 번들 내부에 property list가 암호화되지 않은 상태로 존재하기 때문입니다. 탈취한 API Key로 여러분의 의도하지 않은 요청을 보낸다면 API Key가 접근 제한을 당하거나, 예상치 못한 요금이 청구될 수 있습니다. API Key를 안전하게 다루기 위해 어떤 옵션들을 선택할 수 있을지에 대해 알아보시면 좋겠습니다.

2024-02-18 17:34 UTC, ryan-son commented on BoxOffice/Utility/Enumeration/HTTPStatusError.swift
> +}
이런 에러를 반환하는 것도 나름 의미있을 수 있지만, `invalidStatusCode(Int)`와 같은 케이스 하나로 처리해줄 수도 있을 것 같습니다.

2024-02-18 17:34 UTC, ryan-son commented on BoxOffice/Utility/Enumeration/KoreanFilmCouncilURLEnumeration.swift
> +enum KoreanFilmCouncilURLEnumeration {
타입 이름에 Enumeration이 포함되지는 않아도 좋을 것 같네요.

2024-02-18 17:34 UTC, ryan-son commented on BoxOffice/Utility/Enumeration/KoreanFilmCouncilURLEnumeration.swift
> +    case movieDetailInformation(String, String)
케이스의 associated value에 매개변수 이름을 달아주지 않는다면 사용하는 입장에서 어떤 내용을 작성해야할지 알 수 없게 됩니다. 케이스 이름으로부터 당연히 유추되는 내용이 아니라면 아래와 같이 매개변수 이름을 달아보는 게 좋겠습니다.

```swift
case dailyBoxOffice(key: String, targetDate: String)
```

2024-02-18 17:34 UTC, ryan-son commented on BoxOffice/Utility/Enumeration/KoreanFilmCouncilURLEnumeration.swift
> +    }
1. https://kobis.or.kr/kobisopenapi/webservice/rest는 중복되는 내용이네요. 케이스별 필요한 path와 query parameter만 다룰루도록 구성해볼 수 있을 것 같습니다.
2. 동일한 endpoint에 GET, POST 등의 요청을 처리할 때 매개변수가 서로 달라 곤란해질 수 있을 것 같은데요, 동일한 endpoint에 다른 HTTP method를 통해 요청해야한다면 이 열거형의 케이스를 어떻게 다루실 예정이실까요?
3. URL 구성 방식을 변경하라는 것은 아니지만, [URLComponents](https://developer.apple.com/documentation/foundation/urlcomponents)에 대해서도 알아보시면 좋겠습니다.

2024-02-18 17:34 UTC, ryan-son commented on BoxOffice/Utility/Enumeration/KoreanFilmCouncilURLEnumeration.swift
> +    }
1. https://kobis.or.kr/kobisopenapi/webservice/rest는 중복되는 내용이네요. 케이스별 필요한 path와 query parameter만 다룰루도록 구성해볼 수 있을 것 같습니다.
2. 동일한 endpoint에 GET, POST 등의 요청을 처리할 때 매개변수가 서로 달라 곤란해질 수 있을 것 같은데요, 동일한 endpoint에 다른 HTTP method를 통해 요청해야한다면 이 열거형의 케이스를 어떻게 다루실 예정이실까요?
3. URL 구성 방식을 변경하라는 것은 아니지만, [URLComponents](https://developer.apple.com/documentation/foundation/urlcomponents)에 대해서도 알아보시면 좋겠습니다. URL을 구성하는 로직을 작성하시는 데 도움이 될거예요.

2024-02-18 17:34 UTC, ryan-son commented on BoxOfficeTests/ParseJSONDataTests.swift
> +    func test_parseJSONData_성공시_BoxOfficeResult_인스턴스를_반환하는가() {
기능 명세를 작성한다고 생각하고 테스트 이름을 지어보시면 좋겠습니다.
```suggestion
    func test_parseJSONData_성공시_BoxOfficeResult_인스턴스를_반환한다() {
```

2024-02-18 17:34 UTC, ryan-son commented on BoxOfficeTests/ParseJSONDataTests.swift
> +        }
단위 테스트 메서드가 에러를 던질 수 있도록 만들어주면 do-catch 구문을 작성하시지 않으셔도 됩니다. 이 경우 try에서 에러가 발생하면 테스트가 실패하고, 제공한 에러가 에디터와 콘솔에 표시됩니다.

2024-02-18 17:34 UTC, ryan-son commented on BoxOfficeTests/RequestDataTests.swift
> +final class RequestDataTests: XCTestCase {
`RequestDataTests`는 꽤 범용적인 이름이네요. 테스트할 대상에 적합한 상세한 이름을 지어주면 좋겠습니다.

2024-02-18 17:34 UTC, ryan-son commented on BoxOfficeTests/RequestDataTests.swift
> +            let input: String = "https://kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key=f5eef3421c602c6cb7ea224104795888&targetDt=20220105"
BoxOffice 관련 네트워크 처리를 하는 타입을 만들어 URL이 테스트 케이스 내부에서 등장하지 않도록 만들어 보는 것이 좋겠습니다.

2024-02-18 17:34 UTC, ryan-son commented on BoxOfficeTests/Utility/FakeBoxOfficeDTO.swift
> +}
FakeBoxOfficeDTO는 FakeServer로 요청을 보내고 처리하는 것 이외에는 boxOfficeDTO와 차이가 없네요. 네트워크 요청을 만들고 처리하는 타입을 구성한다면 이 타입이 없어도 동일한 로직을 수행할 수 있을 것 같습니다.

2024-02-18 17:34 UTC, ryan-son commented on BoxOfficeTests/Utility/FakeServer.swift
> +    static func data(from url: URL) throws -> (Data?, HTTPURLResponse?) {
이러한 방식을 사용해 네트워크 의존성이 분리된 단위 테스트를 작성할 수 있겠지만, 요청의 종류가 늘어날 때마다 메서드 구현이 달라져야하므로 기능 수정과 확장에 취약해질 수 있습니다. 네트워크 요청을 만들고 처리하는 타입을 분리하며 해당 타입이 처리하는 로직을 프로토콜로 추상화해보고, 해당 프로토콜을 준수하는 Mock 타입을 만들어 목적에 맞는 구현을 추가해보는 방향으로 진행해보시면 좋을 것 같습니다.

2024-02-19 10:14 UTC, eensungkim commented on BoxOffice.xcodeproj/project.pbxproj
>  				8A8903842B7B756200E0A48D /* View */,
View 내부에 있던 파일들을 Resource 폴더로 옮기면서 View 폴더가 빈 폴더가 되었고, git 에서 빈 폴더는 업로드 하지 않아서 문제가 발생한 것으로 확인됩니다.
Step 3 로 넘어가면 View 폴더에 파일을 업로드하게 되겠지만, 일단 이번 스텝에서는 삭제하는 것으로 대응하겠습니다! 🙏

2024-02-19 10:23 UTC, eensungkim commented on BoxOffice.xcodeproj/project.pbxproj
> +				9BB8EB062B7DE94500B33116 /* MovieStructure.swift */,
Structure 를 제거하고 도메인 모델 이름을 소폭 수정하여 변경했습니다.

2024-02-19 12:18 UTC, eensungkim commented on BoxOffice/Model/BoxOfficeDTO.swift
> +            let data = try await URLSession.shared.data(from: URL)
1. 변경했습니다!
2. 의존성을 분리하기 위해 기존의 타입 메서드를 인스턴스 메서드로 변경하고, 외부에서 주입할 수 있는 urlSession 프로퍼티를 추가했습니다.
3. 넵! 안그래도 dataTask 를 학습하고 난 뒤에 data(from:) 으로 넘어왔었습니다!

2024-02-19 12:22 UTC, LeeSe0ngYe0n commented on BoxOffice/Model/BoxOfficeDTO.swift
> +    static func requestData(with url: String) async -> Data? {
`BoxOfficeDTO`가 `DTO`로써의 역할보다는 `Network 요청` 및 `처리`를 담당하고 있다고 판단하여 `NetworkManager`로 이름을 변경하고 기능을 추가하였습니다!

2024-02-19 12:24 UTC, LeeSe0ngYe0n commented on BoxOffice/Model/MovieStructure.swift
> +    }
넵 참고하여 수정하겠습니다!

2024-02-19 12:25 UTC, eensungkim commented on BoxOffice/Model/BoxOfficeDTO.swift
> +            return data
Step 1 에서 2 로 넘어오면서 네트워크 요청과 연관된 로직을 떼어내면서, 요 부분이 별도 메서드로 구성이 되었구요.
말씀해주신대로 다를 것이 없는 내용이 굳이 별도의 메서드로 있을 필요가 없다고 판단되어 제거하고 네트워크 처리 메서드에서 파싱까지 담당하도록 변경했습니다.

2024-02-19 12:28 UTC, eensungkim commented on BoxOffice/Model/MovieStructure.swift
> +    }
`private` 접근제어자 추가했습니다!

2024-02-19 12:29 UTC, LeeSe0ngYe0n commented on BoxOffice/Utility/Enumeration/HTTPStatusError.swift
> +}
해당 `HTTPStatusError`는 `invalidStatusCode`라는 하나의 케이스로  말씀해주신대로 구현하였습니다!
`invalidStatusCode`에서 `httpResponse.statusCode`의 에러번호를 받아 몇번대 에러인지 알 수 있게 구현해주었습니다!

2024-02-19 12:35 UTC, LeeSe0ngYe0n commented on BoxOffice/Utility/Enumeration/KoreanFilmCouncilURLEnumeration.swift
> +enum KoreanFilmCouncilURLEnumeration {
참고하여 변수명을 변경하겠습니다!

2024-02-19 12:37 UTC, LeeSe0ngYe0n commented on BoxOffice/Utility/Enumeration/KoreanFilmCouncilURLEnumeration.swift
> +    case movieDetailInformation(String, String)
키는 중복되다 보니 계산 프로퍼티 안에서 한번에 처리할 수 있게 변경하였습니다! 그리고 targetDate의 매개변수명은 두가지를 포괄할 수 있는 queryValue라는 변수명으로 지정했습니다!

2024-02-20 10:48 UTC, eensungkim commented on BoxOffice/Utility/APIKey.plist
말씀주신 내용 관련해서 몇가지 궁금한 점이 있습니다.

1. 리뷰 내용을 반영하기 위해 xcconfig 를 활용하는 쪽으로 수정하도록 하겠습니다.

2. 혹시 참고할 수 있는 공식 문서나 아티클이 있을까요?
API Key 를 안전하게 다루는 방법 관련해서 Apple 에서 다루고 있는 별도의 아티클이나 문서를 아직까지는 발견하지 못해서 여쭤봅니다.

3. .xcconfig 활용하기와 관련한 궁금증
블로그 정보들을 종합해보니 크게 2가지 정도의 방법을 찾을 수 있었습니다. 1) .xcconfig 활용하기 2) 백엔드 서버를 통해 인증된 유저만 정보를 받도록 하기
2번은 지금의 프로젝트에서 다룰 수 있는 내용은 아니라고 판단이 되는데요.
.xcconfig 를 활용하면 해당 파일은 패키징되는 과정에서 제외되고, 컴파일된 소스코드 등에 정보가 남아있게 된다고 하더라구요.
리버스 엔지니어링을 하더라도 소스코드 그 자체를 확인하는 것은 쉽지 않기 때문에 이러한 방법이 더 안전한 방법이라고 할 수 있는 것일까요?

2024-02-20 11:13 UTC, eensungkim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        }
1. `viewDidLoad()` 에서 호출하도록 변경했습니다.
2. `loadData()` 메서드로 분리했습니다.
3. 네트워크 로직을 담당할 NetworkManager 를 새롭게 만들어보았습니다.

2024-02-20 11:15 UTC, eensungkim commented on BoxOffice/Utility/Enumeration/KoreanFilmCouncilURLEnumeration.swift
> +    }
1. 나름의 방법으로 변경해 보았습니다. 
(URLComponents 를 알아보다 보니 이러한 형태를 잘 다루게 되면 더 좋은 구현이 가능할 것 같습니다. 이 점은 Step 3 이후에서 고민해볼 예정입니다.)
2. NetworkManager.makeRequest 에서 요청하게 될 HTTP 메서드 유형을 받아 전달하도록 구현해보았습니다.
3. 넵!

2024-02-20 12:31 UTC, eensungkim commented on BoxOfficeTests/Utility/FakeServer.swift
> +    static func data(from url: URL) throws -> (Data?, HTTPURLResponse?) {
Mock 타입을 구현해 보았는데요. 의도하신 방향성이 맞을지 모르겠습니다.
피드백 주시면 다음 스텝에서도 반영해 보도록 하겠습니다!

2024-02-20 12:32 UTC, eensungkim commented on BoxOfficeTests/Utility/FakeBoxOfficeDTO.swift
> +}
MockURLSession 을 만들어서 처리하는 것으로 변경했습니다!

2024-02-20 12:32 UTC, eensungkim commented on BoxOfficeTests/RequestDataTests.swift
> +            let input: String = "https://kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key=f5eef3421c602c6cb7ea224104795888&targetDt=20220105"
URL 을 enum 에서 계산 프로퍼티로 다루도록 하여 해결했습니다!

2024-02-20 12:33 UTC, eensungkim commented on BoxOfficeTests/RequestDataTests.swift
> +final class RequestDataTests: XCTestCase {
NetworkManager 구조체를 만들면서 해당 기능을 테스트하게 되어, NetworkManagerTests 로 이름을 변경했습니다.

2024-02-20 12:33 UTC, eensungkim commented on BoxOfficeTests/ParseJSONDataTests.swift
> +        }
앗 처음 알았네요. 😅 
do catch 를 삭제하겠습니다!

2024-02-20 12:33 UTC, eensungkim commented on BoxOfficeTests/ParseJSONDataTests.swift
> +    func test_parseJSONData_성공시_BoxOfficeResult_인스턴스를_반환하는가() {
test 를 아예 새롭게 구성하면서, 말씀해주신 내용을 최대한 반영해보았습니다.

2024-02-20 12:55 UTC, LeeSe0ngYe0n commented on BoxOffice/Model/BoxOfficeDTO.swift
> +        }
step3를 구현하면서 사용자에게 알럿창을 띄어주는 형태로 구현하려고 생각하는데 의도하신 방향이 맞을까요?

2024-02-21 04:55 UTC, eensungkim commented on BoxOffice.xcodeproj/project.pbxproj
> +			);
폴더링 방법을 아예 새롭게 개편해 보았습니다.
Network 폴더를 부모로 두고, 그 하위에 URL, Error 폴더가 있어 각각 `KoreanFilmCouncilURL` 과 `NetworkError` 를 담도록 했습니다.

2024-02-21 04:57 UTC, eensungkim commented on BoxOffice/Model/BoxOfficeDTO.swift
> +        }
알럿 컨트롤러를 활용하는 방식으로 기능을 추가해봤습니다!

2024-02-21 16:25 UTC, ryan-son commented on BoxOffice.xcodeproj/project.pbxproj
> +			);
Network 기능을 세분화해서 `NetworkManager`에 의존하면서 `KoreanFilmCouncilURL`도 이용하는 계층을 만들어볼 수 있을 것 같습니다. 폴더 구분도 이런식으로 해볼 수 있을 것 같네요.

2024-02-21 16:26 UTC, ryan-son commented on BoxOffice/Model/BoxOfficeDTO.swift
> +        }
맞습니다!

2024-02-21 17:07 UTC, ryan-son commented on BoxOffice/Utility/APIKey.plist
1. xcconfig와 info.plist를 조합한 방법은 보안 측면에서는 property list를 앱 번들에 포함한 것과 동일합니다. 앱 타겟을 Release configuration으로 아카이빙하여 앱 스토어에 배포하면 `BoxOffice.app` 패키지 내부에 info.plist가 포함되어 있고, 이 파일 내부에 API Key가 존재하기 때문입니다. 아래는 여러분의 프로젝트에 `Secret.xcconfig`를 임의로 만들어 아카이브 했을 때 앱 번들 내부를 열어본 모습입니다.
<img width="1219" alt="image" src="https://github.com/tasty-code/ios-box-office/assets/69730931/f7ffe307-3c0a-4f76-9dbf-372e4f08fe14">
2. 클라이언트에 존재하는 정보는 비밀을 유지하기는 어려우므로 보안을 위해서는 여러분께서 알아보신 것처럼 백엔드를 이용해야합니다. 자체 서버를 구현할 정도가 아니라면 [On-Demand Resources](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/On_Demand_Resources_Guide/), [CloudKit](https://developer.apple.com/kr/icloud/cloudkit/), [Apple Push Notification Service(APNS)를 이용한 백그라운드 업데이트](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app), [Firebase Remote Config](https://firebase.google.com/docs/remote-config?hl=ko)를 이용해볼 수 있습니다. 이번 프로젝트에서는 이러한 방법을 적용하지 마시고 현재 설정 그대로 진행해보세요.
3. 2의 경우에도 보안이 취약한 HTTP를 이용하는 경우 중간자 공격(MITM)으로 보안 정보를 탈취할 수 있으며, HTTPS를 이용하는 경우에도 Charles, Proxyman, Fiddler와 같이 사용자가 자신의 HTTPS 트래픽을 의도적으로 모니터링하는 경우(self-MITM/self-sniffing) 정보를 탈취할 수 있습니다. 이러한 행위를 차단하기 위해 SSL Pinning과 같은 방식을 적용하기도 합니다. 지금은 이 내용을 이해하지 않으셔도 괜찮으니 향후에 관심이 생기시면 용어를 찾아 학습해보세요.

2024-02-21 18:07 UTC, ryan-son approved these changes
댄, L, 피드백에 따라 수정해보시느라 고생 많으셨습니다.

추가 코멘트로 수정해보실 부분이 적지는 않아보이지만 Step 3 요구사항과 함께 처리해보시면 좋겠습니다.

리뷰 내용 중 이해하기 어려운 부분이 있으시다면 언제든지 말씀해주세요!

2024-02-21 18:07 UTC, ryan-son commented on BoxOffice/Controller/AlertController.swift
> +    }
`NetworkError`가 `LocalizedError` 프로토콜을 준수하고 있으니 errorDescription과 같은 프로퍼티를 통해 메시지를 전달해줄 수도 있을 것 같네요. 현재와 크게 다를 것 같지는 않습니다. 아래 문서를 통해 LocalizedError 프로토콜에서 지원하는 프로퍼티들을 확인해보세요.

- [LocalizedError - Apple Developer](https://developer.apple.com/documentation/foundation/localizederror)

2024-02-21 18:07 UTC, ryan-son commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    private func loadData() {
클라이언트는 워낙 데이터를 불러오는 일이 잦다보니 하나의 ViewController 내부에서도 여러가지 다른 데이터를 불러올 때가 많습니다. `loadData`보다 수행하는 행위에 더 맞는 메서드 이름을 지어보시면 좋겠습니다.

2024-02-21 18:07 UTC, ryan-son commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +            }
이곳에서 return 구문으로 빠지는 경우가 있을 수 있을까요? 언제 그럴까요? 잠재적으로 버그가 발생할 수 있는 구간에서 아무런 동작을 하지 않는다면 버그의 원인을 찾는 데 시간이 오래 걸릴 수 있습니다.

2024-02-21 18:07 UTC, ryan-son commented on BoxOffice/Network/DTO/MovieInformationResult.swift
> +    }
private 적용 가능하겠네요.

2024-02-21 18:07 UTC, ryan-son commented on BoxOffice/Network/NetworkManager.swift
> +    private(set) var urlSession: URLSessionProtocol?
1. 외부에서 참조하지 않아도 괜찮다면 private으로 변경해줄 수 있을 것 같아요.
2. `urlSession` 인스턴스를 이니셜라이저를 통해 주입 받고 있으므로 옵셔널 타입이 아니라도 괜찮을 것 같아요.

2024-02-21 18:07 UTC, ryan-son commented on BoxOffice/Network/NetworkManager.swift
> +    }
1. NetworkManager라는 범용적인 이름을 사용함에도 불구하고 `KoreanFilmCouncilURL`이라는 구체적인 타입에 의존하고 있네요. 범용적인 인터페이스로 변경해볼 수 있을 것 같아요.
2. httpMethod를 열거형 또는 구조체의 타입 인스턴스로 정의해서 문자열을 사용하지 않도록 변경해줄 수 있을 것 같습니다. 이러면 동료가 메서드를 사용하기 편할거예요.
3. `URL(string:)` 이니셜라이저가 실패하는 케이스가 존재합니다. 꼭 알아두세요.
4. 이 처리는 `request(_:into:errorHandler:)` 메서드 내부에서 자체적으로 처리할 수 있을 것 같네요. 그렇게 되면 개발자 편의가 더 늘어날 것같아요.

2024-02-21 18:07 UTC, ryan-son commented on BoxOffice/Network/NetworkManager.swift
> +    }
1. makeRequest -> request 순서로 메서드를 사용하는 것을 의도하셨다면 `KoreanFilmCouncilURL`을 두 메서드 모두 요구하고 있다는 점에 주목해볼 수 있을 것 같네요. 단순하게 만들어볼 수 있을 것 같습니다.
2. nil을 반환하기보다 상황에 맞는 에러를 던지고 반환값을 옵셔널이 아닌 형태로 만들 수 있을 것 같습니다. 옵셔널 리턴인 경우에는 어떤 에러로 인해 문제가 발생했는지 파악하기 어려워 디버깅할 때 고통스러울 수 있습니다.
3. catch scope에서 발생하는 에러는 try 메서드에서도 에러가 발생할 수 있으므로 반드시 NetworkError 타입이라고 확신할 수 없습니다. 이곳에서 error handling할 계획이시라면 이러한 Error 프로토콜을 준수하는 에러를 표현하는 방법을 마련하시는 것이 좋겠습니다.
4. async 메서드가 에러를 closure 형식으로 처리하는 인터페이스를 제공하는 것은 일반적인 구성 방식은 아닐 수 있습니다. async 메서드에서 에러가 발생하면 보통 던지거나 사용한 쪽에서 에러를 몰라도 되어서 무시하는 케이스가 있습니다.
5. 반환할 타입을 외부에서 지정할 수 있도록 제네릭 메서드를 구성해보시는 건 어떨까요?

2024-02-21 18:07 UTC, ryan-son commented on BoxOffice/Network/URL/KoreanFilmCouncilURL.swift
> +    case movieDetailInformation(queryValue: String)
queryValue보다는 각자의 query parameter key 이름이 전달하는 인자의 내용을 더 명확하게 파악할 수 있을 것 같은데, queryValue로 변경하신 이유는 무엇인가요?

2024-02-21 18:07 UTC, ryan-son commented on BoxOffice/Network/URL/KoreanFilmCouncilURL.swift
> +        let path: String = "https://kobis.or.kr/kobisopenapi/webservice/rest/"
이건 프로토콜, 도메인과 path가 조합된 URL이니 path라고 칭하기에는 조금 애매할 수 있겠네요. 이럴 때 사용할 수 있는 변수명은 `baseURL`, `apiBase`, `apiRoot` 같은 것들이 있습니다.

2024-02-21 18:07 UTC, ryan-son commented on BoxOffice/Network/URL/KoreanFilmCouncilURL.swift
> +            return url
연산 프로퍼티 이름이 url이니 반환하는 것은 url이라고 판단할 수 있습니다. 상수 선언하지 않고 반환해도 괜찮을 것 같네요.

2024-02-21 18:07 UTC, ryan-son commented on BoxOffice/Network/URL/KoreanFilmCouncilURL.swift
> +    }
좋은 접근이지만, request 메서드 사용할 때 디코딩할 타입을 지정할 수 있도록 제네릭 메서드를 만들어봐도 좋을 것 같네요.

2024-02-21 18:07 UTC, ryan-son commented on BoxOfficeTests/NetworkManagerTests.swift
> +    }
이건 Swift를 의심하는 테스트인 것 같은데, 반환 타입을 검증하기보다 dailyBoxOffice(queryValue: input) 부분 자체가 input이 되고, URLRequest 인스턴스가 의도한 요청을 만들었는지, 예를 들어 HTTP method가 GET이면서 url이 의도한 문자열인지 검증해볼 수 있을 것 같습니다.

2024-02-21 18:07 UTC, ryan-son commented on BoxOfficeTests/NetworkManagerTests.swift
> +        }
테스트에서 early exit을 사용하는 경우가 생긴다면 exit하기 전에 XCTFail과 같은 메서드를 배치해주세요. 이 구문이 실패해서 탈출하는 경우 테스트가 성공 처리됩니다.

2024-02-21 18:07 UTC, ryan-son commented on BoxOfficeTests/NetworkManagerTests.swift
> +        }
1. 테스트 메서드에 async를 적용하면 Task를 사용하지 않아도 됩니다.
2. 네트워크 에러가 발생하는 경우에도 XCTFail을 적용해볼 수 있을 것 같습니다.

2024-02-21 18:07 UTC, ryan-son commented on BoxOfficeTests/Utility/MockURLSession.swift
> +        }
이 경우에는 statusCode를 받기 전이니 invalidStatusCode라는 에러가 적합하지 않을 것 같습니다. invalidURL 같은 에러를 만들어서 사용해보면 좋겠습니다.

2024-02-21 18:07 UTC, ryan-son commented on BoxOfficeTests/Utility/MockURLSession.swift
> +        }
각 상황에 맞는 에러를 던져주면 좋겠습니다.

2024-02-21 18:07 UTC, ryan-son commented on BoxOfficeTests/Utility/MockURLSession.swift
> +        }
인스턴스 내부에 성공과 실패, 성공 시 반환할 데이터, 실패 시 던질 에러를 설정할 수 있도록 장치를 마련하고 이에 따라 `data(for:delegate:)` 메서드를 구현해보시면 단위 테스트에 접근하시기 더 편하실 것 같습니다.

2024-02-21 18:14 UTC, merged

2024-02-22 01:55 UTC, LeeSe0ngYe0n commented on BoxOffice/Controller/AlertController.swift
> +    }
LocalizedError 프로토콜에서 제공하는 errorDescription 속성으로 변경하였습니다!

2024-02-22 01:57 UTC, LeeSe0ngYe0n commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    private func loadData() {
loadData에서 loadDailyBoxOffficeData로 변경해주었습니다!

2024-02-22 01:57 UTC, LeeSe0ngYe0n commented on BoxOffice/Network/DTO/MovieInformationResult.swift
> +    }
말씀해주신대로 수정하였습니다!

2024-02-22 01:58 UTC, LeeSe0ngYe0n commented on BoxOffice/Network/NetworkManager.swift
> +    private(set) var urlSession: URLSessionProtocol?
말씀해주신 대로 수정하였습니다!

2024-02-22 02:00 UTC, LeeSe0ngYe0n commented on BoxOffice/Network/URL/KoreanFilmCouncilURL.swift
> +        let path: String = "https://kobis.or.kr/kobisopenapi/webservice/rest/"
baseURL로 변경하였습니다!

2024-02-22 02:00 UTC, LeeSe0ngYe0n commented on BoxOffice/Network/URL/KoreanFilmCouncilURL.swift
> +            return url
말씀해주신대로 변경하였습니다!

2024-02-23 05:25 UTC, eensungkim commented on BoxOfficeTests/NetworkManagerTests.swift
> +    }
1. HTTP method 가 "GET" 인지 검증하는 테스트
2. 알맞은 URL 을 돌려주는지 확인하기 위해 lastPathComponent 가 의도한 파일 명을 반환하는지 검증하는 테스트
이렇게 2가지로 나누어 보았습니다!

2024-02-23 05:33 UTC, eensungkim commented on BoxOfficeTests/NetworkManagerTests.swift
> +        }
적용했습니다!

2024-02-23 05:39 UTC, eensungkim commented on BoxOfficeTests/NetworkManagerTests.swift
> +        }
넵 적용했습니다.

2024-02-23 06:58 UTC, eensungkim commented on BoxOfficeTests/Utility/MockURLSession.swift
> +        }
MockURLSession 을 통해서 사실상 서버를 대체하는 개념이 된다고 생각했었습니다!
MockURLSession 을 아예 새롭게 대체해 보았습니다!!

2024-02-23 06:58 UTC, eensungkim commented on BoxOfficeTests/Utility/MockURLSession.swift
> +        }
MockURLSession 을 아예 새롭게 대체해 보았습니다!!

2024-02-23 06:59 UTC, eensungkim commented on BoxOfficeTests/Utility/MockURLSession.swift
> +        }
MockURLSession 을 아예 새롭게 대체해 보았습니다!!

2024-02-23 07:14 UTC, LeeSe0ngYe0n commented on BoxOffice/Network/URL/KoreanFilmCouncilURL.swift
> +    }
넵 제네릭 메서드로 바꿔주었습니다!

2024-02-23 07:17 UTC, LeeSe0ngYe0n commented on BoxOffice/Network/URL/KoreanFilmCouncilURL.swift
> +    case movieDetailInformation(queryValue: String)
중간에 개념을 살짝 착각한 부분이 생겨 원래대로 수정하였습니다!

2024-02-23 07:37 UTC, eensungkim commented on BoxOffice/Network/URL/KoreanFilmCouncilURL.swift
> +    }
제네릭으로 변경해 보았습니다!

2024-02-23 07:40 UTC, eensungkim commented on BoxOffice/Network/NetworkManager.swift
> +    }
1. 변경을 진행했는데 의도하신 바가 맞을지 모르겠습니다.
2. 에러를 추가하여 구현해보았습니다.
3. request 를 throws 메서드로 변경한 뒤 상위에서 처리하도록 바꾸었습니다.
4. 3번에서 함께 변경되었습니다.
5. 제네릭 메서드로 변경했습니다!

2024-02-23 08:16 UTC, eensungkim commented on BoxOffice/Network/NetworkManager.swift
> +    }
1. string 을 받도록 변경했습니다.
2. 별도의 구조체를 만들었습니다.
3. 넵
4. private 으로 변경하고 request 메서드 내부에서 호출하도록 수정했습니다.

2024-02-23 08:27 UTC, eensungkim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +            }
기존 상태에서는 makeRequest 가 URL() 인스턴스가 생성되지 않는 경우 문제가 생길 소지가 있었습니다.
makeRequest 를 request 내부에서 호출하고 에러 처리를 해주어 guard 없이 활용하도록 변경했습니다.