박스오피스 앱 [STEP1 & STEP2 PR] NERO, 노움
tasty-code/ios-box-office pull request #34
Opened 2024-02-18 07:24 UTC by Gnoam-R

안녕하세요!! 두두(@FirstDo) 
네로(@ODDNERO), 노움(@Gnoam-R)입니다.

PR을 너무 늦게 보내서 정말 죄송합니다...
시간 여유되실때 편히 리뷰 부탁드립니다.

<br/>

## 프로젝트 디렉토리

```swift
├── BoxOffice
│   ├── Resources
│   │   ├── Assets.xcassets
│   │   │   ├── AccentColor.colorset
│   │   │   │   └── Contents.json
│   │   │   ├── AppIcon.appiconset
│   │   │   │   └── Contents.json
│   │   │   └── Contents.json
│   │   ├── Base.lproj
│   │   │   ├── LaunchScreen.storyboard
│   │   │   └── Main.storyboard
│   │   └── Info.plist
│   └── Sources
│       ├── Application
│       │   ├── AppDelegate.swift
│       │   └── SceneDelegate.swift
│       ├── DTO
│       │   ├── DailyBoxOfficeDTO.swift
│       │   └── DetailMovieDTO.swift
│       ├── Model
│       │   └── Network
│       │       ├── JsonParser.swift
│       │       ├── KobisInterface
│       │       │   └── KobisAPI.swift
│       │       ├── KobisService
│       │       │   ├── BoxOfficeManager.swift
│       │       │   ├── DailyBoxOfficeManager.swift
│       │       │   ├── DetailMovieManager.swift
│       │       │   └── KobisService.swift
│       │       ├── NetworkError.swift
│       │       └── Result.swift
│       └── Presentation
│           └── ViewController.swift
└── BoxOfficeTests
    └── BoxOfficeTests.swift
```
<br/>

## [STEP1] 작업 목록

- [x]  파싱한 JSON 데이터와 매핑할 모델 설계
- [ ]  `CodingKeys` 프로토콜의 활용
- [x]  단위 테스트(Unit Test)를 통한 설계와 검증
<br/>

## [STEP1] 고민한 부분

### 폴더링

<img src="https://github.com/tasty-code/ios-box-office/assets/67363759/df663016-eecd-4183-b102-c603c12934b7" width="300" height="400"/>

새싹에서 프로젝트를 진행하면서 점차 코드 규모와 난이도가 높아지고 있다고 생각해요

그래서 구글링과 저 스스로의 고민을 통해 폴더링 구조를 만들게 되었는데 옳은 방법인지 확신이 들지 않아서요

물론 정답은 없지만 최대한 맞는 방법으로 구성하고 싶었습니다.

제가 폴더링을 하면서 고민한 내용은 다음과 같습니다.

1. 클린 폴더?, 협업 개발자들에게 잘 이해되는 폴더 구조인가?
2. 코드 재 사용성
    1. 추후 비슷한 프로젝트 진행시 해당 폴더를 가져와서 그대로 사용할 수 있는 폴더와 그에 맞는 코드 구조
3. MVC에 적합한가?
    1. STEP1, STEP2에서는 아직 뷰를 적용하지 않았지만 뷰 적용시 대응이 가능한가?
<br/>

## [STEP2] 작업 목록

- [x]  URL Session을 활용한 서버와의 통신
- [x]  JSON 데이터 매핑할 모델 설계 및 사용
- [ ]  TEST Double을 통해 네트워크 상태와 무관하게 로직을 테스트

<br/>

## [STEP2] 고민한 부분

### 네이밍

```swift
│   └── Sources
│       ├── Application
│       │   ├── AppDelegate.swift
│       │   └── SceneDelegate.swift
│       ├── DTO
│       │   ├── DailyBoxOfficeDTO.swift
│       │   └── DetailMovieDTO.swift
│       ├── Model
│       │   └── Network
│       │       ├── JsonParser.swift
│       │       ├── KobisInterface
│       │       │   └── KobisAPI.swift
│       │       ├── KobisService
│       │       │   ├── BoxOfficeManager.swift
│       │       │   ├── DailyBoxOfficeManager.swift
│       │       │   ├── DetailMovieManager.swift
│       │       │   └── KobisService.swift
│       │       ├── NetworkError.swift
│       │       └── Result.swift
│       └── Presentation
│           └── ViewController.swift
└── BoxOfficeTests
    └── BoxOfficeTests.swift
```
박스 오피스 프로젝트부터 파일들이 많아지고 나서 파일과 변수의 네이밍이 정말 어려웠습니다.

때문에 그 안에 코드 구조도 달라지는 상황이 많이 발생하여 더욱 시간이 오래걸리게 되었는데 PR을 작성하는 지금도 위화감이 계속 들고있네요…

<br/>

### 비동기적인 네트워킹

[STEP2]에서 제일 고민했던 부분은 서버에 저장된 박스 오피스 API 정보를 조회할때, 클라이언트는 동기적으로 요청을 보내지만 서버는 클라이언트에게 비동기적으로 응답을 보내는 점입니다

때문에 처음에는 `Async`를 이용해 API 데이터를 가져오려 했으나 결국 `탈출 클로저` 를 사용해 네트워크 통신 결과 & 응답 데이터를 받아오게 되었습니다.

`탈출 클로저`를 사용하게 되면 서버로부터 응답메시지를 수신할때와 같은 비동기적 처리가 필요한 상황에서는 좋은 장점이 있지만, 저희 코드의 경우 응답에 대한 결과를 가져오고 이를 비교하기 위해서는 계층적으로 클로저를 사용해야 되었습니다

<img src="https://github.com/tasty-code/ios-box-office/assets/67363759/36384703-22d8-412e-a4f3-db22ddbadf93" width="1000" height="230"/>

<img src="https://github.com/tasty-code/ios-box-office/assets/67363759/9c71af04-736d-4d2c-86ee-2351edfc9d0b" width="1000" height="180"/>

<br/>
<br/>

### 유닛 테스트

네트워킹 API를 테스트 하기 위해서 제일 먼저 Postman으로 API가 정상적으로 동작하는지 테스트를 진행했고, 코드 구현 후에는 ViewController의 ViewDidLoad에서 구현된 객체를 생성하여 동작 확인을 진행했습니다.

그런데 유닛 테스트에서 테스트를 진행시에 응답 메시지를 받기 전에 종료하는 이슈가 발생했는데 ViewController에서는 ViewDidLoad에 네트워킹을 실행하고 다른 추가 task를 실행하지 않아 결국 응답 메시지를 확인할수 있는데,

유닛 테스트의 경우 테스트 function을 실행하고 `tearDownWithError` 라는 메서드를 통해 초기화와 함께 앱을 종료시켜서 따로 대기하는 코드가 있지 않다면 응답을 받을수 없다고 생각했습니다.

그래서 아래와 같이 `fulfill` 이 실행될때까지 `wait` 를 통해 대기하는 코드를 추가 했어요

```swift
func test_일별박스오피스API_조회후_응답하는_boxOfficeType이_일별_박스오피스가_맞는지() {
    //given
    let result = "일별 박스오피스"
    var boxOfficeType: String?
    let expectation = XCTestExpectation(description: "데이터 응답 요청 중")
    
    //when
    let date = sutBoxOffice.dailyFormatter()
    let dailyBoxOffice = KobisAPI.dailyBoxOffice(
        url: "https://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json",
        key: "2c7b3f6025093cbb1df0f1e819bf8c65",
        date: date
    )
    sutBoxOffice.requestDailyBoxOffice(kobisAPI: dailyBoxOffice, responseHandler: { result in
        switch result {
        case .success(let response):
            let dailyBoxOfficeResponse = response as! DailyBoxOfficeDTO
            boxOfficeType = dailyBoxOfficeResponse.boxOfficeResult.boxofficeType
        case .failure(_):
            boxOfficeType = nil
        }
        expectation.fulfill()
    })
    wait(for: [expectation])
    
    //then
    XCTAssertEqual(result, boxOfficeType!)
}
```
<br/>

### 궁금한 점

[STEP3] 부터는 서버의 응답을 수신 받을 때까지 대기하고 비동기적으로 들어오는 데이터를 tableView에 업데이트를 해야 하는데요

현재 처럼 탈출 클로저를 사용하게 되면 유지보수 측면에서도 불리하고 클린 코드도 어려울거라고 생각이 들어요

비동기 처리 로직을 구현하는것이 맞을까요? 아니면 옵저버나 Delegate패턴을 사용하는게 맞을까요?

<br/>

2024-02-19 04:46 UTC, FirstDo requested changes
안녕하세요 두분~ 좋은 월요일(?) 입니다!
주말까지 너무 고생이 많으셨습니다 ㅎㅎ

이번 프로젝트는 Json 파싱과 Network 구조를 잡는 프로젝트였는데요~
두분이 enum , protocol, struct등을 활용해서 네트워킹 구조를 열심히 짜보려고 노력한게 보였습니다!!

다만 조금 더 역할을 확실히 분리한 좋은 방식으로 수정할 수 있을것 같아 코맨트 남겼으니 참고 부탁드려요

## 궁금한 점

**[STEP3] 부터는 서버의 응답을 수신 받을 때까지 대기하고 비동기적으로 들어오는 데이터를 tableView에 업데이트를 해야 하는데요 
현재 처럼 탈출 클로저를 사용하게 되면 유지보수 측면에서도 불리하고 클린 코드도 어려울거라고 생각이 들어요
비동기 처리 로직을 구현하는것이 맞을까요? 아니면 옵저버나 Delegate패턴을 사용하는게 맞을까요?**

--- 
우선 용어부터 다시 잡고 가야할거 같아요

현재 구현하신게 비동기 처리 로직입니다.
보통 네트워크는 비동기로 동작하기에, 완료되는 시점에 UI를 업데이트 시키거나 다른 작업을 하기 위해선 완료되는 시점을 알아야 하는데요, 보통 가장 많이 쓰이는 두 방법이

1. 클로져 콜백 (현재쓰신 방식)
2. Swift Concurrency (async await 방식)

현 프로젝트 단계에서는 둘다 문제가 없습니다
다만 2번 방식이 좀 더 클린한 코드를 작성하는데 도움이 되긴합니다. 클로져 중첩이 없으니까요?

옵져버나 델리게이트 패턴은 현재네트워크 구조에서 필요한 부분은 아닌거 같은데, 어떤것때문에 그런 생각을 하셨을까요??

## 폴더링

Model과 Service 구분이 제대로 되지 않아서 지금 섞여있는것 같아요
뭐 사람마다 정의하기 나름이겠지만, 현재 단계에서는 이정도로 충분할것 같습니다

### Model
앱에서 사용하는 Entity. 주로 DTO로부터 변환됨
아니면, 에러모델, 네트워크와 상관없는 그냥 앱 내부적으로 사용하는 모댈 등

### Service
특정 동작을 수행하기 위한 객체
- JsonParser
- NetworkManager
- Logger

### API 혹은 TargetType (이름은 자유?)
- 개선된 KobisAPI나, DailyBoxOfficeManager가 속합니다

해당부분 참고해서 개선할부분있다면 개선하고, 꼭 고치지 않아도 되니 저랑 얘기 많이 해서 의견교류 해보면 좋을것 같습니다~~

2024-02-19 04:46 UTC, FirstDo commented on BoxOffice/Sources/Application/SceneDelegate.swift
> +            window?.makeKeyAndVisible()
아래처럼 만드는게 좀 더 일반적인것 같네요..!
UIScreen.main은 deprecated 되었기도 하고요?
```swift
guard let windowScene = (scene as? UIWindowScene) else { return }
window = UIWindow(windowScene: windowScene)
window?.rootViewController = ViewController()
window?.makeKeyAndVisible()
```

추가적으로 AppDelegate나,  SceneDelegate도 깔끔하게 정리(주석제거나 내려쓰기)를 해주는것이
추후 사전과제를 하거나 그럴때 더 깔끔하고 디테일에 신경쓴 느낌을 줄 수 있다고 생각합니다 ㅎㅎ


추가적으로 아직 UI를 볼 필요는 없지만,
코드베이스로 가기로 마음을 먹었다면, Storyboard는 현재 단계에서 지우고 가는게 좋을것 같네요 :)

2024-02-19 04:46 UTC, FirstDo commented on BoxOffice/Sources/DTO/DetailMovieDTO.swift
> +}
DTO를 만드신거 좋습니다! CodingKey를 만드신것도 좋고요 ㅎㅎ

다만 이런식으로 모든 구조체를 전역에 써버리면 네임스페이스가 오염되고, 파일이 조금만 늘어나도 이름이 겹처버리겠죠?
nested structrure를 사용해서 구조체 안에 중첩으로 만들수 있을것 같네요

나머지 DTO도 마찬가지 입니다..!

```swift
struct DetailDTO: Codable {
   let movie: Movie

   struct Movie: Codable {
     //...
    }
}
``

추가적으로 디코딩모델에는 Decodable만, 인코딩모델에는 Encodable만, 둘다 필요한 경우만 Codable을 붙여주는게 좀 더 명확할것 같습니다

2024-02-19 04:46 UTC, FirstDo commented on BoxOffice/Sources/Model/Network/Result.swift
> +
이부분은 어떤의도로 작성하신걸까요??
두분의 생각이 궁금합니다

제가 보기에는 문제가 있는게
- Error라는 Generic 변수는 현재 사용하지 않고 있네요
- 또 Swift의 기본 Result과 이름이 겹칩니다

2024-02-19 04:46 UTC, FirstDo commented on BoxOffice/Sources/Model/Network/JsonParser.swift
> +}
JsonParser 객체를 만드신점은 너무 좋습니다!
몇가지 질문 & 개선사항이 있는것 같아요

-  왜 class여야 하나요?
- Generic을 사용해서, 모든 .json 파일에 대해서 동작하게 한것 같은데, 매서드 이름이 맞지않습니다

2024-02-19 04:46 UTC, FirstDo commented on BoxOffice/Sources/Model/Network/NetworkError.swift
> +}
LocalizedError를 채택하신 이유가 뭘까요?

LocalizedError를 채택했다면, 보통 errorDescription 프로퍼티도 구현을 해주는 편입니다!
왜일까요?

2024-02-19 04:46 UTC, FirstDo commented on BoxOffice/Sources/Model/Network/KobisInterface/KobisAPI.swift
> +
코드를 보면서 네트워크를 추상화 하시는데에 상당히 많은 고민과 생각을 하신것을 느꼈습니다!

제가 보기에는 조금 더 역할을 확실히 하고, 개선할 수 있는 여지가 있어보여요

enum KobisAPI  이친구는, 
URLRequest까지 완전히 만드는걸 목표로 했으면 좋겠습니다

```swift
enum KobisAPI {
  case dailyBoxOffice
  case detailMovie
}

extension KobisAPI {
   var asURLRequest: URLRequest? {
      // TODO
    }
}
```

현재 사용을 이렇게 하고 있는데 이 코드를 VC에서 호출해야한다는건데 이게 좋아보이지는 않죠?
특히 url을 통째로 박아주는 부분이요

```swift
        let date = sutBoxOffice.dailyFormatter()
        let dailyBoxOffice = KobisAPI.dailyBoxOffice(
            url: "https://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json",
            key: "--------",
            date: date
        )
        sutBoxOffice.requestDailyBoxOffice(kobisAPI: dailyBoxOffice, responseHandler: { result in
            switch result {
            case .success(let response):
                let dailyBoxOfficeResponse = response as! DailyBoxOfficeDTO
                boxOfficeType = dailyBoxOfficeResponse.boxOfficeResult.boxofficeType
            case .failure(_):
                boxOfficeType = nil
            }
```


이런식으로 호출됬으면 좋겠습니다 ( 단순 예시이고, async await이나 클로저 콜백 방식이 중요한게 아닌, 형태를 봐주세요~)

```swift
let networkManager = NetworkManager()
let api = KobisAPI.dailyBoxOffice(필요한 파라미터들)

let model = try await networkManager.request<T>(api)
```

KobisAPI의 dailyBoxOffice와, detailMovie를 호출하기 위한 쿼리는 정해져 있습니다
바뀌는값 (date 라던지) 만 외부에서 받으면되고, 바뀌지않는 값, 여기서는 URL이 되겟죠?, 은 KobisAPI enum에 써버리면 됩니다

조금 더 예시를 들자면 아래와 같은 방식을 말한 것입니다

ex)

```swift

enum KobisAPI {
   case dailyBoxOffice(date: String)
   case deetailMovie
}

// 바뀌지않는 고정데이터는 KobisAPI 만들때 고정으로 박아넣습니다

extension KobisAPI {
  // baseURL의 경우 바뀌지 않음
   var baseURL: String {
       return "https://www.kobis.or.kr/kobisopenapi/webservice/rest/"
   }
   
   // path의 경우 case마다 다름, 
   var path: String {
       switch self {
       case dailyBoxOffice: return ....
        case deetailMovie: return ....
        }
    }

   // httpMethod의 경우도 case 마다 다름
   var httpMethod: String {
       switch self {
       case dailyBoxOffice: return "get"
        case deetailMovie: return "get"
        }
    }

   var asURLRequest: URLRequest? {
       
       var components = URLComponents(string: baseURL + path)
       // .. 대충 쿼리들
       var urlRequest = URLRequest(url: components.url)
       urlRequest.httpMethod = httpMethod
      urlRequest.addValue("application/json", forHTTPHeaderField: "Content-Type")
      return urlRequest
    }

}
```

모든 종류의 네트워크 요청을 처리하는 네트워크 매니저는 다음과 같이 만들 수 있습니다
```swift
class NetworkManager {
    let session: URLSession

    func request<T: Decodable>(api: KobisAPI) async throw -> T {
        let (data, response) = try await session.data(for: api.asURLRequest)

        // 대충 에러처리와 디코딩

        return model
    } 
}
```

제방식이 정답은 아니며, 여러 라이브러리 (Alamofire나, Moya 등) 나 다른분들의 코드를 참고하셔서 두분만의 방식을 정립하시는것도 좋을것 같네요


꼭 이런방식은 아니더라도 현재 

KobisAPI 이친구가 하는일이 하나도 없습니다.
현재는 저 친구를 삭제하고
바로 DailyBoxOfficeManager, DetailMovieManager 를 써도 아무런 문제가 없는 상황인것 같아요



아니면 차라리 똑같은 느낌이긴 한데 이런방법도 있습니다
두분 현재 코드에서는 이 방식이 더 어울릴 수도 있겠네요

as-is

```swift
struct DailyBoxOfficeManager {
    var urlRequest: URLRequest?
    var urlString: String
    var keyValue: String
    private var targetDtValue: String
    
    init(urlString: String, keyValue: String, targetDtValue: String) {
        self.urlString = urlString
        self.keyValue = keyValue
        self.targetDtValue = targetDtValue
    }
}
```

to-be

```swift
struct DailyBoxOfficeAPI {
   var baseURL = "기본값 넣어주기 변하지않음"
   var httpMethod = "Get"
   var keyValue = "key값"
   var targetDtValue = "~~ 값"
    
   init() {
     // 여기서는 꼭 외부에서 받아야할 변수만 받기
    }
}
```

이런식으로 꼭 필요한 매개변수만 이니셜라이저 시점에 받아서 초기화 해서 DailyBoxOfficeAPI 객체를 만들고
외부에서 사용은 이런식으로 할 수 있겠네요

class NetworkManager {
    func requestDailyBox<T: Decodable>(api: kobisService) -> T{
     let urlRequest = api.request()

     // 대충 네트워크 통신!
   }
}


지금은 뭔가 enum 방식과 struct 방식이 섞여서 매우 혼잡한것 같아요!
두분 고민 많이 하셨을텐데, 이런 방식도 한번 참고해서 좀 더 구조화 되고 추상화된 네트워크 레이어를 짜보셨으면 합니다

참고: https://github.com/Moya/Moya

2024-02-19 04:46 UTC, FirstDo commented on BoxOffice/Sources/Model/Network/KobisService/BoxOfficeManager.swift
> +class BoxOfficeManager {
모든 경우에 쓸수있게 이름은 networkManager가 나은것 같아요

2024-02-19 04:46 UTC, FirstDo commented on BoxOffice/Sources/Model/Network/KobisService/KobisService.swift
> +}
이런거 좋습니다
좀더 일반화 시켜서 모든경우에 쓸수있는 네이밍을 짓는게 나을것 같아요
현재 이 프로토콜은 모든 경우에 쓸 수 있을것 같은데요??

또한 `Result<Any, Error>`
진짜진짜진짜 방법이 없는경우빼고는 Any타입은 지양해야 합니다. 왜일까요?

또 위에와 마찬가지로 URLRequest를 만드는 부분과, 실제 Response 하는 부분은 구분하는게 좋을것 같아요

2024-02-28 01:50 UTC, Gnoam-R commented on BoxOffice/Sources/Model/Network/Result.swift
> +
처음 enum을 작성했을때는 Result라는 스위프트에서 제공해주는 타입의 존재를 알지 못했습니다 
탈출 클로저의 Result를 사용하려면 개발자가 따로 정의해서 사용해야 하는줄 알고 위와 같이 enum 타입으로 작성하게 되었습니다
```swift
func dataTask(with request: URLRequest, complection: @escaping (Result<Any, Error>) -> Void)
```
현재는 제가 작성한 Result 타입을 삭제 완료했습니다

2024-02-28 01:52 UTC, Gnoam-R commented on BoxOffice/Sources/Application/SceneDelegate.swift
> +            window?.makeKeyAndVisible()
넵 반영했습니다!

2024-02-28 01:52 UTC, Gnoam-R commented on BoxOffice/Sources/DTO/DetailMovieDTO.swift
> +}
넵 반영했습니다!

2024-02-28 02:09 UTC, Gnoam-R commented on BoxOffice/Sources/Model/Network/NetworkError.swift
> +}
에러 케이스만 만들고 네트워크 통신이 완성되는 대로 다른 케이스들과 함께 추가 구현하려고 했는데 추가 작업을 빼먹은거 같습니다. 
수정해서 다시 올리도록 하겠습니다!

2024-02-28 02:28 UTC, Gnoam-R commented on BoxOffice/Sources/Model/Network/JsonParser.swift
> +}
- 왜 class여야 하나요?
처음 목적은 JsonParser라는 클래스와 위 클래스가 채택하는 프로토콜을 만들고 프로토콜을 사용하는 특정 클래스에서만 JsonParser 기능을 사용하게 하려고 작성했지만 이 코드를 작성했을때 다른 사항들을 먼저 작업할 필요가 있어서 따로 추가하지 않았습니다
따로 클래스일 필요는 없다고 생각하고 현재는 클래스에 final 키워드를 추가했습니다
- Generic을 사용해서, 모든 .json 파일에 대해서 동작하게 한것 같은데, 매서드 이름이 맞지않습니다 
네 맞습니다 확인해보니 적절하지 못한 네이밍인거 같습니다 클래스 이름과 메서드 이름을 수정하도록 하겠습니다 

```swift 
final class JsonFileManager {
   func decode<T: Decodable>(resourse: String) -> T? {
```

2024-02-28 02:44 UTC, Gnoam-R commented on BoxOffice/Sources/Model/Network/KobisInterface/KobisAPI.swift
> +
이번 프로젝트에서 이부분에 대해서 제일 많이 고민했던거 같아요 
전에 디스코드로 말씀 드렸듯이 Network 기능을 완전 모듈화 하고 싶었습니다.
여러 자료와 오픈소스를 참고, 고민해서 아래와 같은 구조로 만들겠다는 생각을 하게 되었습니다

![image](https://github.com/tasty-code/ios-box-office/assets/67363759/4885e779-0f2e-4517-a3f4-11024096e948)

- Network
request, session
request와 세션에서 필요한 인터페이스는 전부 생성자로 통해 제공받음
- API
kobis (DailyBoxOffice, DetailMovie, etc)  API 
 kobis API 에서 공통 인자는 프로토콜로 빼버리고 나머지 변경사항을 각각의 API에서 인터페이스로 제공받음
- DTO
입력되는 데이터를 사용자의 틀에 맞는 규격으로 사용
- Manager
네트워크 통신에서 사욛되는 코드를 조합하여 
NetWork의 인터페이스에 API 정보를 전달하고 반환되는 데이터를 DTO로 변환함

```swift
let dailyBoxOfficeAPI = DailyBoxOffice(
    path: "/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json",
    date: dailyFormatter(format: "yyyyMMdd")
)

let networkRequestBuilder = NetworkRequestBuilder(
    baseUrl: dailyBoxOfficeAPI.url,
    path: dailyBoxOfficeAPI.path,
    header: ["Content-Type" : "application/json"],
    query: [
        "key" : dailyBoxOfficeAPI.key,
        "targetDt" : dailyBoxOfficeAPI.date
    ],
    method: HTTPMethodType.get,
    urlScheme: URLScheme.https
)

var networkManger = NetworkManager<DailyBoxOfficeDTO>(
    networkSession: networkSession,
    networkRequestBuilder: networkRequestBuilder
)
```

2024-02-28 02:54 UTC, Gnoam-R commented on BoxOffice/Sources/Model/Network/KobisService/KobisService.swift
> +}
Any 타입은 어떠한 타입이든 구분 없이 전부 사용이 가능합니다
하지만 이 부분이 장점이자 단점인것이 항상 모든 타입에 대해서 허용되어 있다는 것은 사용되는 부분에서 모든 타입에 대한
핸들링이 완료되어야 합니다. 
왜냐하면 Any 타입의 경우 컴파일 시 타입의 정보를 확인할 방법이 없기 때문에 에러를 감지하기 어렵기 때문입니다.
따라서 Any타입은 특정 경우를 제외하면 지양해야 됩니다.

2024-02-28 06:08 UTC, FirstDo approved these changes
안녕하세요 두분!

방학때도 이리 열심히시라니.. 대단하십니다 ㅎㅎ
저번에 코맨트 드린후 정말 많은 고민을 하고 코드를 작성하신것 같아 좋습니다

저번에도 그렇고 이번에도 그렇고 제가 코드를 보면서 느낀점들이 있어요

우선 조각조각 최대한 분리하시려고 하는점은 너무 좋습니다.
작은 기능 마져도 다 분리하고 고민한 수고가 느껴집니다

다만, 이렇다보니 객체의 응집성이 너무떨어집니다

```swift
// 1
sturct NumberNamager {
 let number: Int
}

// 2
struct NumberManager {
   let number: NumberProtocol
}

protocol NumberProtocol {
   var num: Int { get set }
}

struct Number: NumberProtocol {
  let num: Int
}
```

2번코드가 1번코드보다 과연 좋은 코드일까요?
아무도 그렇게 생각하지 않겠죠?

객체의 분리는 좋으나, 같은 객체에서 수행해야할 역할마저 다 찢어놓으면 코드 가독성도 떨어지고 구조적으로도 오히려 별로입니다

추가로 단순 구현을 위한 프로토콜이 잘못됬다고 생각하진 않으나
단순 프로퍼티나 매서드를 사용하기 위해 (ex) StatusCodeProtocol) 프로토콜을 구현하고 해당 프로토콜을 채택하는건 좀 더 고민해야 할 부분인것 같네요.

코맨트들은 한번 읽어보시고 다른의견이야 이야기해야할 부분이있다면 언제든지 dm 주세요!
STEP2는 여기서 마무리 하겠습니다 :) 오랜기간 고생하셨어요!

2024-02-28 06:08 UTC, FirstDo commented on BoxOffice/Sources/JSON/JsonDecoder.swift
> +}
이친구를 만드신 이유가 뭘까요?
그리고 만든시점에 얻을수 있는 이점이 있을까요?

무조건 프로토콜과 객체를 만든다고 좋은것은 아닐겁니다

현재 구현
```swift
        let decoder = JsonDecoder.shared
        let data = jsonString.data(using: .utf8)
        guard let data = data,
              let result = try? decoder.decode(T.self, data)
        else {
            return nil
        }
```

객체 없을때 구현
```swift
        let data = jsonString.data(using: .utf8)
        guard let data = data,
              let result = try? JsomDecoder().decode(T.self, data)
        else {
            return nil
        }
```

위 방식이 아래방식보다 좋나요..?
저는 아닌것 같습니다만, 두분의 생각이 궁금합니다!

틀린것이 아닌, 왜 이걸 만들게 되었는지가 궁금해요.

2024-02-28 06:08 UTC, FirstDo commented on BoxOffice/Sources/JSON/JsonEncoder.swift
> +}
JsonDecoder와 같은 코맨트입니다

2024-02-28 06:08 UTC, FirstDo commented on BoxOffice/Sources/JSON/JsonFileManager.swift
> +}
이부분 좋습니다!

여기서 또 질문이 있다면

1. 프로토콜 추상화를 하는 이유는 무엇인가요?
2. 왜 여기서는 하지 않았나요?
3. JsonFileManager 인스턴스를 만들필요가 있나요? static으로 만드는 방법도 있지 않을까요? 이 방식을 선택한 이유가 궁금하네요

2024-02-28 06:08 UTC, FirstDo commented on BoxOffice/Sources/Model/DailyFormatter.swift
> +}
DailyFormatter 라는 친구를 프로토콜로 만들어서 얻는 이점이 무엇일까요?
좀 더 근본적으로 프로토콜 추상화를 하는 이유는 뭘까요?

구체적으로 다른 객체와 비교해서 여쭤본다면
JsonFileManager 이친구는 그냥 객체로 만들고, DailyFormatter는 프로토콜로 만들어서 채택한 이유가 뭘까요?
구현이야 그렇다 처도 두분만의 기준이 있어야합니다

현재 이친구는 단순히 dailyFormatter라는 매서드를 추가해주기 위해 사용한 상황입니다만
이런식의 방식보다는 DateFormatter를 관리하는 객체를 하나 만드는게 더 나아보입니다

2024-02-28 06:08 UTC, FirstDo commented on BoxOffice/Sources/Network/Response/Interface/NetworkResponse.swift
> +}
good :)

2024-02-28 06:08 UTC, FirstDo commented on BoxOffice/Sources/Network/RequestBuilder/Implementation/NetworkRequestBuilder.swift
> +final class NetworkRequestBuilder: NetworkRequestBuilderProtocol {
두분의 클래스/구조체 선택 방식은 무엇일까요?

`NetworkRequestBuilder` 이친구는 상당히 좋고 유연하게 대응할 수 있습니다.
많은 고민을 하시고 작성하신게 느껴집니다 ㅎㅎ

다만 매번 아래 코드를 작성하는게 좋은 방법은 아닌것 같네요

내가만든 api를 다른 개발자가 쓴다고 할때, 현재 unitTest에 나와있는것처럼 쓰라고 한다면..?

```swift
        let networkRequestBuilder = NetworkRequestBuilder(
            baseUrl: dailyBoxOfficeAPI.url,
            path: dailyBoxOfficeAPI.path,
            header: ["Content-Type" : "application/json"],
            query: [
                "key" : dailyBoxOfficeAPI.key,
                "targetDt" : dailyBoxOfficeAPI.date
            ],
            method: HTTPMethodType.get,
            urlScheme: URLScheme.https
        )
```

2024-02-28 06:08 UTC, FirstDo commented on BoxOffice/Sources/Network/Response/Interface/StatusCodeProtocol.swift
> +}
이친구도 추상화를 위해서가 아닌, 단순히 아래 프로퍼티들을 networkManager에서 사용하기 위해 만든 프로토콜인데,
이런식의 구현은 어떤 장점이 있을까요?

networkManager에 그냥 statusCode를 판별하는 매서드를 추가해줘도 되지않나요??
어떤차이가 있기에 이런식으로 만드셨는지 궁금합니다

2024-02-28 06:08 UTC, FirstDo commented on BoxOffice/Sources/Network/Session/Implementation/NetworkSession.swift
> +        self.session = session
session을 받는 이유가 있을까요?

2024-02-28 23:32 UTC, Gnoam-R commented on BoxOffice/Sources/JSON/JsonDecoder.swift
> +}
처음 JsonDecoder를 사용했을 때는 첫번쨰로 커스텀에 대한 고민을 했습니다. 
반환 형태를 제네릭이 아닌 단일 타입으로 하는것이 안정성 측면에서 좋지 않나? 하지만 범용성 측면에서 좋은 방식이 아니라 판단되어 해당 부분을 지우게 되었습니다. 
두번쨰로는 오픈 클래스인 JSONDecoder는 싱글톤이 아니기 때문에 항상 객체를 생성하는것으로 알고있는데 커스텀으로 싱글톤으로 만들어서 사용하자고 생각하게 되었습니다

2024-02-28 23:46 UTC, Gnoam-R commented on BoxOffice/Sources/JSON/JsonFileManager.swift
> +}
1. 코드의 유지 보수와 확장성을 좋게 하기위해서 사용한다고 생각합니다
2. 큰 이유는 없지만 JsonFIleManager의 경우 decode 함수 말고는 다른 기능을 하고 있지 않아서 이 행동을 쪼갤 생각을 딱히 하지 않았던거 같아요. 지금 보면 JsonDecodable, BundleManger 등등으로 프로토콜을 만들어서 사용할수 있었을거 같습니다
3. 위에서 JsonDecoder처럼 여기도 static으로 했으면 더 좋았을거 같네요! 이렇게 한 이유는...생각하지 못해서 입니다 ㅎㅎ...

2024-02-29 00:08 UTC, Gnoam-R commented on BoxOffice/Sources/Network/RequestBuilder/Implementation/NetworkRequestBuilder.swift
> +final class NetworkRequestBuilder: NetworkRequestBuilderProtocol {
맞습니다. 재사용성과 범용성을 고민하다 보니 이와 같은 구조가 나타나게 된거 같습니다
제 생각에는 Manager 모델을 통해서 API와 Network 기능을 분리해서 가져오는것을 생각했기 때문에 다음과 같은 결과로 나왔던거 같아요.

Network와 API의 공통 요소를 묶어서 API에서 설정할수 있도록 하면 다른 개발자 입장에서 API를 통한 더욱 간편한 방법이 
될거 같습니다

2024-02-29 00:15 UTC, Gnoam-R commented on BoxOffice/Sources/Network/Session/Implementation/NetworkSession.swift
> +        self.session = session
URLSession의 경우 자체 싱글톤이 있어서 다음과 같이 가져올 수 있는데요
반드시 싱글톤으로 URLSession을 가져오는 것이 아니라 URLSession을 여러 객체로서 사용해도 되겠다고 생각을 해서
그에 대한 의존성을 외부에서 제공받도록 만들어야겠다고 생각했습니다
```swift
networkSession = NetworkSession(session: URLSession.shared)

networkSession = NetworkSession(session: URLSession())
```

2024-02-29 00:22 UTC, Gnoam-R commented on BoxOffice/Sources/Network/Response/Interface/StatusCodeProtocol.swift
> +}
추상화를 고민하다 여러 코드들이 목적에 벗어나게 되는거 같네요... 
이부분 또한 어떠한 장점 또는 목적이 있어서 라기 보다 조금 더 책임을 잘게 쪼개서 
향후 다른 프로젝트에서 재 사용하고자 하는 생각 때문에 만들게 되었습니다. 
앞으로 코드 작업에 있어 왜라는 고민을 더 해야 될거 같아요!

2024-03-03 10:26 UTC, merged