박스오피스앱 [Step2] 미르, 이안
tasty-code/ios-box-office pull request #37
Opened 2024-02-20 09:12 UTC by mireu930

@keeplo 안녕하세요 말꼬!
이번 박스오피스앱 STEP2 보내드립니다!
STEP2도 잘부탁드립니다!🙇

### 🤔 고민했던점
- URL을 활용해서 JSON decode하는 부분이 고민되었습니다.

처음하는부분이라서 많은 고민이 있었습니다. URLSession의 dataTask메서드로 task를 생성하고, completionHandler에서 가공된 data, response, error를 전달받아 처리를 하였고, completion에 제네릭타입과 errror을 tuple로 전달하여 처리하도록 구현해줬습니다.
```swift
func taskUrl<T: Codable>(url: String, type: T.Type, completion: @escaping (T?, Error?) -> Void) {
        guard let url = URL(string: url) else {
            completion(nil, FetchError.invalidURL)
            return
        }
        
        urlSession.dataTask(with: url) { (data, response, error) in
            if let error = error {
                completion(nil, error)
                return
            }
            guard let response = response as? HTTPURLResponse,(200...299).contains(response.statusCode) else {
                completion(nil, FetchError.invalidResponse)
                return
            }
            
            guard let data = data else {
                completion(nil, FetchError.invalidData)
                return
            }
            
            guard let movie = try? JSONDecoder().decode(T.self, from: data) else {
                return
            }
            completion(movie, nil)
            
        }.resume()
    }
```
- Unit Test를 어떻게 해줄까에 대한 고민을 했습니다.
NetworkManager의 URLSession의 dataTask메서드를 그대로 가져와서 유닛테스트를 했을때 오류가 나고, fail이 뜨는게 지속되어 단순히 테스트를 위한 URLProtocol 클래스를 상속받는 서브 클래스를 생성 후 해당하는 객체를 URLSession configuration에 주입하는 방식으로 테스트를 구현해줬습니다.

### 🧐 조언을 얻고 싶은 부분
CodingKeys 타입을 중첩으로 작성해서도 API 특성으로 묶여 있는 BoxOfficeResult 정도는 생략할 수 있게 만들 수 있다고 하였는데, 디코딩을 해주지 못하더라구요.. 보내주신 블로그도 참고해봤지만 이렇게 하는게 맞는지 모르겠습니다..
```swift
struct BoxOfficeDataResponse: Codable {
    let boxOfficeType: String?
    let showRange: String?
    let dailyBoxOfficeList: [DailyBoxOfficeInfo]?

    enum CodingKeys: String, CodingKey {
        case showRange, dailyBoxOfficeList
        case showRange
        case dailyBoxOfficeList
        case boxOfficeType = "boxofficeType"
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.boxOfficeType = try container.decodeIfPresent(String.self, forKey: .boxOfficeType)
        self.showRange = try container.decodeIfPresent(String.self, forKey: .showRange)
        self.dailyBoxOfficeList = try container.decodeIfPresent([DailyBoxOfficeInfo].self, forKey: .dailyBoxOfficeList)

    }
}
```

2024-02-20 10:48 UTC, keeplo requested changes
두 분 Step 2 진행하시라 고생 많으셨습니다!
이번 주도 힘차게 달려보시죠! 🙌🙌

---
### 고민했던점
> Unit Test를 어떻게 해줄까에 대한 고민을 했습니다.

혹시 어떤 에러였는지 자세히 알려주실 수 있으신가요?
UnitTest 환경에서만 네트워크 통신이 실패했나요? 
아니면 ViewController 에서 동작시켜도 동일하게 실패했나요?

제가 알기론 유닛테스트에서 통신해도 동작에는 문제가 없는걸로 알고 있습니다

---
### 조언을 얻고 싶은 부분
> CodingKeys 타입을 중첩으로 작성해서도 API 특성으로 묶여 있는 BoxOfficeResult 정도는 생략할 수 있게 만들 수 있다고 하였는데, 디코딩을 해주지 못하더라구요.. 보내주신 블로그도 참고해봤지만 이렇게 하는게 맞는지 모르겠습니다..

참고 형태로 소개해드린 부분이라 아마 블로그만으로 이해하시기는 힘드셨을거에요!
블로그는 작성자가 이해한 만큼만 보여지는 정보이면서 작성자의 설명 능력에 따라
내용이 틀릴 수도 있기 때문에 참고는 하되 가능하면 공식문서를 꼭 참고하시는걸 권장드립니다.

[Encoding and Decoding Custom Types](https://developer.apple.com/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types)
전반적인 인코딩, 디코딩에 관한 아티클입니다. 중반부 부터 말씀드린 CodingKey 사용이 나옵니다.

그리고 예시로 한번 보여드리면 좋을것 같아서 작성해본 코드 드려봅니다.
실제 디코딩 테스트까진 안해보았는데 참고를 위해 작성합니다

~~~swift
// MARK: - BoxOfficeResult
struct BoxOfficeResult: Decodable {
    let boxofficeType: String
    let showRange: String
    let dailyBoxOfficeList: [DailyBoxOfficeInfo]
    
    enum CodingKeys: String, CodingKey {
        case boxOfficeResult
    }
    
    enum NestedKeys: String, CodingKey {
        case boxofficeType
        case showRange
        case dailyBoxOfficeList
    }
    
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        
        let boxOfficeResult = try container.nestedContainer(keyedBy: NestedKeys.self, forKey: .boxOfficeResult)
        self.boxofficeType = try boxOfficeResult.decode(String.self, forKey: .boxofficeType)
        self.showRange = try boxOfficeResult.decode(String.self, forKey: .showRange)
        self.dailyBoxOfficeList = try boxOfficeResult.decode([DailyBoxOfficeInfo].self, forKey: .dailyBoxOfficeList)
    }
}
~~~
위처럼 디코딩을 하면 `BoxOfficeDataResponse` 구현은 하지 않을 수 있어요!

--- 

추가적으로 [Comment](https://github.com/tasty-code/ios-box-office/pull/30/files/f8c0f36537213bd380979d30d0ae7b42bda94da6#r1492490917)
이렇게 남겨주셨는데 BoxOfficeDailyDTO.swift 이 파일에 수정이 안되어있더라구요 
확인해주세요!

---

이번 프로젝트에서 모두 처음접하시는 영역들이라면 많이 어려우신게 맞고 
어려운 영역이 맞습니다. 하지만 앱 개발에서 가장 중요한 부분이기도 하니
탄탄한 이해가 필요하기도 해요!

Step 진도도 중요하지만 공식문서나 공부자료를 통해서 기초부터 쌓아가시면 좋을것 같아요!

디엠으로 언제든 어려운 부분이 있으시면 연락주세요!

리뷰 남긴 부분들 고민해주시고 답변 또는 수정해주세요!

2024-02-20 10:48 UTC, keeplo commented on BoxOffice/Model/MovieDetail.swift
혹시 모든 데이터를 파싱 하신 의도가 있으실까요?

알아차리기 힘든 정보도 많은데 데이터를 1:1로 매칭하신 이유가 있으신가요?

2024-02-20 10:48 UTC, keeplo commented on BoxOffice/Model/FetchError.swift
> +enum FetchError: Error {
enum을 이용해서 Error 타입을 구성해주셨군요!

좋습니다 👍👍

2024-02-20 10:48 UTC, keeplo commented on BoxOffice/Model/BoxOfficeUrlPath.swift
> +}
`/kobisopenapi` 라거나 `/webservice` , `/rest` 등의 path는 중복되기도 하고
다른 API를 생각하면 다양한 조합이 가능할 것 같은데

`URL` 이라거나 `URLComponents` 등 키워드로 조금더 학습하고
url 구성을 짜보면 좋을것 같아요
지금은 2개 뿐이지만 API 가 많아진다면 모두 하드코딩으로 관리하기 힘들 수 있습니다.

2024-02-20 10:48 UTC, keeplo commented on BoxOffice/Model/NetworkManager.swift
> +    init(urlSession: URLSession = URLSession.shared) {
URLSession의 shared 싱글턴 개체를 사용하셨군요!

URLSession 개체는 sharedInstance 형태로 인스턴스 생성도 자유롭게 가능한데
싱글턴 개체로 사용하신 의도가 있으신가요?

2024-02-20 10:48 UTC, keeplo commented on BoxOffice/Model/NetworkManager.swift
> +}
NetworkManager의 fetchData 메서드라면

네트워크 통신을 요청하고 data만 fetch 하는게 메서드의 목적으로 추론할 수 있을것 같아요
현재 구현대로라면 불러온 데이터도 Parse 동작까지 함게 하는것 같은데
데이터 파싱은 외부에서 할 수 있게 수정해보면 어떨까요?

2024-02-20 10:48 UTC, keeplo commented on BoxOffice/Model/NetworkManager.swift
> +            }
response 개체에서 상태코드를 이용해서 패킷의 성공 유무를 확인해주셨군요!

StatusCode에 관해서 간략하게 설명해주실 수 있을까요?

2024-02-20 10:48 UTC, keeplo commented on NetworkManagerTests/Extension/MovieDetail+.swift
작성해주신 것처럼 모든 값을 비교하는 점은 코드의 양이 상당합니다.

전통적으로 프로그래밍에서 `구조체` 라는 타입을 공부해보면 좋을것 같아요

모든 데이터를 내부에 모든 프로퍼티까지 같은지 확인하는건 너무나 리소스 낭비가 되기 때문에
같은 데이터인지는 서버에서 이미 처리했다는 신뢰를 가지고 데이터를 처리하면 좋을것 같아요.
이런 신뢰를 가지고 데이터를 처리한다면 데이터의 `id`를 비교해서 같은 식별자라면. 
`같은 데이터` 또는 `덮어써야할 데이터`로 인식하고 처리하는게 일반적일 것 같아요.

Swift에서도 관련된 처리를 돕는 프로토콜이 있는데 소개해드리겠습니다 
`Identifiable` 프로토콜에 대해서 조사해보시고 이용하셔도 좋고 굳이 이용하시지 않더라도
현재 데이터에서 식별자로 사용될만한 프로퍼티로 각 데이터의 비교점으로 이용하면 좋을것 같아요!

2024-02-20 10:48 UTC, keeplo commented on NetworkManagerTests/NetworkManagerTests.swift
> +        configuration.protocolClasses = [TestURLProtocol.self]
`URLProtocol`을 채택한 개체를 테스트를 위한 Mock으로 사용하셨군요!

음 저는 `URLProtocol`의 대한 기초가 없다보니 이해가 힘들어서 그런데
configuration.protocolClasses = [TestURLProtocol.self] 이런 형태로 구현하면
자동으로 URLProtocol 타입에 개체가 TestURLProtocol로 대체되는 걸까요?

2024-02-20 10:48 UTC, keeplo commented on NetworkManagerTests/NetworkManagerTests.swift
> +        sut.fetchData(url: "https://kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key=ab168a1eb56e21306b897acd3d4653ce&targetDt=20240210", type: BoxOfficeDataRespon
25번 라인에서 사용되었는데 동일한 스트링을 하드코딩하신 의도가 있으신가요?
불필요한 중복은 줄이면 좋을것 같아요!

2024-02-20 10:48 UTC, keeplo commented on NetworkManagerTests/Extension/TestURLProtocol.swift
> +}
이 개체를 인스턴스화 해서 사용할 수는 없는 걸까요?

2024-02-21 04:50 UTC, mireu930 commented on BoxOffice/Model/NetworkManager.swift
> +    init(urlSession: URLSession = URLSession.shared) {
`URLSession 개체는 sharedInstance 형태로 인스턴스 생성도 자유롭게 가능하다`라는 것은 따로 init하지않아도 새로운 인스턴스를 생성할수 있다는 말씀이실까요? 이와같이 정의해준경우는 URLSession 인스턴스를 받지 않으면 기본적으로는 전체적으로 공유?되는 URLSession.shared를 사용하도록 되어 있지만, 필요함에 따라 다른 URLSession 인스턴스를 제공할 수 있도록 해주기 위함이였습니다.

2024-02-21 04:58 UTC, mireu930 commented on BoxOffice/Model/NetworkManager.swift
> +            }
HTTP 응답코드로, 서버로부터 받은 요청에 대한 처리 결과를 세자리 숫자로 나타내주어 그 상태에 따라 처리결과를 알수 있도록 해줍니다.

2024-02-21 06:15 UTC, mireu930 commented on NetworkManagerTests/NetworkManagerTests.swift
> +        configuration.protocolClasses = [TestURLProtocol.self]
넵. TestURLProtocol이 URLSession 구성과 관련된 protocolClasses 배열에 추가되고, URLSession을 사용하는 네트워크 요청이 네트워크로 전송되기 전에 TestURLProtocol에 의해 가로채지고 처리된다는 의미입니다. 
[WWDC](https://developer.apple.com/videos/play/wwdc2018/417/)

2024-02-21 06:46 UTC, mireu930 commented on BoxOffice/Model/NetworkManager.swift
> +}
[해당커밋](https://github.com/tasty-code/ios-box-office/pull/37/commits/af39483f006e165e5b12a6838b025c75a775310b)수정했습니다!

2024-02-21 06:48 UTC, mireu930 commented on NetworkManagerTests/NetworkManagerTests.swift
> +        sut.fetchData(url: "https://kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key=ab168a1eb56e21306b897acd3d4653ce&targetDt=20240210", type: BoxOfficeDataRespon
단순히 테스트를 위해서 하드코딩식으로 하였습니다..의도는 없었습니다.
api라는 프로퍼티를 추가해줬습니다!

2024-02-21 08:24 UTC, mireu930 commented on BoxOffice/Model/MovieDetail.swift
모든 데이터를 파싱한 것은 테스트 용도로 1:1로 매칭하여 정확성을 검증하기 위해서 파싱했었습니다.

2024-02-22 07:58 UTC, mireu930 commented on NetworkManagerTests/Extension/TestURLProtocol.swift
> +}
URLProtocol의 서브클래스이며 테스트 목적으로 주로 사용되며, 일반적으로 직접 인스턴스화해서 사용하지는 않는 걸로 알고 있습니다.

2024-02-22 08:03 UTC, mireu930 commented on BoxOffice/Model/BoxOfficeUrlPath.swift
> +}
[해당커밋](https://github.com/tasty-code/ios-box-office/pull/37/commits/c469c9f4eccd9eb02a86bbd14e51b727264f8768) 수정하였습니다!

2024-02-22 12:26 UTC, Marcorable commented on BoxOffice/Model/NetworkManager.swift
> +    init(urlSession: URLSession = URLSession.shared) {
[Singletons and Shared Instances in Swift](https://drewag.me/posts/2019/09/03/singletons-and-shared-instances-in-swift) 이 Article을 추천드릴게요!

Shared Instance는 싱글턴 개체를 제공하는 타입임에도 인스턴스 할당이 가능한 타입을 말합니다.

음 주입을 선택적으로 할 수있게 해주신 의도가 있군요 좋습니다!

2024-02-22 12:41 UTC, merged

2024-02-22 12:42 UTC, Marcorable commented
우선 리뷰도 잘 반영해주시고 정리가 되었다고 생각해서 머지했습니다!

Step 3 진행하시다가도 코멘트 남긴 부분 수정하거나 유념하면서 진행해주시면 좋을것 같아요!