박스오피스 앱 [STEP2] Sidi, Yuni
tasty-code/ios-box-office pull request #38
Opened 2024-02-20 09:23 UTC by jus1234

안녕하세요. 지성([[@yim2627](https://github.com/yim2627)](https://github.com/yim2627))!

시디, 유니입니다.

이번 스텝도 잘 부탁드립니다. 🙇🙇‍♀️

네트워크 통신을 담당하는 타입을 설계하고 구현하면서 `URLSession`에 대한 공부를 진행하고 만들어 보고자 많은 고민을 하게 되었습니다. PR이 늦어진 점 죄송합니다ㅜㅜ

## **STEP2** 요구사항

- 네트워크 통신을 담당할 타입을 설계하고 구현
- 일일 박스오피스 조회
- 영화 개별 상세 조회

## PR Point

이번 스텝에서는 네트워크 통신 담당 타입을 구현했습니다. 데이터를 요청하는 네트워크 통신 과정을 책임 별로 나누어 보았습니다.

- `Requestable`: API호출에 필요한 HTTP 요소 소유(가진 정보를 통해 `URLRequest` 생성)
- `DataTransferService`: 데이터 전송 담당(`encoding`, `decoding`을 통해 데이터 변환)
- `NetworkService`: `Requestable`를 통해 생성한 `URLRequest`를 `URLSession`으로 전달
- `NetworkSessionManager`: `URLSession` 관리 및 작업 실행 담당

다양한 요청과 다양한 상황에 대응하기 위해 책임 별 객체를 분리해 보았습니다. 더 개선될 수 있는 방향이 있다면 조언 부탁드립니다!!

2024-02-20 15:43 UTC, yim2627 requested changes
안녕하세요 Sidi, Yuni!

전체적으로 깔끔하게 잘 구현해주신 것 같습니다! 예외처리도 잘 해주셨네요.

너무 파편화되지 않았나 생각도 들었지만, 이 부분은 커멘트에 객체의 책임 관련으로 조금 남겨보았습니다.

확인 부탁드리고, 테스트는 네트워크 의존적이라 올바른 테스트가 진행되진 않을 것 같습니다. 이 부분도 확인 부탁드립니다!

궁금하신 점이 있다면 언제든지 DM 주세요! 수고 많으셨습니다.

2024-02-20 15:43 UTC, yim2627 commented on BoxOffice/Model/Movie.swift
> +    }
각 모델들에 Equatable을 채택해주셨는데 이유가 궁금합니다. 테스트 떄문일까요?

2024-02-20 15:43 UTC, yim2627 commented on BoxOffice/Network/APIConfig.swift
> +}
```suggestion
enum URLScheme: String {
    case http
    case https
}
```

2024-02-20 15:43 UTC, yim2627 commented on BoxOffice/Network/APIConfig.swift
> +    associatedtype Response
associatedtype은 어떤 역할을 할까요?

2024-02-20 15:43 UTC, yim2627 commented on BoxOffice/Network/APIConfig.swift
> +}
한 파일에 많은 객체가 들어있어서 이 부분 나눠주시면 더 찾기편할 것 같습니다~

2024-02-20 15:43 UTC, yim2627 commented on BoxOffice/Network/DataTransferService.swift
> +}
👍👍

2024-02-20 15:43 UTC, yim2627 commented on BoxOffice/Network/APIConfig.swift
> +    var responseDecoder: ResponseDecoder { get }
이 타입은 Request 관련 책임을 가지는 타입인데, Response 관련 스펙을 갖고 있는 것이 조금 어색해보이네요. 이 부분은 어떻게 생각하시나요?

2024-02-20 15:43 UTC, yim2627 commented on BoxOffice/Network/APIConfig.swift
> +        }
고차함수를 잘 사용하시네요! 👍

2024-02-20 15:43 UTC, yim2627 commented on BoxOffice/Network/NetworkService.swift
> +    func request(apiConfig: any Requestable,
`any`는 무엇일까요?

2024-02-20 15:43 UTC, yim2627 commented on BoxOfficeModelTests/NetworkServiceTests.swift
> +    }
현재 코드를 보면 네트워크 상황에 따라 테스트 결과값이 달라질 것 같은데, 이를 어떻게 해결할 수 있을까요?

2024-02-21 05:24 UTC, jus1234 commented on BoxOffice/Network/APIConfig.swift
> +}
오타 수정했습니다! 감사합니다

2024-02-21 05:35 UTC, Jin0Yun commented on BoxOffice/Network/APIConfig.swift
> +    associatedtype Response
`associatedtype` 은 제네릭과 유사하게 실제 타입을 추상화해주어
이 프로토콜을 채택한 구조체, 클래스 등에서 타입을 지정해서 사용할 수 있어 다형성을 구현할 수 있습니다.

2024-02-21 06:10 UTC, jus1234 commented on BoxOffice/Network/APIConfig.swift
> +        }
감사합니다☺️

2024-02-21 07:39 UTC, jus1234 commented on BoxOffice/Network/APIConfig.swift
> +    var responseDecoder: ResponseDecoder { get }
`Responsable` 프로토콜을 생성해 책임 분리 했습니다!

2024-02-21 07:39 UTC, jus1234 commented on BoxOffice/Network/APIConfig.swift
> +}
Requestable 파일, Responsible 파일 나누어 분리 했습니다!

2024-02-21 07:41 UTC, jus1234 commented on BoxOfficeModelTests/NetworkServiceTests.swift
> +    }
테스트를 위한 `MockNetworkSessionManager`을 사용해 네트워크 상황에 상관없이 테스트 가능하도록 수정 했습니다.

2024-02-21 07:42 UTC, Jin0Yun commented on BoxOffice/Model/Movie.swift
> +    }
네! 테스트로 인해서 채택했었는데 다시 확인해보니 `Equatable` 프로토콜을 채택하지 않아도 비교가 가능해서 수정하였습니다.

2024-02-21 07:54 UTC, jus1234 commented on BoxOffice/Network/NetworkService.swift
> +    func request(apiConfig: any Requestable,
`any`는 existential type임을 명시적으로 구분시키는 키워드 입니다.
- `concrete type`: static dispatch(컴파일시 결정)
- `existential type`: dynamic dispatch(static dispatch보다 비용이 많이 발생) ex) 프로토콜을 타입으로 사용하는 경우

2024-02-21 08:27 UTC, yim2627 commented on BoxOffice/Model/Movie.swift
> +    }
넵 그 부분도 있고, 테스트에서 필요한 부분이라면 테스트 타겟에서 Extension으로 채택해주는 것이 더 용도에 맞는 것 같아 말씀드렸습니다.

2024-02-21 08:48 UTC, yim2627 approved these changes

2024-02-21 08:48 UTC, merged