박스오피스 앱 [STEP2] Hoi,Hong
tasty-code/ios-box-office pull request #39
Opened 2024-02-20 09:46 UTC by happykwon

안녕하세요 July @July911, 만나서 반갑습니다! 😆
hoi @happykwon hong @ujhong7 입니다.
박스오피스 앱 STEP2 PR 드립니다.

# 🔍 PR Point
1. 일일 박스오피스 조회
2. 영화 코드를 활용한 영화 개별 상세조회 
3. EndPoint 구조체를 활용한 URL Component 관리

# 질문사항 
### 1.SOLD원칙 적용에 관하여
`Fetcher`와 `JSONLoader`를 구현 할 때 최대한 SRP원칙을 준수하려고 노력했습니다.
`protocol`을 활용하여 결합도와 의존성을 좀 더 분리시킬 수 있을 것 같다는 생각을 했지만(리스코프 치환),어떻게 해야할지 사실 감이 잡히지 않습니다.
protocol을 활용해 좀 더 유연한 코드를 만들 수 있는지 July의 의견이 궁금합니다. 

### 2. EndPonit 구현 방식에 관하여
이번 프로젝트를 진행하면서 EndPoint에 대한 대용을 처음 접했고 적용해봤습니다.
이렇게 하면 URL에 대한 관리가 훨씬 편해질 것 같아 좋은 방법인 것 같다고 생각합니다.
기능상에는 문제가 없지만 처음 구현해보는 것이기 때문에 July가 보기에 어색한 부분이나 개선 사항이 있다면 조언 부탁드립니다. 
그리고 현업에서도 `EndPoint`의 개념을 활용하는지 궁금합니다. 

# 📸 Screenshot
### 일일 박스오피스 
![스크린샷 2024-02-20 오후 5.35.16](https://hackmd.io/_uploads/ry4KUkf3T.png)

### 영화상세정보

![스크린샷 2024-02-20 오후 5.35.38](https://hackmd.io/_uploads/S1qtLyz2T.png)

2024-02-21 10:17 UTC, July911 requested changes

2024-02-21 10:17 UTC, July911 commented on BoxOffice/Model/DTO/BoxOfficeResponse.swift
> +    let boxOfficeResult: BoxOfficeResult
아직 결과라는 이름으로 남아있네요 :)

2024-02-21 10:17 UTC, July911 commented on BoxOffice/Model/DTO/BoxOfficeResponse.swift
> +    let dailyBoxOfficeLists: [DailyBoxOfficeList]
DailyBoxOfficeList 은 조금 부자연스러운거같습니다.

2024-02-21 10:17 UTC, July911 commented on BoxOffice/Model/DTO/MovieInfoResponse.swift
> +struct Actor: Codable {
예약어는 다른 이름으로 바꾸시는게 좋아보입니다 :)

2024-02-21 10:17 UTC, July911 commented on BoxOffice/Model/DTO/MovieInfoResponse.swift
> +    enum CodingKeys: String, CodingKey {
외부에서 쓰일까요 ?

2024-02-21 10:17 UTC, July911 commented on BoxOffice/Model/EndPoint.swift
> +        queryItems.append(URLQueryItem(name: "key", value: "f5eef3421c602c6cb7ea224104795888"))
키는 따로 보관하는게 좋아보입니다. 어디가 적절할까요 ?

2024-02-21 10:17 UTC, July911 commented on BoxOffice/Model/Fetcher.swift
> +struct Fetcher {
구조체를 선택하신 이유가 궁금합니다. 또한 이름이 너무 모호합니다.

2024-02-21 10:17 UTC, July911 commented on BoxOffice/Model/Fetcher.swift
> +        var movieInfoData = EndPoint.moviInfoPath
data는 빼주세요 :)

2024-02-21 10:17 UTC, July911 commented on BoxOffice/Model/Fetcher.swift
> +        movieInfoData.getDetailMovieInfoQueryItems(movieCode: movieCode)
getDetailMovieInfoQueryItems. get 의 동작을 하고 있나요 ?

2024-02-21 10:17 UTC, July911 commented on BoxOffice/Model/JSONLoader.swift
> +    func loadJSONFromURL<T: Codable>(from urlString: String, completion: @escaping (Result<T, Error>) -> Void) {
JSONLoader 가 네트워킹까지 하고있는 모습인데요. 
다른 방식으로 수정해보시는걸 권장드립니다.

2024-02-27 04:26 UTC, happykwon commented on BoxOffice/Model/DTO/BoxOfficeResponse.swift
> +    let boxOfficeResult: BoxOfficeResult
수정 완료했습니다 :)

2024-02-27 04:27 UTC, happykwon commented on BoxOffice/Model/DTO/BoxOfficeResponse.swift
> +    let dailyBoxOfficeLists: [DailyBoxOfficeList]
수정 완료했습니다 :) 
네이밍을 어떻게 해야할지 참 고민이 많이 되는 부분 같습니다..

2024-02-27 04:27 UTC, happykwon commented on BoxOffice/Model/DTO/MovieInfoResponse.swift
> +struct Actor: Codable {
Codingkey를 활용해 수정 완료했습니다 .

2024-02-27 04:28 UTC, happykwon commented on BoxOffice/Model/DTO/MovieInfoResponse.swift
> +    enum CodingKeys: String, CodingKey {
`private`를 빼먹었네요 😖 수정완료했습니다.

2024-02-27 04:36 UTC, happykwon commented on BoxOffice/Model/Fetcher.swift
> +struct Fetcher {
구조체를 선택한 이유는 두가지입니다.
애플 공식문서에 보면 특별한 이유가 있지 않다면, 구조체를 Default 값으로 권장한다는 내용이 있었고,
Step2까지의 내용을 봤을 때 class(참조타입)이 주는 이점이 없어보였습니다.

2024-02-27 04:36 UTC, happykwon commented on BoxOffice/Model/EndPoint.swift
> +        queryItems.append(URLQueryItem(name: "key", value: "f5eef3421c602c6cb7ea224104795888"))
두가지 방법이 있을 것 같습니다 
1. gitignore와 plist 활용 
2. xcconfig 파일 활용 
다만 이번 프로젝트에서는 코드에 대한 리뷰를 받아야 하고 
과금이 되거나 보안이 중요한 요소가 아니여서 구현은 따로 하지 않았습니다.

2024-02-27 04:37 UTC, happykwon commented on BoxOffice/Model/Fetcher.swift
> +        var movieInfoData = EndPoint.moviInfoPath
data를 빼고 어떤 단어를 집어넣어야 직관적으로 이해될 수 있는 네이밍이 될까 한참을 고민했습니다.. 
네이밍을 쉽게 생각했는데 앞으로는 조금 더 깊게 고민하고 신경써야 할 것 같습니다 :)

2024-02-27 04:38 UTC, happykwon commented on BoxOffice/Model/Fetcher.swift
> +        movieInfoData.getDetailMovieInfoQueryItems(movieCode: movieCode)
get -> add로 수정완료했습니다. 
get은 ~에서 얻어진것으로 위와 같은 경우에는 add가 더 자연스러운 표현일 것 같네요 감사합니다 ! !

2024-02-27 04:40 UTC, happykwon commented on BoxOffice/Model/JSONLoader.swift
> +    func loadJSONFromURL<T: Codable>(from urlString: String, completion: @escaping (Result<T, Error>) -> Void) {
`protocol` 특강을 듣고 결합도를 낮추는 설계로 다시 구현을 해봤습니다 : )

2024-02-27 04:53 UTC, merged