박스오피스 앱 [STEP2] Jane, Tommy
tasty-code/ios-box-office pull request #40
Opened 2024-02-20 11:31 UTC by jane1choi

리뷰어:
@cherrishRed

버드:

@jane1choi
@angryeon7

안녕하세요 레드❗
척척학사가 되어 돌아온 제인, 토미입니다!(토미는 원래 척척학사였습니다..ㅎ)
먼저, 약속드린 기한 보다 늦어진 점 죄송합니다..🥲 
네트워크 레이어를 구성하는 과정에서 고민하고 논의하는 과정이 길어져 예상보다 PR이 늦어지게 되었네요..
그만큼 고민하고 네트워크 레이어를 구성했으니 읽어보시고 편하게 피드백해 주세요!! 이번 PR도 잘 부탁드립니다 :)
**⭐️ 조언, 제안, 논의 언제나 환영합니다 ⭐️**

## 🔍 What is this PR?
박스오피스 프로젝트 STEP 2 기능을 구현했습니다.

<구현 사항>
- `URLSession`을 이용한 네트워크 레이어 세팅
- 영화 상세 정보 조회, 일일 박스 오피스 조회(어제 날짜 기준) 네트워킹 진행
    - 현재 통신 코드가 ViewController에 위치해 있는데, 추후 스텝에서 기능구현을 실제로 하면서 수정하도록 하겠습니다! 이 부분 확인 부탁드립니다! 

## ✏️ PR Point
### URLSession을 모듈화하여 네트워크 레이어 세팅
프로토콜, 제네릭을 활용한 추상화, 상속을 이용한 일반화를 통해 모든 네트워크 통신에서 사용되는 공통적인 부분을 하나로 묶어 효율적인 통신이 될 수 있도록 네트워크 레이어를 구성하였습니다.

주요 사항

**1. `TargetType` 프로토콜 정의**
`TargetType`은 API들의 공통 Endpoint를 가지고 있는 프로토콜입니다. `TargetType` 프로토콜에서는 모든 request에 필요한 endpoint를 프로퍼티로 정의해두어 해당 준수하는 곳에서 endpoint를 필수로 구현하도록 해주었으며, 프로토콜 extension에서 모든 request에서 필요한 공통 프로퍼티(baseURL), 메서드들을 기본 구현해두어 해당 프로토콜을 준수하는 곳에서는 request마다 달라지는 endpoint 값들만 정의해줄 수 있도록 구성해 반복되는 코드를 줄일 수 있었습니다.

**2. TargetType 준수하는 Service 정의**
TargetType 을 준수하여 API별로 request에 필요한 것들을 쉽게 지정할 수 있도록 했습니다. 
enum 을 이용해 각 API 별 endpoint 에 대한 설정을 한 곳에서 할 수 있도록 하여 유지보수 면에서의 장점을 살렸습니다.
TargetType을 준수하는 곳에서 enum 으로 요청 목록을 작성하고, 각 케이스에 맞는 Endpoint를 정의하여 최종적인 `URLRequest`를 만들기 때문에 읽기 쉬운 코드가 되고, 같은 종류의 요청(ex. 영화, 박스오피스, 로그인 등..)을 하나의 enum으로 묶어 각각 다른 파일로 관리할 수 있기 때문에 서버 측 변경사항에 대응에도 쉽게 수정(Service 파일만 확인하면 됨)할 수 있는 구조로 코드를 구성했습니다.

**3. 요청 후 처리 단위 분리**
request 요청 후 서버로부터 받은 값을 처리하는 단위를 분리(역할 단위를 나눔)하여 공통된 코드를 묶고 디버깅 작업에도 용이하도록 하였습니다. 
- `NetworkProvider.request`: request를 하고 받은 결과를 가지고 request 성공 여부만 판단함.
- `~API` 클래스의 요청 메서드:` BaseAPI`의 `judgeStatus` 메서드를 통해 decode 작업 및 StatusCode 별 분기처리
- 최종 request 함수 (현재는 VC에 위치): 모델에 파싱된 결과 값(데이터 or 에러 메시지) 핸들링 

### configuration를 이용하여 api 키를 숨기는 이유
API 키는 서비스에 대한 접근 권한을 부여하므로, 누군가가 이 키를 알고 있다면 해당 서비스에 대한 접근을 제어할 수 있습니다. 따라서 API 키를 git에 올려서 공개적으로 노출하는 것은 보안 위험을 초래할 수 있습니다.

또한 API 키가 공개되면 다른 사용자가 해당 키를 사용하여 서비스를 남용할 수 있기때문에 `.gitignore`를 사용하여 리모트에 키 정보가 올라가지 않도록 하여 키를 숨겼습니다. 이를 통해 보안 문제를 최소화하고 서비스를 안전하게 유지할 수 있습니다.

2024-02-20 15:40 UTC, cherrishRed requested changes
안녕하세요! 제인 토미!
이번 PR도 정말 수고 많으셨습니다!

두분이 네트워킹에 대해서 열심히 공부하시고, 토론한 흔적이 PR에 남아있는 것 같습니다!

## 칭찬드리고 싶은점 
**🍋 api 키를 저장한 부분**
	정말 너무 중요합니다!
**🍋 network 통신을 각 단계를 잘 나눠서 진행한 부분**
	각 단계에서 필요한 일들만 하도록 메서드 분리가 잘 된 것 같습니다.
**🍋BaseAPI, TargetType 등을 사용해, 새로운 API를 추가하기 쉽게 만든 부분**
	파일별로 관리하면 되는 부분은 좋은 것 같습니다!

## 수정하셨으면 좋겠는 점
**🍋 에러처리**
	전체적으로 에러를 어떻게 처리할 것인가에 대해서 print 문으로만 나오고 있어 에러 핸들링이 더 필요할 것 같습니다. 
**🍋 화면에 보여줄 DataType**
	구현하실 화면 예시를 보니, 서버에서 받은 정보를 모두 사용하는 것이 아니죠. 화면에 보여지는 것을 위한 데이터 타입이 있으면, 레이어도 분리가 되어 더욱 좋을 것 같습니다.

나머지 내용은 댓글로 남겨놓았습니다 😀

2024-02-20 15:40 UTC, cherrishRed commented on BoxOffice/Extension/String+.swift
> +}
간편하게 `extension` 에 `convertYesterdayDateToString` 메서드를 만드셨네요!
그런데, self 를 전혀 사용하지 않는 메서드라, String extension에 있을 이유가 없어 보이네요. 

이런 제안은 어떤가요?
1. viewController에 `getYesterdayDateToString() ` 같은 메서드를 만들기
2. Date를 활용해 Date extension에 만들기 
3. DateConverter 같은 서비스 객체 만들기

2024-02-20 15:40 UTC, cherrishRed commented on BoxOffice/Network/API/BoxOfficeAPI.swift
> +    static let shared = BoxOfficeAPI(provider: NetworkProvider())
API 들을 싱글톤으로 작성하신 이유는 무엇인가요?

2024-02-20 15:40 UTC, cherrishRed commented on BoxOffice/Network/API/BaseAPI.swift
> +    }
Base API 를 만들어서, 겹치는 구현들을 미리 구현하신 부분 너무 좋습니다!

2024-02-20 15:40 UTC, cherrishRed commented on BoxOffice/Network/API/BoxOfficeAPI.swift
> +            .creatURLRequest()
BoxOfficeService 타입은 현재, requestDailyBoxOfficeAPI 내부에서만 사용하는데, 싱글톤으로 만드신 이유가 궁금합니다.

2024-02-20 15:40 UTC, cherrishRed commented on BoxOffice/Network/API/BoxOfficeAPI.swift
> +            }
request 자체에서 실패했을 때는 completion에서 처리하지 않고, print만 하신게 조금 아쉽네요!
request에 실패를 한다고 하더라도 앱은 계속 되야 할 경우가 대부분이니, 어떻게든 다른 방법으로 처리해 보면 어떨까요?

2024-02-20 15:40 UTC, cherrishRed commented on BoxOffice/Network/Foundation/NetworkProvider.swift
> +        session.timeoutIntervalForRequest = TimeInterval(requestTimeOut)
timeOut 기능을 넣으셨군요!
만약 timeout 이 된다면, request 는 어떻게 처리가 되는지 궁금합니다!

2024-02-20 15:40 UTC, cherrishRed commented on BoxOffice/Network/Foundation/Requestable.swift
> +
`Requestable` 이라는 프로토콜을 만드신 이유는 무엇인가요?

2024-02-20 15:40 UTC, cherrishRed commented on BoxOffice/Presentation/ViewController.swift
> +            }
두 메서드 모두 data 를 어떤 타입으로 파싱할지를 제외하고는 겹치는 부분이 있네요. 
에러들을 처리하기 편하도록 만들어 보는것이 어떨까요?

2024-02-21 05:13 UTC, jane1choi commented on BoxOffice/Network/API/BoxOfficeAPI.swift
> +            .creatURLRequest()
`~Service` 타입은 class가 아닌 enum이라 주입없이도 전역에서 사용 가능합니다!

2024-02-21 05:35 UTC, jane1choi commented on BoxOffice/Network/API/BoxOfficeAPI.swift
> +    static let shared = BoxOfficeAPI(provider: NetworkProvider())
현재, `~Service`라는 enum을 통해 request에 필요한 endpoint들을 정의해두고
`~API` 클래스에서 요청 메서드들을 정의해두는 형태로 같은 종류(동일한 path로 가는 요청)의 API는 같은 클래스에 정의하도록 하여 유지보수성을 높였습니다.

이렇게 구성할 경우, 각기 다른 객체에서 하나의 API 클래스의 메서드들을 사용하는 일이 빈번하게 발생합니다.
예를 들면, 영화 상세 조회 요청, 영화 리스트 조회 요청이 다른 객체에서 이루어지게 되면 `MovieAPI` 클래스의 인스턴스를  매번 주입해서 요청 메서드를 사용해주어야 하겠죠! API가 많아지면 이러한 작업들이 번거로워진다고 생각해서 여러 곳에서 인스턴스 생성없이 하나의 API 클래스의 메서드들을 사용할 수 있도록 싱글톤을 이용했습니다. 

저희의 의도는 이러한데, 이 코멘트를 보고 정리를 하다보니 사실 같은 프로퍼티에 여러 스레드에서 접근하는 것이 아니라 단순히 메서드 사용의 편의성을 위한 것이라 싱글톤을 사용하지 않으면 안되는 것은 아닌 것 같다는 생각이 드네요! 여러 객체에서 주입해서 사용하는 것이 나을지, 아니면 이 방법이 좋을 지 고민이 되는데, 여기에 대한 레드의 의견도 궁금합니다! 어떤 방법이 더 좋다고 생각하시나요?

2024-02-21 06:50 UTC, angryeon7 commented on BoxOffice/Extension/String+.swift
> +}
Date를 활용해 Date extension으로 변경하여 수정하였습니다.

2024-02-21 07:04 UTC, jane1choi commented on BoxOffice/Network/Foundation/NetworkProvider.swift
> +        session.timeoutIntervalForRequest = TimeInterval(requestTimeOut)
저희가 공부한 바로는 디폴트 타임아웃 시간이 60초라 너무 길다고 생각해서 `timeoutIntervalForRequest` 프로퍼티를 통해 30초로 설정해주었습니다. 타임아웃 시 [NSURLErrorTimedOut](https://developer.apple.com/documentation/foundation/1508628-url_loading_system_error_codes/nsurlerrortimedout?language=objc) 이라는 에러가 발생해 해당 메서드에서 error로 빠지게 되는데, 이 부분에 대한 처리가 제대로 안되고 있어서 수정해주었습니다! 
반영 커밋: [4b8eff1](https://github.com/tasty-code/ios-box-office/pull/40/commits/4b8eff13f23b96afdc05f5998b058d7a6181ba4b)

한 가지 고민되는 부분은, 타임아웃 발생 시 retry를 한번이나 두번정도 해주는 것이 좋은 처리라고 생각이 드는데요! 이전 경험으로는 `Alamofire` 내부 `RequestInterceptor` 프로토콜의 `retry` 메서드 구현으로 처리를 해주었는데 `URLSession`을 이용한 네트워크 통신에서는 retry하는 방식을 찾아봐도 정확히 나와있는 자료를 찾기가 힘들어 이 부분에 대한 조언 구합니다! 해당 함수에서 error 발생 시 timeout 에러 임을 판단해서 재요청할 수 있는 방법이 있을까요??

2024-02-21 08:17 UTC, angryeon7 commented on BoxOffice/Network/Foundation/Requestable.swift
> +
네트워크 요청을 처리하는 객체가 가져야 하는 속성과 메서드를 정의하기 위해서 사용하였습니다.
1. 의존성 :  프로토콜을 사용하여 네트워크 요청을 처리하는 클래스가 구체적인 타입이 아닌 프로토콜에 의존하도록 함으로써 의존성을 역전다형성을 활용하여 여러 종류의 네트워크 요청을 처리할 수 있습니다.
2. 다형성 및 확장성: 프로토콜을 사용하면 여러 클래스가 동일한 인터페이스를 구현할 수 있으므로, 다형성을 활용하여 여러 종류의 네트워크 요청을 처리할 수 있습니다. (ex. timeout 시간이 다르게 지정해줄수 있다던가, 세부 구현이 다른 request를 추가해서 사용할 수 있음)

이러한 의도로 프로토콜을 구현하여서 provider를 만들었는데, 구현 과정에서 구체타입에 의존하도록 명시해버려서 이 부분을 프로토콜에 의존하도록 수정하였습니다.
확인 감사합니다. 👍 
반영 커밋 : [30f1497](https://github.com/tasty-code/ios-box-office/pull/40/commits/30f14978073340fc0caf15b1f5c1aafc6e29c823)

2024-02-21 08:21 UTC, angryeon7 commented on BoxOffice/Presentation/ViewController.swift
> +            }
에러 처리를 따로 분리하여 겹치는 부분을 수정하였습니다.
반영 커밋 : [00af401](https://github.com/tasty-code/ios-box-office/pull/40/commits/00af401fbe095249a28011ef7d24aa86c182e1a3)

2024-02-21 15:10 UTC, cherrishRed approved these changes

2024-02-23 11:25 UTC, merged