박스오피스 앱 [STEP 1] Andy
tasty-code/ios-box-office pull request #42
Opened 2024-02-21 18:05 UTC by andyanappdev

> 리뷰어 : @Mino777
> 
> 
> 버드 : @andyanappdev (Andy) 
> 

안녕하세요 마이노

이번 프로젝트 진행함에 있어 많은 편의를 봐주셔서 정말 감사드립니다.

아직 저의 수준이 많이 부족하기 때문에 

저만의 속도로 기한 내에 완성하지 못하더라도 끝까지 포기 하지 않고  해보고자 합니다.

잘 부탁드립니다.

---

## STEP 1 : 요구사항

### 모델타입 구현

- [[영화진흥위원회의 일별 박스오피스 API 문서](https://www.kobis.or.kr/kobisopenapi/homepg/apiservice/searchServiceInfo.do?serviceId=searchDailyBoxOffice)]의 데이터 형식을 고려하여 모델 타입을 구현합니다.
    - 제공된 JSON 데이터를 위에서 구현한 Model 타입으로 Parsing 할 수 있는지에 대한 단위 테스트(Unit Test)를 진행합니다.
    - [[box_office_sample.json](https://drive.google.com/file/d/1A3jFJnpyYKOkef4eq4MeVEk7grwipRIS/view?usp=share_link)]

### 스텝 핵심 경험

- [x]  파싱한 JSON 데이터와 매핑할 모델 설계
- [ ]  `CodingKeys` 프로토콜의 활용 (DTO에서 적용 예정)
- [ ]  단위 테스트(Unit Test)를 통한 설계의 검증 (추후 예정)

---

## 파일트리

```
📦BoxOffice
 ┣ 📂App
 ┃ ┣ 📂AppDelegate
 ┃ ┃ ┣ 📜AppDelegate.swift
 ┃ ┃ ┗ 📜SceneDelegate.swift
 ┃ ┣ 📂Assets.xcassets
 ┃ ┣ 📂Base.lproj
 ┣ 📂Domain
 ┃ ┣ 📂Model
 ┃ ┃ ┣ 📜BoxOfficeResult.swift
 ┃ ┃ ┗ 📜MovieDetailInfo.swift
 ┣ 📜Info.plist
 ┣ 📜Secrets.xcconfig
 ┗ 📜ViewController.swift
```

---

## 설계 및 구현 설명

### BoxOfficeResult (Data Model - struct)

- boxOfficeType : 박스오피스 종류 (enum)
    - 일별 박스오피스, 주간 박스오피스, 주말 박스오피스
- boxOfficeList : 각각의 BoxOffice 들의 List
    - BoxOffice : 박스 오피스 순위, 전일대비 순위 증감, 랭킹 신규 진입여부, 영화명, 영화 개봉일, 해당일 매출액 등
        - RankingNewcomer : 랭킹 신규 진입여부 (enum)

### MovieDetailInfo (Data Model - struct)

- 영화명, 상영시간,, 제작연도, 개봉일, 개봉상태, 영화유형, 장르명, 감독명, 배우, 참여 영화사, 심의 정보 등
    - ProductionStatus : 개봉상태 (enum)
    - Genre : 장르 (struct)
    - Actor : 배우 (struct)
    - ParticipatingFilmCompanies : 참여 영화사 (struct)
    - AuditInfo : 심의 정보 (struct)

2024-02-22 13:32 UTC, Mino777 requested changes
안녕하세요!! 앤디!

STEP 1 진행하시느라 정말 수고 많으셨습니다!!🥳

리뷰를 진행하기전에 제가 드리는 말들이 모두 정답이 아니라는걸 꼭 인지하시면 좋을 것 같아요!

학습을 하시면서 많은분들이 말씀하시겠지만, 코드에는 정답이 없답니다!

만약 제가 코멘트를 달았던 부분에 대해서 여러분들의 코드에 근거가 있고, 이게 더 나은 방향인 것 같은데 라는 생각이 드신다면 저를 설득시키고, 토론하는 과정 또한 저와 여러분 모두에게 정말 좋은 경험이 되실 것 같아요!

언제든지 궁금하신 점이 생기시면 바로바로 말씀해주세요😁

## 코멘트

- 궁금하신점이 있으시면 바로바로 DM으로 질문주시면서 프로젝트 진행하셨으면 좋겠어요! 혼자만의 고민도 좋지만, 너무 길어지면 오히려 독이될때도 있습니다!
- 앞으로 PR 메세지에 고민한 점에 대해서 꼭 적어주세요! 어떤점을 고민하셨는지 제가 알 수 있다면, 더 많고, 더 좋은 리뷰를 해드릴 수 있습니다😎
- Codable과 CodingKeys에 대해 학습하시고 이 프로토콜들을 활용해서 Json 파싱을 하는 방법에 대해서 제대로 학습해보시고 프로젝트 진행하셨으면 좋을 것 같습니다💪
- 해외에서 진행하시느라 어려움이 많으실텐데 계속해서 열심히 하시는 모습 너무 좋습니다!! 빠이팅💪💪

2024-02-22 13:32 UTC, Mino777 commented on .gitignore
gitignore 활용 좋습니다👍👍

2024-02-22 13:32 UTC, Mino777 commented on BoxOffice.xcodeproj/project.pbxproj
> +				7F5848572B804E5B0012B247 /* Secrets.xcconfig in Resources */,
xcconfig를 활용해서 API Key를 관리한 부분 너무너무 좋습니다👍👍

나중에 앱을 product, stage, dev 등 스키마를 나누어 관리할 때도 xcconfig를 활용할 수 있습니다😊

2024-02-22 13:32 UTC, Mino777 commented on BoxOffice/Domain/Model/BoxOfficeResult.swift
> +}
Codable, CodingKeys에 대해서 학습하신 후에 프로젝트를 진행하시면 좋을 것 같아요!

꼭 학습하실 때 왜 이런 프로토콜이 만들어지게 되었고, 왜 이 프로토콜을 사용해야하는지를 중점적으로 학습 해보시면 좋을 것 같습니다😊

2024-02-22 13:32 UTC, Mino777 commented on BoxOffice/Domain/Model/BoxOfficeResult.swift
> +}
Codable에 대해 공부해보시고 적용해보시면, 이러한 enum 타입을 매핑할 때 초기화 구문이 존재하면 오히려 복잡성을 증가시킵니다.

boxOfficeType() 같은 메서드도 불필요하다고 느껴지실꺼에요!
직접 적용해보시면서 왜 제가 이렇게 말씀드렸는지 한번 확인해보시면 좋을 것 같습니다💪

2024-02-22 13:32 UTC, Mino777 commented on BoxOffice/Domain/Model/BoxOfficeResult.swift
> +}
저는 개인적으로 네트워킹을 위한 엔티티의 프로퍼티값들을 옵셔널로 정의해주는걸 좋아합니다.

외부 시스템이나, API를 통해 들어오는 데이터의 경우 완전성이 보장되지 않기 때문에 옵셔널로 정의해줄 경우 이런 불완전성을 개발자가 핸들링해줄 수 있습니다😊

2024-02-22 13:32 UTC, Mino777 commented on BoxOffice/Domain/Model/MovieDetailInfo.swift
> +struct MovieDetailInfo: Equatable {
Equatable을 사용해보셨네요! 해당 프로토콜에 대해서 설명해주세요!

2024-02-22 13:32 UTC, Mino777 commented on BoxOffice/Domain/Model/MovieDetailInfo.swift
해당 파일도 BoxOfficeResult 파일에 대한 피드백과 동일합니다.

2024-02-23 03:42 UTC, andyanappdev commented on BoxOffice.xcodeproj/project.pbxproj
> +				7F5848572B804E5B0012B247 /* Secrets.xcconfig in Resources */,
주로 plist를 활용하여 API Key를 숨기는 방법을 사용하다가
이번에 처음 시도해본 부분인데 xcconfig를 활용하여 마이노가 알려 주신 스키마를 나누어서 관리 하는 것도 하는 군요
사실 스키마 관리 라는 부분이 어떤 것인지 잘 와닫지는 않지만 이번 기회에 한번 찾아 보면서 개념을 익혀 보겠습니다.
감사합니다.

2024-02-23 04:00 UTC, andyanappdev commented on BoxOffice/Domain/Model/BoxOfficeResult.swift
> +}
넵~ 알겠습니다 ^^
처음에 빨리 이번 STPE을 끝내야지 라는 생각에 data model struct에 직접 Codabel을 채택하여 DTO없이 작성 하였다가 
이번 프로젝트를 진행함에 있어 제 스스로가 얻어 가고자 하는 것을 빠른 완성이 아닌 남들보다는 많이 느리더라도
이런 저런 많은 고민을 해보고 그 과정에서 필요한 부분을 학습 하자로 목표를 선회 하였습니다.

DTO를 도입하기로 결정하고 Codable 및 CodingKey 프로토콜은 DTO에 적용하고
Mapper를 만들어 (data model struct의 extension) DTO -> data model 과정에서 nil 값이 있을경우 기본값을 주는 형태로 하여 
data model에서는 옵셔널로 선언 하지 않고도 완전성을 보장 받을수 있도록 하려고 합니다.

2024-02-23 04:09 UTC, andyanappdev commented on BoxOffice/Domain/Model/BoxOfficeResult.swift
> +}
조언 너무나도 감사합니다.
이번 기회에 Codable 프로토콜을 좀더 자세히 학습해 보도록 하겠습니다.

2024-02-23 04:12 UTC, andyanappdev commented on BoxOffice/Domain/Model/BoxOfficeResult.swift
> +}
이 부분은 위에 Codable, CodingKeys 관련한 comment에 저의 생각이 포함되어 있어 생략 하겠습니다.

2024-02-23 04:26 UTC, andyanappdev commented on BoxOffice/Domain/Model/MovieDetailInfo.swift
> +struct MovieDetailInfo: Equatable {
인스턴스화된 객체(swift에서는 class의 인스턴스만 object==객체 라고 부르지만 편의상 모두 객체라고 부르겠습니다.)의 _**동등성을 비교하기 위해**_ 사용했습니다.
즉 인스턴스화된 MovieDetailInfo 객체들이 동일한 객체인지를 판별할때 "영화의 대표 코드"가 같은 값이면 동일한 객체로 취급하겠다 다른 값들은 동일하던 동일하지 않던 오직 유일 값이라고 판단했던 "영화의 대표 코드"로 판별 하겠다 라는 의미로 구현해 보았습니다.

2024-02-23 07:57 UTC, merged