박스오피스 앱 [Step 3] 댄, L
tasty-code/ios-box-office pull request #44
Opened 2024-02-23 11:01 UTC by eensungkim

Step 3
멤버 : @eensungkim, @LeeSe0ngYe0n
리뷰어 : @ryan-son

박스오피스 앱 프로젝트의 세 번째 스텝입니다!
정리하여 PR 드립니다. 잘 부탁드립니다! :bow: 

# PR 상세
- 박스오피스 화면 UI 구현
- 로딩 인디케이터 활용
- `refresh control` 기능 구현
</br>

# 이번 스텝을 통해서 배운 점
- 콜렉션뷰 활용
- 커스텀 콜렉션뷰셀 활용
- `SFSymbol` 활용
- 스택뷰의 `arrangedSubviews` 학습 및 활용
- `UIActivityIndicatorView` 학습 및 활용
- `UIRefreshControl` 학습 및 활용
- `LocalizedError` 프로토콜 학습
- `Task` 학습 및 활용
- `async/await` 학습 및 활용
</br>

# 질문
- `SOLID` 원칙을 적용해보려고 조금씩이나마 고민을 이어나가고 있는데요. 
책임을 나눠야 하는 기준을 무엇으로 잡으면 좋을지 아직 갈피를 잡지 못하고 있습니다. 
`NetworkManager` 파일의 `request` 메서드를 예로 들자면, 
`request` 메서드는 내부에서 `makeRequest` 메서드를 호출하면서 `URLRequest` 를 생성하는 책임을 넘긴다고 이해할 수 있는 것일까요?
만약 그렇게 이해할 수 있다면, `request` 메서드는 `makeRequest` 나 `urlSession.data(for:delegate:)`, `JSONDecoder().decode(_:from:)` 과 같은 함수에 책임을 넘겨주고, 그 결과만을 받아서 실행한다고 보면 될까요?
`SOLID` 를 더 알아나가기 위해서 어떤 부분을 더 고민하면 좋을지 궁금합니다.

- 처음에 저희는 `MockURLSession`이 네트워크가 필요한 과정을 대체해주고 있다는 점 때문에, 서버의 역할을 대체해주고 있다고 판단하고 접근을 했었는데요.
혹시 이 이해가 잘못된 이해일지 궁금합니다.
참고로 현재의 구현 내용은 리뷰를 바탕으로 새롭게 짰기 때문에 위의 질문과는 다소 차이가 있습니다.

- 지난 리뷰 내용 중에 *"테스트에서 early exit을 사용하는 경우가 생긴다면 exit하기 전에 XCTFail과 같은 메서드를 배치해주세요. 이 구문이 실패해서 탈출하는 경우 테스트가 성공 처리됩니다*." 라는 말씀을 해주셨었는데요.
`XCTFail` 문서를 살펴보니, 해당 메서드가 실행되면 즉시로 테스트가 `Fail` 처리가 된다고 나와있었습니다.
혹시 저희가 이해하지 못한 다른 내용이 있는 것인가 싶어서 확인차 여쭤봅니다!

2024-02-25 12:09 UTC, ryan-son requested changes
댄, L, 네트워크 단 구조를 변경하고 View 구성해보시느라 고생 많으셨습니다.

점점 더 코드 구성이 익숙한 모습으로 되어가고 있네요. iOS 개발자라면 프로젝트 구성과 세부적인 구현 방식이 일반적으로 해오던 것과 크게 다르지 않아 여러분 프로젝트 코드를 처음 읽는다고 하더라도 크게 괴리감이 있을 것 같지는 않습니다. 지금까지와 마찬가지로 세부적인 내용은 세부 리뷰를 참고해보시고, 본문에서는 여러분이 남기신 질문에 대한 답변만 다루도록 하겠습니다.

># 질문
>- `SOLID` 원칙을 적용해보려고 조금씩이나마 고민을 이어나가고 있는데요. 
책임을 나눠야 하는 기준을 무엇으로 잡으면 좋을지 아직 갈피를 잡지 못하고 있습니다. 
`NetworkManager` 파일의 `request` 메서드를 예로 들자면, 
`request` 메서드는 내부에서 `makeRequest` 메서드를 호출하면서 `URLRequest` 를 생성하는 책임을 넘긴다고 이해할 수 있는 것일까요?
만약 그렇게 이해할 수 있다면, `request` 메서드는 `makeRequest` 나 `urlSession.data(for:delegate:)`, `JSONDecoder().decode(_:from:)` 과 같은 함수에 책임을 넘겨주고, 그 결과만을 받아서 실행한다고 보면 될까요?
`SOLID` 를 더 알아나가기 위해서 어떤 부분을 더 고민하면 좋을지 궁금합니다.

책임을 넘긴다는 표현은 객체지향 프로그래밍 관점에서 살펴보면 책임을 나누고 역할을 수행한다(위임한다)고 표현해볼 수 있을 것 같습니다. 예를 들어, URLSession 인스턴스에 data(for:delegate:)라는 인터페이스를 호출하면 내부적으로 어떤 일이 일어나는지는 모르겠지만(캡슐화) Data와 URLResponse 인스턴스를 반환한다는 것을 알 수 있습니다. 이것이 수많은 URLSession의 역할 중 하나라고 볼 수 있습니다. 이 인터페이스에 맞게 인자를 전달받아서 원하는 반환을 해주는 것이 책임 중 하나인 것이고요. 다만 makeRequest와 같이 메서드가 분리된 형태만으로는 확실히 역할과 책임을 분리했다고 표현하기는 어려울 수 있습니다. 여기에서 역할과 책임을 분리했다함은 내가 아닌 다른 타입이 이러한 역할을 수행할 책임을 가지고 있고, 나는 그가 제공하는 인터페이스를 이용해 작업상 도움을 받는다는 개념으로 이해할 수 있습니다. 캡슐화와 재사용성 측면에서 타입을 설계해 나가다보면 객체들 간의 대화는 인터페이스만으로 이뤄질 수 있으며, 기능 추가 또는 변경이 생긴다고 하더라도 기능 변경이 필요한 타입 이외에는 변경사항이 전파되지 않으므로 이에 대한 유용성이 증명된다고 할 수 있습니다. 이 과정에서 하나의 기능을 구성하기 위해 수많은 타입으로 분리할 수 있으며, 어떤 수준으로 분리해서 구성할 것인가는 전적으로 개발자가 고민해야할 영역입니다. 대부분 요구사항에 기반해 재사용될 가능성이 있는지를 기준으로 구성하는 경우가 많습니다.

>- 처음에 저희는 `MockURLSession`이 네트워크가 필요한 과정을 대체해주고 있다는 점 때문에, 서버의 역할을 대체해주고 있다고 판단하고 접근을 했었는데요.
혹시 이 이해가 잘못된 이해일지 궁금합니다.
참고로 현재의 구현 내용은 리뷰를 바탕으로 새롭게 짰기 때문에 위의 질문과는 다소 차이가 있습니다.

서버의 역할을 대신해주고 있다는 점은 맞지만, 테스트에서 여러분이 의도한대로만 동작하면 된다는 점이 실제 서버와 다른 점입니다. 여러분은 유닛 테스트를 수행할 때, 외부 의존성인 서버에서 어떤 성공 응답, 어떤 에러가 있을지를 가정하고 그러한 응답을 받았을 때 어떻게 동작하는지를 테스트에 포함하면 클라이언트에서 로직 검증은 마쳤다고 볼 수 있기 때문에 모든 케이스에 대한 구현은 필요 없는 것입니다. 예를 들어, 서버에서는 날짜별 박스오피스 목록을 제공해야할 책임이 있지만, 클라이언트 유닛 테스트에서는 어떤 날짜로 요청해도 동일한 응답이 올 것을 가정하고 테스트를 진행할 수 있습니다. 클라이언트의 관심사는 예상된 응답을 할 때, 에러 응답을 할 때, 그리고 네트워크 상태에 의해 예상치 못한 에러가 발생했을 때의 처리가 의도한대로 동작하는지에 있기 때문입니다.

>- 지난 리뷰 내용 중에 *"테스트에서 early exit을 사용하는 경우가 생긴다면 exit하기 전에 XCTFail과 같은 메서드를 배치해주세요. 이 구문이 실패해서 탈출하는 경우 테스트가 성공 처리됩니다*." 라는 말씀을 해주셨었는데요.
`XCTFail` 문서를 살펴보니, 해당 메서드가 실행되면 즉시로 테스트가 `Fail` 처리가 된다고 나와있었습니다.
혹시 저희가 이해하지 못한 다른 내용이 있는 것인가 싶어서 확인차 여쭤봅니다!

예상치 못한 상황이 발생했다면 테스트를 실패처리하는 것이 의도된 동작이기 때문에 사용을 권장드렸습니다. 의도하지 않은 상황이 발생했는데 테스트가 성공한다면 테스트의 역할을 다한다고 보기 어렵기 때문입니다.

이번에도 다소 변경사항이 있을 것 같네요. 화이팅입니다! 궁금한 점 있으시면 언제든지 말씀해주세요~

2024-02-25 12:09 UTC, ryan-son commented on BoxOffice.xcodeproj/project.pbxproj
> +				8A65CC822B8617E800414589 /* Extension */,
`Extension`이라는 이름도 괜찮아 보이네요. 저는 텍스트와 날짜 관련 기능 등 프로젝트의 기본 기능을 제공하니 `Foundation`이라는 이름이 떠오릅니다. 이후에 이런 기능을 모듈로 분리하게 된다면 어떤 이름으로 지을지 생각해보는 차원에서 기능들을 더 잘 표현할 수 있는 이름을 폴더 이름으로 지어보시면 좋을 것 같습니다.

2024-02-25 12:09 UTC, ryan-son commented on BoxOffice.xcodeproj/project.pbxproj
> +				9B8ACB432B7F291000AF2527 /* Network */,
현재 Network는 DTO, URL, Error, Session으로 구성되어 있네요. 조금 더 응집성 있게 구성해본다면, Network 폴더에는 Infrastructure, BoxOffice가, Model에는 DTO가 포함될 수 있을 것 같습니다. Infrastructure에는 NetworkManager와 NetworkManager의 추상 계층, 그리고 내부적으로는 URLSessionProtocol을 가지고 있고, BoxOffice는 NetworkManager에 의존한 네트워크 요청 및 처리의 책임을 가지는 타입을 배치할 수 있겠습니다. 테스트를 위해 BoxOffice 또한 interface 계층을 제공해줄 수 있습니다. DTO의 경우 데이터 표현의 역할로 Network 뿐만 아니라 View에서도 역할이 필요할 수 있으므로 Model로 배치해볼 것을 고려해볼 수 있습니다.

2024-02-25 12:09 UTC, ryan-son commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    private let loadingIndicatorView: UIActivityIndicatorView
`UIActivityIndicatorView`는 View의 성격이 강하니 주입 받기보다 이곳에서 인스턴스를 생성해도 괜찮을 것 같습니다.

2024-02-25 12:09 UTC, ryan-son commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    }
`dataSource`라는 이름에 비해서는 한정된 데이터를 다루고 있네요. 현재는 `BoxOfficeViewController`에서 다루는 데이터가 `DailyBoxOffice.BoxofficeMovie`의 배열이지만, 상황에 따라 오늘 날짜, 본인에게 온 알림 메시지 개수, 읽지 않은 알림 존재 여부와 같은 데이터를 함께 다뤄야 할 수도 있습니다. 이번 프로젝트에서는 이렇게 구성한 상태로 진행해보시고, 제가 가정한 요구사항이 추가된다면 어떻게 대응할 수 있을지 고민해보시면 좋겠습니다.

2024-02-25 12:09 UTC, ryan-son commented on BoxOffice/Controller/BoxOfficeViewController.swift
>      private let networkManager: NetworkManager
dataSource가 View에 데이터를 공급하는 역할을 부여받았다고 한다면, 네트워크 기능은 View와 dataSource 중 어떤 타입이 처리하는 것이 더 적합할까요?

2024-02-25 12:09 UTC, ryan-son commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    init(dataSource: [DailyBoxOffice.BoxOfficeMovie] = [], networkManager: NetworkManager, loadingIndicatorView: UIActivityIndicatorView) {
기본값이 예상된다면 이니셜라이저에 기본값을 포함해주시는 것도 좋은 방법입니다. 사용하는 입장에서 더 간편하게 사용할 수 있고, 유닛 테스트 등 특별한 상황에서는 필요에 따라 주입해줄 인스턴스를 지정해서 전달해주면 되기 때문입니다.

2024-02-25 12:09 UTC, ryan-son commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        view = boxOfficeView
UIViewController의 view를 변경할 소요가 있다면 [이 문서](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621454-loadview)를 참고해보세요.

2024-02-25 12:09 UTC, ryan-son commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    }
이 작업은 NetworkManager 또는 NetworkManager의 추상화된 인터페이스에 의존하는 네트워크 레이어를 구성하고, 도메인 모델 인스턴스 또는 에러를 던지거나 반환해서 View는 이 결과를 이용함으로써 네트워크 요청에 필요한 많은 부분들을 추상화시켜볼 수 있을 것 같습니다.

2024-02-25 12:09 UTC, ryan-son commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "BoxOfficeCollectionViewCell", for: indexPath) as? BoxOfficeCollectionViewCell else {
앞으로도 UICollectionViewCell, UITableViewCell과 같은 요소들을 사용할 때 String 기반의 reuseIdentifier를 사용하게 될텐데요, 이를 간편하게 사용할 수 있도록 기능을 확장해보시면 좋겠습니다. 아래는 메서드 요구사항입니다.

```swift
collectionView.register(BoxOfficeCollectionViewCell.self)
let cell: BoxOfficeCollectionViewCell = collectionView.dequeueReusableCell(for: indexPath)
```

2024-02-25 12:09 UTC, ryan-son commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        cell.configure(data: dataSource[indexPath.row].destructed())
array 인스턴스를 사용할 때 유효하지 않은 index에 subscript 방식으로 접근하면 런타임 에러가 발생하죠. 물론 논리가 잘 구성된 경우에는 이런 현상이 발생하지 않겠지만, 앞으로 요구사항에 따라 구현이 변경되며 어떤 일이 일어날지는 알 수 없습니다. 그런 경우에 대비해 유효하지 않은 index에 접근할 경우 방어 코드를 작성해보시는 것도 좋겠습니다. 그런 경우가 발생한다면 일차적으로 사용자에게 문제가 발생했으며 다시 로드해줄 것을 요청해볼 수 있겠죠. 그 다음 예상치 못한 논리 결함이 발생했음을 개발팀에 리포팅하는 로직을 구성해볼 수 있습니다. 이번 프로젝트에서는 방어 코드를 작성하고 사용자에게 현재 상황과 기존 상태로 회복할 수 있는 방법을 알려주도록 구성해보시길 바랍니다.

2024-02-25 12:09 UTC, ryan-son commented on BoxOffice/Extension/DateFormatter.swift
> +}
메서드의 개발자 경험을 향상시켜본다면 이런 인터페이스도 생각해볼 수 있을 것 같네요. iOS 15.0부터 Foundation 프레임워크에서 Date를 포함한 다양한 타입에 formatted 메서드를 지원하고 있으니 알아보시면 좋겠습니다.

```swift
extension Date {
    static let yesterday: Date {
        return Calendar.current.date(byAdding: .day, value: -1, to: Date()) ?? Date()
    }
    
    enum Format: String {
        case standard = "yyyy-MM-dd"
        case withTime = "yyyy-MM-dd HH:mm:ss"
        case monthDayYear = "MM/dd/yyyy"
        // ...
    }

    func formatted(using format: Format) -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = format.rawValue
        return formatter.string(from: self)
    }
}

// Usage
let formattedYesterday: String = Date.yesterday.formatted(using: .standard)
```

- [formatted(date:time:) - Apple Developer](https://developer.apple.com/documentation/foundation/date/3766588-formatted)

2024-02-25 12:09 UTC, ryan-son commented on BoxOffice/Extension/IntFormatter.swift
> +}
아래 자료들도 참고해보세요. 현재 업계에서 일반적인 최소 지원 OS 타겟이 iOS 14.0이라 현업에서 빈번하게 사용되지는 않고 있고, 여러분들도 제공되는 API에 의존하기보다 직접 구현하실 수 있는 방법을 파악하시는 것이 중요하므로 이번 프로젝트에서 적극적으로 채택하시는 것은 권장드리지 않지만, 최소 지원 OS가 iOS 15.0로 올라간다면 고려해볼 수 있는 선택지이므로 학습해두시면 도움이 될 것입니다.

- [FormatStyle - Apple Developer](https://developer.apple.com/documentation/foundation/formatstyle)
- [Formatters: Make data human-friendly - WWDC20](https://developer.apple.com/videos/play/wwdc2020/10160/)

2024-02-25 12:09 UTC, ryan-son commented on BoxOffice/Model/DailyBoxOffice.swift
> +        }
튜플은 간단하게 사용하기는 좋지만, 프로퍼티의 추가, 제거 및 변경 시 관련된 구현을 모두 수정해야한다는 점과 Equatable과 같은 프로토콜을 채택할 수 없다는 단점으로 인해 적극적으로 사용하지는 않습니다. 데이터를 표현할 수 있는 타입인 BoxOfficeMovie를 그대로 이용하시면 좋을 것 같은데, 이러한 메서드를 구성하신 이유가 무엇이었나요?

2024-02-25 12:09 UTC, ryan-son commented on BoxOffice/Network/Error/NetworkError.swift
>  }
이러한 에러는 개발자가 확인하기에는 좋지만, 사용자가 확인하기에는 적합해보이지 않네요. 사용자 친화적인 문구에는 어떤 상황인지, 어떻게 정상적인 상태로 돌아갈 수 있는지가 포함되어 있으면 좋습니다.

2024-02-25 12:09 UTC, ryan-son commented on BoxOffice/Network/Error/NetworkError.swift
> +            "전달받은 URLResponse 가 적합한 URLResponse 가 아닙니다."
유효하지 않은 상태 코드 케이스처럼, 유효하지 않은 URL이라면 어떤 url인지, 적합한 URLResponse가 아니라면 어떤 response인지 표현할 수 있도록 associated value를 추가해볼 수 있을 것 같습니다.

2024-02-25 12:09 UTC, ryan-son commented on BoxOffice/Network/NetworkManager.swift
> +            throw NetworkError.invalidStatusCode(httpResponse.statusCode)
1. statusCode가 200번대가 아닌 경우에도 에러가 발생할 수 있어보이네요. `data(for:delegate:)` 메서드와 `decode(_:from:)`에서 그럴 수 있겠네요. 이런 케이스를 상위 수준에서 사용자 친화적인 메시지로 변환할 수 있도록 `NetworkError` 케이스로 만들어줄 수 있으면 좋겠습니다. 아래는 예시이며 여러분들이 고려하셔서 원하는 구조를 만들어보세요.
```swift
enum NetworkError {
    case underlying(Error)
}

do {
    // try method
} catch {
    throw NetworkError.underlying(error)
}
```
2. 유효하지 않은 API key를 사용한 경우와 같이 API에서 에러 응답을 반환하는 경우가 있습니다. 이런 경우 응답을 통해 문제 해결을 할 수 있도록 어떤 형태로 응답하는지 특성을 살펴보시고 적합한 형태로 파싱해서 API에서 제공한 정보를 활용해보시기 바랍니다.

2024-02-25 12:09 UTC, ryan-son commented on BoxOffice/Network/URL/HTTPMethod.swift
> +}
예상되는 모든 케이스를 미리 만들어두시기보다, 필요할 때 만들어도 좋을 것 같습니다.

2024-02-25 12:09 UTC, ryan-son commented on BoxOffice/Network/URL/KoreanFilmCouncilURL.swift
> +    case movieDetailInformation(movieCode: String)
URL 구성 방식을 한 단계 고도화시켜볼까요? 예시에서의 핵심 기능은 API를 묶음 형식으로 표현할 수 있도록 enum으로 제공한 기존 구현은 유지하되, 각 케이스가 필요로하는 HTTP 메서드를 프로퍼티로 요구하며, 이를 통해 URLRequest 인스턴스를 생성하는 방법까지 제공한다는 점입니다. 물론 아래는 정답이 아니고 조금 더 범용적인 인터페이스로 사용할 수 있도록 구조를 만들어 본 예시이므로 따르실 필요는 없습니다. 아래와 같은 구성이 아니라 protocol-struct로 동일한 구조를 표현할 수 있습니다. 어러분이 구현하신 방식을 포함해서 각 방식의 장단점을 비교해보시고, 여러분은 어떤 접근 방식을 취하시고 싶으신지 결정해보세요.

```swift
protocol APIRequest {
    var baseURL: String { get }
    var path: String { get }
    var method: HTTPMethod { get }
    var body: Data? { get }
    var parameters: [String: Any]? { get }
    var headers: [String: String]? { get }
    
    func asURLRequest() throws -> URLRequest
}

extension APIRequest {
    func asURLRequest() throws -> URLRequest {
        // provide default implementation...
    }
}

// Case definition
enum BoxOfficeAPI {
    case dailyBoxOffice(date: String)
    case movieDetailInformation(movieCode: String)
}

// Protocol implementation
extension BoxOfficeAPI: APIRequest {
    var baseURL: String {
        // 개발 환경과 릴리즈 환경에 따라 이 URL이 변경되어야 한다면 어떤 방식으로 접근할 것인가?
        "https://kobis.or.kr/kobisopenapi/webservice/rest/"
    }
    
    var path: String {
        switch self {
        case .getMovies:
            return "/boxoffice/searchDailyBoxOfficeList.json"
        case .movieDetailInformation:
            return "/movie/searchMovieInfo.json"
        }
    }
    
    var method: HTTPMethod {
        switch self {
        case .dailyBoxOffice:
            return .get
        case .movieDetailInformation:
            return .get
        }
    }
    
    var body: Data? { ... } // POST, PUT 등 필요 시 활용
    
    var parameters: [String: Any]? { // key 파라미터는 공통적으로 활용할 수 있도록 구성 필요
        switch self {
        case let .dailyBoxOffice(date):
            return ["targetDt": date]
        case let .movieDetailInformation(movieCode):
            return ["movieCd": movieCode]
        }
    }
    
    var headers: [String: String]? {
        ["Content-Type": "application/json"]
    }
}
```

2024-02-25 12:09 UTC, ryan-son commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +class BoxOfficeCollectionViewCell: UICollectionViewListCell {
더이상 상속할 필요가 없다면 final 키워드를 적용해볼까요?

2024-02-25 12:09 UTC, ryan-son commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +    }()
프로퍼티를 미리 지정해 초기화하는 방식으로 코드를 구조화시켜보셨네요. `UIStackView`, `UILabel`에서 이런 프로퍼티를 지정할 일이 많으니 convenience initializer를 제공하는 방식도 고려해볼 수 있을 것 같습니다.

```swift
extension UILabel {
    convenience init(style: UIFont.TextStyle, alignment: NSTextAlignment, color: UIColor) {
        self.init()
        font = .preferredFont(forTextStyle: style)
        textAlignment = alignment
        textColor = color
    }
}

extension UIStackView {
    convenience init(axis: NSLayoutConstraint.Axis, distribution: UIStackView.Distribution) {
        self.init()
        self.axis = axis
        self.distribution = distribution
    }
}

// Usage
private let rankLabel = UILabel(style: .largeTitle, alignment: .center, color: .black)
private let rankStackView = UIStackView(axis: .vertical, distribution: .fillProportionally)
```

2024-02-25 12:09 UTC, ryan-son commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +    }
튜플 대신 정의한 커스텀 타입의 인스턴스를 주입 받을 수 있도록 구성해볼까요?

2024-02-25 12:09 UTC, ryan-son commented on BoxOffice/View/BoxOfficeView.swift
> +class BoxOfficeView: UIView {
마찬가지로 final 키워드 적용해볼 수 있을 것 같습니다.

2024-02-25 12:09 UTC, ryan-son commented on BoxOffice/View/BoxOfficeView.swift
> +    }()
UIViewController에서 제공하는 navigationBar 대신 View 레벨에 navigationBar를 포함하신 이유는 무엇이었나요? 각각 어떤 장단점이 있을까요?

2024-02-25 12:09 UTC, ryan-son commented on BoxOffice/View/BoxOfficeView.swift
> +    }()
`UITableView`와 비교해봤을 때 `UICollectionLayoutListConfiguration`을 이용한 `UICollectionView` 구성은 어떠셨나요?

2024-02-25 12:09 UTC, ryan-son commented on BoxOffice/View/BoxOfficeView.swift
> +    }
각 프로퍼티를 설정하는 것과 로딩 인디케이터 애니메이션을 시작하는 것, 그리고 delegate를 지정하는 인터페이스를 각각 분리한다면 메서드 이름을 더 명확하게 표현할 수 있을 것 같아요.

2024-02-25 12:09 UTC, ryan-son commented on BoxOffice/View/BoxOfficeView.swift
> +    }
`BoxOfficeViewController` 인스턴스를 전달받아 활용한다면 Child -> Parent 방향으로 의존성이 발생하므로 본인이 몰라야할 인터페이스까지 알게된다는 단점이 있을 것 같네요. delegate pattern으로 풀어보면 어떨까요?

2024-02-25 12:09 UTC, ryan-son commented on BoxOfficeTests/NetworkManagerTests.swift
> +    func test_makeRequest메서드는_기본적으로GET메서드를_반환한다() throws {
기본적으로 대신 `httpMethod를 전달하지 않으면`이라는 표현을 사용하면 상황을 더 명확하게 표현할 수 있을 것 같습니다.

2024-02-25 12:09 UTC, ryan-son commented on BoxOfficeTests/NetworkManagerTests.swift
> +        XCTAssertEqual(request?.url?.lastPathComponent, expectation)
lastPathComponent보다 전체 URL을 매칭한다면 의도한 URL을 적절하게 표현하고 있는지 확인하기 좋을 것 같아요.

2024-02-25 12:09 UTC, ryan-son commented on BoxOfficeTests/NetworkManagerTests.swift
>      }
이 케이스는 성공 케이스와 실패 케이스를 가정해서 각각 테스트 메서드로 만들어볼 수 있을 것 같네요.

2024-03-06 09:34 UTC, eensungkim commented on BoxOffice.xcodeproj/project.pbxproj
> +				8A65CC822B8617E800414589 /* Extension */,
`Foundation` 이 좋은 것 같습니다. 실제로 `Foundation` 에서 제공하는 기본 객체들의 extension 이라서 명확하게 보일 것 같아요!
수정했습니다! 🙏

2024-03-06 09:38 UTC, eensungkim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    private let loadingIndicatorView: UIActivityIndicatorView
수정했습니다!

2024-03-06 10:49 UTC, eensungkim commented on BoxOffice/Controller/BoxOfficeViewController.swift
>      private let networkManager: NetworkManager
dataSource 가 처리하는 것이 더 적합하다고 판단하여, networkManager 를 모델인 DailyBoxOffice 가 가지도록 변경했습니다.

2024-03-06 10:51 UTC, eensungkim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    init(dataSource: [DailyBoxOffice.BoxOfficeMovie] = [], networkManager: NetworkManager, loadingIndicatorView: UIActivityIndicatorView) {
이해했습니다!
`dataSource` 를 변경하고 `NetworkManager` 를 데이터소스가 가지도록 변경하면서, 아예 주입이 필요없어진 관계로 특별히 변경하지는 않겠습니다!

2024-03-06 10:58 UTC, eensungkim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        view = boxOfficeView
레퍼런스 감사합니다!
적용하여 수정했습니다. 🙇

2024-03-07 01:40 UTC, eensungkim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "BoxOfficeCollectionViewCell", for: indexPath) as? BoxOfficeCollectionViewCell else {
static 변수 className 을 선언하여 쉽게 불러올 수 있도록 구현해 보았습니다.

2024-03-07 08:12 UTC, LeeSe0ngYe0n commented on BoxOffice/Extension/DateFormatter.swift
> +}
말씀해주신 인터페이스로 변경해보았습니다!
그대로 가져다 쓰기가 민망해서 사실 `Date.FormatStyle.DateStyle`에 정적프로퍼티를 추가해주고 싶어서 찾아봤지만 실제 구현부인 소스코드를 찾지 못했습니다 혹시 어디에서 찾아볼 수 있을까요?
[Swift OpenSource Github](https://github.com/apple/swift-corelibs-foundation/tree/main/Sources/Foundation)

2024-03-07 08:14 UTC, LeeSe0ngYe0n commented on BoxOffice/Extension/IntFormatter.swift
> +}
참고해서 학습해보겠습니다! 감사합니다!!

2024-03-07 08:24 UTC, LeeSe0ngYe0n commented on BoxOffice/Model/DailyBoxOffice.swift
> +        }
튜플 형태의 데이터가 분해하기 편리하다고 생각하여 위와 같이 구현하였습니다.
단점에 대해 언급해주셔서 현재는 별도에 중첩 클래스를 만들어서 DTO의 데이터를 변환해주었습니다!

2024-03-07 08:44 UTC, LeeSe0ngYe0n commented on BoxOffice/Network/Error/NetworkError.swift
>  }
사용자에게 노출되어야 하는 에러와 개발자에게 노출되어야 하는 에러의 맥락이 겹쳐있는 것이 지금 구현의 문제인 것 같습니다.
사용자가 알아야 하는 에러 메세지와 개발자가 알아야 하는 에러가 분리되어야 하고, 사용자들이 앱을 사용하면서 발생한 에러는 수집되어 로그로 남아야 한다고 생각합니다.
다만 현재 구현한 에러 케이스 중, API 서버 에러를 제외하면 나머지 상황은 앱의 구현 자체에 문제가 발생한 것이기 때문에 개발자가 수정하지 않는 이상 정상적인 앱의 작동이 불가능한 상황이라고 생각합니다. 말씀해 주신대로 사용자에게 중요한 것이 에러가 발생했을 때 어떻게 정상적인 상태로 돌아갈 수 있는지가 중요하다면, API 서버 에러가 발생하는 경우만 별도의 에러로 분리해서 사용자에게 노출하고 나머지는 앱을 종료할 수 밖에 없지 않을까 싶습니다.
저희가 이해한 바가 말씀해주신 의도에 잘 부합할까요?

2024-03-07 08:45 UTC, LeeSe0ngYe0n commented on BoxOffice/Network/Error/NetworkError.swift
> +            "전달받은 URLResponse 가 적합한 URLResponse 가 아닙니다."
위에서 저희가 이해한 바가 맞다면, 이 경우에는 개발자에게만 메세지가 노출되는 것이 좋다고 생각합니다!
이런 점에서 말씀해주신대로 associated value를 추가하는 것이 좋다고 생각합니다!

2024-03-07 08:57 UTC, eensungkim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    }
dataSource 의 타입을 프로토콜을 활용하여 추상화하는 것으로 대응책을 고민해 보았습니다.
다만 새로운 데이터를 다뤄야 하는 경우 프로토콜과 구현체를 수정해야 하는 문제가 발생할 것 같습니다. 😿

2024-03-07 08:58 UTC, eensungkim commented on BoxOffice/Network/URL/HTTPMethod.swift
> +}
넵! 그렇다면 활용도가 높을 것 같은 일부만 남기고 삭제하도록 하겠습니다.

2024-03-07 10:27 UTC, eensungkim commented on BoxOffice/View/BoxOfficeView.swift
> +    }
`handleRefreshControl` 메서드를 delegate 패턴을 활용하여 추상화하는 방법을 말씀하셨다고 생각했는데요.
해당 메서드가 @objc 메서드라서 delegate protocol 로 추상화되지 않는 것 같습니다.
혹시 UICollectionView 가 프로퍼티로 가지고 있는 `refreshControl` 을 delegate 패턴으로 활용하는 것을 말씀하신 것일까요?

2024-03-07 10:31 UTC, eensungkim commented on BoxOfficeTests/NetworkManagerTests.swift
> +    func test_makeRequest메서드는_기본적으로GET메서드를_반환한다() throws {
넵! 수정했습니다! 🙇 
이전에 말씀해 주신 사항을 반영해서 makeRequest 메서드가 Request 에서 호출하도록 변경하면서 private 을 적용해 주었는데요.
이렇게 하게 되면서 test 코드를 실행할 수 없는 상황입니다.
혹시 이런 경우 테스트 코드를 삭제하는 것이 맞을까요?

2024-03-07 11:07 UTC, eensungkim commented on BoxOfficeTests/NetworkManagerTests.swift
>      }
잘못된 url 문자열이 전달되었을 때 에러를 반환하는지를 검증하는 테스트 메서드를 추가했습니다!

2024-03-07 11:07 UTC, eensungkim commented on BoxOfficeTests/NetworkManagerTests.swift
> +        XCTAssertEqual(request?.url?.lastPathComponent, expectation)
전체 URL 과 매칭하도록 변경했습니다!

2024-03-07 11:20 UTC, eensungkim commented on BoxOffice/View/BoxOfficeView.swift
> +    }
분리해보았습니다!!

2024-03-07 11:23 UTC, eensungkim commented on BoxOffice/View/BoxOfficeView.swift
> +    }()
`UICollectionView` 는 테이블뷰를 사용할때보다 고민해야 할 것이 많다는 느낌이었습니다. 
저희는 문서를 찾아보다가 샘플 예제 코드를 발견하고 해당 코드를 참고해 가면서 구성을 해나갔었는데요.
샘플 예제 코드가 없었다면 문서만으로는 어떻게 구성해야 하는지 감을 잡기 어려웠을 것 같습니다.

2024-03-07 11:27 UTC, eensungkim commented on BoxOffice/View/BoxOfficeView.swift
> +    }()
우선 `UIViewController` 에서 기본적인 `navigationBar` 를 제공한다는 점을 모르고 있었기 때문에 `navigationBar` 를 View 레벨에 추가하는 것으로 구성했었습니다.
저희가 작성한 코드는 `BoxOfficeView` 를 뷰컨트롤러의 메인 뷰로 대체하고 있기 때문에 하나의 뷰에서 모든 서브 뷰를 관리하고 있다는 점이 장점이 될 수 있지 않을까 생각합니다.
그 대신 뷰컨트롤러가 기본적으로 가지는 `navigationBar` 가 여전히 등록된 상태로 존재하기 때문에 그만큼의 메모리를 낭비하는 셈이 될 수도 있다고 생각합니다.
혹시 추가적으로 고민해야 할 부분이 있다면 말씀해 주시면 감사하겠습니다!

2024-03-07 11:27 UTC, eensungkim commented on BoxOffice/View/BoxOfficeView.swift
> +class BoxOfficeView: UIView {
넵!!

2024-03-07 11:29 UTC, eensungkim commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +    }
튜플 대신 DailyBoxOffice 클래스가 지난번 말씀해주셨던 도메인(?) 역할을 할 수 있도록 구성하고,
중첩된 클래스로 DailyBoxOffice.Movie 를 만들어주어 해당 데이터 타입을 받도록 변경해 주었습니다!

2024-03-07 11:48 UTC, eensungkim commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +    }()
꿀팁 감사드립니다! 안그래도 중복하는 방법밖에 없을까 했었는데 이런 방법이 있었네요 ㅎㅎ

2024-03-07 11:50 UTC, eensungkim commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +class BoxOfficeCollectionViewCell: UICollectionViewListCell {
적용했습니다!

2024-03-08 01:22 UTC, eensungkim commented on BoxOffice/Network/URL/KoreanFilmCouncilURL.swift
> +    case movieDetailInformation(movieCode: String)
보여주신 예시를 참고해서 나름대로 코드를 작성해 보았습니다. 디자인패턴을 배우면서 알게 된 Builder 패턴을 활용해 보았습니다.
URLComponents 를 활용해 생성하는 것이 더 깔끔할 것 같아서, 이번 프로젝트에서는 아래 코드보다는 URLComponents 를 활용해보려고 합니다.

URLRequest 를 생성해주는 Builder
```swift
class URLRequestBuilder {
    var url: String = ""
    var httpMethod: HTTPMethod
    var body: Data?
    var headers: [String: String]?
    
    init(httpMethod: HTTPMethod = .get, body: Data? = nil, headers: [String : String]? = nil) {
        self.httpMethod = httpMethod
        self.body = body
        self.headers = headers
    }
    
    func baseURL(_ baseURL: String) -> Self {
        url += baseURL
        return self
    }
    
    func path(_ path: String) -> Self {
        url += path
        return self
    }
    
    func parameters(_ parameters: [[String: String]]) -> Self {
        url += "?"
        parameters.forEach { parameter in
            for (key, value) in parameter {
                url += key + "=" + value + "&"
            }
        }
        url.removeLast()
        return self
    }
    
    func createURLRequest() -> URLRequest? {
        guard let url = URL(string: self.url) else {
            return nil
        }
        return URLRequest(url: url)
    }
}
```

빌더를 활용하여 request 생성 및 관리할 열거형
```swift
enum BoxOfficeAPI {
    case dailyBoxOffice(targetDate: String)
    case movieDetailInformation(movieCode: String)
    
    var baseURL: String {
        return "https://kobis.or.kr/kobisopenapi/webservice/rest/"
    }
    
    var apiKey: String {
        guard let apiKey = Bundle.main.infoDictionary?["API_KEY"] as? String else {
            return ""
        }
        return apiKey
    }
    
    var urlRequest: URLRequest? {
        switch self {
        case .dailyBoxOffice(let targetDate):
            return URLRequestBuilder()
                .baseURL(baseURL)
                .path("boxoffice/searchDailyBoxOfficeList.json")
                .parameters([["key": apiKey], ["targetDt": targetDate]])
                .createURLRequest()
        case .movieDetailInformation(let movieCode):
            return URLRequestBuilder()
                .baseURL(baseURL)
                .path("movie/searchMovieInfo.json")
                .parameters([["key": apiKey, "targetDt": movieCode ]])
                .createURLRequest()
        }
    }
}
```

2024-03-08 02:32 UTC, eensungkim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        cell.configure(data: dataSource[indexPath.row].destructed())
유효하지 않은 `index` 에 접근할 때 `fatalError` 대신 `nil` 을 반환해주는 별도의 `subscript` 문법을 확장하여 적용해 보았습니다.
```swift
// 확장 구현한 부분
extension Array {
    subscript(safeIndex index: Int) -> Element? {
        guard index >= 0, index < endIndex else {
            return nil
        }

        return self[index]
    }
}

// 적용 부분
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: BoxOfficeCollectionViewCell.className, for: indexPath) as? BoxOfficeCollectionViewCell,
              let movies = dataSource.loadedData as? [DailyBoxOffice.Movie],
              let data = movies[safeIndex: indexPath.row] else {
            return UICollectionViewCell()
        }
        
        cell.configure(data: data)
        
        return cell
    }
```

유효하지 않은 `index` 의 경우 단순히 빈 셀을 반환하게 되므로 기존의 서브스크립트 문법을 활용할 때 발생할 수 있는 앱의 크래시를 방지할 수 있다고 생각합니다.

궁금한 점이 생기는데요.
`numberOfItemsInSection` 에서 돌려주는 특정한 데이터(count)와 `cellForItemAt` 에서 활용하는 데이터가 같은 데이터로 구성되어 있음에도 유효하지 않은 인덱스에 접근할 수 있는 가능성에 어떤 것이 있을까요?
두 메서드에서 서로 다른 데이터의 정보를 알려주게 된다면 말씀하신 문제가 일어날 가능성이 있다고 생각되는데요. 오히려 이런 경우에는 앱이 크래시나는 것이 개발자가 문제를 확인하기에 좀 더 용이한 상황이 아닌가 싶은 생각도 들어서요.

2024-03-08 02:55 UTC, eensungkim commented on BoxOffice.xcodeproj/project.pbxproj
> +				9B8ACB432B7F291000AF2527 /* Network */,
폴더 구조를 변경해 보았습니다.
에러를 사용자에게 노출될 에러와 내부적으로 개발자가 확인해야 하는 에러, 크게는 이렇게 2가지로 나눠보려고 하는데요.
이 에러를 어디에 배치하는 것이 좋을지가 헷갈리는 것 같습니다.
일단 지금은 `Foundation` 에 배치해 보았습니다.

2024-03-08 04:34 UTC, eensungkim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +    }
네트워크 요청에 필요한 내용을 전부 dataSource 의 책임으로 넘겨주었습니다!

2024-03-08 08:19 UTC, eensungkim commented on BoxOffice/Network/NetworkManager.swift
> +            throw NetworkError.invalidStatusCode(httpResponse.statusCode)
1. 서버 에러가 아닌 모든 에러는 앱이 정상으로 작동하기 어려운 상황이라고 판단하여, 해당하는 경우에는 앱을 사용하기 어렵다는 알럿을 띄우고 `TemporaryUnavailableView` 를 띄워주는 것으로 구현해 보았습니다.

2. 응답 코드는 `200`이었고, `json` 을 돌려주는 것으로 확인했습니다. `json` 을 문자열로 변환한 뒤에 API 에러 응답의 시작부분과 비교하여 일치하는 경우 `invaildAPIKey` 에러를 던지도록 구성해 보았습니다.

2024-03-11 14:31 UTC, ryan-son commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        cell.configure(data: dataSource[indexPath.row].destructed())
일반적으로는 말씀하신 상황이 발생하지 않습니다. 하지만 필요에 따라 `insertItems(at:)`, `deleteItems(at:)`을 수행하고, 배열의 요소를 제거하지 않아 실제 배열 요소의 갯수와 컬렉션뷰의 아이템 갯수가 다르면 해당 문제가 발생할 수 있습니다.

2024-03-11 14:39 UTC, ryan-son commented on BoxOffice/Extension/DateFormatter.swift
> +}
Foundation 프레임워크 저장소에서 찾을 수 있기는 하지만, 직접 커스텀 타입을 정의해서 사용하시는 편이 사용하시는 케이스별로 잘 정리해둘 수 있어서 더 좋을 것 같네요.
- [Date.FormatStyle.DateStyle - Foundation/apple](https://github.com/apple/swift-foundation/blob/52271156a6eab349c65eea75650230f1aa4150a2/Sources/FoundationInternationalization/Formatting/Date/DateFormatStyle.swift#L802-L820)

2024-03-11 14:46 UTC, ryan-son commented on BoxOffice/Network/Error/NetworkError.swift
>  }
사용자가 고칠 수 없는 에러라고 하더라도 앱을 종료한다는 건 사용자가 예상하지 않은 상황일 겁니다. 여러분이 만든 프로덕트라고 가정한다면 어떤 방식으로 에러를 처리하고 싶으신가요? 사용자에게는 비정상적인 상황이라는 것을 알리고, 가장 빠르게 정상화가 가능한 방법이 무엇일지 고민해볼 수 있을 것 같습니다. 현재 프로젝트에서 모든 것을 구현하기는 어렵더라도, 향후에 본인의 프로젝트에서 이러한 일이 발생했을 때 어떻게 처리해둘 것인지를 미리 생각해보는 게 재미있는 포인트일 것 같습니다. 백엔드가 있다면의 가정을 해보아도 좋고요.

2024-03-11 14:47 UTC, ryan-son commented on BoxOffice/Network/URL/KoreanFilmCouncilURL.swift
> +    case movieDetailInformation(movieCode: String)
최초에 구현하신 방법과 제가 제시해드린 방법, 그리고 여러분께서 빌더 패턴을 활용해 구성해본 방식이 어떤 장단점이 있을지 고민해보시는 것도 재미있겠네요.

2024-03-11 14:49 UTC, ryan-son commented on BoxOffice/View/BoxOfficeCollectionViewCell.swift
> +    }
네, 도메인 모델은 여러분 프로젝트에서 핵심 비즈니스 로직을 수행할 때 사용할 모델 타입을 의미합니다. 그 외에는 여러분들께서 활용하고 계신 데이터 전달을 위한 DTO와 같은 모델 타입이 있습니다.

2024-03-11 14:54 UTC, ryan-son commented on BoxOffice/View/BoxOfficeView.swift
> +    }()
1. 커스텀 내비게이션 바를 제공하는 경우라면 여러분이 제시해주신 방식이 더 적합합니다. 
2. 커스텀 내비게이션 바를 제공하지 않는 경우라도 `UIViewController`와 `UIView`를 나눌 때 내비게이션 바 영역을 `UIView`에서 다루는 것이 좋겠다라고 판단하신다면 그것 또한 괜찮은 방식입니다. 이 경우 UIViewController에서 기본적으로 제공하는 `navigationBar`를 활용하지 않으므로 상황에 따라 숨김 처리, 스와이프 백 제스처를 통한 내비게이션 관련 코드 재정의와 같은 추가 작업이 필요할 수 있습니다.
3. `UIViewController`에서 제공하는 내비게이션바를 이용하지 않는다고 하더라도 메모리를 유의미하게 사용하지는 않습니다. 메모리 관련 사항은 고려 대상에서 제외해도 괜찮습니다.

2024-03-11 14:57 UTC, ryan-son commented on BoxOffice/View/BoxOfficeView.swift
> +    }()
`UICollectionViewCompositionalLayout`와 같은 Modern Cell Configuration 방식은 비교적 최근에 도입되었지만, Apple이 직관적이고 쉽게 사용할 수 있다는 점을 강조하기 위함인지 공식문서, 공식 샘플 프로젝트와 WWDC 영상과 같은 참고자료가 잘 마련되어 있습니다. 앞으로도 공식문서를 적극적으로 활용해보시면 좋겠습니다.

2024-03-11 15:11 UTC, ryan-son commented on BoxOffice/View/BoxOfficeView.swift
> +    }
이런 방식은 어떨까요?

```swift
protocol BoxOfficeViewDelegate: AnyObject {
    func boxOfficeViewDidRequestRefresh(_ view: BoxOfficeView)
}

final class BoxOfficeView: UIView {
    private func configureRefreshControl() {
        boxOfficeCollectionView.refreshControl = UIRefreshControl()
        boxOfficeCollectionView.refreshControl?.addTarget(self, action: #selector(handleRefreshControl), for: .valueChanged)
    }

    @objc private func handleRefreshControl() {
        delegate?.boxOfficeViewDidRequestRefresh(self)
    }
}

extension BoxOfficeViewController: BoxOfficeCollectionViewDelegate {
    func boxOfficeViewDidRequestRefresh(_ view: BoxOfficeView) { ... }
}
```

2024-03-11 15:12 UTC, ryan-son commented on BoxOfficeTests/NetworkManagerTests.swift
> +    func test_makeRequest메서드는_기본적으로GET메서드를_반환한다() throws {
네, 다른 테스트가 해당 영역을 테스트해주고 있으므로 제거해주셔도 됩니다.

2024-03-11 15:14 UTC, ryan-son approved these changes
댄, L, Step 3 고생 많으셨습니다.

질문 주신 점에 대해 답변 남겼고, 계속해서 Step 4 진행하고 계신 점 확인했습니다.

추가 질문 있으시면 언제든지 말씀해주세요!

2024-03-11 15:14 UTC, merged