박스오피스 앱 [STEP2] Jin, Sam
tasty-code/ios-box-office pull request #45
Opened 2024-02-24 07:27 UTC by ParkChanH

# 박스오피스 앱 🎬

**리뷰어**: 알라딘 [@junbangg]

**버드**: Jin [@wlsdud-dev], Sam [@ParkChanH]

안녕하세요. 알라딘!

박스오피스 앱 프로젝트를 진행하는 Jin과 Sam입니다.

STEP2 PR 보내드립니다.

리뷰 부탁드립니다! 🤲

## 프로젝트 요구사항
- 네트워크 통신을 담당할 타입을 설계하고 구현합니다.
- [영화진흥위원회의 일별 박스오피스 API 문서] 의 데이터 형식을 고려하여 서버와 실제로 데이터를 주고받도록 구현합니다.
    - 이번 스텝에서 진행할 네트워킹 요소
        - `일일 박스오피스 조회`(어제 날짜 기준)
        - `영화 개별 상세 조회`

## 이번 PR에서 집중한 부분

- **네트워크 통신 로직 구현** : `URLSession` 을 사용하여 영화진흥위원회의 일별 박스오피스 데이터와 영화 상세 정보를 가져오는 기능을 구현했습니다.
- **모델 타입 정의** : API로 부터 받아온 데이터를 저장하기 위해 모델 타입 (`BoxOfficeMovieDTO`, `MovieDatailDTO`) 를 정의하고 필요한 데이터 형식에 맞게 파싱할 수 있도록 구현했습니다.
- **에러 핸들링** : 네트워크 요청 및 응답 과정에서 발생할 수 있는 다양한 에러 상황을 처리하기위해 NetworkError 열거형을 더 확장하여 다양한 에러 케이스를 추가했습니다.
- **날짜 처리** : Date+Extensions 에서 어제의 날짜를 “yyyyMMdd” 형식의 문자열로 얻을수 있도록 처리했습니다.

## 고민했던 점

1. 네트워크 요청 최적화에 대해 : 현제 코드에서는 네트워크 요청을 보낼 때 매번 ‘**URLSessionDataTask**’ 를 생성하고 있습니다. 네트워크 요청의 성늘을 향상 시키거나 관리를 최적화할 수 있는 패턴이나 방법이 있는지 질문하고 싶습니다.

1. NetworkManager 클래스가 앱 내에서 모든 네트워크 통신을 담당하고 있는데 이부분을 더 나누거나 다른방식으로 구조를 바꾸는 게 좋을지 리뷰어님의 생각을 듣고 싶습니다.

1. 파싱한 데이터를 다시 분리하는 점에 대해(**JIN):** 현재 코드에서는 데이터를 서버에서 파싱하고 나서 **`BoxOfficeMovieDTO, MovieDatailDTO`** 객체에 저장하여 뷰(테스트)에 뿌려주는 형태입니다. 파싱한 원본 데이터를 조작하지 않으니 원본의 훼손이 일어나지 않아 안전성이 높아질거라 생각은 하지만 다른 객체에 다시 담는 것이 효율적으로 봤을때 좋은 처리 방식인지 궁금합니다.

1.  데이터 서버요청과 데이터 디코딩의 분리의 필요성: `performRequest` 메서드가 SRP 를 위배 한다고 생각하여 서버요청을 보내고 응답을 받는 기능만 가지게 하고 Json 디코딩 기능을 하는 메서드를 따로 분리 하여 구현하려 했지만 결과적으로 완성은 하지 못했습니다. 하지만 구현하는 도중에 의문점이 생겼는데 굳이 분리해야 할 필요성 이였습니다. 우리 프로젝트에서의 네트워크는 SRP는 꼭 필요한 원칙 일까요?

2024-03-01 03:56 UTC, junbangg requested changes
수고하셨습니다! 코드에서 깔끔함이 느껴지네요 ㅎ
코멘트 확인해주세요!

그리고 질문 주신것에 대한 저의 생각을 말씀 드리면 ...

> 네트워크 요청 최적화에 대해 : 현제 코드에서는 네트워크 요청을 보낼 때 매번 ‘URLSessionDataTask’ 를 생성하고 있습니다. 네트워크 요청의 성늘을 향상 시키거나 관리를 최적화할 수 있는 패턴이나 방법이 있는지 질문하고 싶습니다.
> NetworkManager 클래스가 앱 내에서 모든 네트워크 통신을 담당하고 있는데 이부분을 더 나누거나 다른방식으로 구조를 바꾸는 게 좋을지 리뷰어님의 생각을 듣고 싶습니다.

네트워크 요청의 성능을 향상 시키는 것,, 저도 한번 생각을 해봤는데 
개인적으로는 다음과 같은것들을 생각해볼 수 있을것 같네요..!
- 당연하지만, 비동기로 호출을 하고 메인스레드는 UI 관련된 일만 시킨다
- 필요할때는 캐싱을 활용한다. 대표적으로 이미지 캐싱이 있겠는데, 곧 공부를 하게 되실것 같네요 :)
- 에러 핸들링을 잘한다. 그리고 이걸 유저에게 어떻게 알릴지 고민한다
- 타임아웃을 잘 핸들링한다
- 리다이렉트는 필요할때만 
- 이것도 나중에 고민 해보시겠지만, 효율적인 Pagination 을 활용한다.

그리고 관리에 좋은 패턴이나 방법에 대해서 질문 주셨는데
개인적인 생각으로 지금 테스트할 수 있는 구조는 아닌것 같아요..! (단위 테스트를 말하는겁니다) 
그래서 테스트 할 수 있는 구조로 바꿀 수도 있고
앱내에서 다른 네트워크 호출을 할때도 재사용성이 있는지에 대해서도 고민해볼 수 있을것 같네요!


> 파싱한 데이터를 다시 분리하는 점에 대해(JIN): 현재 코드에서는 데이터를 서버에서 파싱하고 나서 BoxOfficeMovieDTO, MovieDatailDTO 객체에 저장하여 뷰(테스트)에 뿌려주는 형태입니다. 파싱한 원본 데이터를 조작하지 않으니 원본의 훼손이 일어나지 않아 안전성이 높아질거라 생각은 하지만 다른 객체에 다시 담는 것이 효율적으로 봤을때 좋은 처리 방식인지 궁금합니다.

두분은 다른 객체에 담았을때의 장점이 뭐가 있다고 생각하시는지 궁금합니다!

> 데이터 서버요청과 데이터 디코딩의 분리의 필요성: performRequest 메서드가 SRP 를 위배 한다고 생각하여 서버요청을 보내고 응답을 받는 기능만 가지게 하고 Json 디코딩 기능을 하는 메서드를 따로 분리 하여 구현하려 했지만 결과적으로 완성은 하지 못했습니다. 하지만 구현하는 도중에 의문점이 생겼는데 굳이 분리해야 할 필요성 이였습니다. 우리 프로젝트에서의 네트워크는 SRP는 꼭 필요한 원칙 일까요?

performRequest 가 너무 많은 일을 한다고 생각하실 수도 있죠 ㅎㅎ 
근데 그러면 메서드의 내용을 적절히 메서드로 분리해내는 방법도 있을것 같네요!
SRP 에 대해서 고민해보신 점 아주 좋습니다!👏

2024-03-01 03:56 UTC, junbangg commented on BoxOffice/Model/BoxOfficeMovieDTO.swift
> +    let movicode: String
오타가 있네요!

2024-03-01 03:56 UTC, junbangg commented on BoxOffice/Date+Extensions.swift
> +        return convertNowStr
축약어는 웬만하면 피하는게 좋을것 같아요!

2024-03-01 03:56 UTC, junbangg commented on BoxOffice/Model/JsonManager.swift
> +class JsonManager {
final 에 대해서 혹시 공부 해보셨을까요??

2024-03-01 03:56 UTC, junbangg commented on BoxOffice/Model/JsonManager.swift
> +                if let data = data {
`if let` vs `guard let` 각각 어떻게 구분해서 쓰고 계신가요?

2024-03-01 03:56 UTC, junbangg commented on BoxOffice/Model/JsonManager.swift
> +                        print(error)
어떤 용도의 print 일까요??

2024-03-01 03:56 UTC, junbangg commented on BoxOffice/Model/MovieInfoResponse.swift
> +    let peopleName: String
타입명이 소문자네요..?

2024-03-01 03:56 UTC, junbangg commented on BoxOffice/Model/MovieInfoResponse.swift
> +        case productionStatus = "prdtStatNm"
적절히 네이밍을 잘 수정 하셨군요??👍

2024-03-01 03:56 UTC, junbangg commented on BoxOffice/Model/MovieInfoResponse.swift
> +    let castEn: String
En 이 뭘까요?

2024-03-01 03:56 UTC, junbangg commented on BoxOffice/Network/NetworkError.swift
> +    case APIInvalidResponse
대문자로 시작하게 하신 이유가 있을까요?

2024-03-01 03:56 UTC, junbangg commented on BoxOffice/Network/NetworkError.swift
> +    case requestFiled
requestField 는 어떤 오류인가요?

2024-03-01 03:56 UTC, junbangg commented on BoxOffice/Network/NetworkManager.swift
> +    private init() {}
혹시 객체의 결합도, 의존성 주입에 대해서 공부 해보셨을까요?!

2024-03-01 03:56 UTC, junbangg commented on BoxOffice/Network/NetworkManager.swift
> +
의도된 줄바꿈들일까요??

2024-03-01 03:56 UTC, junbangg commented on BoxOffice/Model/MovieInfoResponse.swift
> +
의도된 줄바꿈일까요?

2024-03-01 03:56 UTC, junbangg commented on BoxOffice/Network/NetworkManager.swift
> +            case 200..<300:
지금 구분하려고 하는 statusCode 들로 타입(enum)으로 변환시키는 과정을 추가하는건 어떨까요??

2024-03-01 03:56 UTC, junbangg commented on BoxOffice/ViewController.swift
> +    private func fetchDailyBoxOffice() {
이건 그럼 추후에 수정/제거될 예정일까요?

2024-03-05 07:17 UTC, wlsdud-dev commented on BoxOffice/Model/BoxOfficeMovieDTO.swift
> +    let movicode: String
코드 점검이 부족했습니다. 더 꼼꼼히 확인하여 오타가 없도록 노력 하겠습니다.
수정 했습니다.

2024-03-05 07:19 UTC, wlsdud-dev commented on BoxOffice/Date+Extensions.swift
> +        return convertNowStr
명확성을 위해 축약어를 피하도록 다시한번 확인하겠습니다.

2024-03-05 07:23 UTC, wlsdud-dev commented on BoxOffice/Model/JsonManager.swift
> +class JsonManager {
클래스의 파이널 키워드를 붙이면 다이나믹 디스패치에서 스태틱디스패치로 메모리를 최적화 할 수 있습니다.
상속을 하지 않을 클래스는 final 키워드를 붙여야 한다고 생각은 했는데 놓치게 되네요.
한번 더 확인 할 수 있도록 노력 하겠습니다.

2024-03-05 07:24 UTC, wlsdud-dev commented on BoxOffice/Model/MovieInfoResponse.swift
> +    let peopleName: String
실수 하지 않도록 주의하겠습니다.
수정 했습니다!

2024-03-05 07:28 UTC, wlsdud-dev commented on BoxOffice/Model/MovieInfoResponse.swift
> +    let castEn: String
En은 언어 코드라 생각해 축약을 했습니다.
English라는 표현이 더 명확한것 같습니다.

2024-03-05 07:28 UTC, wlsdud-dev commented on BoxOffice/Network/NetworkManager.swift
> +
코드컨벤션에 좀 더 신경 쓰겠습니다.

2024-03-05 07:28 UTC, wlsdud-dev commented on BoxOffice/Model/MovieInfoResponse.swift
> +
코드컨벤션에 좀 더 신경 쓰겠습니다.

2024-03-06 08:43 UTC, wlsdud-dev commented on BoxOffice/ViewController.swift
> +    private func fetchDailyBoxOffice() {
네트워크 유닛테스트 하는방법을 학습하지 못해서 뷰컨트롤에서 직접 테스트를 진행 하였습니다.
fetchDailyBoxOffice 메서드는 삭제할 예정입니다.

2024-03-06 09:51 UTC, wlsdud-dev commented on BoxOffice/Network/NetworkManager.swift
> +    private init() {}
의존성 주입에 대해 개념을 얇게 아는 정도입니다.
A라는 개체가 B라는 개체를 프로퍼티로 소유하게 된다면 둘의 관계가 밀접하게 되어 결합도가 증가합니다.
그런 의존도를 낮추기 위해서 의존성 주입과 의존관계 역전법칙을 이용 할 수 있습니다.
의존성 주입은 B라는 객체를 외부에서 생성하고 생성한 B의 인스턴스를 A에게 넘겨주는 방식으로 의존도를 어느정도는 낮출 수 있지만 의존도를 완전히 줄이기 위해서는 의존 관계 역전 법칙을 사용 할 수 있습니다.
A 와 B 개체 사이에 protocol을 이용해 B는 프로토콜을 채택하고 A는 B가 채택한 프로토콜을 소유하여
개체를 독립적으로 만들 수 있습니다.

개념적으로는 조금 이해를 하지만 실제 프로젝트에서 반영하기는 쉽지 않아 구현만 생각했던것 같습니다.

2024-03-07 07:53 UTC, wlsdud-dev commented on BoxOffice/Model/JsonManager.swift
> +                if let data = data {
if let은 조건문의 옵셔널 값이 nil 인지 확인하고 2분기로 작업 할때 사용합니다.
guard let 은 gaurd 문이  Early Exit 이기 때문에  성공을 하면 다음 작업을 수행하고 실패 할 경우 제어문을 이용해 빠른 종료가 필요할때 사용합니다.

2024-03-07 07:56 UTC, wlsdud-dev commented on BoxOffice/Model/JsonManager.swift
> +                        print(error)
예외 케이스를 지정 하지 않았을때 테스트용으로 사용했던 메시지 이었습니다.
수정해서 반영하도록 하겠습니다.

2024-03-07 08:25 UTC, wlsdud-dev commented on BoxOffice/Network/NetworkError.swift
> +    case APIInvalidResponse
사실 다른 프로젝트에서 참고하여 만들다 보니 이해하지 못하고 사용을 했던것 같습니다.
상황에 맞게 에러를 수정 했습니다.

2024-03-07 08:31 UTC, ParkChanH commented on BoxOffice/Network/NetworkError.swift
> +    case requestFiled
해당 케이스는 서버에 요청을 했지만 해당 API 서버 에 문제로 인해 받아오지 못하는 오류 사례입니다,
현재는 사용하고 있는 곳이 없어서 일단 case 만 적어놨지만, 추후 이 부분은 더 검토하여 step3를 진행하도록 하겠습니다.

2024-03-08 03:28 UTC, junbangg commented on BoxOffice/Network/NetworkManager.swift
> +    private init() {}
넵 session도 주입하는 방식으로 수정하면 테스트성이 높아질것 같아요..!

2024-03-08 03:37 UTC, junbangg commented on BoxOffice/Network/NetworkManager.swift
> +            case 200..<300:
statusCode -> enum 에 대한 이야기를 왜 했냐면(지금 같은 경우는 약간 다르긴 해서 넘어가셔도 좋습니다) 

**Type Safety**에 대한 이야기를 말씀드리고 싶어서였어요..! (약간 빌드업 느낌)

저희가 보통 에러를 만나는 경우는 크게 두가지가 있는데요

1. 컴파일 에러
2. 런타임 에러

간혹 하드코딩된 숫자, 문자열을 직접 코드에서 비교하여 사용하면, 의도하지않은 런타임 에러를 만나서 버그가 생길 수가 있습니다. (휴먼 에러)
물론 조심해서 버그가 발생 안할 수도 있겠지만, 나중에 다른 사람이 코드를 수정하면서 잘못 되어서 사이드 이펙트가 생길 수도 있고요!

이걸 방지하기 위해 최대한 Type Safety 를 이용해서 **런타임** 에 만날 수 있는 에러를 **컴파일 타임**으로 미리 확인하는 것입니다..! 

요걸 이야기 드리고 싶었어요,,ㅎㅎ 꽤 과소평가 하기 쉬운 practice 인데, 알아두시면 좋을것 같아서 해당 케이스 이용해서 말씀 드려봅니다~~🙋🏻‍♂️

예)

```
if statusCode == 200 {
    뭐뭐를한다()
} else if statusCode == 400 {
    다른거를한다()
}
```

```
enum StatusCode {
    case 200
    case 404
}
if statusCode == .200 {
    뭐뭐를한다()
} else if statusCode == .404 {
    다른거를한다()
}
```

만약에 200을 실수로 2000 으로 누르면 컴파일 에러가 발생하겠죠..!

2024-03-08 03:37 UTC, junbangg approved these changes

2024-03-09 12:29 UTC, merged