박스오피스 앱 [STEP3] Sidi, Yuni
tasty-code/ios-box-office pull request #48
Opened 2024-02-29 08:37 UTC by Jin0Yun

안녕하세요. 지성 [@yim2627](https://github.com/yim2627)

시디, 유니입니다.

이번 스텝도 잘 부탁드립니다. 🙇🙇‍♀️

### STEP3 요구사항
Step 2에서 구현한 네트워킹 기능을 통해 실제로 상품목록을 API 서버에 요청하여 불러옵니다.
어제의 박스오피스를 볼 수 있는 화면을 구현합니다.
리스트를 아래로 잡아끌어서 놓으면 리스트를 새로고침합니다 (당겨서 새로고침)
처음 목록을 로드할 때, 사용자에게 빈 화면만 보여주는 대신, 로드 중임을 알 수 있게 해주세요.
화면 상단에는 날짜를 표기합니다
리스트 형태로 박스오피스 정보를 표기합니다

### PR Point
**Observable 활용**
- `Observable`을 활용해 `ViewModel`과 `ViewController`를 바인딩해 반응형 프로그래밍 구현

**Clean Architecture 적용**
- `Presentaion`: View, ViewModel
- `Domain`: Entity, Use Case, Repository Interface
- `Data`: Repository
- 의존성의 방향이 안쪽 방향으로만(Domain) 향하게 하고 안쪽에서 바깥 방향으로는 의존하지 않는 구조 

### 질문
info.plist 경로 재설정 후 Scene이 실행되기는 하나 기종별로 안되는 경우가 발생하는데
짐작가는 원인이 더 있을까요..ㅜㅜ?
<img width="1694" alt="스크린샷 2024-02-29 오후 5 31 16" src="https://github.com/tasty-code/ios-box-office/assets/133867430/38786358-a4ac-442e-bf09-a04a8d1111ec">

2024-02-29 14:24 UTC, yim2627 requested changes
안녕하세요 sidi, yuni!

MVVM을 사용하셨네요! 다음부턴 아키텍쳐 관련 변경사항이 있을 땐 논의하고 진행 부탁드립니다!

자잘한 것들은 커멘트로 남겨놓았습니다. 이번 스텝도 고생많으셨어요!

질문 주신 사항은.. 저도 한번 보겠습니다. Xcode 문제인지 뭔지 시뮬마다 상태가 다른건 이유가 잘 파악이 안되네요.

2024-02-29 14:24 UTC, yim2627 commented on BoxOffice/Domain/UseCase/BoxOfficeUseCase.swift
> +    }
👍👍

2024-02-29 14:24 UTC, yim2627 commented on BoxOffice/Domain/UseCase/BoxOfficeUseCase.swift
> +    }
함수가 하나밖에 없는데 굳이 Extension을 통해 분리해주신 이유가 있으신가요?

2024-02-29 14:24 UTC, yim2627 commented on BoxOffice/Infra/Util/Extension/Bundle+.swift
> +    }
👍👍

2024-02-29 14:24 UTC, yim2627 commented on BoxOffice/Infra/Util/Extension/Date+.swift
> +}
더 범용성 있게 만들 수 있을 것 같습니다.

2024-02-29 14:24 UTC, yim2627 commented on BoxOffice/Presentation/MoviesList/View/MovieDetailView.swift
> +final class MovieDetailView: UIViewController {
Cell에서 사용할 CustomView같은데, UIViewController를 상속하신 이유가 있을까요?

2024-02-29 14:24 UTC, yim2627 commented on BoxOffice/Presentation/MoviesList/View/MovieDetailView.swift
> +    private let movie: MoviesCellViewModel
CustomView가 CellViewModel을 알고 있는 것은 어색한 것 같습니다. Cell이 알고 있는 CustomView이니 configure시 필요한 타입만 주입시켜주면 될 것 같은데, 어떻게 생각하시나요?

2024-02-29 14:24 UTC, yim2627 commented on BoxOffice/Presentation/MoviesList/View/MovieDetailView.swift
> +    }
```suggestion
    private func setupNavigationBar() {
        navigationItem.title = "\(movie.movieName)"
    }
```

2024-02-29 14:24 UTC, yim2627 commented on BoxOffice/Presentation/MoviesList/ViewModel/MoviesListCellViewModel.swift
> +    private var movie: MovieBoxOffice
이 프로퍼티는 왜 변수로 선언하셨나요?

2024-02-29 14:24 UTC, yim2627 commented on BoxOffice/Presentation/MoviesList/ViewModel/MoviesListCellViewModel.swift
> +    }
현재 CellViewModel 내부에선 연산프로퍼티만 존재하여 ViewModel처럼 보이지 않는 것 같습니다. 또한 아무 Input이 없으니 더더욱  ViewModel의 역할을 하지 않는 것 같습니다.
ViewModel은 어떤 역할을 하는 것인지 말씀 부탁드립니다.

2024-02-29 14:24 UTC, yim2627 commented on BoxOffice/Presentation/MoviesList/ViewModel/MoviesListViewModel.swift
> +}
이 ViewModel은 데이터를 가져와서 맵핑밖에 안해주고 있는 것 같습니다.
CellViewModel에 위치한 로직들을 이쪽으로 옮기고, 뷰에 원하는 데이터로 변형시킨뒤 셀에선 Configure만 해주는 것이 더 어울릴 것 같은데 어떻게 생각하시나요?

2024-02-29 14:24 UTC, yim2627 commented on BoxOffice/Presentation/MoviesList/View/MoviesListViewController.swift
> +    }
외부에서 사용하나요?

2024-02-29 14:24 UTC, yim2627 commented on BoxOffice/Presentation/MoviesList/View/MoviesListViewController.swift
> +    let refreshControl = UIRefreshControl()
외부에서 사용하지 않는 것 같습니다.

2024-02-29 14:24 UTC, yim2627 commented on BoxOffice/Presentation/MoviesList/View/MoviesListViewController.swift
> +        }
ViewModel을 두셨으니, refresh에 대한 상태 관리 또한 ViewModel로 종속시키면 더 이상적일 것 같습니다.

2024-03-07 07:59 UTC, Jin0Yun commented on BoxOffice/Presentation/MoviesList/ViewModel/MoviesListCellViewModel.swift
> +    }
입력과 관련된 메서드가 없고 데이터 처리만 하고 있어 뷰모델로서의 역할이 명확해 보이지 않아 보이네요😅😅
`MoviesListViewModel`로 로직을 옮기면서 수정하였습니다!!! 감사합니다

`ViewModel`은 UI와 데이터 사이의 중간자로서, UI에 표시할 데이터를 처리하고 제공하며, 사용자 입력을 처리하는 역할을 합니다.

2024-03-07 08:00 UTC, Jin0Yun commented on BoxOffice/Presentation/MoviesList/View/MoviesListViewController.swift
> +    }
`private`키워드 추가하였습니다 감사합니다!

2024-03-07 08:00 UTC, Jin0Yun commented on BoxOffice/Presentation/MoviesList/View/MoviesListViewController.swift
> +    let refreshControl = UIRefreshControl()
수정하였습니다! 감사합니다

2024-03-07 08:01 UTC, Jin0Yun commented on BoxOffice/Infra/Util/Extension/Date+.swift
> +}
수정하였습니다! 9a787e4

2024-03-07 08:01 UTC, Jin0Yun commented on BoxOffice/Presentation/MoviesList/ViewModel/MoviesListViewModel.swift
> +}
수정하였습니다!

2024-03-07 08:03 UTC, Jin0Yun commented on BoxOffice/Presentation/MoviesList/View/MovieDetailView.swift
> +    }
감사합니다!

2024-03-07 08:26 UTC, Jin0Yun commented on BoxOffice/Presentation/MoviesList/View/MovieDetailView.swift
> +final class MovieDetailView: UIViewController {
영화 상세 정보를 보여줄 뷰라서 UIViewController를 상속하여 구현하였습니다.  다음스탭에서 사용할 예정입니다.

2024-03-07 08:30 UTC, Jin0Yun commented on BoxOffice/Presentation/MoviesList/ViewModel/MoviesListCellViewModel.swift
> +    private var movie: MovieBoxOffice
앗... 상수로 선언했어야했는데 더 신경쓰면서 작성하도록 하겠습니다!

2024-03-07 08:37 UTC, Jin0Yun commented on BoxOffice/Presentation/MoviesList/View/MovieDetailView.swift
> +    private let movie: MoviesCellViewModel
CellViewModel을 알고 있는 것은 어색해보이네요..😅😅! 다음스탭에서 적용해 보겠습니다!

2024-03-07 08:39 UTC, jus1234 commented on BoxOffice/Presentation/MoviesList/View/MovieDetailView.swift
> +    private let movie: MoviesCellViewModel
MoviesCellViewModel을 없애 CustomView는 뷰모델을 알고있지 않게 하고 MoviesListViewModel으로 기능을 합치는 것으로 리팩토링 했습니다!

2024-03-07 08:39 UTC, Jin0Yun commented on BoxOffice/Presentation/MoviesList/View/MoviesListViewController.swift
> +        }
`MoviesListViewModel` 모델로 옮겼습니다! 감사합니다

2024-03-07 08:41 UTC, jus1234 commented on BoxOffice/Domain/UseCase/BoxOfficeUseCase.swift
> +    }
이전 프로젝트 컨벤션이 메서드는 익스텐션으로 분리하는 것이었어서 습관적으로 저렇게 작성했습니다ㅎㅎ.. 하나 밖에 없어 함께 있는 것이 가독성이 더 좋다고 판단되어 합치는 것으로 수정했습니다.

2024-03-07 14:14 UTC, yim2627 approved these changes

2024-03-07 14:14 UTC, merged