[Step2] 박스오피스 앱 이지, 희동
tasty-code/ios-box-office pull request #49
Opened 2024-02-29 08:53 UTC by yoruck2

@minsson
안녕하세요 민쏜! 이지, 희동입니다!
박스오피스 STEP2 PR 올려드립니다!
URLSession과 네트워크에 대한 고민이 많아
PR이 많이 늦었습니다.. 그럼에도 너그러이 기다려주셔서 감사합니다. 리뷰 잘 부탁드립니다!! 🙇🏻

---

## ✅ **요구사항 & 체크리스트**
- [x]  URL Session을 활용한 서버와의 통신
- [x]  CodingKeys 프로토콜의 활용

## 🙌🏻 PR Point
이번 STEP2는 URLSession을 통한 네트워킹의 구현과 동작방식에 대해 깊게 고찰해보는 시간이었던 것 같습니다. 특히 재사용성과 유지보수에 용이한 코드 구현을 위하여 리팩토링하는 과정에서 많은 고민을 하였습니다..!

## 🤔 고민했던 점

### 다양한 타입에 대응하는 JSONParser
```swift
struct JSONParser{
    
    func parseJSON<T: Decodable>(_ movieData: Data, DTO: T.Type) -> T? {
        do {
            let decodedData = try JSONDecoder().decode(T.self, from: movieData)
            return decodedData
        } catch {
            print("파싱 에러")
            return nil
        }
    }
}
```
민쏜이 말씀해주신 범용적인 역할에 대한 코멘트에 아이디어를 얻어 다양한 DTO 타입에 대응할 수 있는 `JSONParser`를 구현했습니다. 구현을 하면서 메타타입 이란 개념에 대해 잘 알수 있었고, 제네릭과도 좀 더 친숙해질 수 있는 기회였습니다.

### 다양한 쿼리문을 호출할 수 있는 메서드
```swift
extension NetworkAPI {
    func buildDailyBoxOfficeAPI(targetDate: APIURLCompnents.QueryValues, keys: APIURLCompnents.QueryKeys..., values: Any...) -> URL? {
        let dict: [APIURLCompnents.QueryKeys: Any] = zip(keys, values).reduce(into: [:]) { partialResult, now in
            partialResult[now.0] = now.1
        }
        return buildUrl(apiType: .dailyBoxOffice, requiredQuery: targetDate, queries: dict).url
    }
    
    private func buildUrl(apiType: APIType, requiredQuery: APIURLCompnents.QueryValues, queries: [APIURLCompnents.QueryKeys: Any]) -> URLComponents {
        var components = URLComponents()
        components.scheme = APIURLCompnents.schema
        components.host = APIURLCompnents.host
        components.path = apiType.makePath()

        components.queryItems = [
            URLQueryItem(name: "key", value: APIURLCompnents.QueryValues.APIKey.rawValue),
            URLQueryItem(name: apiType.rawValue , value: requiredQuery.rawValue)
        ]
        queries.forEach { (key: APIURLCompnents.QueryKeys, value: Any) in
            components.queryItems?.append(URLQueryItem(name: key.rawValue,
                                                       value: value as? String))
        }
        return components
    }
}
```
일일 박스오피스API의 요청 인터페이스에는 필수 쿼리문 이외에 여러 선택사항인 쿼리들이 있었습니다. 그래서 필수 쿼리만을 받는 메서드에 여러 쿼리문들을 받아 요청할 수 있는 메서드를 만드는 방법에 대해 고민했습니다. 
`buildDailyBoxOfficeAPI` 에서 가변 파라미터를 통해 여러 key와 value를 받고, key-value 쌍의 딕셔너리를 순회하며 쿼리문을 생성할 수 있었습니다. 

## 🧐 궁금했던 점

### 가변 파라미터의 값들을 인자로 전달하는 방법..?
![image](https://hackmd.io/_uploads/BJL12962a.png)

`MovieListViewController` 에서 API를 호출하는 메서드가 원하는 url의 쿼리값들을 파라미터로 받아 전달하고 싶었습니다. 그래서 위 처럼 시도를 해봤는데 가변 파라미터인 key를 `buildDailyBoxOfficeAPI`메서드로 전달할때 에러가 났습니다. 여러 시도를 해보았는데 방법을 찾지 못해서 지금과 같이 수정했습니다. 혹시 가변파라미터를 인자로 전달하는 방법이 존재할까요?

### ViewController의 역할
```swift
private func callMovieDetailAPI() {
        let url = networkAPI.buildMovieDetailAPI(movieCode: .movieCode)
        networking.performRequest(with: url) { result in
            switch result {
            case .success(let data):
                guard let data = data,
                      let decodedData = JSONParser().parseJSON(data as! Data, DTO: MovieDetailDTO.self)
                else {
                    return
                }
                print(decodedData.movieInfoResult.movieInfo.companys)
            case .failure(let error):
                print(error)
            }
        }
    }
```

처음엔 `URLSession` 내에 JSON 파싱 코드가 있었지만 `dataTask` 가 `parseJSON` 의 제네릭 반환값을 알 수 없는 문제로 `ViewController에서` 호출하는 것으로 구현했습니다. 아직 MVC 패턴 등의 디자인 패턴에 대해 무지한 단계라 이런 로직을 뷰컨에서 관리하는게 적절한가 의문이 듭니다..!

2024-03-03 12:26 UTC, minsson requested changes
안녕하세요, 이지, 희동!

고생 많으셨어요. 오랜 시간 고민하신만큼, 고민하신 내용이 PR과 코드에 잘 드러나서 무척 멋지다고 생각했어요. 재사용성과 유지보수에 용이한 코드 구현을 생각하셨다고 했는데, 저도 정말 중요한 부분이라고 생각해요. 항상 고민하는 부분이고요. 

이와 관련해 요즘 드는 생각이 있는데요. 지금 단계에서는 어쩌면 재사용성과 유지보수성에 대해 너무 깊게 고민하지 않아도 될 것 같다는 생각이 들어요. 재사용 해본 경험, 유지보수해본 경험이 없는 상황에서 그런 상황을 상상하며 완벽한 구현을 추구하다보면 코딩이 너무 괴로워질 수 있다고 생각하기 때문이에요. 제가 예전에 그랬었어요..😅 그러니 일단 캠프에서 다양한 코드를 써보고, 다양한 피드백을 받으며 넘어가고, 나중에 실제로 재사용하고, 유지보수하며 그 피드백들이 어떤 경험에서 나온 건지 체감(?)하는 게 더 효율적일 수 있겠다는 생각이 들었어요.

---

### 고민했던 점 답변
### 다양한 타입에 대응하는 JSONParser
이 부분은 코드 코멘트 참고 부탁드려요.

### 다양한 쿼리문을 호출할 수 있는 메서드
이 부분이 개인적으로 재미있었어요. 특히 `APIURLCompnents`, `APIURLCompnents.QueryKeys` 객체에 구현된 내용은 제가 해보지 않은 방식이라 신기했어요. 우선 유지보수성과 확장성을 염두에 두고 최대한 범용적인 메서드를 구현해보려고 노력해보신 게 보여서 놀랐어요.

`APIURLCompnents.QueryKeys`를 보면 각 쿼리 파라미터들을 enum으로 정리해두셨는데, 이렇게 하면 처음엔 번거로울 수 있겠지만 여러 방법으로 재사용할 수 있어서 편하겠네요.

한편으로, 제가 개인적으로 느끼기에는 조금 번거롭게 느껴지기는 했어요. 저라면 각 EndPoint를 별개의 것으로 보고, 쿼리파라미터 이름이 중복되더라도 각 EndPoint 내에서 String으로 갖고 있을 것 같았거든요. 이런 건 정답이 없으니 이렇게 생각하는 사람도 있다는 정도로만 생각해주시면 돼요.

또, 지금은 GET 요청에 집중해서 API EndPoint를 구성하고, 쿼리파라미터를 추가하는 방법만 구현되어 있는 것 같은데, 나중에 다른 HTTP Methods를 사용할 때 어떻게 구현하실지 궁금하기도 해요. 가령, HTTP Header나 Request Body에 데이터를 추가하는 것도 고려해보시면 좋을 것 같아요. 

## 질문 답변
### 가변 파라미터의 값들을 인자로 전달하는 방법
저도 예전에 개념만 공부해보고 실제로 사용해본 적이 없어 검색을 좀 해봤어요. 다행히 아래와 같이 잘 설명된 아티클을 찾을 수 있었어요. 

[How to use Variadic parameters in Swift](https://www.avanderlee.com/swift/variadic-parameters/)의 Understanding the limitations of Variadic Parameters라는 부분을 읽어보시면 두 분이 겪는 문제에 대한 답과 해결법이 나와있으니 참고해보시면 좋을 것 같아요.

### ViewController의 역할
MVC 패턴, MVVM 패턴 등을 처음 접했을 때는 워낙 다양한 전문 용어가 사용되어 이해하기 어려울 수 있어요. 간단하게 생각하면, 새롭게 기능을 추가, 수정, 제거할 때 뭐가 어디있는지 빨리 알아차리고 쉽게 구현하기 위해 각 객체의 역할을 나눈 거라고 보시면 돼요. 이걸 얼마나 세부적으로 나누느냐에 따라 MVC, MVVM 등 여러가지가 있고요.

질문에 포함된 로직은 네트워크 호출, 데이터 파싱으로 보이는데, 이를 ViewController에서 직접 처리하는 게 좋아보이지는 않아요. 

ViewController는 말 그대로 View를 Control한다고 생각하시면 돼요. Model 데이터를 View에 띄워 사용자가 볼 수 있게 만들고, 사용자가 버튼을 누르는 등 상호작용하면 그에 맞춰서 버튼 색을 바꾸는 등 View를 업데이트하는 역할을 수행해요.

ViewController가 네트워크 호출, 데이터 파싱까지 직접적으로 수행하는 건 역할 밖의 일이에요. 이를 개선하기 위해 NetworkService 등 별도의 객체를 만들고, 이 역할을 수행하게 만들 수 있어요. 현재 구조에서만 생각한다면 callMovieDetailAPI, callDailyBoxOfficeAPI 메서드 모두 NetworkService 객체로 옮길 수 있어요. ViewController에서는 이 NetworkService 객체를 자신의 프로퍼티로 갖고 있고, networkService.callMovieDetailAPI()로 호출하면 돼요.

위에서 말씀드린 내용은 가장 간단한 방법이고, 그 외에도 정말 다양한 방법이 있으니 차차 공부해보시면 좋을 것 같아요. 

이 내용을 객체 간 역할을 분담하고, 자신의 역할이 아닌 부분에 대해서는 그 역할을 담당하는 다른 객체에게 요청해서 원하는 정보를 받아오는 거라고 생각하시면 될 것 같아요. 회사에서 사람들이 일하는 모습과 비슷해보이지 않나요? 전 예전에 이런 부분이 무척 어렵고 재미있었어요. (사실 객체의 역할 분담은 지금도 어렵고, 앞으로도 어려울 것 같아요.) 관련해서 객체지향의 사실과 오해라는 책도 읽어보시면 좋을 것 같아요.

2024-03-03 12:26 UTC, minsson commented on BoxOffice/Model/DTO/MovieDetailDTO.swift
> +}
- DTO란 무엇인가요?
- 어떤 의도로 DTO를 사용하고 있나요?

2024-03-03 12:26 UTC, minsson commented on BoxOffice/Model/DTO/MovieDetailDTO.swift
> +}
- `MovieDetailDTO`내부 프로퍼티들의 타입인 `Nation`, `Genre`, `Director` 등은 무엇인가요? 이것도 DTO인가요? 만약 그렇다면, 어떤 이유로 DTO라는 단어를 붙이지 않았나요? 만약 아니라면, 왜 아닌가요?

2024-03-03 12:26 UTC, minsson commented on BoxOffice/Model/DTO/MovieDetailDTO.swift
> +}
- `DailyBoxOfficeResultDTO`, `MovieDetailDTO`라는 객체를 만들어주셨는데, 이 DTO 객체들은 어떤 객체(뷰 컨트롤러 등)에서 사용할 예정인가요?

2024-03-03 12:26 UTC, minsson commented on BoxOffice/Network/Errors.swift
> +}
앱에서 사용하기 위한 에러군요! 그런데 우리가 네트워킹을 하다보면 다양한 문제가 생길 수 있는데, 3개의 경우의 수로는 그러한 다양한 문제에 대응하기 어려울 수 있겠다는 생각이 들어요.

또, 각 case들이 정확히 어떤 걸 의미하는지 네이밍을 봐서는 이해하기 어려운 것 같아요. 좀 더 개선할 수 있을까요?

2024-03-03 12:26 UTC, minsson commented on BoxOffice/Network/JSONParser.swift
> +}
앱 전반에서 사용할 범용적인 객체이니만큼 아규먼트 레이블인 `movieData`는 그냥 `data`로 수정하는 게 좋을 것 같아요. 앱에서 사용하는 데이터가 movie 외에 다른 것도 있을 수 있으니까요.

2024-03-03 12:26 UTC, minsson commented on BoxOffice/Network/JSONParser.swift
> +}
호출하는 쪽에서는 `JSONParser().parseJSON(_:DTO:)`의 형식으로 사용하게 될텐데, 객체명과 메서드명에 중복이 있어 가독성이 좋아보이지 않아요.

제 생각에는 `decode`, `deserialize` 등 이 메서드의 결과값을 예측할 수 있는 네이밍을 사용하면 좋을 것 같아요.

2024-03-03 12:26 UTC, minsson commented on BoxOffice/Network/JSONParser.swift
> +}
이 프로젝트에서 사실 JSONParser라는 객체가 그렇게 유의미해보이지는 않아요. 부정적으로 보면 단순히 `JSONDecoder().decode(_:from:)`을 사용하는, 불필요한 Wrapper 객체로 보이기도 해요. 하지만 프로젝트가 커진다고 생각하면 코드의 추상화와 응집도를 좋게 만들 수 있을 것 같아요. 앞으로 다른파싱 로직이 추가된다면 이 한 곳에 모아두면 되니 유지보수할 때 좀 더 편할 수 있겠네요!

2024-03-03 12:26 UTC, minsson commented on BoxOffice/Network/JSONParser.swift
> +}
에러 처리 측면에서 아쉬움이 있어요. 디코드가 실패해서 catch에 걸리는 경우, 단순히 '파싱 에러'라는 로그만 남고 아무 일도 일어나지 않게 되어 있어요.

단순히 개발자가 읽을 로그 생성 용도로만 쓸 거라면, 아주 간단하게는 `print("파싱 에러:\(error))`라고 쓸 수도 있어요. 이건 아주 단순한 방법이고, swift error log, swift console log 등으로 검색해보시면 더 많은 정보를 얻으실 수 있을 거예요.

다음 스텝에서는 유저에게 Error Alert 등을 띄우는 상황까지 고려해서 에러 핸들링을 해보시면 좋을 것 같아요.

2024-03-03 12:26 UTC, minsson commented on NetworkManager.swift
> +}
`networkAPI` 프로퍼티의 접근제어가 누락되었어요.

2024-03-03 12:26 UTC, minsson commented on NetworkManager.swift
> +}
현재는 200번대 코드 외에는 모두 `completion(.failure(.netWorkingError))`가 실행되게 되어 있네요. 실제로 네트워킹을 진행하다보면 더 다양한 이유를 알아야할 필요가 있어요. 특히 400번대, 500번대를 구분하고, 각 상황에 맞는 대응이 필요해요. 200번대 코드 외의 다른 코드에 대한 것도 반영되면 좋을 것 같아요.

2024-03-03 12:26 UTC, minsson commented on NetworkManager.swift
> +}
- Result 타입을 활용해주셨는데, Result 타입이 무엇인가요?
- Result 타입이라는 게 없다면 이런 메서드를 어떻게 구현했을지 간단하게 생각해보고 말씀해주실 수 있나요?

2024-03-03 12:26 UTC, minsson commented on NetworkManager.swift
> +}
또, 나중에 Swift Concurrency도 공부해보시면 좋을 것 같아요! 일단은 Result 타입을 지금처럼 잘 활용하시는 것만으로도 충분해보이네요.

2024-03-05 12:14 UTC, MyNB1 commented on BoxOffice/Network/Errors.swift
> +}
현재로서는 발생할 에러케이스가 다양하지 않아 세 개 정도로만 구현되어 있습니다! 추후에 다양한 에러케이스에 대하여 고민해보도록 하겠습니다!

netWorkingError -> 네트워킹연결 실패에러
parseError -> 데이터파싱 실패에러
dataError ->  데이터가 없을 때 나오는 에러
의 의미로 네이밍을 했는데 더 개선해보겠습니다!

2024-03-05 12:21 UTC, MyNB1 commented on BoxOffice/Model/DTO/MovieDetailDTO.swift
> +}
계층간의 데이터전달을 위한 객체로 별도의 로직이나 설계없이 단순 데이터만을 담은 객체로 알고 있습니다.
현재는 외부 데이터를 xcode에서 인식할 수 있도록 변환하는 의도로 사용했습니다.

2024-03-05 12:21 UTC, MyNB1 commented on BoxOffice/Model/DTO/MovieDetailDTO.swift
> +}
> * DTO란 무엇인가요?
> * 어떤 의도로 DTO를 사용하고 있나요?

2024-03-05 12:22 UTC, MyNB1 commented on BoxOffice/Model/DTO/MovieDetailDTO.swift
> +}
> * DTO란 무엇인가요?
> * 어떤 의도로 DTO를 사용하고 있나요?

2024-03-05 12:32 UTC, MyNB1 commented on BoxOffice/Model/DTO/MovieDetailDTO.swift
> +}
계층간의 데이터전달을 위한 객체로 별도의 로직이나 설계없이 단순 데이터만을 담은 객체로 알고 있습니다.
현재는 외부 데이터를 xcode에서 인식할 수 있도록 변환하는 의도로 사용했습니다!

DTO가 맞다고 생각합니다. 뒤에 DTO를 붙이지 않은 이유가 따로 있는 건 아니고, 미처 고려하지 않은 것 같습니다..

둘 다 MovieListViewController에서 사용하고 있습니다!

2024-03-07 09:23 UTC, MyNB1 commented on NetworkManager.swift
> +}
다양한 상황별로 대응하는 코드 역시 고민해 보겠습니다!

Result 타입은 Swift5부터 새롭게 추가된 에러처리 방식으로 제네릭 타입인 success와 failure를 case로 가지고 있는 열거형 입니다!
Result 타입이 없다면 do catch 문으로 에러처리를 했을 것 같습니다.

2024-03-08 02:06 UTC, yoruck2 commented on BoxOffice/Model/DTO/MovieDetailDTO.swift
> +}
데이터를 주고 받을 때 그 데이터를 담아 사용할 수 있게 객체화 시킨 양식 이라고 생각합니다
MovieListViewController 에서 API를 호출해 응답받은 json을 파싱 할 때 호출한 API에 따라 적절한 DTO를 지정해 주는 것으로 사용하고 있습니다.

2024-03-08 06:06 UTC, yoruck2 commented on BoxOffice/Network/JSONParser.swift
> +}
불필요한 Wrapper 객체라고 판단하는 기준은 메서드가 단 하나만 있기 때문인가요?

> 이 프로젝트에서 사실 JSONParser라는 객체가 그렇게 유의미해보이지는 않아요. 부정적으로 보면 단순히 `JSONDecoder().decode(_:from:)`을 사용하는, 불필요한 Wrapper 객체로 보이기도 해요. 하지만 프로젝트가 커진다고 생각하면 코드의 추상화와 응집도를 좋게 만들 수 있을 것 같아요. 앞으로 다른파싱 로직이 추가된다면 이 한 곳에 모아두면 되니 유지보수할 때 좀 더 편할 수 있겠네요!

2024-03-08 06:13 UTC, yoruck2 commented on BoxOffice/Network/JSONParser.swift
> +}
> 이 프로젝트에서 사실 JSONParser라는 객체가 그렇게 유의미해보이지는 않아요. 부정적으로 보면 단순히 `JSONDecoder().decode(_:from:)`을 사용하는, 불필요한 Wrapper 객체로 보이기도 해요. 하지만 프로젝트가 커진다고 생각하면 코드의 추상화와 응집도를 좋게 만들 수 있을 것 같아요. 앞으로 다른파싱 로직이 추가된다면 이 한 곳에 모아두면 되니 유지보수할 때 좀 더 편할 수 있겠네요!

네이밍 조언 반영 하겠습니다🙆‍♂️ 다음 PR때도 자연스러운 네이밍을 위해 고민해볼게요!

2024-03-08 06:17 UTC, yoruck2 commented on BoxOffice/Network/JSONParser.swift
> +}
> 에러 처리 측면에서 아쉬움이 있어요. 디코드가 실패해서 catch에 걸리는 경우, 단순히 '파싱 에러'라는 로그만 남고 아무 일도 일어나지 않게 되어 있어요.
> 
> 단순히 개발자가 읽을 로그 생성 용도로만 쓸 거라면, 아주 간단하게는 `print("파싱 에러:\(error))`라고 쓸 수도 있어요. 이건 아주 단순한 방법이고, swift error log, swift console log 등으로 검색해보시면 더 많은 정보를 얻으실 수 있을 거예요.
> 
> 다음 스텝에서는 유저에게 Error Alert 등을 띄우는 상황까지 고려해서 에러 핸들링을 해보시면 좋을 것 같아요.

기껏 만들어 놓은 에러타입을 활용하지 않고 있었네요..😅 `print("파싱 에러: \(NetworkError.parseError)")` 으로 일단 고쳐 보겠습니다. 

말씀해 주신 swift error log 에 대해 알아 보았는데 한번도 열어보지 않았던 콘솔앱이 이렇게 유용한 기능인것을 처음 알았네요! ㅎㅎ 앞으로 STEP에도 고려 해보겠습니다

2024-03-08 06:24 UTC, yoruck2 commented on NetworkManager.swift
> +}
> 현재는 200번대 코드 외에는 모두 `completion(.failure(.netWorkingError))`가 실행되게 되어 있네요. 실제로 네트워킹을 진행하다보면 더 다양한 이유를 알아야할 필요가 있어요. 특히 400번대, 500번대를 구분하고, 각 상황에 맞는 대응이 필요해요. 200번대 코드 외의 다른 코드에 대한 것도 반영되면 좋을 것 같아요.

다음 STEP때 반영 해 보겠습니다! 더불어 현재는 `String` 타입인 url을 받아 get 요청만을 처리하고 있는데, URLRequest을 받아 여러 상황에 맞게 처리되는 `performRequest` 메서드를 만들어 볼 예정입니다

2024-03-11 13:26 UTC, minsson commented on BoxOffice/Network/JSONParser.swift
> +}
> 불필요한 Wrapper 객체라고 판단하는 기준은 메서드가 단 하나만 있기 때문인가요? 저희는 단순히 JSON을 파싱하는 역할을 하나의 객체가 담당하면 좋겠다 라고 생각해 나누었는데 기능을 나눌 때 유의미한 객체일지 구분하는 기준이 궁금합니다..!

개인적으로는 JSONDecoder가 완전하게 대신할 수 있는 별도의 객체를 만들 필요가 있었을지 의문이었어요. 만약 DTO를 디코딩할 때 반복적으로 작성해야 하는 재사용 코드가 있다든가, decode 후에 처리해야할 로직이 있다든가 하는 경우에는 별도의 객체를 만들었을 것 같은데 이번 경우에는 잘 모르겠습니다. 지금 코멘트를 달면서 다시 살펴보니 호출부에서 do-catch라는 구문을 줄일 수 있다는 건 좋아보이는데, 실패했을 때의 에러처리 등 추가 로직이 없어서 아쉽기도 하고요.

다만 '그렇게 유의미해보이지 않아요'라고 말씀드렸던 건 다시 생각해보니 좀 더 조심해서 말씀드려야 했어요. 어디까지나 제 개인적인 생각일 뿐이니, 위에 말씀드린 내용처럼 생각하는 사람도 있다고 생각하시면 좋을 것 같아요.

2024-03-11 13:27 UTC, merged