박스오피스 앱 [STEP3] Hoi,Hong
tasty-code/ios-box-office pull request #50
Opened 2024-03-07 09:57 UTC by happykwon

안녕하세요 July @July911, 만나서 반갑습니다! 😆
hoi @happykwon hong @ujhong7 입니다.
박스오피스 앱 STEP3 PR 드립니다.

# 파일구조 
```=swift
├── BoxOffice
   ├── Controller
   │   └── BoxOfficeListViewController.swift
   ├── DateExtension.swift
   ├── Error
   │   ├── JSONFileError.swift
   │   └── NetworkError.swift
   ├── Model
   │   ├── CustomDailyBoxOffice.swift
   │   ├── DTO
   │   │   ├── BoxOfficeResponse.swift
   │   │   └── MovieInfoResponse.swift
   │   ├── EndPoint.swift
   │   ├── JSONLoader.swift
   │   ├── MovieAPIFetcher.swift
   │   └── NetworkManager.swift
   └── View
       ├── BoxOfficeListView.swift
       ├── BoxOfficeListViewCell.swift
       └── StackView
           ├── MovieStackView.swift
           ├── OldAndNewStackView.swift
           └── RankStackView.swift
```

# 질문사항 
### 1. 데이터 모델 변환 로직
 8ee8ff3fd432ce3fd0c92876cbd74cf7d3eb248c 에서 `convertToMyDailyBoxOfficeList` 메서드를 통해 서버로부터 받은 박스오피스 데이터를 처리하고, 이를 우리 앱의 데이터 모델인 `[CustomDailyBoxOffice]` 배열로 변환하고 있습니다.
map함수를 활용하는 방법 외에 더 효율적인 방법이 있는지 궁금합니다. 

### 2. `Date` 확장활용
b8b2b10492ca578e40cef3a1be454837199495c2 에서 앱에 필요한 잘짜 표기법을 `Date`타입을  `extension` 해서 구현하였는데  
날짜를 나타내는 것에 대해서 공통점을 갖고 있다고 생각해 `String`타입에 대한  로직도 추가해서 사용했습니다. 
다른 타입이라고 해도 사용 환경에 따라 내부적으로 합의가 된다면 지금처럼 사용이 가능한지 궁금합니다. 

###3. `AutoLayout` 적용
코드로 적용시키는 일이 처음이라 시간이 굉장히 많이 걸렸습니다.. 
혹시 AutoLayout을 조금 더 효과적으로 구성하기 위한 july만의 팁이나 효과적인 작업툴이 있을까요?

# 📸 Screenshot
![Simulator Screen Recording - iPhone 15 Pro - 2024-03-07 at 18 46 00](https://github.com/tasty-code/ios-box-office/assets/149054154/c5529598-1015-4f70-8d7d-dbca256c2e20)

2024-03-07 10:27 UTC, July911 requested changes

2024-03-07 10:27 UTC, July911 commented on BoxOffice/View/BoxOfficeListView.swift
> +final class BoxOfficeListView: UICollectionView {
BoxOfficeListView 는 CollectionView가 아니라 View일거 같다는 생각이 드네요.

2024-03-07 10:27 UTC, July911 commented on BoxOffice/View/BoxOfficeListView.swift
> +    func refreshBoxOfficeData()
refreshBoxOfficeData 
모든것이 Data아닐까요 ?

2024-03-07 10:27 UTC, July911 commented on BoxOffice/View/BoxOfficeListView.swift
> +protocol BoxOfficeListDelegate: AnyObject {
AnyObject 는 무엇인가요 ?

2024-03-07 10:27 UTC, July911 commented on BoxOffice/View/BoxOfficeListView.swift
> +    let loadingIndicator = UIActivityIndicatorView(style: .medium)
외부에서 쓰이나요 ?

2024-03-07 10:27 UTC, July911 commented on BoxOffice/View/BoxOfficeListViewCell.swift
> +    private let movieStackView = MovieStackView()
스택뷰를 굳이 뺄 이유가 있을까요?

2024-03-07 10:27 UTC, July911 commented on BoxOffice/View/BoxOfficeListViewCell.swift
> +    private lazy var mainStackOfMovieListCollectionViewCell: UIStackView = {
mainStackOfMovieListCollectionViewCell 스택뷰 아닌가요 ?

2024-03-07 10:27 UTC, July911 commented on BoxOffice/View/BoxOfficeListViewCell.swift
> +    private let separatorLine: UIView = {
separatorLine 뷰 아닌가요 ?

2024-03-07 10:27 UTC, July911 commented on BoxOffice/View/StackView/OldAndNewStackView.swift
> +        if rankOldAndNew == "NEW" {
String비교보다는 enum을 활용해보는것도 좋아보입니다.

2024-03-07 10:27 UTC, July911 commented on BoxOffice/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
makeKeyAndVisible 어떤 동작을 하나요 ?

2024-03-07 10:27 UTC, July911 commented on BoxOffice/Controller/BoxOfficeListViewController.swift
> +            DispatchQueue.main.async {
DispatchQueue.main.async { 로 묶으신 이유가 무엇인가요 ? 
 안묶으면 어떤 일이 일어나는지, 또한 묶은 범위가 적당한지 고려해주세요.

2024-03-07 10:27 UTC, July911 commented on BoxOffice.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 15.0;
타겟이 15면 compositional Layout에 대한 니즈도 있었을거 같은데 아닌가요 ?

2024-03-07 10:27 UTC, July911 commented on BoxOffice/Controller/BoxOfficeListViewController.swift
> +        configureNavigationBarTitle()
setup은 한번에 하고 그 후에 데이터를 받아오지않나요 ? 
  setupCollectionView()
  fetchBoxOfficeData()
  configureNavigationBarTitle() 
  콜렉션뷰와 네비게이션 사이에 fetch가 있는건 조금 어색해보이네요.

2024-03-07 10:27 UTC, July911 commented on BoxOffice/Controller/BoxOfficeListViewController.swift
> +    private var movieAPIFetcher: MovieAPIFetcher
추후에 교체의 여지가 있을까요 ?

2024-03-07 10:27 UTC, July911 commented on BoxOffice/View/BoxOfficeListView.swift
> +    weak var movieListDelegate: BoxOfficeListDelegate?
weak 를 붙여주신 이유를 설명해주세요. 
어떤 작용을 하는지 BoxOfficeListView를 누가 가지고 있고 등등의 모든 과정들을요 !

2024-03-12 02:16 UTC, happykwon commented on BoxOffice/View/BoxOfficeListViewCell.swift
> +    private let movieStackView = MovieStackView()
처음에는 프로퍼티로  선언해주는 방식이 아닌 아래와 같이 직접 인스턴스를 생성하는 방식으로 구현을했었습니다. 
```swift
final class BoxOfficeListViewListCell: UICollectionViewListCell {
    static let reuseIdentifier = String(describing: BoxOfficeListViewListCell.self)

    private lazy var mainStackOfMovieListCollectionViewCellStackView: UIStackView = {
        let stack = UIStackView(arrangedSubviews: [OldAndNewStackView(), MovieStackView()])
        stack.axis = .horizontal
        stack.distribution = .fillProportionally
        stack.spacing = 0
        stack.alignment = .center
        return stack
    }()
```

```swift
    private func setupConstraints() {
        OldAndNewStackView.widthAnchor.constraint(equalTo: contentView.widthAnchor, multiplier: 0.2).isActive = true
        mainStackOfMovieListCollectionViewCellStackView.translatesAutoresizingMaskIntoConstraints = false
        NSLayoutConstraint.activate([
            mainStackOfMovieListCollectionViewCellStackView.topAnchor.constraint(equalTo: contentView.topAnchor, constant: 0),
            mainStackOfMovieListCollectionViewCellStackView.leadingAnchor.constraint(equalTo: contentView.leadingAnchor, constant: 10),
            mainStackOfMovieListCollectionViewCellStackView.trailingAnchor.constraint(equalTo: contentView.trailingAnchor, constant: -10),
            mainStackOfMovieListCollectionViewCellStackView.bottomAnchor.constraint(equalTo: contentView.bottomAnchor, constant: -10)
        ])
    }
```
컴파일러에서는 오류가 발생하지 않았지만, setupConstraints() 함수를 실행할 때 EXC_BAD_ACCESS 오류가 발생하며 앱이 중단되었습니다. 조사해본 결과, 제약을 설정할 때 직접 생성한 인스턴스가 프로퍼티에 저장되지 않으면 해당 메서드의 실행이 끝난 후 곧바로 메모리에서 해제될 수 있으며, 이로 인해 EXC_BAD_ACCESS 오류가 발생할 수 있다는 정보를 찾을 수 있었고 따라서, 프로퍼티를 통해 접근하는 방식을 선택했습니다.

따로 빼지 않고, 혹시 더 좋은 방법이 있다면 알려주시면 감사하겠습니다 !!!

2024-03-12 02:16 UTC, happykwon commented on BoxOffice/View/BoxOfficeListViewCell.swift
> +    private lazy var mainStackOfMovieListCollectionViewCell: UIStackView = {
수정완료했습니다

2024-03-12 02:16 UTC, happykwon commented on BoxOffice/View/BoxOfficeListViewCell.swift
> +    private let separatorLine: UIView = {
수정완료했습니다

2024-03-12 02:16 UTC, happykwon commented on BoxOffice/View/StackView/OldAndNewStackView.swift
> +        if rankOldAndNew == "NEW" {
수정 완료했습니다. enum타입을 활용하니 훨씬 가독성이 좋아보입니다 !

2024-03-12 02:18 UTC, happykwon commented on BoxOffice/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
`makeKeyAndVisible() `메서드는 윈도우(window)를 화면에 보이게 하고, 
해당 윈도우를 주 윈도우(key window)로 설정하는 역할을 합니다.  이 메서드를 통해서 
스토리보드의 window로 지정되어있는 keyWindow를 코드로 지정해준 window로 지정이 되게 합니다.

2024-03-12 02:22 UTC, happykwon commented on BoxOffice.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 15.0;
compositional Layout에 대한 구현은 생각을 못했었는데 15이상부터 지원되는 복잡한 collectionView를 효과적으로 만들기 위한 
녀석이라는 것을 알게되었습니다 👍
```swift
    private func configuerCompositionalLayout() -> UICollectionViewLayout {
        let layout = UICollectionViewCompositionalLayout { (sectionIndex: Int, layoutEnvironment: NSCollectionLayoutEnvironment) -> NSCollectionLayoutSection? in
            let itemSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0), heightDimension: .fractionalHeight(1.0))
            let item = NSCollectionLayoutItem(layoutSize: itemSize)
            let groupSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0), heightDimension: .absolute(100))
            let group = NSCollectionLayoutGroup.horizontal(layoutSize: groupSize, subitems: [item])
            let section = NSCollectionLayoutSection(group: group)
            return section
        }
        return layout
    }
```

이 코드에서 `sectionIndex: Int`, `layoutEnvironment: NSCollectionLayoutEnvironment` 파라미터는 사용되지는 않지만 
추후 필요할 경우 조금 더 편하게 사용할 수 있게 추가해서 구현했습니다 !

2024-03-12 02:24 UTC, happykwon commented on BoxOffice/View/BoxOfficeListView.swift
> +    weak var movieListDelegate: BoxOfficeListDelegate?
`weak` 키워드는 `BoxOfficeListViewController` 내부의 `BoxOfficeListCollectionView`에 대한 델리게이트 참조에 사용되었고, 순환 참조를 방지하고 메모리 누수를 막기 위한 조치입니다.

`BoxOfficeListViewController`는 `BoxOfficeListCollectionView`를 생성하고 관리합니다. `BoxOfficeListCollectionView`는 사용자의 상호작용(예: 새로고침 제스처)에 반응하여, 자신을 관리하는 `BoxOfficeListViewController`에 특정 작업을 수행하도록 요청하고 이 때, `BoxOfficeListCollectionView`는 델리게이트 패턴을 통해 `BoxOfficeListViewController`에게 이러한 요청을 전달합니다.

`weak` 키워드를 사용하는 이유는
`BoxOfficeListViewController`는 `BoxOfficeListCollectionView`를 강하게 참조하고 있기 때문에, `BoxOfficeListCollectionView`가 다시 `BoxOfficeListViewController`를 강하게 참조할 경우 순환 참조가 발생합니다. 
`weak` 키워드를 사용함으로써 `BoxOfficeListCollectionView`는 `BoxOfficeListViewController`를 약하게 참조하게 만들고, `BoxOfficeListViewController`가 메모리에서 해제될 때 `BoxOfficeListCollectionView`의 델리게이트 참조가 자동으로 nil로 설정되도록 하여 순환 참조를 방지하는 역할을 합니다.

2024-03-12 02:27 UTC, happykwon commented on BoxOffice/Controller/BoxOfficeListViewController.swift
> +        configureNavigationBarTitle()
얼마전 읽은 책에서 개발은 글을 쓰는것과 같다는 표현이 인상깊었는데
호출이 되는 상황에서라도 보다 더 자연스럽게 읽히는 결과를 얻기 위해 노력하겠습니다 !

2024-03-12 02:40 UTC, happykwon commented on BoxOffice/View/BoxOfficeListView.swift
> +    let loadingIndicator = UIActivityIndicatorView(style: .medium)
`BoxOfficeListViewController`에서 사용되고 있었고, 메서드를 추가해 프로퍼티는 은닉화를 해줬습니다. 
제가 질문의 의도를 잘 파악하지 못한 것 같고 이렇게 해주는게 맞는지, 그리고 어떤점이 좋은지 모르겠습니다.
프로퍼티를 은닉화를 해준다해도 결국 그에 때라 구현된 메서드 `toggleLoadingIndicator` `setboxOfficeDelegete`는 내부가 아닌 
`BoxOfficeListViewController` 에서 쓰여져  결과적으로 외부에서 쓰이게 되는 형태는 같아지는 것 같은데 줄리이는 어떻게 생각하시는지 궁금합니다 :)

2024-03-12 04:54 UTC, happykwon commented on BoxOffice/Controller/BoxOfficeListViewController.swift
> +            DispatchQueue.main.async {
`fetchBoxOffice` 함수의 결과 처리 과정에서 UI에 대한 업데이트가 포함되어 있어 `DispatchQueue.main.async { }`에서 실행시켰습니다. 

 main에서 처리하지 않는다면 성능저하와 동시다발적인 UI업데이트로 의도와는 전혀 다른 화면 수정이 일어날 수 있습니다. 
View Drawing Cycle에  UIApplication이 RunLoop를 초기화 시키면서 UI를 업데이트 합니다.

동시다발적인 UI업데이트의 가능성
> 만약 global에서 처리하게 된다면 각 스레드에서는 동시다발적으로 RunLoop를 끝내고 CoreAnimation에 전달 -> Display(화면표시)의 순서로 돌아가게 되고, 이는 의도한 바와는 다르게 동시다발적인 화면 변환이 일어날 수 있습니다. 

성능저하
> CoreAnimation에서는 UI를 화면에 표시하기 위해 일련의 단계를 거치고 이 단계들은 자원이 많이 소모되는 편이기 때문에 동시다발적으로 많은 양의 요청이 들어오면 앱의 성능저하를 불러올 수 있습니다. 


`DispatchQueue.main.async { }`에서 요청함으로서  각 스레드의 RunLoop를 메인 스레드에서 일괄적으로 초기화함으로써, 모든 뷰의 변경 사항을 일관적으로 처리할 수 있으며, 이로 인해 모든 변경 사항이 동시에 적용될 수 있도록 보장됩니다.

2024-03-12 05:49 UTC, happykwon commented on BoxOffice/View/BoxOfficeListView.swift
> +final class BoxOfficeListView: UICollectionView {
수정완료했습니다

2024-03-12 05:49 UTC, happykwon commented on BoxOffice/View/BoxOfficeListView.swift
> +    func refreshBoxOfficeData()
수정완료했습니다.

2024-03-12 05:59 UTC, happykwon commented on BoxOffice/View/BoxOfficeListView.swift
> +protocol BoxOfficeListDelegate: AnyObject {
AnyObject란 class, classType, class-only 프로토콜 이런것들이 올것이다라고 보장을 해주는 타입입니다.
코드에서는 
델리게이트 패턴 적용시 발생될 수 있는 강한참조 사이클을 해결하기 위해 `weak`키워드를 사용하고, `weak` 키워드를 사용하기 위해  AnyObject타입을 채택했습니다.

2024-03-12 06:28 UTC, happykwon commented on BoxOffice/Controller/BoxOfficeListViewController.swift
> +    private var movieAPIFetcher: MovieAPIFetcher
`Protocol`을 사용함으로써 추후에 교체의 여지가 있도록 리팩터링했습니다.
의존성 주입 패턴을 적용하여, MovieAPIFetcher의 구체적인 구현에 대한 의존성을 줄이고, 프로토콜을 통해 추상화된 인터페이스에만 의존하게 변경했고
아래와 같은 이점이 있다고 생각합니다.
1. 유연성: 프로토콜을 사용함으로써, 나중에 다른 데이터 소스나 API 페처로 쉽게 교체할 수 있는 유연성을 제공

2. 테스트 용이성: 프로토콜을 준수하는 모의 구현을 사용하여, 네트워크 호출 없이 단위 테스트를 수행 가능

3. 확장성과 유지보수성: 시스템의 다른 부분과의 결합도를 낮춤으로써, 코드의 확장성과 유지보수성이 향상

2024-03-13 04:44 UTC, July911 commented on BoxOffice/View/BoxOfficeListView.swift
> +protocol BoxOfficeListDelegate: AnyObject {
weak 키워드를 사용하기 위해 AnyObject타입을 채택했습니다. 는 무슨뜻인가요 ?

2024-03-13 04:48 UTC, July911 commented on BoxOffice/View/BoxOfficeListView.swift
> +    let loadingIndicator = UIActivityIndicatorView(style: .medium)
프로퍼티에 접근하는것과 메서드로 접근하는게 같은 효과를 하나요 ?

2024-03-13 04:50 UTC, July911 commented on BoxOffice.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 15.0;
아주 좋습니다. 
추가적으로 layoutEnvironment 이게 어디에 쓰이는지 학습을 권장드립니다. 
생각보다 사용 케이스가 많습니다.

2024-03-13 04:51 UTC, July911 commented on BoxOffice/Controller/BoxOfficeListViewController.swift
> +    private var movieAPIFetcher: MovieAPIFetcher
아주 좋습니다.

2024-03-13 04:58 UTC, merged