박스오피스 앱 [Step 4] 댄, L
tasty-code/ios-box-office pull request #53
Opened 2024-03-12 08:06 UTC by eensungkim

Step 4
멤버 : @eensungkim, @LeeSe0ngYe0n
리뷰어 : @ryan-son

박스오피스 앱 프로젝트의 네 번째 스텝입니다!
정리하여 PR 드립니다. 잘 부탁드립니다! :bow: 

# PR 상세
- 영화 상세화면 구현 (`MovieInformationView`)
- 카카오 이미지 검색 API의 활용
</br>

# 이번 스텝을 통해서 배운 점
- `Builder` 패턴의 학습 및 활용
- `URLRequest` 헤더를 통해 API 인증 키 전달하는 방법 학습 및 활용
- `UIViewController` 내장 `navigationController` 및 `navigationItem` 의 활용
</br>

# 이번 스텝에서 새롭게 추가한 파일
- Network/RESTAPI/KakaoAPI.swift
- Model/DTO/MovieImageDocument.swift
- Model/MovieInformation.swift
- View/MovieInformationView.swift
- View/InformationStackView.swift
- Controller/MovieInformationViewController.swift
</br>

# 질문
- 현재는 이미지를 받아오는 시간 동안 로딩 인디케이터가 노출되도록 구현했는데요. 
캐싱을 구현해서 `BoxOffice` 화면이 노출되고 난 뒤 바로 필요한 모든 영화들의 포스터 이미지를 다운로드 할 수도 있지 않을까라는 생각을 하게 되었습니다.
`BoxOfficeAPI는` 최대 10편의 영화만 보내주기 때문에 전체 영화의 갯수가 10개로 고정되어, 불필요하게 많은 양의 데이터를 쓰지 않으면서도 사용자의 경험을 좋게 만들 수 있지 않을까 생각합니다.
혹시 이런 아이디어를 실제로 구현할 때 미리 생각해보거나, 조심해야 할 것들이 있을지 궁금합니다.

- iOS에서 지향하는 Cocoa MVC 패턴에서는 모델과 뷰가 뷰컨트롤러라는 중개자를 사이에 두고 상호 소통한다고 이해하고 있습니다.
지난번 리뷰 답변 중에서 뷰컨트롤러를 뷰로 넘겨주기 보다는, `delegate` 패턴을 활용하여 뷰를 뷰컨트롤러로 넘겨주는 것이 더 낫다는 말씀을 해주셨는데요.
Cocoa MVC 패턴에서 뷰컨트롤러를 모델과 뷰의 상위 객체로 이해해도 무방한 것일까요?

- `MovieInformationView` 의 초기 구현 과정에서 포스터 이미지와 (글로 이루어진)영화의 상세 정보를 하나의 스택뷰로 묶어서 구현을 했었습니다.
`스택뷰.arrangedSubview` 내부에 추가해주는 뷰의 경우, 스택뷰가 가진 속성에 따라 오토 레이아웃이 자동적으로 결정된다고 이해했기 때문인데요.
특정 포스터 이미지를 불러올 때 아예 `MovieInformationView` 전체가 화면에서 사라지는 문제가 있었습니다.
결국 포스터 이미지와 영화 상세 정보를 스택뷰로 묶는 대신, 이미지를 별도의 이미지뷰로 만들고 오토레이아웃을 잡아주는 것으로 문제를 해결할 수 있었습니다.
arrangedSubview 에 삽입된 이미지뷰를 다룰 때 혹시 주의해야 하는 점이 있었을까요?
(예시 코드가 없다 보니 상황 전달이 잘 되지 않을 것 같습니다만, 혹시나 하는 마음에 여쭤보아요.)

2024-03-13 16:06 UTC, ryan-son requested changes
L, 댄, Step 4까지 수행해보셨네요.

Swift Concurrency를 이용한 네트워킹 기능에 이어 UIScrollView까지 익숙하지 않은 요소들을 학습해보시고 사용해보시느라 어려우셨을 것 같은데요, 와중에 타입별 역할 분리까지 고민하신 흔적이 보여 고생이 많으셨겠다는 생각이 듭니다.

지난번과 마찬가지로 본문에서는 PR에 남겨주신 질문만 다루고, 개별 코멘트는 코드에서 확인하시면 되겠습니다.

># 질문
>- 현재는 이미지를 받아오는 시간 동안 로딩 인디케이터가 노출되도록 구현했는데요. 
캐싱을 구현해서 `BoxOffice` 화면이 노출되고 난 뒤 바로 필요한 모든 영화들의 포스터 이미지를 다운로드 할 수도 있지 않을까라는 생각을 하게 되었습니다.
`BoxOfficeAPI는` 최대 10편의 영화만 보내주기 때문에 전체 영화의 갯수가 10개로 고정되어, 불필요하게 많은 양의 데이터를 쓰지 않으면서도 사용자의 경험을 좋게 만들 수 있지 않을까 생각합니다.
혹시 이런 아이디어를 실제로 구현할 때 미리 생각해보거나, 조심해야 할 것들이 있을지 궁금합니다.

필요한 포스터 이미지를 미리 로드해서 캐싱해둔다면 영화 상세 정보를 표시할 때 사용자 경험은 향상될 수 있습니다. 하지만 사용자는 목록만 확인하고 앱을 사용하지 않을지, 10 개의 영화 중 몇 개의 상세화면을 확인할지를 알 수 없는 상황에서 미리 이미지를 로드하는 전략은 데이터를 낭비하는 것일 수 있으며, 특정 상세화면에서의 이미지만을 로드하는 것보다 여러 이미지를 한꺼번에 로드하게 되므로 오히려 사용자 경험이 떨어질 수도 있다는 점을 고려해야 합니다. 박스오피스 앱이 무한 스크롤로 구성되어 있다고 한다면, 목록에 존재하는 모든 영화의 포스터를 로드하려고 시도할 것이기 때문에 말씀드린 현상은 더욱 심각해질 가능성이 있습니다. 사용자들은 이미 이미지를 로드하는 데 어느정도 시간이 필요하다는 점을 인지하고 있기 때문에 상세 페이지에서 이미지가 로컬에 존재하는 것처럼 즉시 표시하지 않아도 어느정도의 기다림을 감수할 것입니다. 이 때 사용자들이 이미지 표시까지의 대기시간을 최소화하기 위해 서버에서 제공하는 이미지 크기를 모바일 기기에 제공하기 충분할만큼만 줄이는 것이 가장 효과적이며, 다음으로 메모리 사용 최적화를 위해 다운샘플링과 같은 방식 적용을 고려해볼 수 있습니다. 대기 시간 동안 사용자 경험을 향상시키기 위해 placeholder 이미지 제공을 고려해볼 수 있습니다.

>- iOS에서 지향하는 Cocoa MVC 패턴에서는 모델과 뷰가 뷰컨트롤러라는 중개자를 사이에 두고 상호 소통한다고 이해하고 있습니다.
지난번 리뷰 답변 중에서 뷰컨트롤러를 뷰로 넘겨주기 보다는, `delegate` 패턴을 활용하여 뷰를 뷰컨트롤러로 넘겨주는 것이 더 낫다는 말씀을 해주셨는데요.
Cocoa MVC 패턴에서 뷰컨트롤러를 모델과 뷰의 상위 객체로 이해해도 무방한 것일까요?

상위 객체라고 이해할 수 있습니다. ViewController는 View와 Model을 소유하는 형태로 중재자라는 Controller의 역할을 수행하기 때문입니다. ViewController의 상황과는 다르게 View와 Model은 ViewController과 소통은 하지만, 구체적으로 어떤 ViewController 타입과 소통할지는 알지 못합니다. 이 경우 ViewController와의 소통을 위해 일반적으로 delegate, closure, 드물게는 NotificationCenter, KVO와 같은 기술을 이용해 binding을 구성합니다. 따라서 View와 Model은 특정 ViewController 타입과의 연관이 없기 때문에 재사용성을 확보할 수 있습니다 (delegate 방식을 예로 들면 delegate 프로토콜을 준수하는 모든 타입의 인스턴스와 소통할 수 있습니다). 하지만 이전처럼 특정 View가 소유의 형태로든 메서드의 시그니처를 통해서든 특정 ViewController와 연관이 있다는 사실이 확정되면 View와 ViewController 간 강한 결합이 발생해 재사용성이 떨어지게 됩니다. 설령 다른 ViewController에서 활용할 필요가 없다고 하더라도 특정 타입과의 강한 결합이 발생해 단위 테스트를 수행하기 어려워진다는 단점이 생깁니다.

>- `MovieInformationView` 의 초기 구현 과정에서 포스터 이미지와 (글로 이루어진)영화의 상세 정보를 하나의 스택뷰로 묶어서 구현을 했었습니다.
`스택뷰.arrangedSubview` 내부에 추가해주는 뷰의 경우, 스택뷰가 가진 속성에 따라 오토 레이아웃이 자동적으로 결정된다고 이해했기 때문인데요.
특정 포스터 이미지를 불러올 때 아예 `MovieInformationView` 전체가 화면에서 사라지는 문제가 있었습니다.
결국 포스터 이미지와 영화 상세 정보를 스택뷰로 묶는 대신, 이미지를 별도의 이미지뷰로 만들고 오토레이아웃을 잡아주는 것으로 문제를 해결할 수 있었습니다.
arrangedSubview 에 삽입된 이미지뷰를 다룰 때 혹시 주의해야 하는 점이 있었을까요?
(예시 코드가 없다 보니 상황 전달이 잘 되지 않을 것 같습니다만, 혹시나 하는 마음에 여쭤보아요.)

UIImageView를 UIStackView에 두어 크기를 자동 조절하게 두었다면, 이미지가 로드된 후 UIImageView가 본인의 크기를 결정할 수 없다는 문제가 생깁니다. 로드된 UIImage의 크기를 통해 UIImageView의 크기를 결정해주세요. UIScrollView는 contentLayoutGuide에 컨텐츠의 크기를 알 수 있도록 설정해주어야 올바르게 작동합니다. UIScrollView의 subview가 UIStackView이든, UIImageView이든, UIView이든 이 규칙만 지킨다면 모두 동일한 원리로 정상적으로 배치됩니다.

리뷰 내용 중 궁금하신 점이 있으시거나 막히는 부분이 있으시면 언제든지 말씀해주세요! 계속해서 화이팅입니다!

2024-03-13 16:06 UTC, ryan-son commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        self.navigationItem.title = Date.yesterday.formatted(using: .standard)
날짜 이동 기능이 필요하게 된다면 내비게이션 타이틀을 변경해야할 수도 있겠네요. 현재 지정된 날짜 또는 제목을 상태값으로 관리하면 이런 요구사항에 대응하기 쉬워질 것 같습니다. 특정 상태에 의존을 하는 경우 해당 상태를 메서드 내부에서 생성해 소비하기보다 외부에 할당하는 방법을 고려해보시는 것도 좋겠습니다. 하지만 동시성 프로그래밍을 활용하는 상황이라면 상태를 인스턴스 프로퍼티로 관리하는 방식보다 순수 함수를 이용하는 함수형 프로그래밍을 통해 데이터를 생산하고 소비하는 형태를 고려해야 의도하지 않은 사이드이펙트로 인한 버그를 일으키지 않을 수 있습니다.

2024-03-13 16:06 UTC, ryan-son commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        return data.count
loadedData를 추상화한 결과로 모든 ViewController에서는 자신이 다루는 데이터에 대한 타입 변환을 수시로 수행해주게 되었네요. 공통적인 구성을 이용할 수 있다는 점은 장점이라고 볼 수 있겠지만, 개발자가 ViewController마다 적합한 타입을 기억하고 있어야 하므로 오히려 유지보수하기에 더 어려워질 수도 있겠다는 의견입니다. 하나의 ViewController에서 복수의 데이터를 이용하는 경우에도 어려운 점이 생길 것 같네요. 각 ViewController마다 적절한 타입의 dataSource를 제공하는 방법을 이용해보는 것은 어떨까요?

2024-03-13 16:06 UTC, ryan-son commented on BoxOffice/Controller/MovieInformationViewController.swift
> +        }
1. movieInformationView에서 수행하는 작업을 하나의 스텝으로 캡슐화 한다면 개발 경험이 더 좋아질 것 같아요.
2. Swift Concurrency를 적극적으로 도입하고 계시니 메인 스레드로 dispatch가 필요하실 때 활용하실 수 있도록 `@MainActor`, `MainActor.run { ... }`, `Task { @MainActor in ... }`에 대해 자세히 알아보시면 좋겠습니다.

2024-03-13 16:06 UTC, ryan-son commented on BoxOffice/Model/DailyBoxOffice.swift
>              let rankStatus: DailyBoxOffice.Movie.RankStatus = boxOfficeMovie.rankStatus == "NEW" ? .new : .old
매핑이 필요하다면 BoxOfficeMovice -> Movie로 변환할 수 있는 메서드를 제공하는 것도 좋겠네요.
```swift
extension BoxOfficeMovie {
    func toMovie() -> Movie { ... }
}
```

2024-03-13 16:06 UTC, ryan-son commented on BoxOffice/Model/MovieInformation.swift
> +    }
1. model과 controller 간 binding을 구현하셨네요. 이미 느끼셨겠지만, 모델 변경 시 ViewController에 피드백을 제공하되 특정 ViewController에 대한 종속성이 없으므로 컴포넌트의 재사용성을 향상시킬 수 있습니다. 또 다른 binding은 어떤 방식으로 구성해볼 수 있을지 생각해보시는 것도 재미있을 거에요.
2. 이 타입에서는 데이터를 제공하는 역할을 가지고 있으므로 View 요소에 해당하는 UIImage보다 Data 형태로 다루면 더 좋을 것 같아요. 이 타입에서는 최대한 Foundation 프레임워크의 기능을 이용해 구성하고, UIKit 프레임워크를 이용하는 UIView 또는 UIViewController에서 Data를 UIImage 인스턴스로 변환해 사용하는 편이 제공하는 기능에 더 어울릴 것 같습니다.

2024-03-13 16:06 UTC, ryan-son commented on BoxOffice/Model/MovieInformation.swift
> +final class MovieInformation: LoadDataProtocol {
이제 순수한 모델 느낌이 나는 `MovieInformation` 보다 기능을 제공해주는 `MovieDataProvider`가 더 어울릴 것 같습니다. 더 어울리는 이름이 있다면 그것으로 설정하셔도 좋습니다.

2024-03-13 16:06 UTC, ryan-son commented on BoxOffice/Model/MovieInformation.swift
> +    let networkManager: NetworkManager = NetworkManager(urlSession: URLSession.shared)
의존하는 인스턴스는 내부에서 생성해 사용하기보다 외부에서 주입받아 사용하시면 의존성이 분리되어 재사용하거나 테스트를 하기 더 용이하실거에요.

2024-03-13 16:06 UTC, ryan-son commented on BoxOffice/Model/MovieInformation.swift
> +    }
인터페이스를 공통적으로 추상화하려고 하다보니 어떤 데이터를 요청하는지에 대한 정보를 나타내기 어려워졌다고 생각합니다. 이전의 코멘트에서 말씀드린 것처럼 공통적인 구조라는 장점을 잃더라도 명시성을 챙기는 편이 더 좋을 것 같습니다.

2024-03-13 16:06 UTC, ryan-son commented on BoxOffice/Model/MovieInformation.swift
> +        guard let imageUrl = imageDocument.documentResults[safeIndex: 0]?.imageURL,
safeIndex: 0 subscript는 first와 같은 역할을 하는군요. Array.first가 조금 더 명시적일 것 같으며, 이것을 의도했다는 것을 알려주기 위해 imageUrl 대신 firstImageURL이라고 이름지어줄 수 있을 것 같습니다.

2024-03-13 16:06 UTC, ryan-son commented on BoxOffice/Model/MovieInformation.swift
> +              let URL = URL(string: imageUrl) else {
변수명은 lower camel case로 지어볼까요?
```suggestion
              let url = URL(string: imageUrl) else {
```

2024-03-13 16:06 UTC, ryan-son commented on BoxOffice/Model/MovieInformation.swift
> +        }.joined(separator: separator)
Movie 타입에서 이러한 기능을 제공할 수 있도록 하거나, String을 element로 가지는 Array에서 이러한 표현 방식을 지원하도록 적용해볼 수도 있을 것 같네요.

2024-03-13 16:06 UTC, ryan-son commented on BoxOffice/Model/MovieInformation.swift
> +    final class MovieDetail {
class로 구성하신 이유는 무엇인가요?

2024-03-13 16:06 UTC, ryan-son commented on BoxOffice/Network/Infrastructure/URLRequestBuilder.swift
> +        }
`httpMethod == .post`가 아니더라도 httpMethod를 설정해줘야할 것 같네요.

2024-03-13 16:06 UTC, ryan-son commented on BoxOffice/Network/RESTAPI/KakaoAPI.swift
> +        return "KakaoAK " + apiKey
저는 이런 경우 String interpolation 방식으로 표현하는 것이 더 가독성이 있다고 생각하는 편인데, 여러분은 어떠신가요?

2024-03-13 16:06 UTC, ryan-son commented on BoxOffice/View/MovieInformationView.swift
> +    private let directorStackView: InformationStackView = InformationStackView().setTitleText("감독")
공통적으로 필요한 사항이니 이니셜라이저로 title을 전달하는 방법도 고려해볼 수 있을 것 같네요.

2024-03-13 16:06 UTC, ryan-son commented on BoxOffice/View/MovieInformationView.swift
> +        addDetailInformationStackViewSubview()
레이아웃을 설정한다거나 로딩을 시작한다는 의미단위로 분리해서 메서드 구성을 한다면 이 부분 가독성이 더 높아질 것 같습니다.

2024-03-13 16:06 UTC, ryan-son commented on BoxOffice/View/MovieInformationView.swift
> +    }
행위를 보면 insert보다 set이 어울리겠네요.

2024-03-13 16:06 UTC, ryan-son commented on BoxOffice/View/MovieInformationView.swift
> +    }
행위를 보면 append보다 set이 어울리겠네요. 이미지 로드에 실패했을 때 적절한 이미지를 표시해주는 건 어떨까요?

2024-03-13 16:06 UTC, ryan-son commented on BoxOffice/View/MovieInformationView.swift
> +            imageView.centerXAnchor.constraint(equalTo: safeAreaLayoutGuide.centerXAnchor),
이 방식이라면 로드된 이미지와 imageView의 비율이 달라 이미지가 어그러져 보이겠네요. Data가 이미지로 변환된 상태에서 size를 통해 imageView의 크기를 결정하도록 로직을 구성해보시는 것이 좋겠습니다. 이렇게 된다면 이미지가 로드되기 전에 placeholder imageView의 크기를 정해줘야할 것이고, 이미지가 로드된 후 placeholder imageView constraints를 inactive 상태로 만들어줘야할 거에요.

2024-03-13 16:06 UTC, ryan-son commented on BoxOffice/View/MovieInformationView.swift
> +            scrollView.contentLayoutGuide.trailingAnchor.constraint(equalTo: safeAreaLayoutGuide.trailingAnchor),
frameLayoutGuide와 contentLayoutGuide가 무엇인지, 어떤 역할을 수행하는지에 대해 자세히 알아보시는 것이 좋겠습니다. UIScrollView의 constraints를 설정할 때는 UIScrollView superview - UIScrollView 간 edge constraints 설정, UIScrollView의 subview를 이용해 contentLayoutGuide 설정을 하고, subview - frameLayoutGuide 간 width 또는 height 설정을 통해 스크롤 방향을 결정합니다.

2024-03-14 05:58 UTC, eensungkim commented on BoxOffice/View/MovieInformationView.swift
> +    }
수정했습니다!

2024-03-14 06:01 UTC, eensungkim commented on BoxOffice/View/MovieInformationView.swift
> +    }
넵. 메서드 명을 수정하고 대체 이미지를 표시하도록 수정했습니다.

2024-03-14 06:04 UTC, eensungkim commented on BoxOffice/Network/RESTAPI/KakaoAPI.swift
> +        return "KakaoAK " + apiKey
동의합니다! 보간법 활용하는 것으로 변경했습니다!

2024-03-14 06:06 UTC, eensungkim commented on BoxOffice/Network/Infrastructure/URLRequestBuilder.swift
> +        }
`URLRequest` 가 갖는 httpMethod 프로퍼티는 기본값이 "GET" 이라고 되어있어서 특별히 설정해주지 않아도 된다고 생각했었는데요.

마치 .post 일때만 프로퍼티를 설정해주는 것처럼 오해될 소지가 있어보인다는 의미로 말씀해주신 것으로 이해하고 반영하여 수정했습니다!!

2024-03-14 06:08 UTC, eensungkim commented on BoxOffice/Model/MovieInformation.swift
> +    final class MovieDetail {
음 특별히 이유가 있었다기보다는, 이전에 DailyBoxOffice 를 만들 때에도 클래스를 활용했었다보니 비슷하게 만들어준다고 생각하고 적용했었습니다.

DailyBoxOffice 에 중첩된 Movie 도 역할을 고려해볼 때 구조체로 구성하는 것이 나은 것 같아서 함께 일괄적으로 변경하도록 하겠습니다.

2024-03-14 06:09 UTC, eensungkim commented on BoxOffice/Model/MovieInformation.swift
> +              let URL = URL(string: imageUrl) else {
넵!! 🙏

2024-03-14 06:17 UTC, eensungkim commented on BoxOffice/Model/MovieInformation.swift
> +        guard let imageUrl = imageDocument.documentResults[safeIndex: 0]?.imageURL,
말씀해주신대로 first 로 변경하고 변수명도 바꿨습니다!

2024-03-14 06:19 UTC, eensungkim commented on BoxOffice/Model/MovieInformation.swift
> +final class MovieInformation: LoadDataProtocol {
변경했습니다!

2024-03-14 06:36 UTC, eensungkim commented on BoxOffice/Model/DailyBoxOffice.swift
>              let rankStatus: DailyBoxOffice.Movie.RankStatus = boxOfficeMovie.rankStatus == "NEW" ? .new : .old
변경했습니다!! 🙇

2024-03-14 07:08 UTC, LeeSe0ngYe0n commented on BoxOffice/Model/MovieInformation.swift
> +    }
- 말씀해주신 대로 MovieInformationView에서는 포스터를 Data 형태로 저장하고 이미지로 변환해주는 과정은 MovieInformationView에서 실행하게 해주었습니다

2024-03-14 07:12 UTC, LeeSe0ngYe0n commented on BoxOffice/Model/MovieInformation.swift
> +    let networkManager: NetworkManager = NetworkManager(urlSession: URLSession.shared)
말씀해주시대로 NetworkManager를 외부에서 주입받는 코드로 리팩토링 하였습니다!
그리고 기본값을 넣어줬습니다!

2024-03-14 07:49 UTC, LeeSe0ngYe0n commented on BoxOffice/Model/MovieInformation.swift
> +        }.joined(separator: separator)
매핑 책임을 Movie 타입이 갖도록 변경하였고, String을 Element로 갖는 배열일 때 모든 Element를 합쳐 하나의 String으로 바꾸는 메서드를 Array Extension에 추가했습니다!

2024-03-14 08:06 UTC, LeeSe0ngYe0n commented on BoxOffice/View/MovieInformationView.swift
> +    private let directorStackView: InformationStackView = InformationStackView().setTitleText("감독")
말씀해주신대로 변경하였습니다!

2024-03-14 08:11 UTC, LeeSe0ngYe0n commented on BoxOffice/View/MovieInformationView.swift
> +        addDetailInformationStackViewSubview()
말씀해주신대로 변경하였습니다!

2024-03-15 09:22 UTC, eensungkim commented on BoxOffice/View/MovieInformationView.swift
> +            imageView.centerXAnchor.constraint(equalTo: safeAreaLayoutGuide.centerXAnchor),
스크롤뷰의 동작을 위아래로만 제한하려는 만큼,
이미지뷰의 widthAnchor 와 centerXAnchor 만 잡아주고 높이는 자동으로 조절되도록 변경하려고 합니다.
블로그에서 찾은 방법이 깔끔하다고 생각해서 실제 적용은 블로그 버전으로 하고자 하는데요.
말씀해주신 내용을 듣고 나름대로 구현해본 코드를 아래와 같이 첨부합니다.

```swift
// MovieInformationView.swift
func setImage(_ data: Data) {
        loadingIndicatorView.stopAnimating()
        let image = UIImage(data: data)
        
        guard let imageWidth = image?.size.width,
        let imageHeight = image?.size.height else { return }
        
        let scale = bounds.width * 0.9 / imageWidth
        imageView.heightAnchor.constraint(equalToConstant: imageHeight * scale).isActive = true
        
        imageView.image = image
    }
```

블로그 검색으로 찾은 실제 적용할 구현
```swift
// Foundation.ImageResizer.swift
extension UIImage {
    func resize(newWidth: CGFloat) -> UIImage {
        let scale = newWidth / self.size.width
        let newHeight = self.size.height * scale

        let size = CGSize(width: newWidth, height: newHeight)
        let render = UIGraphicsImageRenderer(size: size)
        let renderImage = render.image { context in
            self.draw(in: CGRect(origin: .zero, size: size))
        }
        
        return renderImage
    }
}
```

2024-03-15 09:53 UTC, eensungkim commented on BoxOffice/View/MovieInformationView.swift
> +            scrollView.contentLayoutGuide.trailingAnchor.constraint(equalTo: safeAreaLayoutGuide.trailingAnchor),
수정해 보았습니다! 의도하신 대로 잘 설정했는지 체크 부탁드립니다! 🙇

2024-03-15 10:08 UTC, eensungkim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        return data.count
BoxOfficeViewController 와 MovieInformationViewController 각각에 대응하는 dataSource 프로토콜을 생성하여
해당 프로토콜을 준수하도록 변경해보았습니다.

2024-03-15 10:09 UTC, eensungkim commented on BoxOffice/Model/MovieInformation.swift
> +    }
변경했습니다!

2024-03-15 10:16 UTC, eensungkim commented on BoxOffice/Controller/MovieInformationViewController.swift
> +        }
1. 넵 변경했습니다!!
2. 넵 알아보도록 하겠습니다 🙏

2024-03-15 10:26 UTC, eensungkim commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        self.navigationItem.title = Date.yesterday.formatted(using: .standard)
BoxOfficeViewController 에 새로운 메서드를 만들고 해당 메서드를 통해 세팅해주도록 구현해보았습니다.

2024-03-16 10:59 UTC, ryan-son commented on BoxOffice/Controller/BoxOfficeViewController.swift
> +        self.navigationItem.title = Date.yesterday.formatted(using: .standard)
의도한 기능이 잘 동작하는지 확인할 때는 해당 메서드를 호출하는 메서드를 호출하고 navigationitem.title 문자열을 비교해보면 되겠네요. 좋습니다!

2024-03-16 13:00 UTC, ryan-son approved these changes
댄, L, 남겨주신 코멘트에는 답을 달아두었으니 확인해보시기 바랍니다. 
Step 4 수행하시느라 고생 많으셨습니다. 다음 step에서 뵙겠습니다!

2024-03-16 13:00 UTC, ryan-son commented on BoxOffice/Model/Interface/DataProtocol.swift
>  }
현재와 같이 `DataSource`와 `DataDelegate` 구조를 가져간다면 어느 View에도 종속되지 않는 로직을 구성할 수 있지만 어떤 의도를 가지고 `reloadView`를 수행하는지 알기는 어려울 것 같습니다. DataSource와 ViewController 간 대화에 의도를 담으려면 번거롭더라도 개별적으로 인터페이스를 구성해주는 것이 좋을 수 있을 것 같네요. ViewController별 의존하는 DataSource 인터페이스가 나뉘었으므로 DataSource에서 연관 타입을 제거해줄 수 있을 것이고, DataSource -> ViewController 방향으로 메시지를 전송하는 delegate 프로토콜을 별도로 구성해줌으로써 목적을 달성할 수 있을 것 같습니다. 데이터를 전송하는 방식은 delegate 메서드로 전달해줄 수도 있고, 지금처럼 프로퍼티를 요구사항에 포함시킬 수도 있을 것 같네요.

2024-03-16 13:00 UTC, ryan-son commented on BoxOffice/Model/MovieDataProvider.swift
> +    init(movieCode: String, networkManager: NetworkManager = NetworkManager(urlSession: URLSession.shared)) {
`NetworkManager` 인스턴스가 Provider마다 공유되어 사용해도 괜찮다면 이니셜라이저에 기본값을 제공하기보다 Provider 인스턴스를 생성할 때 전달받을 수 있을 것 같습니다. 그렇다면 여러 개의 NetworkManager 인스턴스를 관리하지 않아도 되겠네요.

2024-03-16 13:00 UTC, ryan-son commented on BoxOffice/Model/MovieDataProvider.swift
> +    }
메서드의 반환을 통해 View를 구성해줄 수도 있겠네요. 목록에서는 향후에 페이지네이션 기능이 추가되면 로드한 데이터가 View의 내용과 다를 수도 있기 때문에 상태 관리를 해야했다면 이곳에서는 로드한 데이터를 한번만 소비하므로 로드 결과가 페이지 결과와 일치하므로 반환값 자체를 활용할 수도 있을 것 같습니다. 물론 현재 구성이 delegate 프로토콜을 구성하고 구현하는 번거로움이 있지만 조금 더 범용적인 솔루션에 가깝다고 보입니다. 각 컴포넌트별로 동일한 논리구조를 가져갈 것인지, 상황에 따라 가변적으로 구성할 것인지는 팀원과 논의해서 결정하시면 될 것 같습니다.

2024-03-16 13:00 UTC, ryan-son commented on BoxOffice/Model/MovieDataProvider.swift
> +    }
저는 이 메서드보다 `movie.toMovieDetail()` 쪽이 의미상 더 이해하기 쉬운 느낌이라 메서드로 래핑할 필요가 없을 것 같습니다. 여러분은 어떠신가요?

2024-03-16 13:00 UTC, ryan-son commented on BoxOffice/Model/MovieDataProvider.swift
> +    }
MovieDetail 타입이 MovieDataProvider 이외의 타입에서도 공유되는 것이라면 MovieDataProvider와의 종속성은 없애주는 편이 더 좋을 수도 있겠네요. 혹시 Provider 내부에 도메인 모델을 정의하신 이유가 무엇이었을까요?

2024-03-16 13:00 UTC, ryan-son commented on BoxOffice/Foundation/ArrayConverter.swift
> +}
메서드의 역할을 조금 더 명확하게 표현하기 위해 `joinedWithComma` 또는 `commaSeparatedString`과 같은 이름을 사용해볼 수 있을 것 같습니다.

2024-03-16 13:00 UTC, ryan-son commented on BoxOffice/Model/DTO/MovieImageDocument.swift
> +}
Meta라는 이름만으로는 어떤 데이터의 메타데이터인지 유추하기 어려울 것 같습니다. MovieImageDocument 타입 내부에 위치시키는 것도 괜찮을 것 같아요.

2024-03-16 13:00 UTC, ryan-son commented on BoxOffice/Model/DTO/MovieInformationResult.swift
> +        }.toString()
[Key Path](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/expressions/#Key-Path-Expression) 방식으로 아래와 같이 작성할 수도 있으니 참고하세요.

```swift
let directors: String = directors.map(\.personName).toString()
```

2024-03-16 13:00 UTC, ryan-son commented on BoxOffice/Model/DTO/MovieInformationResult.swift
> +                                                  actors: actors)
들여쓰기 수준을 동일한 레벨로 맞추면 좋겠네요.

2024-03-16 13:00 UTC, ryan-son commented on BoxOffice/Network/RESTAPI/KakaoAPI.swift
> +                .parameters([["query": query + " 영화 포스터"], ["size": "1"]])
apiKey에서 String interpolation 방식을 사용하기로 결정하셨다면 이곳에서도 컨벤션을 맞춰줄 수 있을 것 같아요.

2024-03-16 13:00 UTC, ryan-son commented on BoxOffice/Model/DTO/BoxOfficeResult.swift
> +                                         audienceAccumulated: audienceAccumulated)
indentation 맞춰주면 좋을 것 같습니다.

2024-03-16 13:00 UTC, ryan-son commented on BoxOffice/View/MovieInformationView.swift
> +    }
로드된 이미지와 placeholder 이미지 크기 차이가 크면 로드 전후로 사용자의 시선도 크게 이동하니 피로감이 있을 수 있죠. 이미지 로드 전후로 제약을 달리 설정해볼 수도 있을 것 같아요. 물론 이미지 로드 전에는 로드된 후의 이미지 크기를 알 수 없기 때문에 임의의 크기를 정해야 할거에요.

2024-03-16 13:00 UTC, ryan-son commented on BoxOffice/View/MovieInformationView.swift
> +        ])
이미지의 크기가 확정됐다고 생각하신다면 stackView 안으로 넣어줄 수도 있을 것 같아요. 현재 수준에서 stackView 내부로 imageView를 위치시킨다면 추가적인 처리가 더 필요한지 알아보실 수 있겠네요.

2024-03-16 13:00 UTC, ryan-son commented on BoxOffice/Model/MovieInformation.swift
> +    final class MovieDetail {
모델 역할을 수행하는 타입은 구조체로 구성하면 value semantics로 인해 동등성 비교 시 Equatable 프로토콜 채택 등 class 보다 편리한 점이 있으니 구조체를 활용해보시는 것을 권장드려요.

2024-03-16 13:00 UTC, ryan-son commented on BoxOffice/Network/Infrastructure/URLRequestBuilder.swift
> +        }
네, http method가 늘어날 때도 대응이 가능하도록 구성하는 편이 좋아보였어요.

2024-03-16 13:00 UTC, ryan-son commented on BoxOffice/View/MovieInformationView.swift
> +            imageView.centerXAnchor.constraint(equalTo: safeAreaLayoutGuide.centerXAnchor),
UIGraphicsImageRenderer API를 이용한 리사이징 로직이 포함되어있네요. 이 내용에 대해서도 학습해보시면 좋을거에요. 리사이징 뿐만 아니라 향후에 이미지 로드 시 메모리 최적화를 목표로 하는 경우에는 [imageI/O](https://developer.apple.com/documentation/imageio) 프레임워크, iOS 15부터는 preparingForDisplay(), preparingForThumbnail(of:) 또는 prepareForDisplay(completionHandler:), prepareThumbnail(of:completionHandler:)를 사용할 수 있으니 참고하세요.

2024-03-16 13:00 UTC, ryan-son commented on BoxOffice/View/MovieInformationView.swift
> +            scrollView.contentLayoutGuide.trailingAnchor.constraint(equalTo: safeAreaLayoutGuide.trailingAnchor),
잘 구성하셨네요. imageView 크기가 정해진다면 stackView 내부로 위치를 이동시켜줄 수도 있을 것 같습니다. 그럼 제약이 더 간단해지겠네요.

2024-03-16 13:02 UTC, merged

2024-03-19 05:44 UTC, eensungkim commented on BoxOffice/Model/Interface/DataProtocol.swift
>  }
개별적인 delegate 프로토콜로 분리한 뒤, 각각 자기 자신을 담아 전달하도록 구성해 보았습니다!

2024-03-19 05:51 UTC, eensungkim commented on BoxOffice/Model/MovieDataProvider.swift
> +    init(movieCode: String, networkManager: NetworkManager = NetworkManager(urlSession: URLSession.shared)) {
NetworkManager 를 싱글톤 패턴을 적용하여 구현해 보았습니다.

2024-03-19 06:10 UTC, eensungkim commented on BoxOffice/Model/Interface/DataProtocol.swift
>  }
아래에서 의견 주신 내용을 반영해 보면서, MovieDataProviderDelegate 를 삭제했습니다. 🙏

2024-03-19 06:13 UTC, eensungkim commented on BoxOffice/Model/MovieDataProvider.swift
> +    }
메서드 반환을 통해 뷰를 구성해줄 수 있도록 리팩토링해 보았습니다.
기존 구성이 조금 번거롭더라도 범용적인 솔루션이었기 때문에 굳이 바꿀 이유는 없었을 것 같습니다만,
공부하는 차원에서 변경을 진행했습니다! 🙏

2024-03-19 06:14 UTC, eensungkim commented on BoxOffice/Model/MovieDataProvider.swift
> +    }
동의됩니다! 래핑을 제거해 주었습니다!

2024-03-19 06:16 UTC, eensungkim commented on BoxOffice/Model/MovieDataProvider.swift
> +    }
BoxOfficeProvider 와 유사하게 구조를 가져가려는 생각에서 내부에 모델을 정의해 주었던 것이구요.
이번에는 Movie 라는 타입의 이름을 통일하되, 각각의 도메인 모델(BoxOfficeProvider, MovieDataProvider) 에서 사용하는 타입이라는 점을 강조하기 위해, BoxOfficeProvider.Movie, MovieDataProvider.Movie 로 변경해 보았습니다.

2024-03-19 06:17 UTC, eensungkim commented on BoxOffice/Foundation/ArrayConverter.swift
> +}
`joinedWithComma` 가 좋은 것 같아서 변경했습니다!

2024-03-19 06:20 UTC, eensungkim commented on BoxOffice/Model/DTO/MovieInformationResult.swift
> +        }.toString()
Key Path 방식이 조금 더 가독성이 좋다고 생각해서 반영했습니다!

2024-03-19 06:23 UTC, eensungkim commented on BoxOffice/Model/DTO/MovieImageDocument.swift
> +}
명칭을 변경하기보다는 말씀해주신대로 중첩 타입으로 바꾸었습니다!

2024-03-19 06:24 UTC, eensungkim commented on BoxOffice/Model/DTO/MovieInformationResult.swift
> +                                                  actors: actors)
넵!!

2024-03-19 06:24 UTC, eensungkim commented on BoxOffice/Network/RESTAPI/KakaoAPI.swift
> +                .parameters([["query": query + " 영화 포스터"], ["size": "1"]])
넵!

2024-03-19 06:24 UTC, eensungkim commented on BoxOffice/Model/DTO/BoxOfficeResult.swift
> +                                         audienceAccumulated: audienceAccumulated)
넵!

2024-03-19 07:06 UTC, eensungkim commented on BoxOffice/View/MovieInformationView.swift
> +    }
스택뷰 안에 이미지를 넣어두고, 이미지의 높이를 고정적으로 주었습니다.
아래 코드의 조건을 통해 좌우, 또는 상하 여백이 생기는 것이, 
이미지의 높이가 변경되는 것보다 조금 더 나아 보인다는 판단 때문이었습니다.

```swift
imageView.contentMode = .scaleAspectFit
```

2024-03-19 07:07 UTC, eensungkim commented on BoxOffice/View/MovieInformationView.swift
> +        ])
위에서 말씀드린대로 이미지를 스택뷰 안에 넣어줌에 따라, 제약 조건 일부를 변경했습니다!