박스오피스 앱 [STEP4] Sidi, Yuni 
tasty-code/ios-box-office pull request #54
Opened 2024-03-14 07:42 UTC by Jin0Yun

안녕하세요. 지성 [@yim2627](https://github.com/yim2627)

시디, 유니입니다.

이번 스텝도 잘 부탁드립니다. 🙇🙇‍♀️

**STEP4 요구사항**

- 영화의 상세내용을 확인할 수 있는 화면을 구현합니다.
- 표시할 영화 정보
    - 제목
    - 포스터 이미지
    - 감독
    - 제작년도
    - 개봉일
    - 상영시간
    - 관람등급
    - 제작국가
    - 장르
    - 배우
    - 영화 포스터 이미지는 `[영화제목] + [영화 포스터]`로 이미지 검색하여 제일 첫 이미지를 사용합니다
    - 이미지가 로드되기 전에는 이미지가 로드중임을 알 수 있도록 적절히 처리해주세요
- 내용이 길어지면 위아래로 스크롤 할 수 있도록 구현해주세요

**질문**

1. 이미지뷰의 로딩화면만 인디케이터로 구현하였는데, 라벨 또한 로딩중임을 표현해 주는게 좋을 것 같은데 이미지뷰와 라벨의 데이터가 로딩되기전까지 하나의 인디케이터로 구현하는게 좋을지, 또 다른 방법이 있는지 궁금합니다.
2. 이미지뷰를 불러오는 현재 디테일뷰컨트롤러에 있는`configureImageView` 메서드 로직이 단순히 뷰의 기능뿐 아니라 데이터를 처리하는 기능을 가지고 있는 것처럼 보이는데 뷰모델과 뷰컨트롤러 중에 어디에 위치해야 하는지 고민이 됩니다.

```swift
private func configureImageView(with movieImage: MovieImage) {
        guard let imageURLString = movieImage.documents.first?.imageURL,
              let imageURL = URL(string: imageURLString) else {
            print("URL error")
            return
        }
        DispatchQueue.global().async { [weak self] in
            do {
                let imageData = try Data(contentsOf: imageURL)
                let image = UIImage(data: imageData)
                DispatchQueue.main.async {
                    self?.indicatorView.stopAnimating()
                    self?.indicatorView.removeFromSuperview()
                    self?.movieImageView.image = image
                }
            } catch {
                print(error.localizedDescription)
            }
        }
    }
```

2024-03-14 12:59 UTC, yim2627 requested changes
안녕하세요 Sidi, Yuni!

이번 스텝도 많이 어려우셨을텐데, 수고많으셨습니다.

질문 주신 부분은 아래에 답변하였고, 커멘트도 남겼으니 확인 부탁드립니다.

질문 있으시면 언제든지 DM 주세요!

>이미지뷰의 로딩화면만 인디케이터로 구현하였는데, 라벨 또한 로딩중임을 표현해 주는게 좋을 것 같은데 이미지뷰와 라벨의 데이터가 로딩되기전까지 하나의 인디케이터로 구현하는게 좋을지, 또 다른 방법이 있는지 궁금합니다.

다운로드가 오래걸리는 이미지의 경우 따로 처리하기도 합니다. 그래서 보통 이미지뷰 인디케이터, 화면 전체의 인디케이터로 관리하여 이미지가 완전히 다운로드 되지 않아도 컨텐츠는 볼 수 있게끔 합니다.


>이미지뷰를 불러오는 현재 디테일뷰컨트롤러에 있는configureImageView 메서드 로직이 단순히 뷰의 기능뿐 아니라 데이터를 처리하는 기능을 가지고 있는 것처럼 보이는데 뷰모델과 뷰컨트롤러 중에 어디에 위치해야 하는지 고민이 됩니다.
private func configureImageView(with movieImage: MovieImage) {
        guard let imageURLString = movieImage.documents.first?.imageURL,
              let imageURL = URL(string: imageURLString) else {
            print("URL error")
            return
        }
        DispatchQueue.global().async { [weak self] in
            do {
                let imageData = try Data(contentsOf: imageURL)
                let image = UIImage(data: imageData)
                DispatchQueue.main.async {
                    self?.indicatorView.stopAnimating()
                    self?.indicatorView.removeFromSuperview()
                    self?.movieImageView.image = image
                }
            } catch {
                print(error.localizedDescription)
            }
        }
    }

이미지의 경우 URL로 ViewModel에서 ViewController에 넘겨주는 것이 대부분이며, 이는 ViewModel이 UIKit을 의존하지 않도록 하기위함이기도 합니다. 그래서 위같은 경우에는 따로 Extension이나, 이미지 다운로드용 객체를 만들어서 관리하는 것도 좋아보입니다. 더 좋은 방법을 구색해봐도 좋을 것 같아요!

>이번 스텝에서 화면 전환이 추가 되면서 ViewModel에 대한 의존성 주입이 ViewController가 책임을 지게 되면 ViewController의 역할과 무관한 코드들이 생기게 되어 Navigator라는 의존성 주입과 화면 전환을 담당하는 객체를 만들어 사용 했습니다. 화면 전환이 얼마 없어 이 역할을 하는 객체에 대한 필요성이 많이 느껴지지는 않았지만 의존성 관리 측면에서 이점이 보여 사용을 했는데 더 좋은 방향이 있을지 궁금합니다!

라우팅 전용 객체를 만드신 것도 좋은 방법이라고 생각합니다. 다만 Navigator 인스턴스가 여렷 생겨 메모리릭이 발생하는 상황을 주의하셔야될 것 같아요. 지금 상황에서 더 나은 방법이라면, 의존성 주입 객체 또한 따로 빼서 Navigator가 모든 객체를 다 알아 무거워지는 상황을 방지할 수 있을 것 같아요.

2024-03-14 12:59 UTC, yim2627 commented on BoxOffice/Application/Navigator.swift
> +        let dataTransferService = DefaultDataTransferService(with: networkService)
함수 내부에서 인스턴스를 생성하여 주입하게 되면 함수를 실행할때마다 인스턴스가 생성될텐데 이렇게 구현하신 이유가 있을까요?

2024-03-14 12:59 UTC, yim2627 commented on BoxOffice/Application/Navigator.swift
> +            viewController.navigationController?.pushViewController(detailViewController, animated: true)
```suggestion
        case .detailMovie:
            guard let detailViewController = initializeViewController(destination: destination) as? MovieDetailViewController else {
                fatalError("MovieDetailView 에러")
            }
            viewController.navigationController?.pushViewController(detailViewController, animated: true)
```

2024-03-14 12:59 UTC, yim2627 commented on BoxOffice/Application/Navigator.swift
> +        }
이 케이스는 어떤 화면으로 이동하는건지 명확하지 않은 것 같습니다.

2024-03-14 12:59 UTC, yim2627 commented on BoxOffice/Application/Navigator.swift
> +class Navigator: NavigatorProtocol {
```suggestion
final class Navigator: NavigatorProtocol {
```

2024-03-14 12:59 UTC, yim2627 commented on BoxOffice/Domain/Interface/MovieDetailRepository.swift
> +}
CleanArchitecture에서 이렇게 추상화를 하는 이유는 무엇일까요?

2024-03-14 12:59 UTC, yim2627 commented on BoxOffice/Domain/Interface/MovieDetailRepository.swift
> +}
의존성 역전을 통해 얻는 이점은 무엇이 있을까요?

2024-03-14 12:59 UTC, yim2627 commented on BoxOffice/Domain/UseCase/MovieDetailUseCase.swift
> +}
CleanArchitecture에서 Repository와 UseCase를 나누는 기준은 어떻게 정하셨나요? 또한 UseCase는 어떤 역할을 할까요?

2024-03-14 12:59 UTC, yim2627 commented on BoxOffice/Domain/Interface/MovieImageRepository.swift
> +}
Repository는 어떤 역할을 하는 객체인가요?

2024-03-14 12:59 UTC, yim2627 commented on BoxOffice/Domain/UseCase/MovieDetailUseCase.swift
> +    }
Repository에서도 URLSessionTask를 내려주는데, UseCase에서도 URLSessionTask를 동일하게 내려주고 있네요.
이러면 UseCase의 용도가 없어보이는데, 이렇게 구현해주신 이유가 궁금합니다!

2024-03-14 12:59 UTC, yim2627 commented on BoxOffice/Infra/Util/Extension/Bundle+.swift
> +        }
예외처리 👍👍

2024-03-14 12:59 UTC, yim2627 commented on BoxOffice/Infra/Util/Extension/String+.swift
>          return dateFormatter.date(from: self)
더 범용성있어졌네요 👍

2024-03-14 12:59 UTC, yim2627 commented on BoxOffice/Presentation/MoviesList/View/MovieDetailViewController.swift
> +    private var callMovieImageEvent: Observable<Void> = Observable(())
모두 변수인 이유가 있을까요?

2024-03-14 12:59 UTC, yim2627 commented on BoxOffice/Presentation/MoviesList/View/MovieDetailViewController.swift
> +    }()
lazy일 필요가 있나요?

2024-03-14 12:59 UTC, yim2627 commented on BoxOffice/Presentation/MoviesList/View/MovieDetailViewController.swift
> +    private func addSubviewsAndSetupLayout() {
뷰 구성만 하는 것 같은데, SetupLayout이 붙어 어색해보입니다. 또한 네이밍에 and가 포함되면 단일책임이 아닌 것일 수 있으니 함수 생성시 한번씩 더 검증해보는 것도 좋을 것 같아요.

2024-03-14 12:59 UTC, yim2627 commented on BoxOffice/Presentation/MoviesList/View/MoviesListViewController.swift
> +    private lazy var output = viewModel.transform(input: input)
좀 더 명확해보이네요 👍

2024-03-14 12:59 UTC, yim2627 commented on BoxOffice/Presentation/MoviesList/ViewModel/MovieDetailViewModel.swift
> +    }
👍

2024-03-14 12:59 UTC, yim2627 commented on BoxOffice/Presentation/MoviesList/ViewModel/MovieDetailViewModel.swift
> +                }
UI 관련 업데이트는 메인스레드에서 👍👍

2024-03-14 12:59 UTC, yim2627 commented on BoxOffice/Presentation/MoviesList/ViewModel/MoviesListViewModel.swift
>  }
👍👍

2024-03-14 12:59 UTC, yim2627 commented on BoxOffice/Application/Info.plist
> +	<string>KakaoAK 426d6eab07e03ccf42add55365c8dcad</string>
👍

2024-03-14 12:59 UTC, yim2627 commented on BoxOffice/Presentation/MoviesList/View/MoviesListViewController.swift
> +    private var loadCellEvent: Observable<Int> = Observable(-1)
-1 은 어떤것을 의미하나요?

2024-03-14 12:59 UTC, yim2627 commented on BoxOffice/Presentation/MoviesList/View/MoviesListViewController.swift
>      private func bind() {
일관성이 없어보여서 bindInput, bindOutput 정도의 네이밍을 지어주면 좋을 것 같은데, 어떻게 생각하시나요?

2024-03-15 04:20 UTC, jus1234 commented on BoxOffice/Application/Navigator.swift
> +        let dataTransferService = DefaultDataTransferService(with: networkService)
프로퍼티로 둘지 메서드 내에서 생성을 할지 고민이 되었던 부분이긴 했습니다. 지성 말씀을 들으니 프로퍼티로 두는 것이 메모리적으로 더 효과적인 것으로 생각되어 프로퍼티로 두어 인스턴스를 한번만 생성하는 것으로 변경했습니다!

2024-03-15 04:47 UTC, Jin0Yun commented on BoxOffice/Application/Navigator.swift
> +        }
명확하게 구분해주기 위해 `movieList` 와 `detailMovie` 케이스로 구분하여 수정해주었습니다.

2024-03-15 06:30 UTC, jus1234 commented on BoxOffice/Presentation/MoviesList/View/MovieDetailViewController.swift
> +    private var callMovieImageEvent: Observable<Void> = Observable(())
`ViewController`와 `ViewModel`를 양뱡향 바인딩 하기 위해서 `ViewModel`에서 `ViewController`를 관측할 수 있는 `Observable` 이벤트가 이것을 필요한데 RxCocoa에서 쓰이는 `ControlEvent`처럼 만들기 위해서 `Observable`로 이벤트를 명시적으로 생성하여 사용했습니다. 이 방법 이외에 양방향 바인딩을 위한 다른 더 좋은 방법이 있다면 조언 부탁드립니다!!

2024-03-15 06:42 UTC, Jin0Yun commented on BoxOffice/Domain/UseCase/MovieDetailUseCase.swift
> +}
`UseCase` 는 비즈니스 로직이 위치한 곳으로 Reposiory의 Interface를 가지는데, 현재 저희는 UseCase에 비즈니스 로직이 존재하진 않지만 서버에서 받아온 데이터를 매핑해서 사용하기에 `dependency Rule`을 기준으로 DTO의 사용여부에 따라 `Repository`와 `UseCase`로 역할을 나누었습니다.

2024-03-15 07:07 UTC, jus1234 commented on BoxOffice/Presentation/MoviesList/View/MoviesListViewController.swift
> +    private var loadCellEvent: Observable<Int> = Observable(-1)
셀의 0번 인덱스 이전을 의미하게 하려고 -1로 초기 값을 두었습니다.

2024-03-15 07:21 UTC, Jin0Yun commented on BoxOffice/Presentation/MoviesList/View/MoviesListViewController.swift
>      private func bind() {
수정하였습니다!

2024-03-15 07:27 UTC, Jin0Yun commented on BoxOffice/Presentation/MoviesList/View/MovieDetailViewController.swift
> +    private func addSubviewsAndSetupLayout() {
수정하였습니다!!

2024-03-15 08:12 UTC, Jin0Yun commented on BoxOffice/Domain/Interface/MovieDetailRepository.swift
> +}
CleanArchitecture에서 이렇게 추상화를 하는 이유는 확장성과 유지보수성을 향상시키기 위해 각 계층을 독립적으로 유지하기 위함으로, 
모든 의존성이 도메인을 향하게 되면 구체적인 구현이 아니라 추상화에 의존함으로써 결합도를 낮출 수 있어 확장성과 유지보수에 좋아진다고 생각했습니다.

2024-03-17 10:03 UTC, Jin0Yun commented on BoxOffice/Presentation/MoviesList/View/MoviesListViewController.swift
>      private func bind() {
수정하였습니다!!

2024-03-17 10:07 UTC, Jin0Yun commented on BoxOffice/Presentation/MoviesList/View/MovieDetailViewController.swift
> +    }()
앗,,..`let`으로 수정하였습니다!!

2024-03-17 10:10 UTC, jus1234 commented on BoxOffice/Domain/Interface/MovieImageRepository.swift
> +}
도메인 영역의 Repository는 도메인 영역인 UseCase가 Data 영역의 Repository에 의존성을 갖지 않게 하기 위한 인터페이스 입니다.
데이터 영역의 Repository는 Repository 인터페이스의 구현체로 DataSource(로컬 DB, 네트워크 등)으로 부터 데이터를 가져오고 저장하기 위한 객체 입니다.

2024-03-17 10:25 UTC, jus1234 commented on BoxOffice/Domain/UseCase/MovieDetailUseCase.swift
> +    }
UseCase의 용도는 비즈니스 로직을 담당 합니다. 현재 저희 BoxOffice 앱에서는 비즈니스 로직이 영화 데이터를 보여 주는 것 입니다. 그래서 Repository로부터 받아온 데이터를 전달하는 역할만 수행합니다.

2024-03-18 13:24 UTC, yim2627 commented on BoxOffice/Presentation/MoviesList/View/MovieDetailViewController.swift
> +    private var callMovieImageEvent: Observable<Void> = Observable(())
더 좋은 방법은 크게 생각나지 않네요! MVVM패턴에선 대부분 저런 구조라고 생각해서요.
다만 Observable을 사용하고싶었다면 차라리 RxSwift를 도입해봤음 더 좋았을 것 같고 그게 아니라면 현재 구조에서 클로저를 전달하는 식의 구현이 공부에 더 도움이 되었을 것 같은 아쉬움은 있습니다!
그래도 처음이신데 잘 구현해주신 것 같아요.

2024-03-18 13:25 UTC, yim2627 approved these changes

2024-03-18 13:36 UTC, merged