Step3
tasty-code/ios-box-office pull request #56
Opened 2024-03-15 06:42 UTC by Gnoam-R

안녕하세요!! 두두 ([@FirstDo](https://github.com/FirstDo))

네로 ([@ODDNERO](https://github.com/ODDNERO)), 노움 ([@Gnoam-R](https://github.com/Gnoam-R))입니다.

시간 여유되실때 편히 리뷰 부탁드립니다.

## [STEP3] 작업 목록

- [x]  Safe Area을 고려한 오토 레이아웃 구현
- [x]  Collection View의 활용
- [x]  박스 오피스 API 모델 데이터 바인딩

## **[STEP3] 구현 사항**

### `UI 작업 및 API 데이터 연결 & AutoLayout 설정`

화면 UI를 개발할때 storyboard가 아닌 code base로 작업을 했습니다.
AutoLayout을 잡아주는 작업을 통해 다양한 기기에 대한 화면 대응이 가능합니다.
메인 뷰에 CollectionVIew를 추가하고 STEP2에서 진행했던 BoxOfficeAPI를 가져와 CollectionView의 아이템들에 값을 바인딩 하였습니다.
화면의 리스트를 잡아 당길때 네트워크 통신으로 API를 다시 호출하고 리스트를 업데이트 합니다.

<br/>

## **[STEP3] 질문**

CollectionView 화면을 구성하는데 필요한 뷰들을 생성하는 코드입니다.
라벨과 같은 뷰들을 생성하는데 있어서 아래와 같은 작업들이 필요한데 반복되는 작업들도 많고, 스토리 보드에서 코드 기반의 프로그래밍으로 넘어감에 있어서 너무 많은 역할이 해당 클래스에 부여되는거 같다는 생각이 들었습니다
이를 해결하기 위한 좋은 방법이 있을까요?

```swift
  let movieNameLabel: UILabel = {
        let label = UILabel()
        label.translatesAutoresizingMaskIntoConstraints = false
        label.font = .systemFont(ofSize: 20)
        label.text = ""
        return label
    }()

  let movieRankLabel: UILabel = {
      let label = UILabel()
      label.translatesAutoresizingMaskIntoConstraints = false
      label.font = .systemFont(ofSize: 30)
      label.text = ""
      return label
  }()

  let movieChangeRankLabel: UILabel = {
      let label = UILabel()
      label.translatesAutoresizingMaskIntoConstraints = false
      label.font = .systemFont(ofSize: 15)
      label.text = ""
      return label
  }()

```

## 📸 Screenshot

<img src="https://github.com/tasty-code/ios-box-office/assets/67363759/00f0abde-5136-4a37-a110-4ba574eac098" width="200" height="400"/>

2024-03-18 23:38 UTC, FirstDo requested changes
두분 고생하셨습니다!
codebase Autolayout과 Refresh기능을 잘 구현해 주셨습니다 !!!
지금 빌드가 안되서 제가 실행모습을 확인할 수 가 없는데, 해당 부분도 수정해주세요 :)

## 질문에 대한 답변

CollectionView 화면을 구성하는데 필요한 뷰들을 생성하는 코드입니다.
라벨과 같은 뷰들을 생성하는데 있어서 아래와 같은 작업들이 필요한데 반복되는 작업들도 많고, 스토리 보드에서 코드 기반의 프로그래밍으로 넘어감에 있어서 너무 많은 역할이 해당 클래스에 부여되는거 같다는 생각이 들었습니다
이를 해결하기 위한 좋은 방법이 있을까요?

1. UILabel의 반복작업이 심하다면, 공통작업을 수행하는 매서드를 만들거나, 이니셜라이저를 만드는 방법이 있습니다

ex)
```swift
extension UILabel {
  convenience init(size: CGFloat) {
    self.init()
    self.translatesAutoresizingMaskIntoConstraints = false
    self.font = .systemFont(ofSize: size)
    self.text = ""
  }
}
```

2. 너무 많은 역할이 해당 클래스에 부여되는거 같다는 생각이 들었습니다 

VC와 Cell 측면에서 말해보겠습니다

Cell은 우선 문제가 없습니다
역할도 하나고, 그냥 단순히 UI가 많을 뿐이에요

VC는 문제가 있습니다
현재는 UI, Controller, 로직이 다 섞여있는데
1차적으로는 View - ViewController로 나눌 수 있습니다 (VC의 mainView를 교체하는 방식)
2차적으로는 View - ViewModel로 나눌수도 있겠네요!

다만 이건 현재 단계에서 고려할 부분은 아닌듯 합니다 ㅎㅎ

2024-03-18 23:38 UTC, FirstDo commented on BoxOffice/Sources/Presentation/BoxOfficeViewController.swift
> +    }()
collectionView의 compositionalLayout을 사용하셨군요 :)

UICollectionView의 레이아웃은 크게 전통적인 방식의 FlowLayout과 
비교적 새로운 방식인 CompositionalLayout으로 나눌수 있습니다

UICollectionView에 데이터를 공급하는 datasource 방식도
전통적인 datasource, delegate를 채택하는 방식 (지금하신것)과 diffableDataSource를 이용하는 비교적 새로운 방식이 있습니다

모두 하실줄 아셔야 하며 처음에는 UITableView, UICollectionView가 어렵게 느껴지실 수 있습니다..!
해당 부분은 반복학습으로 해결해야할 부분으로 보이네요

2024-03-18 23:38 UTC, FirstDo commented on BoxOffice/Sources/Presentation/BoxOfficeViewController.swift
> +    private lazy var boxOfficeCollectionView: UICollectionView = {
lazy를 사용할 이유가 없어보이네요..! 현재 사용하고 있지 않습니다

2024-03-18 23:38 UTC, FirstDo commented on BoxOffice/Sources/Presentation/BoxOfficeViewController.swift
> +            }
DispatchQueue로 감싸주시는 것 좋습니다 :)
왜 UI는 메인스레드에서 업데이트 되어야 할까요?

2024-03-18 23:38 UTC, FirstDo commented on BoxOffice/Sources/Presentation/BoxOfficeViewController.swift
> +        dailyBoxOffice.execute(complection: { [self] result in
[self] 이게 무슨의미일까요?, 이렇게 써도 되는걸까요?
캡처 리스트에서 대해서 아는대로 서술해주세요!
중요한 개념이고, 공부하시고 정리해서 작성해도 됩니다.

2024-03-18 23:38 UTC, FirstDo commented on BoxOffice/Sources/Presentation/BoxOfficeViewController.swift
> +        ])
leading, left
trailing, right 의 차이를 아시나요?

지금 leading과 right를 섞어서 쓰고 있네요!

2024-03-18 23:38 UTC, FirstDo commented on BoxOffice/Sources/Presentation/BoxOfficeViewController.swift
> +        boxOfficeCollectionView.register(CollectionViewCell.self, forCellWithReuseIdentifier: "cell")
cell이 많아진다면?
"cell", "cell1", "cell2" ??
더 좋은 방법을 찾아봐야할것 같습니다

2024-03-18 23:38 UTC, FirstDo commented on BoxOffice/Sources/Presentation/BoxOfficeViewController.swift
> +        }
DispatchQueue로 감싼 의도는 알겠으나!
updatUI가 어느스레드에서 실행되는지를 먼저 파악해야할것 같습니다
현재 실행되는 스레드는 어떻게 파악할까요? 그리고 지금 updateUI 매서드는 어느 스레드에서 실행될까요?

2024-03-18 23:38 UTC, FirstDo commented on BoxOffice/Sources/Presentation/BoxOfficeViewController.swift
> +extension BoxOfficeViewController: UICollectionViewDataSource {
extension으로 분리하시는것 좋네요!!

2024-03-18 23:38 UTC, FirstDo commented on BoxOffice/Sources/Presentation/BoxOfficeViewController.swift
> +        cell.accessories = [.disclosureIndicator()]
configure 매서드 만드신것 정말 좋습니다!
다만 'cell.accessories = [.disclosureIndicator()]'
이친구도 cell의 속성인만큼 외부에서 해주지 마시고 cell 내부에서 하시는게 더 좋아보이네요!

2024-03-18 23:38 UTC, FirstDo commented on BoxOffice/Sources/Presentation/BoxOfficeViewController.swift
> +class BoxOfficeViewController: UIViewController, DailyFormatter{
보통 final을 붙이는걸 선호합니다
왜붙여야 할까요?

2024-03-18 23:38 UTC, FirstDo commented on BoxOffice/Sources/Presentation/CollectionViewCell.swift
> +class CollectionViewCell: UICollectionViewListCell {
프로젝트를 수행하다보면 Cell이 100개가 넘을수도 있는데, 이름을 좀 더 명확하게 짓는게 좋을것 같아요
+ final

2024-03-18 23:38 UTC, FirstDo commented on BoxOffice/Sources/Presentation/CollectionViewCell.swift
> +    let movieNameLabel: UILabel = {
외부에 노출될 필요 없으면 private을 붙이는게 좋을것 같네요

2024-03-18 23:38 UTC, FirstDo commented on BoxOffice/Sources/Presentation/CollectionViewCell.swift
> +        label.translatesAutoresizingMaskIntoConstraints = false
`translatesAutoresizingMaskIntoConstraints` 이거 무슨뜻일까요??

2024-03-18 23:38 UTC, FirstDo commented on BoxOffice/Sources/Presentation/CollectionViewCell.swift
> +        nameAndNumberOfPeopleStackView.translatesAutoresizingMaskIntoConstraints = false
스택뷰 자체적으로 하는게 좋아 보이네요!

2024-03-19 08:31 UTC, Gnoam-R commented on BoxOffice/Sources/Presentation/BoxOfficeViewController.swift
> +    private lazy var boxOfficeCollectionView: UICollectionView = {
`lazy`를 현재는 사용하지 않아야 하는게 맞습니다.
원래 목적은` boxOffice API`를 가져오지 않는 경우에  boxOfficeCollectionView를 메모리에 올리지 않도록 하기 위해서 해당 키워드를 넣게 되었는데 현재 코드에서는 API를 가져오지 못하는 오류에 대한 별도의 코드작업을 진행하지 않아서 문제가 된거 같습니다

2024-03-19 08:41 UTC, Gnoam-R commented on BoxOffice/Sources/Presentation/BoxOfficeViewController.swift
> +            }
앱의 기본적인 UI Event는 UIApplication -> UIWindow -> UIViewController -> UIView -> subVviews와 같은 `Event Chain` 으로 연결되어 있는데 이러한 이벤트 체인이 메인 스레드에서 동작하기 때문에 모든 UI 관련 동작들은 메인 스레드에서 수행하게 됩니다

2024-03-21 02:07 UTC, Gnoam-R commented on BoxOffice/Sources/Presentation/BoxOfficeViewController.swift
> +        ])
left와 right의 경우 화면의 정중앙을 기준으로 나뉘어지는 왼쪽 오른쪽을 의미하고
trailing, leading은 글자가 시작되는 방향을 의미합니다.
2개가 다른 이유는 언어의 경우 시작되는 방향이 나라별로 다르기 때문에 좌우의 경우 방향을 나타내는 메서드가 차이가 나게 됩니다!

2024-03-21 04:40 UTC, Gnoam-R commented on BoxOffice/Sources/Presentation/BoxOfficeViewController.swift
> +        boxOfficeCollectionView.register(CollectionViewCell.self, forCellWithReuseIdentifier: "cell")
커스텀으로 생성된 클래스는 identifier 라는 많이 사용되는 프로퍼티를 생성하여 값을 static으로 사용하는 방법이 있습니다
또 다른 방법으로는 
```swift
String(describing: )

String(describing: CollectionViewCell.self)
```
이 메서드를 사용하여 클래스 자체의 네이밍을 identifer로 사용할 수 있습니다

2024-03-21 04:58 UTC, Gnoam-R commented on BoxOffice/Sources/Presentation/BoxOfficeViewController.swift
> +class BoxOfficeViewController: UIViewController, DailyFormatter{
클래스의 final 키워드를 붙이면 다른 클래스에서 상속이 불가능하고 컴파일 타임에 호출되게 됩니다.
따라서 런타임 성능 향상을 시켜주게 되기 떄문에 final 키워드를 붙이는 것을 지향 해야됩니다.

2024-03-21 05:00 UTC, Gnoam-R commented on BoxOffice/Sources/Presentation/CollectionViewCell.swift
> +class CollectionViewCell: UICollectionViewListCell {
넵 `MovieCollectionVIewCell`로 변경하도록 하곘습니다

2024-03-21 07:19 UTC, Gnoam-R commented on BoxOffice/Sources/Presentation/CollectionViewCell.swift
> +        label.translatesAutoresizingMaskIntoConstraints = false
view class가 SubView에 대한 layout 배치를 재설정 하게끔 해주는 기능입니다
재설정되는 이유는 기존 layout에서 화면의 크기가 변동되는 경우에 있어서 대응하기 위해서 변경된 layout으로 재설정해줍니다

그래서 여기 translatesAutoresizingMaskIntoConstraints가 false인 것은 자동으로 크기를 설정해주는 것에서 내가 새롭게 잡은 위치로 배치를 시키기 위해서 false로 설정하게 됩니다.

2024-03-22 02:39 UTC, Gnoam-R commented on BoxOffice/Sources/Presentation/BoxOfficeViewController.swift
> +        dailyBoxOffice.execute(complection: { [self] result in
저희는 dailyBoxOffice으 메서드 execute의 익명함수를 가져와 호출하고 있습니다
클로저는 호출되는 장소의 외부 context(execute가 호출되는 클래스의 정보)를 가져오기 위해서는 `closure capture`라는 기능을 사용해야 됩니다

그런데 클로저의 캡처는 외부에서 존재하는 context를 내부에서 사용하기 위해 값을 저장하거나 참조를 저장하게 됩니다, 이렇게 되면 변수에 할당된 클로저의 실행이 종료가 되더라도 스텍에서 클로저의 힙 메모리 주소를 계속 가리키고 있어서 메모리 공간을 계속해서 차지하는 일이 나타나게 됩니다

이때 사용되는 것이 캡처 리스트 인데 캡처 리스트는 참조 강도를 명시하여 서로 강한 참조일때 발생되는 순한참조라는 것을 방지할 수 있습니다

하지만 무조건적으로 캡처 리스트 & 순환 참조를 사용하는것으로 좋은 방법이 아닌데요
VIewController의 경우 self는 생명주기와도 연결이 되어있기 때문에 [weak self]를 사용하게 될시에 다른 동작이 발생할수가 있습니다

2024-03-22 07:06 UTC, Gnoam-R commented on BoxOffice/Sources/Presentation/BoxOfficeViewController.swift
> +        }
우선 위의 이전 글처럼 event처리에 대한 모든 UI에 대한 업데이트는 메인 스레드에서 이루어 져야 합니다
CollectionView에 대한 데이터 업데이트또한 마찬가지로 메인 스레드에서 이루어 지게 됩니다.
왜냐하면 메인 쓰레드는 큐로 작업에 대한 처리를 순차적으로 실행해야 하기 때문에 CollectionView의 아이템이 들어오기 전에 뷰가 업데이트되는 것과 같은 비동기적 작업을 수행할수 없습니다

현재 updateUI에 대한 메서드는 메인 스레드로 아래와 같이 현재 큐와 메인 큐를 비교하는 테스트 코드를 작성하여 일치하는것을 알수가 있었습니다
```swift
DispatchQueue.main.asyncAfter(deadline: .now() + 1.5) {
      let result = (OperationQueue.current == OperationQueue.main)
      print("result \(result)")
  
      self.boxOfficeCollectionView.reloadData()
      refresh.endRefreshing()
}
```

<img width="125" alt="image" src="https://github.com/tasty-code/ios-box-office/assets/67363759/1eac4ac1-f302-40f3-8b1d-773992bc691f">

2024-03-25 00:01 UTC, FirstDo commented on BoxOffice/Sources/Presentation/BoxOfficeViewController.swift
> +            }
맞는 말이지만, 추후 이런질문을 면접에서 받았을때
Thread - Safe 문제와, Main Run Loop로 엮어서 답변하시면 더 좋을것 같네요

2024-03-25 00:02 UTC, FirstDo commented on BoxOffice/Sources/Presentation/BoxOfficeViewController.swift
> +        dailyBoxOffice.execute(complection: { [self] result in
정말 정석적인 방법은 객체간의 생명주기 + 순환참조 여부를 확인하고
`[unowned self], [weak self] 혹은 캡처하지 않음`
을 사용하는것이겠지만, 저는 대부분의 경우 [weak self]로 사용하는 편입니다 (가장 문제될 여지가 적음)

물론 알고는 있어야 겠죠?

2024-03-25 00:04 UTC, FirstDo commented on BoxOffice/Sources/Presentation/BoxOfficeViewController.swift
> +        }
`Thread.isMainThread 와 같은 방법으로도 확인할 수 있습니다.

그리고 현재 코드에서 updateUI 매서드는 이미 MainThread에서 호출되었기때문에 굳이 DispatchQueue.main으로 감 쌀 필요가 없겠죠

2024-03-25 00:04 UTC, FirstDo commented on BoxOffice/Sources/Presentation/BoxOfficeViewController.swift
> +class BoxOfficeViewController: UIViewController, DailyFormatter{
맞습니다
method dispatch에 관해서 찾아보시면 좋을것 같네요 :)

2024-03-25 00:05 UTC, FirstDo approved these changes

2024-03-25 23:14 UTC, merged