# 박스오피스 [STEP 1] Sunny, Blu
tasty-code/ios-box-office pull request #6
Opened 2023-04-26 07:53 UTC by calledBlu

>안녕하세요! 븨븨(@YebinKim)🦜!
>🧴**TEAM SUNBLock**🧴 의 Sunny, Blu입니다!
>
>마지막 프로젝트를 븨븨와 함께하게 되어서 정말 기뻐요!
이번에 븨븨의 리뷰로 많은 것을 배우기 위해 둘 다 열정을 불태워보려 합니다! 🔥🔥
>
>STEP 1에서는 모델 타입 구현에 앞서 UML을 작성해 보았으며, 이를 토대로 코드를 작성하였습니다.
>또한, 주어진 JSON 데이터를 Model 타입으로 Parsing 가능한지를 확인하기 위해 Unit Test에 대한 공부도 진행하였습니다.
>
>일정 양해해 주셔서 정말 감사해요 븨븨! 리뷰 잘 부탁드리겠습니다! 감사합니다 😆😆

<br>

# 🧑🏼‍💻 작업 목록
## 모델 타입 구현
- [x] 모델 타입 구현
    - [x] `UML` 작성
    <img src="https://user-images.githubusercontent.com/71758542/234207837-bb5344a8-d07b-48d8-a23c-c5e3350a010d.jpg" width=400>

    - [x] `CodingKeys` 프로토콜 활용
- [x] 주어진 JSON 데이터를 Model 타입으로 Parsing할 수 있는지 `Unit Test` 진행

<br>

# 📚 학습 키워드 및 학습 내용
## 1. Data Transfer Object
> 🖇️　참고문서
> - [Wikipedia - Data transfer object](https://en.wikipedia.org/wiki/Data_transfer_object)
> 
- **학습 내용**
    - DTO는 프로세스간에 데이터를 전달하는 개체
    - DTO는 비즈니스 로직을 가지면 안 됨
- **문제와 해결**
    - 😰 DTO 타입의 파일 분리
    - 🚀 API로 가져온 데이터 중 어떤 데이터를 사용할지 모르기 때문에 우선 각 타입 별로 파일을 분리함
- **추후 개선 방향**
   - 데이터들의 사용 여부가 결정된 이후 DTO 타입 컨벤션 논의 예정
   - 중첩 타입이 존재하는 경우 캡슐화 진행 예정

<br>

## 2. CodingKey
> 🖇️　참고문서
> - [공식문서 - CodingKey](https://developer.apple.com/documentation/swift/codingkey)

- **학습 내용**
   - 코딩키는 인코딩, 디코딩 시 키로 사용할 수 있는 유형
   - 적용해 본 결과, 디코딩/인코딩할 `key`값과 `DTO 타입의 속성`의 이름이 다를 경우 CodingKey를 사용해 둘 사이를 맵핑해주는 역할을 한다.
- **적용 과정**
   - 내부 프로퍼티 네이밍이 `API Design Guidlines`을 준수하도록 대·소문자 변경
- **문제와 해결**
    - 😰 Unit Test 진행 시 `KeyNotFound error` 발생
        - `test_DTO타입으로_Parsing되는지()` test 실행시 오류 발생
        > [Error Message]
failed: caught error: "keyNotFound(CodingKeys(stringValue: "boxofficeType", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"boxofficeType\", intValue: nil) (\"boxofficeType\").", underlyingError: nil))"

    - `boxofficeType`에 해당하는 Key를 찾을 수 없다는 에러가 발생하여 DTO 타입을 재점검 하였으며, 모델 설계 시 `BoxOfficeResultDTO`의 상위 타입을 지정하지 않아서 발생한 오류임을 확인
    🚀 `BoxOfficeDTO` 타입 구현으로 해결
- **추후 개선 방향**
    - 불필요한 속성까지 약어를 축약하지 않은 네이밍으로 변경하는 것보다 속성의 필요 여부가 명확해지는 시점에 변경하는 것이 좋을 것으로 판단하여 추후 개선하도록 함
    
<br>

## 3. Unit Test
> 🖇️　참고문서
> - [야곰닷넷 - Unit Test 작성하기](https://yagom.net/courses/unit-test-%ec%9e%91%ec%84%b1%ed%95%98%ea%b8%b0/)

- **학습 내용**
   - 유닛 테스트는 하나의 함수, 메서드를 기준으로 독립적으로 진행되는 가장 작은 단위의 테스트
   - 유닛테스트를 하는 이유?
       - 테스트를 통해 안정성을 높일 수 있음
       - 유지보수에 유리함
       - 스펙을 문서화 할 수 있음
       - 깔끔한 코드를 작성할 수 있음
    - 이상적인 테스트 케이스는 서로 분리되어야 함
        - 이를 위해 가짜 객체(Mock object)를 생성하는 것도 좋음
    - 예상값과 결과값을 비교하는 방식
    - 좋은 유닛 테스트를 위해 `FIRST 원칙`을 지켜야 함
        - `Fast`: 빠르게 확인, 수정, 반영이 중요함
        - `Independent` / `Isolated`: 각각의 테스트는 독립적이며 서로 의존해서는 안 됨
        - `Repeatable`: 언제 어디서나 같은 결과가 반복되어야 함
        - `Self-Validation`: 성공/실패에 대해 스스로 검증이 가능해야 함
        - `Timely`: 실제 코드 구현 직전에 구현해야 함
- **문제와 해결**
    - 😰 주어진 JSON 파일을 Unit test에만 사용하고 싶음
    - 🚀 `Bundle(for: JSONDeserializerTest.self)`로 테스트 파일과 동일한 폴더 내에 있는 파일을 가져올 수 있도록 함!
    - 😰 독립적인 Unit Test Code 작성하기
    - 🚀 2가지 구현 방향을 생각함! 질문에 작성!

<br>

# 🙋🏻 질문
## 1. 독립적인 unit test code 구현하는 방법
- `JSONDeserializerTest.swift`
- 테스트하는 과정에서 JSON 파일을 가져오고 Data로 변환하는 과정에서 오류가 발생할 수 있다고 생각하였습니다.
- 이런 상황에서, JSON 파일의 decoding test의 환경이 독립적이라 말할 수 있을지에 대한 고민이 생겼습니다.

- `test_DTO타입으로_Parsing되는지()` 테스트 케이스는 MockData에 대한 decoding 과정을 수행합니다.
    - Test 핵심 코드
    ```swift
    XCTAssertNotNil(result)
    XCTAssertEqual(result.boxOfficeResult.boxofficeType, "일별 박스오피스")
    XCTAssertEqual(result.boxOfficeResult.showRange, "20220105~20220105")
    ```
    
    - Test를 하기 위한 부가적인 코드 (JSON 파일 데이터 가져오기)
    ```swift
    let fileName = "box_office_sample"

    // when
    guard let file = Bundle(for: JSONDeserializerTest.self).url(forResource: fileName, withExtension: "json") else {
        throw TestError.fileNotFound
    }

    do {
        let data = try Data(contentsOf: file)
        result = try decoder.deserialize(data)
    } catch {
        throw error
    }
    ```

- 독립적으로 decoding unit test를 하기 위해서는 json 데이터를 가져오는 코드가 방해하지 않아야 한다고 학습하였지만, 과연 독립적인 코드인가에 대한 의문이 생겼고 두 가지 방법을 시도해 보았습니다.

</br>

### 도전 방법 1 : Mock Object 생성
- JSON 파일의 경로를 찾아오는 기능과 파일을 Data 타입으로 변환시키는 기능을 가지고 있는 Mock Object(가짜 객체)를 구현하는 방법입니다.
- Mock Object를 활용한 방법이 test 환경을 독립적으로 구현했는지에 대한 의문이 들어서 작성한 코드를 커밋하지는 않았습니다.
```swift
// MockData.swift
struct MockData {
    
    func findfile(name fileName: String, extension fileExtension: String) throws -> URL? {
        
        let fileURL = Bundle(for: JSONDeserializerTest.self).url(forResource: fileName, withExtension: fileExtension)
        
        return fileURL
    }
    
    func changeToData(from url: URL) throws -> Data {
        
        let data = try Data(contentsOf: url)
        return data
    }
}
```

```swift
func test_DTO타입으로_Parsing되는지() throws {
        
        // given
        let mock = MockData()
        var result: BoxOfficeDTO

        do {
            let mockDataURL = try mock.findfile(name: fileName, extension: fileExtension)
            let mockData = try mock.changeToData(from: mockDataURL)
            result = try decoder.deserialize(mockData)
        } catch {
            throw error
        }
        
        // then
        XCTAssertNotNil(result)
        XCTAssertEqual(result.boxOfficeResult.boxofficeType, "일별 박스오피스")
        XCTAssertEqual(result.boxOfficeResult.showRange, "20220105~20220105")
    }
```

### 도전 방법 2 : extension을 활용한 메서드 분리
- 다른 방법으로는, extension을 사용하여 파일의 경로를 찾는 기능과 타입 변환 기능을 메서드로 분리하는 방법도 생각해 보았습니다.
- 여기서도 extension을 사용하여 test 케이스들과 케이스에 필요한 메서드들을 분리하는 것이 좋을지, extension을 사용하지 않고 test 케이스들과 함께 적을지 고민이 됩니다.
```swift
extension XCTestCase {
    
    func findfile(name fileName: String, extension fileExtension: String) throws -> URL {
        
        guard let fileURL = Bundle(for: JSONDeserializerTest.self).url(forResource: fileName, withExtension: fileExtension) else {
            throw TestError.fileNotFound
        }
        
        return fileURL
    }
    
    func changeToData(from url: URL) throws -> Data {
        
        let data = try Data(contentsOf: url)
        return data
    }
}
```

```swift
   func test_DTO타입으로_Parsing되는지() throws {
        
        // given
        var result: BoxOfficeDTO

       // when
        do {
            let mockDataURL = try self.findfile(name: fileName, extension: fileExtension)
            let mockData = try self.changeToData(from: mockDataURL)
            result = try decoder.deserialize(mockData)
        } catch {
            throw error
        }
        
        // then
        XCTAssertNotNil(result)
        XCTAssertEqual(result.boxOfficeResult.boxofficeType, "일별 박스오피스")
        XCTAssertEqual(result.boxOfficeResult.showRange, "20220105~20220105")
    }
```

<br>

저희가 생각해 본 방법들이 괜찮은 방법인지, 더 나은 방법이 있다면 말씀 부탁드리겠습니다! 감사합니다!

<br>

2023-04-26 21:39 UTC, YebinKim requested changes
블루, 써니 안녕하세요~
박스오피스 프로젝트 리뷰를 함께하게 된 비비입니다 😄

고민했던 내용들을 문서와 함께 꼼꼼하게 작성해주신 덕분에 어떤 생각과 함께 코드를 작성하셨는지 이해하기 편했어요! 👍
작성해주신 내용들은 추후 README에 Trouble Shooting 항목으로 옮겨적어서 문서화해두면 또 좋을 거 같아요 ☺️

그리고 리뷰 코멘트 확인 전 아래 내용 한 번 확인 부탁드릴게요~

```
코멘트는 중요도에 따라 priority 1~5 로 등급을 매겨 작성하고 있습니다.
p1이 가장 수정을 위한 우선 순위가 높으며,
p5는 수정을 해도 OK, 안 해도 OK 정도로 우선 순위가 낮습니다.

또한, p1, p2 코멘트가 있을 때는 Request Changes 를 요청드리고 있습니다.
참고 부탁드려요 🙇
```

---

### 1. 독립적인 unit test code 구현하는 방법

`JSON 파일의 경로를 찾아오는 기능`과 `파일을 Data 타입으로 변환시키는 기능` 두 기능이 하나의 메서드에 들어가게 되었을 때 독립적이지 않다고 생각하셨군요! 👀
우선 저는 테스트를 통해 검증하고자 하는 기능은 제공된 JSON 데이터를 위에서 구현한 Model 타입으로 Parsing하는 것이라고 생각하고, 앞에서 언급한 두 기능 중 `JSON 파일의 경로를 찾아오는 기능` 은 우리가 테스트 할 영역이 아니라는 생각이 들어요. 왜냐하면 Bundle 타입과 내부 메서드는 우리가 작성한 타입이 아니고 설령 오류가 발생하더라도 제어가 가능한 영역이 아니기 때문에 검증이 불필요하다는 생각이 들었어요.

그래서 JSON 파일의 경로를 찾아오는 것은 setup 과정이라 생각하고 그 이후 과정인 `파일을 Data 타입으로 변환시키는 기능` 과 `Parsing 된 타입이 예상된 데이터를 가지고 있는지 확인` 이 각각 검증된다면 모델을 검증하는 테스트의 작성은 충분하다고 생각합니다!

---

블루, 써니 Step1 진행까지 고생 많으셨어요 😆
네이밍과 관련해 p2 코멘트가 있어서 Request Changes 로 요청 드렸습니다!

또한, 파일 참조가 깨진 파일이 있어서 이 부분도 확인 부탁드릴게요. 
<img width="219" alt="파일참조" src="https://user-images.githubusercontent.com/38066039/234708677-003551c3-fb43-496f-9432-70aab59f6a08.png">

코멘트 중 궁금한 점이 있다면 언제든 DM 주세요 🙇🙌

2023-04-26 21:39 UTC, YebinKim commented on BoxOfficeTests/JSONDeserializerTest.swift
> +        }
p3;

혹시 [XCTAssertThrowsError(_:_:file:line:_:)](https://developer.apple.com/documentation/xctest/1500795-xctassertthrowserror) 메서드의 존재를 알고 계셨을까요?

2023-04-26 21:39 UTC, YebinKim commented on BoxOffice/DTO/BoxOfficeResultDTO.swift
> +    let dailyBoxOfficeList: [DailyBoxOfficeListDTO]
p2;

List 보다는 복수형의 `dailyBoxOffices` 가 문법 상 더 자연스러운 이름으로 생각됩니다! 블루와 써니는 어떻게 생각하실까요? 👀
> Swift API Design Guidelines - [Strive for Fluent Usage](https://www.swift.org/documentation/api-design-guidelines/#strive-for-fluent-usage)
> Prefer method and function names that make use sites form grammatical English phrases.

2023-04-26 21:39 UTC, YebinKim commented on BoxOffice/DTO/BoxOfficeResultDTO.swift
> +    let boxofficeType, showRange: String
p2;

`boxofficeType` 은 소문자 카멜케이스를 준수하고 있지 않은 것으로 보여요 👀

2023-04-26 21:39 UTC, YebinKim commented on BoxOffice/DTO/DailyBoxOfficeListDTO.swift
> +    let scrnCnt, showCnt: String
질문;

DTO 타입을 설계하던 중 `불필요한 속성까지 약어를 축약하지 않은 네이밍으로 변경하는 것보다 속성의 필요 여부가 명확해지는 시점에 변경하는 것이 좋을 것으로 판단하여 추후 개선하도록 함` 이와 같이 결정하신 이유가 무엇일까요? 🤔
모델을 설계하는 지금 각 속성을 바탕으로 네이밍을 해두는 것이 추후 속성의 필요 여부를 확인할 때마다 네이밍을 수정하는 것보다 시간이 적게 걸린다는 생각이 듭니다!

2023-04-26 21:39 UTC, YebinKim commented on BoxOffice/DTO/BoxOfficeDTO.swift
> +    let boxOfficeResult: BoxOfficeResultDTO
p4;

```suggestion
    let result: BoxOfficeResultDTO
```

BoxOfficeDTO 타입 내부의 프로퍼티이기 때문에 `result` 로만 이름을 지어도 의미를 전달하는 데 무리가 없을 거 같은데 어떻게 생각하실까요? 👀

2023-04-26 21:39 UTC, YebinKim commented on BoxOffice/DTO/BoxOfficeResultDTO.swift
> +    let boxofficeType, showRange: String
p3;

`showRange` 는 API 문서의 설명대로라면 `박스오피스 조회 일자를 출력` 할 것으로 보이는데,
show~ 로 시작하는 네이밍 특성 상 Bool 결과를 반환할 것으로 읽혀서 `박스오피스 조회 일자` 에 적절한 이름을 붙여주면 어떨까요?
> Swift API Design Guidelines - [Strive for Fluent Usage](https://www.swift.org/documentation/api-design-guidelines/#strive-for-fluent-usage)
> Uses of Boolean methods and properties should read as assertions about the receiver when the use is nonmutating, e.g. x.isEmpty, line1.intersects(line2).

2023-04-26 21:39 UTC, YebinKim commented on BoxOffice/DTO/RankOldAndNewDTO.swift
> +    case old = "OLD"
`rankOldAndNew` 를 두 경우의 String 으로만 결과를 받아올 수 있도록 enum 을 활용하셨군요 🤩
RawValue 의 적절한 사용이라고 생각됩니다!

2023-04-26 21:39 UTC, YebinKim commented on BoxOfficeTests/XCTestCase+extension.swift
> +    enum TestError: Error {
질문;

`TestError` 를 작성한 이유는 무엇일까요?
테스트만을 위한 에러 처리가 필요한 이유가 궁금합니다!

2023-04-27 04:50 UTC, SunnnySong commented
안녕하세요 븨븨😀
Unit Test를 이번 프로젝트에서 열심히 활용해보려고 PR 뿐만 아니라 DM까지 몇 번의 질문을 드렸는데 항상 친절하게 답해주셔서 감사해요!

븨븨의 리뷰를 받고 논의를 한 결과, 각 기능을 아래와 같이 수정했어요.
- `JSON 파일의 경로를 찾아오는 기능` -> `setUpWithError()`
- `파일을 Data 타입으로 변환시키는 기능` -> test 메서드 중 `when`
- `Parsing 된 타입이 예상된 데이터를 가지고 있는지 확인` -> test 메서드 중 `then`

또한 각 메서드들은 `JSONDeserializerTest.swift` 내부에서 메서드만 분리해서 사용하는 방식으로 결정했어요. 

API를 통해 데이터를 호출해오는 test는 해당 `JSONDeserializerTest`가 아닌 추후 생성할 'Network 관련 test'에서 진행하는게 더 맞다는 생각이 들었어요. 때문에 JSON 파일 경로 기능을 `setUpWithError()`에 추가하였어요.😉

2023-04-27 06:29 UTC, calledBlu commented on BoxOffice/DTO/BoxOfficeResultDTO.swift
> +    let dailyBoxOfficeList: [DailyBoxOfficeListDTO]
복수형 네이밍으로도 Array인 것을 충분히 알 수 있는 점을 감안하여 `dailyBoxOffices`가 더 적합하다 생각하였습니다!
아래 커밋에 반영하였습니다!

> 해당 커밋: 245832d

2023-04-27 06:30 UTC, calledBlu commented on BoxOffice/DTO/BoxOfficeResultDTO.swift
> +    let boxofficeType, showRange: String
놓친 부분을 짚어주셔서 소문자 카멜케이스를 준수하도록 수정할 수 있었어요! 감사합니다!
아래 커밋에 반영하였습니다!

> 해당 커밋: 245832d

2023-04-27 06:36 UTC, SunnnySong commented on BoxOfficeTests/JSONDeserializerTest.swift
> +        }
Unit Test의 Error 관련 함수들을 생각하지 못하고 Custom Error를 생성해 처리하려 했었어요.😂

븨븨가 알려주신 키워드와 함께 XCTestCase의 Error 함수들을 공부해보았어요.

- XCTAssertNotNil : expression이 nil이 아님을 확인한다.

- XCTAssertNoThrow : expression에서 오류를 발생하지 않으면 통과한다.

- XCTAssertThrowsError : expression을 인자로 받아 해당 expression에서 오류가 발생했는지 확인하고, errorHandler로 해당 오류를 사용할 수 있다. 

- XCTFail : message로 작성한 String으로 실패를 생성한다.

- XCTUnwrap : expression이 nil이 아님을 확인하고 옵셔널 값을 언래핑해 반환한다.

저희는 findFile() 메서드에서 `try XCTUnwrap(fileURL)`를 리턴하게 변경했어요. 또한 `XCTAssertNoThrow(result)`를 통해 decoding을 한 result가 오류가 나지 않음을 확인했어요.

>해당 커밋: ec4994f350c7872cbbed2a53feb5923d314d2150

2023-04-27 06:37 UTC, SunnnySong commented on BoxOfficeTests/XCTestCase+extension.swift
> +    enum TestError: Error {
XCTestCase의 Error 관련 메서드를 사용할 생각을 하지 못했던 것 같아요!
수정 하였습니다!

2023-04-27 06:40 UTC, calledBlu commented on BoxOffice/DTO/BoxOfficeDTO.swift
> +    let boxOfficeResult: BoxOfficeResultDTO
DTO 타입으로 데이터를 사용할 때 어떤 맥락으로 표현되는지를 고민 후 `result`로만 지어도 명확하다고 생각하였습니다!
해당 부분을 수정하며 `BoxOfficeResultDTO` 타입의 프로퍼티 중 박스오피스 타입, 박스오피스 조회 기간에 해당하는 부분도 `type`, `inqueryRange`로 변경하였고, 일간 박스오피스를 나타내는 `dailyBoxOffices`에는 키워드가 필요하다고 판단하여
아래 커밋에 반영하였습니다!

> 해당 커밋: 245832d

2023-04-27 06:42 UTC, calledBlu commented on BoxOffice/DTO/BoxOfficeResultDTO.swift
> +    let boxofficeType, showRange: String
위의 답변에서 설명드렸습니다! 븨븨! 감사합니다 🥰

2023-04-27 06:53 UTC, SunnnySong commented on BoxOffice/DTO/DailyBoxOfficeListDTO.swift
> +    let scrnCnt, showCnt: String
해당 DTO 타입에 속해있는 속성이 많기 때문에 저희는 다음 Step에서 이 모든 속성을 다 사용하지는 않을 것이라 생각했었어요!
사용하는 데이터 속성이 명확해지는 Step3에서 DTO의 속성을 정리하고 네이밍을 추후 수정하려고 계획했어요. 븨븨의 의견을 수용해 Step2에서 DTO 네이밍을 수정하도록 할게요😀

2023-04-27 12:04 UTC, YebinKim commented
써니, 블루 안녕하세요~ 답변 코멘트 확인했습니다!
Step1 수정까지 고생 많으셨어요 🙌

Step1은 아래 핵심 경험이 모두 충족되었다고 생각해 이대로 머지 진행할게요.
<img width="326" alt="Step1" src="https://user-images.githubusercontent.com/38066039/234856415-377a35c9-780a-43e2-b61d-dd25aa744295.png">

다음 스텝 진행도 화이팅입니다 ☺️💪

2023-04-27 12:04 UTC, YebinKim approved these changes

2023-04-27 12:04 UTC, merged