📽️ BoxOffice [Step2] Team Milo
tasty-code/ios-box-office pull request #7
Opened 2023-04-27 09:22 UTC by longlivedrgn

> 안녕하세요 제이크~! (@jryoun1) 이번 Step은 실제 API 호출을 통해서 원하는 데이터를 받아오는 걸 해보았습니다. 감사해요! 😊
> 

# ✅ 요구사항 & 체크리스트

- [x]  네트워크 통신을 담당할 타입을 설계하고 구현합니다.
- [x]  [영화진흥위원회의 일별 박스오피스 API 문서](https://www.kobis.or.kr/kobisopenapi/homepg/apiservice/searchServiceInfo.do?serviceId=searchDailyBoxOffice)의 데이터 형식을 고려하여 서버와 실제로 데이터를 주고받도록 구현합니다.
    - 이번 스텝에서 진행할 네트워킹 요소
        - `오늘의 일일 박스오피스 조회`
        - `영화 개별 상세 조회`

### **Step 1 핵심 경험**

---

- [x]  URL Session을 활용한 서버와의 통신
- [x]  `CodingKeys` 프로토콜의 활용

# 🛠️ 구현 사항

- 학습용 프로젝트이기 때문에 API key를 숨기기 위한 조취는 하지 않았습니다.
- URL을 구성하는데 있어서 URLComponents를 사용하여 구성되도록 구현 했습니다.
- URL을 이용하여 Request를 만드는데 있어서 Endpoints 를 사용했습니다.
    - boxOffice에 대한 요청과 movieDetail에 대한 요청을 구분하기 위해서 enum 의 Associated Value 를 사용하여 각 요청에 필요한 data를 달리 받아 요청을 구체화 하도록 구현했습니다.

# **⁉️ 궁금한 점**

## 🔨 Network Layer 구조

- 저희는 아래 두 가지 타입을 활용해서 API 호출을 하는 구조에요.
    - `BoxOfficeAPIManager`
    - `NetworkDispatcher`

**두 가지 타입의 역할은 아래와 같아요.**

### NetworkDispatcher

- 파라미터로 받은 URLRequest를 통해서 URLSessionTask를 생성하고 실행하여 Data를 completionHandler로 넘겨줘요.
- 즉, Request를 실행하는 역할을 해요.

```swift
struct NetworkDispatcher {

    func performRequest(_ urlRequest: URLRequest?, completionHandler: @escaping (NetworkResult) -> Void) {

        let session = URLSession.shared

        guard let urlRequest = urlRequest else { return completionHandler(.failure(.invalidURL)) }

        let task = session.dataTask(with: urlRequest) { data, urlRequest, error in

            guard error == nil else {
                return completionHandler(.failure(.failedRequest))
            }
            guard let response = urlRequest, response.checkResponse else {
                return completionHandler(.failure(.outOfResponseCode))
            }
            guard let data = data else {
                return completionHandler(.failure(.emptyData))
            }

            completionHandler(.success(data))
        }

        task.resume()

    }

}
```

### BoxOfficeAPIManager

- 디코딩하는 객체인 `JSONDeserializer()` 와 Request를 실행하는 역할 `NetworkDispatcher()` 를 프로퍼티로 가지고 있어요.
- fetchData 메소드를 활용해서 아래와 같은 로직을 수행해요.
    - `NetworkDispatcher()` 의 **performRequest** 메소드를 통해서 Request를 실행해요.
    - `perfromRequest`를 통해서 받아온 Data를 통해서 원하는 타입으로 디코딩을 해요.

```swift
struct BoxOfficeAPIManager {
    
    private let deserializer = JSONDeserializer()
    private let networkDispatcher = NetworkDispatcher()
    
    func fetchData(to type: Decodable.Type, endPoint: BoxOfficeAPIEndpoints, completionHandler: @escaping (Decodable) -> Void) {
        
        let urlRequest = endPoint.urlRequest
        
        networkDispatcher.performRequest(urlRequest) { networkResult in
            
            switch networkResult {
                
            case .success(let data):
                do {
                    let decodedData = try deserializer.deserialize(type: type, data: data)
                    completionHandler(decodedData)
                }
                catch {
                    print(NetworkError.failedDecoding.errorDescription)
                }
            case .failure(let error):
                print(error.errorDescription)
            }
        }
    }
}
```

> ⁉️🤔 위와 같이 Network Layer 구성을 제이크는 어떻게 보시나요? (타입 명, 메소드 명..)
> 

## 🔨 EndPoint

- 저희는 `EndPoint`라는 구조체를 생성해서 URLcomponents을 관리해요.

```swift
struct EndPoint {
    
    let baseURL: String
    let path: String
    let queryItems: [URLQueryItem]?
    
    init(baseURL: String, path: String, queryItems: [URLQueryItem]? = nil) {
        self.baseURL = baseURL
        self.path = path
        self.queryItems = queryItems
    }
}
```

- `BoxOfficeAPIEndpoints` enum을 활용해서 두 가지 종류의 EndPoint를 관리해요.
    - Endpoint의 queryItems를 생성하는 역할을 해요.
    - Endpoint를 통해서 URLRequest를 생성하는 역할을 해요.

> ⁉️🤔 저희는 위와 같이 EndPoint, 즉 API 호출할 때 사용하는 URL을 핸들링했습니다. 제이크가 보셨을 때는 위와 같이 URLComponents를 활용하여 EndPoint 커스텀 타입을 활용하는 방식이 어떨 지 궁금해요! 또한, **현업에서는 URL을 어떠한 방식으로 다루는 지 또한 궁금합니다!**
>

2023-04-28 09:07 UTC, jryoun1 requested changes
step2도 잘 마무리해주셨군요! 
고생하셨습니다 👍 

전반적으로 코드를 잘 작성해주셔서 코드를 이해하는데 큰 문제 없었던 것 같습니다 👏 💯 
다만 두 분께서 코드를 작성하실 때 어떤 convention으로 작성할지 이야기하고 해당 convention을 지켜가면서 코드를 작성해주시면 좀 더 읽는데 편할 것 같네요 ㅎㅎ 코멘트에도 몇 가지 남겨두었습니다! 

BoxOfficeAPIManager와 NetworkDispatcher는 둘 다 괜찮은 것 같습니다. 👍 💯 
다만 여기서 NetworkDispatcher의 경우에는 다른 곳에서 쉽게 재사용할 수 있을 것 같은데, BoxOfficeAPIManager의 경우에는 endPoint의 타입이 BoxOfficeAPIEndpoints라는 특정 구체 타입에 의존적이기 때문에 다른곳에서의 재활용은 쉬워보이지 않네요!
물론 이 프로젝트에서는 endpoint가 boxOffice밖에 없으니까 위와 같이 구현하셔도 충분할 것 같습니다! 

또한 endpoint를 추상화시킨 객체를 생성하신 부분도 좋네요! 
현업에서는 회사마다 다르겠지만 Moya나 Alamofire와 같은 외부 라이브러리를 사용하는 곳들도 많이 있고, 외부라이브러리를 사용하지 않고 실제 팀내에서 구현해서 사용하는 회사들도 있을 것 같네요! 
추후에 시간이 되신다면 [Alamofire](https://github.com/Alamofire/Alamofire)나 [Moya](https://github.com/Moya/Moya)에 대해서도 한 번 살펴보시면 좋을것 같네요
(이번 프로젝트 동안에 꼭 살펴봐야한다는 내용이 아닙니다!)

2023-04-28 09:07 UTC, jryoun1 commented on BoxOffice/Model/DTO/MovieDetail.swift
> +    let movieOriginalName: String
이미 해당 타입의 네이밍이 MovieInformation이기 때문에 code, name, englishName, originalName과 같이 네이밍해도 괜찮을 것 같습니다.

2023-04-28 09:07 UTC, jryoun1 commented on BoxOffice/Model/DTO/MovieDetail.swift
> +
위에서는 타입을 선언한 뒤에 공백이 없는 것 같은데 여기는 공백이 있네요?! 
두 분은 어떤 convention으로 작성하고 계신걸까요?

2023-04-28 09:07 UTC, jryoun1 commented on BoxOffice/Model/DTO/MovieDetail.swift
> +    let nations: [Nation]
배열일 때 s를 통한 네이밍 좋네요 💯

2023-04-28 09:07 UTC, jryoun1 commented on BoxOffice/Model/DTO/MovieDetail.swift
> +    let auditNuber: String
typo가 있는 것 같습니다.

2023-04-28 09:07 UTC, jryoun1 commented on BoxOffice/Model/DTO/MovieDetail.swift
> +    let companyPartOfMoive: String
여기도 위에서 언급해드린것과 동일합니다!

2023-04-28 09:07 UTC, jryoun1 commented on BoxOffice/Model/DTO/MovieDetail.swift
> +    let peopleEnglishName: String
여기도 name, englishName으로도 충분할 것 같네요!

2023-04-28 09:07 UTC, jryoun1 commented on BoxOffice/Model/DTO/MovieDetail.swift
> +    let genreName: String
동일합니다!

2023-04-28 09:07 UTC, jryoun1 commented on BoxOffice/Model/DTO/MovieDetail.swift
> +    let showTypeName: String
동일합니다 🙏

2023-04-28 09:07 UTC, jryoun1 commented on BoxOffice/Networking/EndPoint/BoxOfficeAPIEndpoints.swift
> +        case .movieDetail(movieCode: let code):
let code만 작성해도 될 것 같아보이네요! 위에 let date도 동일합니다

2023-04-28 09:07 UTC, jryoun1 commented on BoxOffice/Networking/EndPoint/BoxOfficeAPIEndpoints.swift
> +extension BoxOfficeAPIEndpoints {
endpoint 객체를 생성해서 URLRequest를 생성하는 부분 깔끔해보이고 좋네요 👍 💯

2023-04-28 09:07 UTC, jryoun1 commented on BoxOffice/Util/Extensions/URLResponse+.swift
> +}
URLResposne를 extension해서 response가 HTTPURLResponse인지, statusCode를 검증하는 부분 좋네요 👍

2023-04-28 09:07 UTC, jryoun1 commented on BoxOffice/Util/Extensions/URLResponse+.swift
> +    var checkResponse: Bool {
해당 연산프로퍼티는 검증하는 것은 것은데 isValid~와 같은 접두사는 어떨까요?

2023-04-28 09:07 UTC, jryoun1 commented on BoxOffice/Util/Extensions/URLResponse+.swift
> +        }
어떤 부분에서는 else 뒤의 블록이 줄바꿈이 되어있고 아닌 부분이 있는데 두 분은 어떤 convention을 사용하기로 하셨을까요?

2023-04-28 09:07 UTC, jryoun1 commented on BoxOffice/Networking/NetworkError.swift
> +enum NetworkError: LocalizedError {
네트워크 에러의 종류도 잘 분리해주셨군요 👏 
LocalizedError 프로토콜은 어떤 프로토콜일까요?

2023-04-28 09:07 UTC, jryoun1 commented on BoxOffice/Networking/NetworkDispatcher.swift
> +typealias NetworkResult = Result<Data, NetworkError>
typealias를 NetworkDispatcher 타입 내부가 아닌 외부에 선언해주신 이유가 궁금합니다!

2023-04-28 09:07 UTC, jryoun1 commented on BoxOffice/Networking/NetworkDispatcher.swift
> +    func performRequest(_ urlRequest: URLRequest?, completionHandler: @escaping (NetworkResult) -> Void) {
👏

2023-04-28 09:07 UTC, jryoun1 commented on BoxOffice/ViewController.swift
>  final class ViewController: UIViewController {
이 viewController의 목적에 맞게 네이밍 변경해주세요!

2023-04-28 09:07 UTC, jryoun1 commented on BoxOffice/ViewController.swift
> +    }
테스트 코드를 test 파일에서 작성하지 않고, viewcontroller에서 작성해주신 이유가 궁금합니다!

2023-05-01 04:08 UTC, longlivedrgn commented on BoxOffice/ViewController.swift
> +    }
앗, 저희는 따로 테스트라고 생각 못하고 제대로 받아오나만 확인해보려고 view controller에 작성을 했는데, 생각해보니 해당 과정이 Test하는 과정이네요! Test 파일에서 작성해보겠습니다! 감사합니다 :)

2023-05-01 04:08 UTC, longlivedrgn commented on BoxOffice/ViewController.swift
>  final class ViewController: UIViewController {
넵! 감사합니다 🙇‍♂️

2023-05-01 04:10 UTC, longlivedrgn commented on BoxOffice/Networking/NetworkDispatcher.swift
> +typealias NetworkResult = Result<Data, NetworkError>
생각해보니 굳이 외부에 있을 필요가 없네요! typealias가 사용되는 해당 타입 안으로 위치를 옮겼습니다! 감사합니다 :)

2023-05-01 09:02 UTC, longlivedrgn commented on BoxOffice/Model/DTO/MovieDetail.swift
> +
제이크의 코멘트를 보고,  정확한 컨벤션을 정하는 것이 좋을 거 같다는 생각이 들어, 아래와 같은 컨벤션을 적용하여 코드를 작성했어요!

- Type 선언 후, 맨 위 맨 아래 줄은 공백을 줍니다.
    - Nested Type의 경우, 공백을 생략합니다.

```swift
struct BoxOfficeResult: Decodable {

    let type: String
    let rangeOfDate: String
    let dailyBoxOfficeList: [DailyBoxOfficeList]

    enum CodingKeys: String, CodingKey {
        case type = "boxofficeType"
        case rangeOfDate = "showRange"
        case dailyBoxOfficeList
    }

}
```

- 한 줄의 코드는 99자로 제한합니다.
    - 99자를 넘어갈 경우, 아래와 같은 포멧으로 함수를 정의합니다.
    
    ```swift
    func performRequest(_ urlRequest: URLRequest?,
                        completionHandler: @escaping (NetworkResult) -> Void
        ) {
    ```
    
    - 99자가 넘는 함수의 호출 또한 위와 같은 형식으로 코드를 작성합니다.
- 빈 공백의 경우, 들여쓰기를 하지 않습니다.
- guard 문의 경우, else 문 안에서 함수나 클로져를 호출할 경우 아래와 같이 else문을 작성합니다.
    
    ```swift
    guard error == nil else {
        return completionHandler(.failure(.failedRequest))
    }
    ```
    
    - 그렇지 않을 경우, 아래와 같이 작성합니다.
    
    ```swift
    guard let responseCode = self as? HTTPURLResponse else { return false }
    ```

2023-05-01 10:23 UTC, longlivedrgn commented on BoxOffice/Networking/NetworkError.swift
> +enum NetworkError: LocalizedError {
저희는 errorDescription을 통해서 에러 메세지를 확인할 수 있도록 하려고 LocalizedError 프로토콜을 채택했어요!
공식문서를 확인해보니, 오류가 발생한 이유를 설명하는 현지화된 메시지를 제공하는 특수 오류라고 정의되어있었어요. 저희는 각각의 오류에 대해서 오류 메세지를 던지기 위해서 LocalizedError 프로토콜을 채택했어요!

2023-05-02 13:32 UTC, jryoun1 commented on BoxOffice/Model/DTO/MovieDetail.swift
> +
좋네요 ㅎㅎ 다음 step부터는 해당 convention을 지키면서 작성하면 더 가독성이 좋아질 것 같네요 👍

2023-05-02 13:35 UTC, jryoun1 approved these changes
수정사항 확인했습니다. 고생하셨습니다!
step2는 여기서 종료해도 될 것 같아서 머지하겠습니다.
추후에 시간이 남는다면 step2-1도 진행해보시는걸 추천드립니다 👍

2023-05-02 13:35 UTC, jryoun1 commented on BoxOfficeNetworkTest/BoxOfficeNetworkTest.swift
> +    }
XCTestExpectation도 사용해보셨군요! 👏

2023-05-02 13:36 UTC, merged